<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Response data and statistical distributions – Concentration-response modelling</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../vignettes/6Priors_and_Bayesian_inference.html" rel="next">
<link href="../vignettes/4Model_averaging_and_multimodel_inference.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8317e07c38846ddd92fb20fa66b3c33c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Concentration-response modelling</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/0Software-setup.html"> 
<span class="menu-text">Setup</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/1Software-stack.html"> 
<span class="menu-text">Modules</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/open-AIMS/cr_modelling_training/issues"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">Questions and corrections</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/1Software-stack.html">Modules</a></li><li class="breadcrumb-item"><a href="../vignettes/5Response_data_and_statistical_distributions.html">5. Response data and distributions</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Before you start</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/0Software-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Software setup</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Modules</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/1Software-stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. The software stack</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/2Fitting-a-CR-model-using-bayesnec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Fitting a single model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/3Toxicity_estimation_and_available_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Toxicity estimation and the model set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/4Model_averaging_and_multimodel_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Model averaging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/5Response_data_and_statistical_distributions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">5. Response data and distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/6Priors_and_Bayesian_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Priors and Bayesian inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/7Example_case_study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. A worked case study</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/8Factor_covariates_and_groupings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Factor covariates and groupings</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Frequentist comparison</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/drc-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting the same models with drc</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#generalised-modelling" id="toc-generalised-modelling" class="nav-link" data-scroll-target="#generalised-modelling">Generalised modelling</a></li>
  <li><a href="#families-available-in-brms" id="toc-families-available-in-brms" class="nav-link" data-scroll-target="#families-available-in-brms">Families available in <code>brms</code></a></li>
  <li><a href="#link-functions" id="toc-link-functions" class="nav-link" data-scroll-target="#link-functions">Link functions</a></li>
  <li><a href="#families-implemented-in-bayesnec" id="toc-families-implemented-in-bayesnec" class="nav-link" data-scroll-target="#families-implemented-in-bayesnec">Families implemented in <code>bayesnec</code></a></li>
  <li><a href="#default-behaviour" id="toc-default-behaviour" class="nav-link" data-scroll-target="#default-behaviour">Default behaviour</a></li>
  <li><a href="#binomial" id="toc-binomial" class="nav-link" data-scroll-target="#binomial">Binomial</a>
  <ul class="collapse">
  <li><a href="#the-dispersion-screen" id="toc-the-dispersion-screen" class="nav-link" data-scroll-target="#the-dispersion-screen">The dispersion screen</a></li>
  </ul></li>
  <li><a href="#beta-binomial" id="toc-beta-binomial" class="nav-link" data-scroll-target="#beta-binomial">Beta-binomial</a></li>
  <li><a href="#checking-the-family-reproduces-the-data" id="toc-checking-the-family-reproduces-the-data" class="nav-link" data-scroll-target="#checking-the-family-reproduces-the-data">Checking the family reproduces the data</a></li>
  <li><a href="#beta" id="toc-beta" class="nav-link" data-scroll-target="#beta">Beta</a>
  <ul class="collapse">
  <li><a href="#values-on-the-boundary" id="toc-values-on-the-boundary" class="nav-link" data-scroll-target="#values-on-the-boundary">Values on the boundary</a></li>
  </ul></li>
  <li><a href="#poisson" id="toc-poisson" class="nav-link" data-scroll-target="#poisson">Poisson</a>
  <ul class="collapse">
  <li><a href="#counts-observed-over-an-exposure" id="toc-counts-observed-over-an-exposure" class="nav-link" data-scroll-target="#counts-observed-over-an-exposure">Counts observed over an exposure</a></li>
  </ul></li>
  <li><a href="#negative-binomial" id="toc-negative-binomial" class="nav-link" data-scroll-target="#negative-binomial">Negative binomial</a></li>
  <li><a href="#gamma" id="toc-gamma" class="nav-link" data-scroll-target="#gamma">Gamma</a></li>
  <li><a href="#gaussian" id="toc-gaussian" class="nav-link" data-scroll-target="#gaussian">Gaussian</a>
  <ul class="collapse">
  <li><a href="#growth-rates" id="toc-growth-rates" class="nav-link" data-scroll-target="#growth-rates">Growth rates</a></li>
  </ul></li>
  <li><a href="#model-suitability-by-response-type" id="toc-model-suitability-by-response-type" class="nav-link" data-scroll-target="#model-suitability-by-response-type">Model suitability by response type</a></li>
  <li><a href="#censored-values" id="toc-censored-values" class="nav-link" data-scroll-target="#censored-values">Censored values</a></li>
  <li><a href="#zeros" id="toc-zeros" class="nav-link" data-scroll-target="#zeros">Zeros</a></li>
  <li><a href="#hurdle-and-zero-inflated-models" id="toc-hurdle-and-zero-inflated-models" class="nav-link" data-scroll-target="#hurdle-and-zero-inflated-models">Hurdle and zero-inflated models</a>
  <ul class="collapse">
  <li><a href="#a-hurdle-gamma-in-practice" id="toc-a-hurdle-gamma-in-practice" class="nav-link" data-scroll-target="#a-hurdle-gamma-in-practice">A hurdle gamma in practice</a></li>
  </ul></li>
  <li><a href="#preparing-the-response" id="toc-preparing-the-response" class="nav-link" data-scroll-target="#preparing-the-response">Preparing the response</a>
  <ul class="collapse">
  <li><a href="#the-reason-a-divisor-gets-reached-for" id="toc-the-reason-a-divisor-gets-reached-for" class="nav-link" data-scroll-target="#the-reason-a-divisor-gets-reached-for">The reason a divisor gets reached for</a></li>
  </ul></li>
  <li><a href="#modelling-dispersion" id="toc-modelling-dispersion" class="nav-link" data-scroll-target="#modelling-dispersion">Modelling dispersion</a>
  <ul class="collapse">
  <li><a href="#a-worked-case" id="toc-a-worked-case" class="nav-link" data-scroll-target="#a-worked-case">A worked case</a></li>
  </ul></li>
  <li><a href="#open-questions" id="toc-open-questions" class="nav-link" data-scroll-target="#open-questions">Open questions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/open-AIMS/cr_modelling_training/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/1Software-stack.html">Modules</a></li><li class="breadcrumb-item"><a href="../vignettes/5Response_data_and_statistical_distributions.html">5. Response data and distributions</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Response data and statistical distributions</h1>
<p class="subtitle lead">Matching the statistical family to the response being modelled</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>Concentration-response data are of varied kinds, and the measured response follows a correspondingly wide range of natural distributions. The examples below are drawn at random to show the shape of each.</p>
<p><strong>Binary</strong>, modelled by the binomial or beta-binomial. Individual survival, 0 0 1 1 0 1 1 0 0 0, or counts of survivors out of a total.</p>
<p><strong>Bounded continuous</strong>, modelled by the beta. Proportions or ratios that are not counts out of a total: 0.458 0.861 0.246 0.043 0.1 0.697 0.232 0.74 0.866 0.704.</p>
<p><strong>Counts</strong>, modelled by the Poisson or negative binomial. Numbers of whole animals: 7 2 3 3 3 8 6 4 3 1.</p>
<p><strong>Positive continuous</strong>, modelled by the gamma. Growth where shrinkage is not possible: 0.92 5.11 0.46 5.13 1.67 8.9 0.66 0.62 0.82 1.43.</p>
<p><strong>Unbounded continuous</strong>, modelled by the Gaussian. Growth where shrinkage is possible: 0.08 -0.22 -0.94 0.04 -0.12 0.16 -0.8 -0.09 0.88 0.06.</p>
</section>
<section id="generalised-modelling" class="level2">
<h2 class="anchored" data-anchor-id="generalised-modelling">Generalised modelling</h2>
<p>Generalised modelling fits data with a statistical distribution matched to the natural range and scaling of the response, rather than assuming one.</p>
<p>Fitting a linear model with <code>lm()</code> assumes a Gaussian distribution, and so do many non-linear routines such as <code>nls()</code>. The normality assumption familiar from analysis of variance is the most common case of non-generalised modelling. It is sometimes reasonable, but it was adopted largely because it makes the mathematics of fitting and interval estimation tractable.</p>
<p>That constraint no longer applies. Matching the response to an appropriate statistical family is now standard practice, and the theory is covered well elsewhere; this module is concerned with making the right choice in <code>bayesnec</code> rather than with the underlying mathematics.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/glmbooks.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</section>
<section id="families-available-in-brms" class="level2">
<h2 class="anchored" data-anchor-id="families-available-in-brms">Families available in <code>brms</code></h2>
<p><code>brms</code> supports many families, including most of those in the base <code>stats</code> package that other R fitting routines use:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/statsfams.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
<p>and a number that are specific to it:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/brmsfams.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</section>
<section id="link-functions" class="level2">
<h2 class="anchored" data-anchor-id="link-functions">Link functions</h2>
<p>Every statistical family has a link function. A generalised linear model relates the linear predictor to the response through it — a logit link, for example, maps the probabilities of a binary response onto an unbounded continuous scale. Generalised linear models were formulated by Nelder and Wedderburn as a unification of linear regression, logistic regression and Poisson regression, with maximum likelihood estimation of the parameters. Logistic regression is the familiar case.</p>
<p>The native link for a family — logit for the binomial, log for the Poisson — imposes a non-linear transformation. Concentration-response models are already non-linear and do not use linear predictors, so any further non-linearity from a link changes the model being fitted.</p>
<p><code>bayesnec</code> therefore uses the identity link for every family. The Bayesian machinery makes this possible, because the parameters can be estimated without mapping the response onto an unbounded scale. It keeps <code>top</code>, <code>bot</code> and <code>nec</code> on the scale of the response, where they are directly interpretable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>bayesnec<span class="sc">:::</span><span class="fu">supported_links</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "identity" "log"      "logit"   </code></pre>
</div>
</div>
<p>This matters when comparing a <code>bayesnec</code> fit against a <code>brms</code> model written by hand. <code>brms</code> defaults to logit for a beta response and log for a Poisson, so unless the link is passed explicitly the two are different models. ECx and NSEC estimates from a fit using any link other than the identity may not behave as expected.</p>
</section>
<section id="families-implemented-in-bayesnec" class="level2">
<h2 class="anchored" data-anchor-id="families-implemented-in-bayesnec">Families implemented in <code>bayesnec</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bayesnec<span class="sc">:::</span>mod_fams)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "gaussian"                  "Gamma"                    
 [3] "poisson"                   "negbinomial"              
 [5] "bernoulli"                 "binomial"                 
 [7] "beta_binomial"             "beta"                     
 [9] "hurdle_gamma"              "zero_inflated_beta"       
[11] "zero_inflated_poisson"     "zero_inflated_negbinomial"
[13] "hurdle_poisson"            "hurdle_negbinomial"       </code></pre>
</div>
</div>
<p>The first eight are the ordinary cases covered below. <code>hurdle_gamma</code>, <code>zero_inflated_beta</code>, <code>zero_inflated_poisson</code> and <code>zero_inflated_negbinomial</code> handle responses with an excess of zeros — a separate topic, treated in the <code>bayesnec</code> article on hurdle families.</p>
<p>Adding a family is not trivial, because <code>bayesnec</code> generates priors and initial values by algorithms specific to each one. Requests go to the <a href="https://github.com/open-AIMS/bayesnec/issues">issue tracker</a>.</p>
</section>
<section id="default-behaviour" class="level2">
<h2 class="anchored" data-anchor-id="default-behaviour">Default behaviour</h2>
<p>With default settings <code>bnec</code> infers the most likely distribution from the response. That inference must be checked rather than trusted. Two questions decide whether a distribution is adequate:</p>
<ul>
<li>does it capture the variability present in the data?</li>
<li>does it produce sensibly shaped credible bounds across the whole curve?</li>
</ul>
<p>Getting the dispersion right matters directly for toxicity estimates, because it sets the width of their intervals. It matters most for the <em>NSEC</em>, which is defined against the estimated variability in the control: overstate that variability and the estimate becomes less conservative <span class="citation" data-cites="fisheretal2023 fisherfox2023">(<a href="#ref-fisheretal2023" role="doc-biblioref">Fisher et al. 2023</a>; <a href="#ref-fisherfox2023" role="doc-biblioref">Fisher and Fox 2023</a>)</span>.</p>
<p>The sections below fit a threshold and a smooth model to each of several response types. Several of the examples come from <a href="https://github.com/gerard-ricardo/NECs/blob/master/NECs">Gerard Ricardo’s repository</a>.</p>
<p><em>Preparing the response</em>, near the end of the module, covers what to do where a response has already been divided by its control mean or by its observed maximum.</p>
</section>
<section id="binomial" class="level2">
<h2 class="anchored" data-anchor-id="binomial">Binomial</h2>
<p>A response is binomial when it is a count out of a total, such as the number of survivors out of a number exposed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>binom_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"vignettes/example_binomial.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log.x =</span> <span class="fu">log</span>(raw_x))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(binom_data<span class="sc">$</span>raw_x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.10   10.94   37.50   99.23  125.00  400.00 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(binom_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  raw_x suc tot     log.x
1   0.1 101 175 -2.302585
2   0.1 106 112 -2.302585
3   0.1 102 103 -2.302585
4   0.1 112 114 -2.302585
5   0.1  58  69 -2.302585
6   0.1 158 165 -2.302585</code></pre>
</div>
</div>
<p>The predictor runs from 0.1 to 400 and is strongly right skewed, which is typical of a dilution series. Transforming the predictor, usually by a logarithm, often makes fitting more stable, and the design is generally logarithmic in any case, so this example is fitted on <code>log.x</code>. Estimates then come back on the log scale and are returned to concentrations with the <code>xform</code> argument of <code>nec()</code>, <code>nsec()</code> and <code>ecx()</code>, which module 7 works through.</p>
<p><code>suc</code> holds the number of successes and <code>tot</code> the number of trials.</p>
<p>For a binomial or beta-binomial response the formula takes a <code>trials</code> term, exactly as in <code>brms</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>suc <span class="sc">|</span> <span class="fu">trials</span>(tot) <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"your_model"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The column to the left of the <code>|</code> holds the successes — survivors, fertilised eggs — and the one inside <code>trials()</code> the total associated with each. The names are whatever they are in your data frame.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>exp_1nec <span class="ot">&lt;-</span> <span class="fu">bnec</span>(suc <span class="sc">|</span> <span class="fu">trials</span>(tot) <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"nec3param"</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> binom_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_1nec, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_1nec.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_1nec.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_1nec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting all 'trials' variables to 1 by default if not specified otherwise.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-binom-nec" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binom-nec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-binom-nec-1.png" id="fig-binom-nec" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-binom-nec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<p>The credible bounds are very tight. The threshold model itself fits reasonably and the <em>NEC</em> is in a plausible place.</p>
<section id="the-dispersion-screen" class="level3">
<h3 class="anchored" data-anchor-id="the-dispersion-screen">The dispersion screen</h3>
<p>Bounds that look too tight are a judgement by eye, and the judgement can be made properly. <code>dispersion()</code> compares the variability in the data against the variability the fitted model implies:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dispersion</span>(exp_1nec, <span class="at">summary =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimate     Q2.5    Q97.5    P(&gt;1) 
17.56449 11.99124 27.08505  1.00000 </code></pre>
</div>
</div>
<p>For each posterior draw it forms the ratio of the observed to the simulated sum of squared Pearson residuals, and summarises those ratios to a median, a 95% interval, and <code>P(&gt;1)</code>, the posterior probability that the ratio exceeds 1. A value near 1 means the family’s variance assumption holds. A value well above 1 means the data are more variable than the model allows, which is <strong>over-dispersion</strong>.</p>
<p>Read <code>P(&gt;1)</code> rather than the median, because a point estimate says nothing about how well determined it is. The statistic is symmetric, so <code>1 - P(&gt;1)</code> is the posterior probability of under-dispersion, which nothing else reports.</p>
<p>Here the ratio is about 18 with a 95% interval well clear of 1, and <code>P(&gt;1)</code> is 1. The data are roughly eighteen times more variable than a binomial allows, which is why the credible bounds above are as narrow as they are. The eye was right in this case, and the number is what would be reported.</p>
<p>Two limitations apply. Each draw compares one observed residual sum against a single simulated replicate, so the spread of the result is dominated by simulation noise rather than by uncertainty about a dispersion parameter; on a small design it will detect gross over-dispersion and little else. And the screen is conditional on the model it was computed from, because a dispersion ratio cannot distinguish genuine over-dispersion from a shape that fits badly. Check that the screening fit sampled adequately, with <code>check_sampling()</code>, before relying on the number it reports.</p>
<p><code>dispersion()</code> is defined for the binomial and Poisson families only, and returns an empty vector for any other. Those two are the families whose variance is fixed by their mean, so they are the only ones for which over-dispersion is a question about the family rather than a parameter the fit estimates.</p>
<p>Fitting a smooth curve to the same data instead:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>exp_1ecx <span class="ot">&lt;-</span> <span class="fu">bnec</span>(suc <span class="sc">|</span> <span class="fu">trials</span>(tot) <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"ecxll3"</span>),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> binom_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_1ecx, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_1ecx.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_1ecx.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_1ecx)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting all 'trials' variables to 1 by default if not specified otherwise.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-binom-ecx" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binom-ecx-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-binom-ecx-1.png" id="fig-binom-ecx" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-binom-ecx-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="beta-binomial" class="level2">
<h2 class="anchored" data-anchor-id="beta-binomial">Beta-binomial</h2>
<p>The bounds above are implausibly narrow for data of this kind. A binomial distribution has a single parameter, so its variance is fixed by its mean. Real counts out of a total are usually more variable than that, because the individuals within a replicate are not independent — a batch of eggs shares a parent, a container shares its conditions. This is over-dispersion.</p>
<p>The beta-binomial adds a second parameter and estimates the extra variation rather than assuming it away.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>exp_1b <span class="ot">&lt;-</span> <span class="fu">bnec</span>(suc <span class="sc">|</span> <span class="fu">trials</span>(tot) <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ecxll3"</span>, <span class="st">"nec3param"</span>)),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> binom_data, <span class="at">family =</span> <span class="st">"beta_binomial"</span>, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_1b, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_1b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_1b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_1b, <span class="at">all_models =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting all 'trials' variables to 1 by default if not specified otherwise.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"
Setting all 'trials' variables to 1 by default if not specified otherwise.

Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-betabinom" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-betabinom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-betabinom-1.png" id="fig-betabinom" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-betabinom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
</div>
</div>
<p>The bounds are now much wider, and they are a better description of the scatter in the data.</p>
<p>The beta-binomial mixes the success probability over a beta distribution, and mixing can only <em>add</em> variance. It therefore addresses over-dispersion and does nothing for the opposite case. A screen pointing below 1 is telling you something about the fit, the design or the process that generated the data, rather than about the family.</p>
<p><code>bayesnec</code> once supplied this as a custom family called <code>beta_binomial2</code>, because <code>brms</code> did not provide one natively. It does now, and the family is named <code>beta_binomial</code>; code written against <code>beta_binomial2</code> will no longer run.</p>
</section>
<section id="checking-the-family-reproduces-the-data" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-family-reproduces-the-data">Checking the family reproduces the data</h2>
<p>The two sections above chose between two families by eye and then by a dispersion ratio. Neither generalises: the eye is unreliable, and <code>dispersion()</code> is defined for the binomial and Poisson alone. <code>check_fit()</code> is the check that applies to every family, and it is what the rest of this module uses.</p>
<p>A dispersion ratio is one number for the whole fit, and one number can hide a model that is right on average and wrong where it matters. <code>check_fit()</code>, named in module 2, makes the same comparison within concentration groups, and on a model set it reports every equation separately.</p>
<p>What it compares is the observed mean and the observed standard deviation within each group of the predictor against the same two statistics computed from datasets simulated by the fitted model. A family that cannot reproduce those two numbers across the concentration range is the wrong family for the response, whatever it says about the kind of quantity the response is. The control group matters most, because both <code>nsec()</code> and <code>ecx()</code> read their reference from the fitted mean there, so an error in the control propagates into every estimate the analysis reports.</p>
<p>Run on the binomial fit from the section above:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>cf_1nec <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_1nec)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>cf_1nec</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              group n obs_mean sim_mean mean_ratio ppp_mean obs_sd sim_sd
1 -2.30258509299405 6  106.167  102.000      1.041    0.010 24.642  3.861
2  1.83258146374831 6  103.667  100.167      1.035    0.031 14.344  3.939
3  2.52572864430826 6   72.833   77.500      0.940    0.999 24.383  3.345
4   3.2188758248682 6   85.167   81.333      1.047    0.012 11.478  3.451
5  3.91202300542815 6   75.500   82.833      0.911    1.000 20.819  3.497
6  4.60517018598809 6   61.500   60.500      1.017    0.371 29.085  4.782
7  5.29831736654804 6   19.500   22.333      0.873    0.906 13.147  3.975
8  5.99146454710798 6    9.167    7.667      1.196    0.158  3.973  2.464
  sd_ratio ppp_sd control
1    6.383  0.000    TRUE
2    3.641  0.000   FALSE
3    7.289  0.000   FALSE
4    3.326  0.000   FALSE
5    5.953  0.000   FALSE
6    6.082  0.000   FALSE
7    3.308  0.000   FALSE
8    1.612  0.062   FALSE

The control group is flagged. nsec() reads its reference from the 
control, so this is the row most likely to move a reported 
no-effect concentration. See ?check_fit.</code></pre>
</div>
</div>
<p><code>obs_sd</code> and <code>sim_sd</code> are the observed and simulated spread within a group, and <code>ppp_sd</code> is the proportion of simulated datasets in which the simulated spread was at least as large as the observed one. Read the p-values rather than the ratios, and read the <code>control</code> row first, because both <code>nsec()</code> and <code>ecx()</code> take their reference from the fitted mean there.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_1nec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-binom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-binom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-binom-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-binom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: <code>check_fit()</code> on the binomial fit. Each point is the observed statistic for one concentration group against the 95% span of what the fit simulates, with location and scale drawn separately.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The groups are labelled on the logged scale, because that is the scale the model was fitted on: -2.30 is the 0.1 control and 5.99 the highest dose of 400. Seven of the eight points on the scale panel sit above their bar, <code>sd_ratio</code> runs from 1.6 to 7.3, and <code>ppp_sd</code> is 0.000 in seven groups. Four of the eight points on the location panel sit outside their bar as well, because a variance held too low leaves the simulated mean too tightly determined to contain the observed one. This is the dispersion ratio of about 18 seen group by group.</p>
<p>The same check on the beta-binomial fit of the same data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>cf_1b <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_1b)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>cf_1b</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       model    wi             group n obs_mean sim_mean mean_ratio ppp_mean
1     ecxll3 0.656 -2.30258509299405 6  106.167  107.500      0.988    0.577
2     ecxll3 0.656  1.83258146374831 6  103.667  105.167      0.986    0.576
3     ecxll3 0.656  2.52572864430826 6   72.833   80.500      0.905    0.860
4     ecxll3 0.656   3.2188758248682 6   85.167   81.500      1.045    0.258
5     ecxll3 0.656  3.91202300542815 6   75.500   74.000      1.020    0.420
6     ecxll3 0.656  4.60517018598809 6   61.500   57.667      1.066    0.367
7     ecxll3 0.656  5.29831736654804 6   19.500   31.333      0.622    0.903
8     ecxll3 0.656  5.99146454710798 6    9.167   11.333      0.809    0.623
9  nec3param 0.344 -2.30258509299405 6  106.167  104.167      1.019    0.407
10 nec3param 0.344  1.83258146374831 6  103.667  102.833      1.008    0.467
11 nec3param 0.344  2.52572864430826 6   72.833   79.667      0.914    0.831
12 nec3param 0.344   3.2188758248682 6   85.167   83.000      1.026    0.364
13 nec3param 0.344  3.91202300542815 6   75.500   81.833      0.923    0.750
14 nec3param 0.344  4.60517018598809 6   61.500   54.333      1.132    0.263
15 nec3param 0.344  5.29831736654804 6   19.500   28.833      0.676    0.839
16 nec3param 0.344  5.99146454710798 6    9.167   14.833      0.618    0.766
   obs_sd sim_sd sd_ratio ppp_sd control
1  25.398 14.435    1.759  0.096    TRUE
2  15.212 14.271    1.066  0.444   FALSE
3  24.582 11.892    2.067  0.058   FALSE
4  11.497 13.376    0.860  0.647   FALSE
5  20.153 16.183    1.245  0.285   FALSE
6  29.205 20.566    1.420  0.116   FALSE
7  14.449 19.532    0.740  0.754   FALSE
8   3.550 12.559    0.283  0.962   FALSE
9  24.874 16.227    1.533  0.149    TRUE
10 14.658 15.962    0.918  0.578   FALSE
11 24.475 12.224    2.002  0.057   FALSE
12 11.373 12.790    0.889  0.594   FALSE
13 20.758 14.383    1.443  0.165   FALSE
14 29.356 20.897    1.405  0.123   FALSE
15 14.110 19.492    0.724  0.772   FALSE
16  3.475 14.184    0.245  0.984   FALSE

One or more groups show a posterior predictive p-value beyond 
[0.05, 0.95]. See ?check_fit.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_1b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-betabinom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-betabinom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-betabinom-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-betabinom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: The same check on the beta-binomial fit, reported for each equation in the set.
</figcaption>
</figure>
</div>
</div>
</div>
<p>No group is flagged on the mean for either equation. On spread, only the highest concentration is flagged, where the fit simulates three to four times the observed variability. Six replicates at a response near complete mortality supply very little information about spread, so this is what the top of a series usually looks like rather than a fault in the family.</p>
<p><code>brms::pp_check()</code> shows the same comparison as distributions rather than as summary statistics, and module 7 uses it on a continuous response. The grouped form is the one to use, <code>type = "dens_overlay_grouped"</code> for a continuous response and <code>type = "bars_grouped"</code> for a discrete one: pooled over the whole dataset a model can match the overall distribution while being wrong at every concentration.</p>
</section>
<section id="beta" class="level2">
<h2 class="anchored" data-anchor-id="beta">Beta</h2>
<p>A response bounded between 0 and 1 that is not a count out of a total is modelled by the beta distribution. Maximum quantum yield from PAM fluorometry is a common example in coral work: a proportion of light used in photosynthesis, with no underlying trials to count.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>prop_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"vignettes/example_proportion.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log.x =</span> <span class="fu">log</span>(raw_x))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>exp_2 <span class="ot">&lt;-</span> <span class="fu">bnec</span>(resp <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ecxll3"</span>, <span class="st">"nec3param"</span>)),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> prop_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_2, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_2.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_2.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_2, <span class="at">all_models =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"
Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-beta" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-beta-1.png" id="fig-beta" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>exp_2<span class="sc">$</span>mod_stats</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              model      waic         wi dispersion_Estimate dispersion_Q2.5
ecxll3       ecxll3 -417.8802 0.01528452                  NA              NA
nec3param nec3param -433.5478 0.98471548                  NA              NA
          dispersion_Q97.5 dispersion_P_over_1
ecxll3                  NA                  NA
nec3param               NA                  NA</code></pre>
</div>
</div>
<p>The beta has two parameters, so it can generally accommodate the variance in the data, and these bounds are reasonable. The threshold model takes most of the weight here and describes the data much better than the three-parameter log-logistic.</p>
<p><code>bnec()</code> also flags the control group for both equations. That is the <code>check_fit()</code> comparison named in module 2, run over every equation in the set and reported where it fails, and the control is singled out because <code>nsec()</code> reads its reference from there. Running <code>check_fit()</code> gives the per-group table:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>cf_2 <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_2)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>cf_2[, <span class="fu">c</span>(<span class="st">"model"</span>, <span class="st">"wi"</span>, <span class="st">"group"</span>, <span class="st">"mean_ratio"</span>, <span class="st">"ppp_mean"</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">"sd_ratio"</span>, <span class="st">"ppp_sd"</span>, <span class="st">"control"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       model    wi             group mean_ratio ppp_mean sd_ratio ppp_sd
1     ecxll3 0.015 -4.60517018598809      0.994    0.590    0.398  1.000
2     ecxll3 0.015 -1.20397280432594      0.983    0.711    0.671  0.979
3     ecxll3 0.015                 0      0.976    0.808    0.376  1.000
4     ecxll3 0.015  1.09861228866811      0.984    0.707    0.616  0.994
5     ecxll3 0.015  2.30258509299405      1.071    0.009    0.410  1.000
6     ecxll3 0.015  3.40119738166216      1.034    0.176    1.660  0.000
7     ecxll3 0.015  4.60517018598809      0.910    0.984    1.135  0.213
8     ecxll3 0.015   5.7037824746562      1.118    0.012    1.402  0.018
9  nec3param 0.985 -4.60517018598809      1.015    0.263    0.414  1.000
10 nec3param 0.985 -1.20397280432594      1.001    0.486    0.708  0.969
11 nec3param 0.985                 0      0.986    0.725    0.395  1.000
12 nec3param 0.985  1.09861228866811      0.980    0.766    0.651  0.991
13 nec3param 0.985  2.30258509299405      1.026    0.170    0.438  1.000
14 nec3param 0.985  3.40119738166216      1.019    0.303    1.758  0.000
15 nec3param 0.985  4.60517018598809      0.954    0.877    1.208  0.118
16 nec3param 0.985   5.7037824746562      1.042    0.220    1.437  0.010
   control
1     TRUE
2    FALSE
3    FALSE
4    FALSE
5    FALSE
6    FALSE
7    FALSE
8    FALSE
9     TRUE
10   FALSE
11   FALSE
12   FALSE
13   FALSE
14   FALSE
15   FALSE
16   FALSE

The control group is flagged. nsec() reads its reference from the 
control, so this is the row most likely to move a reported 
no-effect concentration. See ?check_fit.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-beta" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-beta-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: <code>check_fit()</code> on the beta fit, reported for each equation in the set. The eight concentrations are design points with twenty replicates each, so no binning is needed.
</figcaption>
</figure>
</div>
</div>
</div>
<p><code>nec3param</code> holds 0.99 of the weight, so it is the row set to read. Its group means are reproduced, with <code>mean_ratio</code> at the control of 1.01 and every point in its location panel inside its bar; <code>ecxll3</code> misses on location in three groups of eight, which is what an equation of the wrong shape looks like and is why it holds the weight it does. What fails for both is the spread: <code>sd_ratio</code> at the control is 0.41, so the fit simulates about two and a half times the variability the twenty control replicates show, and <code>ppp_sd</code> of 1.00 puts the observed spread at the extreme of what the fit produces. The cause is that a beta fit holds one precision parameter across the whole series while the observed variability in these data rises with concentration, which <em>Modelling dispersion</em> below takes apart and measures. Do not report an <em>NSEC</em> from this fit without reading that section.</p>
<p>The predictor was logged in the formula, as in the binomial example above. Estimates returned by <code>nec()</code>, <code>nsec()</code> and <code>ecx()</code> are then on the log scale, and <code>xform = exp</code> returns them to concentrations.</p>
<section id="values-on-the-boundary" class="level3">
<h3 class="anchored" data-anchor-id="values-on-the-boundary">Values on the boundary</h3>
<p>A beta distribution is defined on the <em>open</em> interval between 0 and 1, so a response recorded as exactly 0 or exactly 1 lies outside it. This is common: complete mortality at the highest concentration, or complete survival in the controls, both produce boundary values.</p>
<p><code>bayesnec</code> shifts them rather than refusing the fit. A zero becomes one tenth of the smallest non-zero value in the response, which scales with the data, and a one is reduced by an absolute 0.001. <code>bnec_record()</code> names every value it altered:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bnec_record</span>(exp_2)<span class="sc">$</span>substitutions</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
</div>
<p><code>NULL</code> means the response was fitted as recorded. Where it is not <code>NULL</code>, the analysis was run on shifted values, and a series with several concentrations sitting at a boundary is being modelled through that shift rather than as measured. A methods section has to say so.</p>
<p>Where the boundary values mean something different from a very small response — an organism that died, rather than one that grew very little — the shift is the wrong treatment altogether. The section on zeros below covers that case.</p>
</section>
</section>
<section id="poisson" class="level2">
<h2 class="anchored" data-anchor-id="poisson">Poisson</h2>
<p>Counts of whole things — individuals, cells — are theoretically Poisson distributed: integers from zero upwards. This example builds over-dispersed counts from the package’s example data, in order to show what the negative binomial is for. Real count data are sometimes genuinely Poisson, so check before assuming otherwise.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(nec_data)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>count_data <span class="ot">&lt;-</span> nec_data <span class="sc">|&gt;</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> (y <span class="sc">*</span> <span class="dv">100</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(nec_data), <span class="dv">0</span>, <span class="dv">15</span>)) <span class="sc">|&gt;</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>() <span class="sc">|&gt;</span> <span class="fu">as.integer</span>() <span class="sc">|&gt;</span> <span class="fu">abs</span>()</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(count_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  2 variables:
 $ x: num  1.019 0.816 0.371 0.401 1.295 ...
 $ y: int  85 120 54 96 64 88 111 92 99 86 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>exp_3 <span class="ot">&lt;-</span> <span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ecxll3"</span>, <span class="st">"nec3param"</span>)), <span class="at">data =</span> count_data)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_3, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_3.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_3.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_3, <span class="at">all_models =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"
Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-pois" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pois-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-pois-1.png" id="fig-pois" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-pois-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8
</figcaption>
</figure>
</div>
</div>
</div>
<p>The dispersion screen applies here for the same reason it applied to the binomial: a Poisson has one parameter, so its variance is fixed by its mean. <code>dispersion()</code> takes a single fit and stops on a model set, so for a set the figures are read from the summary, which reports them for every equation alongside its weight:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_3)<span class="sc">$</span>mod_weights</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              waic         wi dispersion_Estimate dispersion_Q2.5
ecxll3    988.9497 0.07795462            3.534905        2.713561
nec3param 957.5460 0.92204538            3.226219        2.482026
          dispersion_Q97.5 dispersion_P_over_1
ecxll3            4.734219                   1
nec3param         4.333053                   1</code></pre>
</div>
</div>
<p><code>nec3param</code> holds 0.92 of the weight and its dispersion estimate is 3.23, with a 95% interval from 2.48 to 4.33 and <code>P(&gt;1)</code> of 1. These counts are about three times more variable than a Poisson allows.</p>
<p>Read the dispersion against the weight rather than on its own. A ratio computed for an equation that fits badly counts the variation its curve cannot describe as dispersion, so it fails the screen whatever the data are doing, and it holds almost no weight for the same reason. A failure matters where it belongs to an equation that contributes to the averaged estimate, which is the case here.</p>
<p><code>check_fit()</code> shows where that extra variation sits. These counts were built from <code>nec_data</code>, whose predictor takes a different value in almost every replicate, so there are no concentration groups to compare within and <code>check_fit()</code> cuts the predictor into ten bins instead. A bin is not a design point, so read the pattern across the bins rather than any single row.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check_fit</span>(exp_3))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-pois" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-pois-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-pois-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-pois-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: <code>check_fit()</code> on the Poisson fit, with the predictor cut into ten bins.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The means are reproduced, one bin excepted. On spread, six of the ten bins for <code>nec3param</code> sit above their bar, and every bin has <code>sd_ratio</code> above 1, running from 1.11 to 2.70 with the two largest values in the top two bins. The counts are more variable than a Poisson allows across the whole series rather than in one part of it.</p>
<section id="counts-observed-over-an-exposure" class="level3">
<h3 class="anchored" data-anchor-id="counts-observed-over-an-exposure">Counts observed over an exposure</h3>
<p>A count is very often observed over an exposure that differs between replicates: offspring counted where the number of fecund adults differs, cells counted over different areas, events counted over different lengths of time. The <code>rate</code> term declares that exposure, and is available for the Poisson and negative binomial families:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>y <span class="sc">|</span> <span class="fu">rate</span>(n_females) <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The raw counts are passed to <code>bnec()</code> unchanged, so a replicate with twenty females contributes more information than one with eight. Fitting <code>y / n_females</code> as a continuous response would discard exactly that.</p>
<p>Because <code>bayesnec</code> uses an identity link, <code>brms</code> applies the denominator multiplicatively on the response scale rather than as a log offset on a linear predictor. The fitted mean therefore <em>is</em> the rate, and <code>top</code>, <code>bot</code> and <code>nec</code> are directly interpretable as offspring per female. The prediction grid holds the denominator at 1, and <code>autoplot()</code> divides the observed counts through to match.</p>
<p>One caveat decides whether <code>rate</code> is the right tool. Where the exposure varies for reasons unrelated to the treatment, because a replicate simply received fewer animals, <code>rate</code> does what is wanted. Where the exposure is itself an effect of the treatment, as it would be if the denominator were the number of females <em>surviving</em> to the point of counting, the endpoint has quietly changed from reproductive output to fecundity conditional on survival. Both are legitimate endpoints and they will not return the same <em>NEC</em>.</p>
</section>
</section>
<section id="negative-binomial" class="level2">
<h2 class="anchored" data-anchor-id="negative-binomial">Negative binomial</h2>
<p>The Poisson has one parameter, so like the binomial its variance is determined by its mean. Counts that are more variable than that need the negative binomial, which estimates the additional variation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>exp_3b <span class="ot">&lt;-</span> <span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ecxll3"</span>, <span class="st">"nec3param"</span>)),</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> count_data, <span class="at">family =</span> <span class="st">"negbinomial"</span>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_3b, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_3b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_3b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_3b, <span class="at">all_models =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"
Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-negbin" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-negbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-negbin-1.png" id="fig-negbin" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-negbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10
</figcaption>
</figure>
</div>
</div>
</div>
<p>The bounds widen, as they did for the beta-binomial, and for the same reason.</p>
<p>The same check on this fit:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check_fit</span>(exp_3b))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-negbin" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-negbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-negbin-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-negbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: <code>check_fit()</code> on the negative binomial fit of the same counts.
</figcaption>
</figure>
</div>
</div>
</div>
<p>No bin is flagged on the mean. On spread, two of the ten bins for <code>nec3param</code> sit outside their bar against six under the Poisson, and <code>sd_ratio</code> now runs from 0.54 to 1.90, so the misses fall on both sides rather than all in one direction. The two are the highest bin, where the fit simulates less spread than the counts show, and one in the middle of the decline, where it simulates about twice as much.</p>
</section>
<section id="gamma" class="level2">
<h2 class="anchored" data-anchor-id="gamma">Gamma</h2>
<p>A continuous response that cannot be negative — a length, a mass, a rate where shrinkage is impossible — is modelled by the gamma.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(nec_data)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>measure_data <span class="ot">&lt;-</span> nec_data <span class="sc">|&gt;</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">measure =</span> <span class="fu">exp</span>(y))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>exp_4 <span class="ot">&lt;-</span> <span class="fu">bnec</span>(measure <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ecxll3"</span>, <span class="st">"nec3param"</span>)),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> measure_data)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_4, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_4.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_4.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_4, <span class="at">all_models =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"
Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-gamma" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gamma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-gamma-1.png" id="fig-gamma" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gamma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12
</figcaption>
</figure>
</div>
</div>
</div>
<p>A gamma has two parameters, so like the beta and the negative binomial it estimates its own spread rather than fixing it by the mean. What it does fix is the <em>relative</em> spread: a gamma holds the coefficient of variation constant, so the standard deviation it simulates is a fixed fraction of the fitted mean. Whether that suits the data is what the check answers.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>cf_4 <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_4)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-gamma" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-gamma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-gamma-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-gamma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: <code>check_fit()</code> on the gamma fit. The predictor takes a different value in almost every replicate, so the range is cut into ten bins.
</figcaption>
</figure>
</div>
</div>
</div>
<p><code>nec3param</code> holds essentially all of the weight, so read its two panels. Its means are reproduced across the series, one bin excepted. Its spread is not, and the failure is the one the family’s own assumption predicts: the simulated coefficient of variation is 0.06 in every bin, while the observed one rises from 0.04 at the control to 0.11 at the top of the series. The consequence is a <code>sd_ratio</code> below 1 over the flat part of the curve, where the fit simulates about half again the spread the data show, and above 1 at the highest concentrations, where it simulates less than the data show.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>cf_4b <span class="ot">&lt;-</span> <span class="fu">subset</span>(<span class="fu">as.data.frame</span>(cf_4), model <span class="sc">==</span> <span class="st">"nec3param"</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">group =</span> cf_4b<span class="sc">$</span>group,</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">observed_cv =</span> <span class="fu">round</span>(cf_4b<span class="sc">$</span>obs_sd <span class="sc">/</span> cf_4b<span class="sc">$</span>obs_mean, <span class="dv">3</span>),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">simulated_cv =</span> <span class="fu">round</span>(cf_4b<span class="sc">$</span>sim_sd <span class="sc">/</span> cf_4b<span class="sc">$</span>sim_mean, <span class="dv">3</span>),</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">sd_ratio =</span> <span class="fu">round</span>(cf_4b<span class="sc">$</span>sd_ratio, <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            group observed_cv simulated_cv sd_ratio
1  [0.0323,0.235]       0.040        0.061     0.66
2   (0.235,0.378]       0.043        0.060     0.72
3   (0.378,0.562]       0.025        0.061     0.41
4   (0.562,0.726]       0.038        0.061     0.62
5   (0.726,0.876]       0.033        0.061     0.56
6    (0.876,1.17]       0.044        0.059     0.75
7     (1.17,1.45]       0.049        0.061     0.81
8     (1.45,1.72]       0.066        0.061     1.14
9     (1.72,2.07]       0.071        0.061     1.11
10    (2.07,3.22]       0.106        0.062     1.65</code></pre>
</div>
</div>
<p>A constant coefficient of variation is exactly what a gamma asserts, so this is the family being wrong about these data rather than the fit being run badly. <em>Modelling dispersion</em> below is the repair, and it is the same pattern the beta example showed on a different family: the response type points at a family, and the check decides whether that family can describe the spread as well as the range.</p>
</section>
<section id="gaussian" class="level2">
<h2 class="anchored" data-anchor-id="gaussian">Gaussian</h2>
<p>A continuous response that can take negative values is modelled by the Gaussian. Growth rates are the usual case, where an organism may shrink, and so are responses that have been transformed onto an unbounded scale. Here the proportion data above are put on a logit scale.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>gaussian_data <span class="ot">&lt;-</span> prop_data <span class="sc">|&gt;</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> car<span class="sc">::</span><span class="fu">logit</span>(resp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>exp_5 <span class="ot">&lt;-</span> <span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ecxll4"</span>, <span class="st">"nec4param"</span>)),</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> gaussian_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_5, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_5.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_5.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_5, <span class="at">all_models =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"
Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-gauss" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gauss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-gauss-1.png" id="fig-gauss" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gauss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14
</figcaption>
</figure>
</div>
</div>
</div>
<p>Transforming a bounded response onto an unbounded scale and modelling it as Gaussian is one way of handling proportion data, and it was standard practice before generalised methods were routine. Modelling the response on its own scale with the beta, as above, is preferable: it keeps the parameters interpretable as proportions, and it does not require the transformation to have made the variance constant.</p>
<p><code>check_fit()</code> measures the last of those. These are the proportion data of the beta example, so the eight concentrations are design points with twenty replicates each and no binning is needed:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>cf_5 <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_5)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>cf_5[, <span class="fu">c</span>(<span class="st">"model"</span>, <span class="st">"wi"</span>, <span class="st">"group"</span>, <span class="st">"sd_ratio"</span>, <span class="st">"ppp_sd"</span>, <span class="st">"control"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       model    wi             group sd_ratio ppp_sd control
1     ecxll4 0.366 -4.60517018598809    0.399  1.000    TRUE
2     ecxll4 0.366 -1.20397280432594    0.685  0.976   FALSE
3     ecxll4 0.366                 0    0.377  1.000   FALSE
4     ecxll4 0.366  1.09861228866811    0.624  0.988   FALSE
5     ecxll4 0.366  2.30258509299405    0.425  1.000   FALSE
6     ecxll4 0.366  3.40119738166216    1.705  0.001   FALSE
7     ecxll4 0.366  4.60517018598809    1.316  0.042   FALSE
8     ecxll4 0.366   5.7037824746562    1.502  0.003   FALSE
9  nec4param 0.634 -4.60517018598809    0.402  1.000    TRUE
10 nec4param 0.634 -1.20397280432594    0.687  0.977   FALSE
11 nec4param 0.634                 0    0.381  1.000   FALSE
12 nec4param 0.634  1.09861228866811    0.625  0.988   FALSE
13 nec4param 0.634  2.30258509299405    0.424  1.000   FALSE
14 nec4param 0.634  3.40119738166216    1.710  0.001   FALSE
15 nec4param 0.634  4.60517018598809    1.313  0.043   FALSE
16 nec4param 0.634   5.7037824746562    1.517  0.002   FALSE</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-gauss" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-gauss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-gauss-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-gauss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: <code>check_fit()</code> on the Gaussian fit of the logit-transformed proportions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The means are reproduced for both equations. The spread is not, and it misses in opposite directions at the two ends of the series. For <code>nec4param</code>, <code>sd_ratio</code> is 0.38 at the control, where the fit simulates about two and a half times the observed variability, and it is above 1.3 at the three highest concentrations, where it simulates less variability than the data show. One standard deviation is describing a series whose variability changes with concentration, and the logit transformation has not removed that change. <em>Modelling dispersion</em> below takes the same data on the beta scale and measures what the <code>disp</code> term does about it.</p>
<section id="growth-rates" class="level3">
<h3 class="anchored" data-anchor-id="growth-rates">Growth rates</h3>
<p>A growth rate is the common Gaussian case in ecotoxicology, and it comes with a naming convention that is worth getting right. OECD Test Guideline 201 <span class="citation" data-cites="oecd2026tg201">(<a href="#ref-oecd2026tg201" role="doc-biblioref">OECD 2026</a>)</span> distinguishes two response variables from the same experiment. The average specific growth rate is the logarithmic increase in biomass over the exposure period, and an effect concentration derived from it is written <strong>ErC<sub>x</sub></strong>. Yield is the biomass at the end of the period minus the biomass at the start, and its effect concentration is written <strong>EyC<sub>x</sub></strong>. The guideline states that an ErC<sub>x</sub> will generally be higher than the corresponding EyC<sub>x</sub>, and that growth rate is the scientifically preferred basis; yield is retained to satisfy current regulatory requirements. An estimate reported without one of those prefixes has not said which quantity it describes.</p>
<p>A growth rate can be negative, because a population can decline. That rules out every family bounded below at zero, and it also rules out the equations whose lower asymptote is fixed at zero, since those cannot predict a negative response. The <code>bayesnec</code> article on growth data and other potentially negative responses covers the consequences, which reach the choice of both the family and the candidate set.</p>
</section>
</section>
<section id="model-suitability-by-response-type" class="level2">
<h2 class="anchored" data-anchor-id="model-suitability-by-response-type">Model suitability by response type</h2>
<p>Not every equation suits every family. A model predicting negative values cannot be used with a response that must be positive, and <code>bayesnec</code> discards any model in a requested set that is unsuitable for the distribution of the response. This is why a set of twenty-three may return fewer than twenty-three fits, and why the <code>zero_bounded</code> set exists.</p>
<p>Three rules account for most of the exclusions.</p>
<p>Equations with an exponential decay and no <code>bot</code> parameter approach zero and cannot go below it, so they cannot describe a Gaussian response, or any response fitted through a log or logit link.</p>
<p>Equations with a linear decay, whose names contain <code>lin</code>, decline without limit, so they cannot describe a response bounded below at zero under an identity link. That covers the gamma, Poisson, negative binomial, binomial, beta and beta-binomial families.</p>
<p>Equations that raise the predictor to a fractional power cannot be evaluated where the predictor is negative, which a logged concentration series is wherever the concentration falls below 1.</p>
<p>You do not have to apply these yourself. <code>bnec()</code> excludes what it cannot fit and reports the reason, and <code>bnec_record()</code> keeps that reason on the fitted object:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bnec_record</span>(exp_2)<span class="sc">$</span>excluded</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] model  reason
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<p>No rows, because that fit named two equations explicitly and both are valid for a beta response on an identity link. A set requested as <code>"all"</code> on the same data returns several rows, with the rule each equation failed against.</p>
</section>
<section id="censored-values" class="level2">
<h2 class="anchored" data-anchor-id="censored-values">Censored values</h2>
<p>Everything above assumes each recorded value is a measurement of the response. In real datasets some are not. A value below a detection limit and a zero that marks a death are both written down as numbers and neither is a measurement of the response, and the two need different treatment from one another. This section and the two that follow take them in turn.</p>
<p>A value is <strong>censored</strong> when the truth is known to lie in an interval rather than at a point: a concentration below a limit of detection, a cell count below the resolution of the counting method, a value rounded at the precision it was recorded to. The number written down is a <em>bound</em> rather than a measurement.</p>
<p>The usual treatments are to substitute something for it, commonly half the detection limit, or to delete the row. <span class="citation" data-cites="helsel2006">Helsel (<a href="#ref-helsel2006" role="doc-biblioref">2006</a>)</span> reviewed two decades of work on both and is blunt about the first: substituted values using any fraction between 0 and 0.99 of the detection limit are “equivalently arbitrary, equivalently precise, equivalently wrong”. Deleting is worse, because it removes the observations at the low end and biases every subsequent estimate of location upwards.</p>
<p><code>bayesnec</code> passes through the <code>cens()</code> term from <code>brms</code>, so the bound can be declared instead of disguised:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>y <span class="sc">|</span> <span class="fu">cens</span>(censoring) <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>censoring</code> is a column in the data rather than a constant, because in a concentration-response dataset only some rows are censored. It takes the values <code>"none"</code>, <code>"left"</code>, <code>"right"</code> or <code>"interval"</code>. Interval censoring takes a second argument giving the upper bound, as <code>cens(censoring, upper)</code>.</p>
<p>The response column holds the bound. On a left-censored row, the number in the response column is the value the truth is known to be at or below, rather than zero and rather than a guess at the unknown truth.</p>
<p>What this changes is the contribution each row makes to the likelihood. An ordinary row contributes a density at a point, which falls away as the fitted curve departs from it, so a substituted value actively pulls the curve back towards the number that was substituted. A censored row instead contributes the probability of falling at or below the bound. As the curve descends past the bound that probability rises towards 1 and then <em>saturates</em>: the curve is neither rewarded for passing further below nor penalised for it.</p>
</section>
<section id="zeros" class="level2">
<h2 class="anchored" data-anchor-id="zeros">Zeros</h2>
<p>A zero needs a different treatment depending on what produced it, and the three cases are distinguishable from the design rather than from the data.</p>
<p>A zero that is a measurement below the resolution of the method is censored, and belongs in the previous section.</p>
<p>A zero that marks a distinct event is <strong>structural</strong>. An organism that died did not grow slowly; its growth is undefined rather than small. A response of this kind has two processes behind it, one deciding whether the event occurred and one generating the response when it did not, and a <strong>two-block</strong> model fits both.</p>
<p>A zero that is an ordinary draw from a distribution admitting zeros is not evidence of anything at all. <span class="citation" data-cites="warton2005">Warton (<a href="#ref-warton2005" role="doc-biblioref">2005</a>)</span> makes the point directly: many zeros does not mean zero inflation, and a Poisson or negative binomial with a low mean produces plenty of them. Fit the simpler family and check it before reaching for a two-block model. <span class="citation" data-cites="martin2005">Martin et al. (<a href="#ref-martin2005" role="doc-biblioref">2005</a>)</span> sets out how to decide which of the three you are looking at, from what the experiment did rather than from a test.</p>
</section>
<section id="hurdle-and-zero-inflated-models" class="level2">
<h2 class="anchored" data-anchor-id="hurdle-and-zero-inflated-models">Hurdle and zero-inflated models</h2>
<p>Both names describe a two-block model and they are not interchangeable. The distinction is whether the zeros are <strong>observed</strong> or <strong>latent</strong>, and it decides whether the second block is worth interpreting.</p>
<p>Under a <strong>hurdle</strong> the zeros are observed to be structural. The individual died, or the replicate failed, and you know which observations those are. The likelihood then separates exactly into a block for whether the event occurred and a block for the response given that it did not, and both blocks describe a curve you can read a threshold from.</p>
<p>Under <strong>zero inflation</strong> a zero could have come from either component, and nothing in the data says which. The two are therefore weakly separated precisely where the ordinary component is small, which is the high-concentration end that determines the <em>NEC</em>. A threshold fitted to the zero-inflation component there describes a class of observation nobody measured.</p>
<p>The practical rule follows from the design rather than from the data. Where you recorded <em>why</em> each zero occurred, a hurdle is available and its second block means something. Where you did not, zero inflation is the description the data support, and the second block should not be read as a concentration-response curve.</p>
<p><code>bayesnec</code> supplies <code>hurdle_gamma</code> for a positive continuous response with structural zeros, and the zero-inflated beta, Poisson and negative binomial:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bayesnec<span class="sc">:::</span>mod_fams)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "gaussian"                  "Gamma"                    
 [3] "poisson"                   "negbinomial"              
 [5] "bernoulli"                 "binomial"                 
 [7] "beta_binomial"             "beta"                     
 [9] "hurdle_gamma"              "zero_inflated_beta"       
[11] "zero_inflated_poisson"     "zero_inflated_negbinomial"
[13] "hurdle_poisson"            "hurdle_negbinomial"       </code></pre>
</div>
</div>
<p><code>bnec_hurdle()</code> and <code>bnec_joint()</code> fit the two blocks. The worked example below fits one; the <a href="https://open-aims.github.io/bayesnec/dev/articles/example6.html"><code>bayesnec</code> article on hurdle and zero-inflated models</a> covers the rest, including the crossed weights of the two model sets and when the joint form is needed rather than the factorised one.</p>
<p>One trap is worth naming even though it is not taught. Fitting the positive part of a count response by dropping the zeros and using an ordinary Poisson is not the same model: with the zeros removed the remaining counts follow a <em>zero-truncated</em> Poisson, so an untruncated fit estimates the wrong quantity. The error grows as the mean falls towards zero, which is the high-concentration end that an <em>NEC</em> or an <strong>EC<sub>x</sub></strong> is read from. The equivalent construction for <code>hurdle_gamma</code> is exact, because a gamma distribution has no mass at zero to begin with, which is why the problem appears only for counts.</p>
<section id="a-hurdle-gamma-in-practice" class="level3">
<h3 class="anchored" data-anchor-id="a-hurdle-gamma-in-practice">A hurdle gamma in practice</h3>
<p>The <code>nassarius</code> dataset ships with <code>bayesnec</code> and holds chronic toxicity tests on the tropical marine snail <em>Nassarius dorsatus</em>, one row per individual snail that entered the experiment. The contaminants are anonymised as A to D and the dose units are not stated, so only the relative spacing of doses is preserved, which is all a toxicity estimate depends on. Contaminant A is used here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(nassarius)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>snail <span class="ot">&lt;-</span> <span class="fu">subset</span>(nassarius, contaminant <span class="sc">==</span> <span class="st">"A"</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(snail)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   204 obs. of  6 variables:
 $ contaminant: Factor w/ 4 levels "A","B","C","D": 1 1 1 1 1 1 1 1 1 1 ...
 $ dose       : num  0 0 0 0 0 0 0 0 0 0 ...
 $ tank       : chr  "A-1" "A-1" "A-1" "A-1" ...
 $ alive      : int  1 1 1 1 1 0 1 1 1 1 ...
 $ growth     : num  8.72 28.17 27.28 15.86 19.02 ...
 $ record     : Factor w/ 5 levels "measured","sentinel_code",..: 1 1 1 1 1 2 1 1 1 1 ...</code></pre>
</div>
</div>
<p>The response is growth, which is positive and continuous, so the survivors are a gamma. <code>alive</code> records which snails died, so the zeros are observed rather than inferred and a hurdle is available.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(snail<span class="sc">$</span>alive, snail<span class="sc">$</span>dose, <span class="cf">function</span>(z) <span class="fu">sprintf</span>(<span class="st">"%d of %d"</span>, <span class="fu">sum</span>(z), <span class="fu">length</span>(z)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         0       0.01       0.02       0.04       0.08       0.16       0.31 
"21 of 24" "17 of 18" "18 of 18" "17 of 18" "18 of 18" "18 of 18" "18 of 18" 
      0.63       1.25        2.5         20 
"18 of 18" "18 of 18"  "3 of 18"  "0 of 18" </code></pre>
</div>
</div>
<p>Mortality is confined to the top two doses and is complete at the highest. That is what makes the endpoint worth fitting as two blocks rather than one. A survivors-only analysis of these data would contain 166 snails of the 204 exposed, and the dose of 20 would not appear in it at all, because a dose at which nothing survived contributes no rows. The dose that killed every animal is the most informative one in the experiment and it is the one that dropping the dead removes.</p>
<p>Two preparation steps are needed and both are stated rather than done quietly. The assay references each snail to a baseline mean rather than to its own starting size, so a few survivors are recorded at or below zero; those are measurement noise around a true value near zero rather than deaths, and they are nudged to half the smallest positive growth in the test. And the doses span several orders of magnitude, so the fit is on a log scale, which needs the control placed somewhere other than <code>log(0)</code>: one decade below the lowest tested dose is far enough to read as a control and close enough not to stretch the fitted range.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>pos_min <span class="ot">&lt;-</span> <span class="fu">min</span>(snail<span class="sc">$</span>growth[snail<span class="sc">$</span>growth <span class="sc">&gt;</span> <span class="dv">0</span>])</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>snail<span class="sc">$</span>growth <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(snail<span class="sc">$</span>alive <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> snail<span class="sc">$</span>growth <span class="sc">&lt;=</span> <span class="dv">0</span>, pos_min <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>                       snail<span class="sc">$</span>growth)</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>offset <span class="ot">&lt;-</span> <span class="fu">min</span>(snail<span class="sc">$</span>dose[snail<span class="sc">$</span>dose <span class="sc">&gt;</span> <span class="dv">0</span>]) <span class="sc">/</span> <span class="dv">10</span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>snail<span class="sc">$</span>log_dose <span class="ot">&lt;-</span> <span class="fu">log</span>(snail<span class="sc">$</span>dose <span class="sc">+</span> offset)</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>back <span class="ot">&lt;-</span> <span class="cf">function</span>(z) <span class="fu">exp</span>(z) <span class="sc">-</span> offset</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>bnec_hurdle()</code> takes the formula for the growth block and fits a survival block alongside it. The same model set is used for both here, and <code>adapt_delta</code> is raised because the survival curve is determined by two doses and samples awkwardly at the default.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>exp_6 <span class="ot">&lt;-</span> <span class="fu">bnec_hurdle</span>(growth <span class="sc">~</span> <span class="fu">crf</span>(log_dose, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"nec3param"</span>, <span class="st">"ecxll3"</span>)),</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> snail, <span class="at">seed =</span> <span class="dv">333</span>,</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_6, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_6.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_6.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_6, <span class="at">xform =</span> back)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Object of class bayesnechurdlefit

   204 individuals exposed; 38 recorded as zero ( 18.6% )

  growth   : gamma -- nec3param, ecxll3 
  survival : bernoulli -- nec3param, ecxll3 

No-effect toxicity estimates
                   Q50 Q2.5 Q97.5
combined (N(S)EC) 0.56 0.21  0.75
growth (N(S)EC)   0.56 0.23  0.75
survival (N(S)EC) 1.72 1.09  2.41

NSEC values appear where a model set contains smooth (ECx) models, which
carry no threshold parameter; N(S)EC is a model-averaged combination
of the two (Fisher et al. 2023).

The combined endpoint is the expected response per individual exposed,
i.e. growth * survival. Use which = to select a component.</code></pre>
</div>
</div>
<p>Three estimates are reported rather than one. <strong>Growth</strong> is the response of the snails that lived, which is what a survivors-only analysis would return. <strong>Survival</strong> is the probability of living to be measured. <strong>Combined</strong> is the expected growth per individual <em>exposed</em>, which is growth multiplied by survival, and it is the endpoint a risk assessment asks about, because an individual that died did not grow.</p>
<p>Growth and survival separate: growth declines from a no-effect estimate of about 0.56 while survival holds to about 1.72, a factor of three. The combined estimate follows growth here, because growth is the more sensitive of the two and the combined endpoint is bounded by whichever declines first.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_6, <span class="at">which =</span> <span class="st">"all"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-nass" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-nass-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Contaminant A as three curves: the combined endpoint, the growth of survivors, and the probability of survival. The predictor is on the log dose scale the fit used.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The right-hand panel is the one a survivors-only analysis cannot produce at any level of effort. Its shape comes entirely from the two doses where snails died, and the highest of those contributes no rows to a dataset of survivors.</p>
</section>
</section>
<section id="preparing-the-response" class="level2">
<h2 class="anchored" data-anchor-id="preparing-the-response">Preparing the response</h2>
<p>Supply the response as it was measured, and match a statistical family to it. The common alternative is to convert it first, to percent inhibition, percent of control or percent of the observed maximum. That conversion introduces error, and the family choice set out above avoids it.</p>
<p>Normalising to the control is conventional in ecotoxicology, usually as <span class="math inline">\(y^0_i = 1 - y_i / \bar{y}_{con}\)</span>, where <span class="math inline">\(\bar{y}_{con}\)</span> is the mean of three to six control replicates. <span class="citation" data-cites="Ritz2026">Ritz et al. (<a href="#ref-Ritz2026" role="doc-biblioref">2026</a>)</span> measured what it does.</p>
<div id="fig-ritz" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ritz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Ritz_etal2026.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ritz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Ritz, Gerhard and Streibig (2026), the source of the measurements in this section.
</figcaption>
</figure>
</div>
<ul>
<li>Every observation is divided by the <em>same random quantity</em>, so the normalised values are correlated and the sampling variability of the divisor is discarded.</li>
<li>The expected value of a reciprocal is not the reciprocal of an expected value, so the inhibition trend is biased downwards and the effect concentrations read off it are biased upwards.</li>
<li>Nothing is lost by leaving the response alone. The concentration at which inhibition rises by <span class="math inline">\(x\)</span> per cent is the concentration at which the response falls by <span class="math inline">\(x\)</span> per cent, and the second is what <code>ecx()</code> returns by default.</li>
<li>Dividing by the observed maximum instead of the control mean is worse again, and it forces one observation onto the boundary of the beta’s support.</li>
<li>Where a divisor is unavoidable it must be a constant fixed in advance of the analysis, such as a physiological or design ceiling.</li>
<li><code>bnec()</code> looks for both practices and reports them.</li>
</ul>
<p>Many proportional responses need no divisor at all. The maximum quantum yield used in module 7 is a genuine physical proportion, as is a survival fraction or a bleached-area fraction, and these are modelled as they stand.</p>
<div class="callout callout-style-default callout-note callout-titled" title="The size of the error">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The size of the error
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>From the simulation of an ED10 with six control replicates in <span class="citation" data-cites="Ritz2026">Ritz et al. (<a href="#ref-Ritz2026" role="doc-biblioref">2026</a>)</span>: normalising gave a bias of 6.8% and a coefficient of variation of 26.4%, against 2.1% and 12.7% for the same quantity estimated from the raw response, and nominal 95% intervals covered at 90% rather than 95%. With a single control replicate the coverage of the normalised analysis fell to 57%.</p>
<p><code>ecx()</code> returns a decline relative to the <em>fitted</em> control rather than to an observed control mean, and because it is evaluated separately within every posterior draw the uncertainty about the control level propagates into the credible interval instead of being thrown away.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Division by the observed maximum">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Division by the observed maximum
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Dividing by the observed maximum is worse than dividing by the control mean on three counts. An extreme order statistic is more variable and more biased than a mean of three to six values. The divisor then depends on every treatment rather than on the controls alone, so treated groups partly determine their own denominator. And it forces exactly one observation to exactly 1, which is outside the open interval a beta distribution is defined on, so <code>bnec()</code> has to shift it off the boundary.</p>
<p><code>bnec()</code> detects both practices from the response as supplied. Dividing by the observed maximum leaves a maximum of exactly 1 attained by exactly one observation, and dividing by the control mean leaves the control observations averaging to exactly 1. The first check is suppressed where the response lies on a rational grid, because a genuine count-derived proportion such as 19 of 20 surviving routinely produces a single observation at 1 and is not evidence of anything.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="A divisor fixed in advance">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A divisor fixed in advance
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A response above 1 that has to be modelled with a beta distribution needs a divisor. It must be a constant settled before the analysis: a physiological or design ceiling, or a value from accumulated historical controls. <span class="citation" data-cites="Ritz2026">Ritz et al. (<a href="#ref-Ritz2026" role="doc-biblioref">2026</a>)</span> are explicit that the problem is dividing by something <em>random</em> rather than dividing as such. An <strong>EC<sub>x</sub></strong> is unaffected by the choice of a constant divisor, because it is a relative decline from the fitted <code>top</code>, and the same holds for any linear rescaling of the response <span class="citation" data-cites="Weimer2012">(<a href="#ref-Weimer2012" role="doc-biblioref">Weimer et al. 2012</a>)</span>.</p>
</div>
</div>
</div>
<section id="the-reason-a-divisor-gets-reached-for" class="level3">
<h3 class="anchored" data-anchor-id="the-reason-a-divisor-gets-reached-for">The reason a divisor gets reached for</h3>
<p>Dividing by the observed maximum is often done for a reason that has nothing to do with normalisation. A response on an arbitrary scale, such as a luminescence reading or a cell count, is divided to put it between 0 and 1 so that a beta distribution can be used, because the beta accommodates variability that changes with the mean and a Gaussian does not.</p>
<p>That reasoning identifies a real problem and answers it indirectly. The problem is that replicate variability at the high concentrations is not the same as at the control. The direct answer is the subject of this module: keep the response on its own scale, choose the family that suits it, and model the variability explicitly where it changes. The sections above covered the choice of family, and the section below covers the <code>disp</code> term for a dispersion that varies across the series.</p>
<p>Doing it that way keeps <code>top</code>, <code>bot</code> and <code>nec</code> in the units the experiment was measured in, avoids the bias <span class="citation" data-cites="Ritz2026">Ritz et al. (<a href="#ref-Ritz2026" role="doc-biblioref">2026</a>)</span> measured, and states the change in variability as something estimated from the data rather than absorbed by a transformation. It also avoids forcing an observation onto the boundary of the beta’s support, which division by a maximum does by construction.</p>
</section>
</section>
<section id="modelling-dispersion" class="level2">
<h2 class="anchored" data-anchor-id="modelling-dispersion">Modelling dispersion</h2>
<p>Everything above chooses a family from what kind of quantity the response is. Sometimes the family that is right on those grounds still fails the check: it cannot reproduce the observed spread across the concentration range, and <code>check_fit()</code> says so. Three fits above are such a case: the beta fit of the proportion data, the Gaussian fit of the same data on a logit scale, and the gamma fit, whose constant coefficient of variation the data do not have. This section is what to do about it.</p>
<p>The reason a correct family can still fail is an assumption made by default and rarely stated. A fit holds the dispersion parameter of the chosen family constant across the whole concentration-response curve. For a Gaussian response that assumes replicate variability is the same at every concentration; for the other families it assumes the coefficient of variation, or the precision, does not change with the mean. Real series often violate it, because variability at a concentration that has killed most of the organisms is not the variability of an untreated control.</p>
<p>Where that is wrong the consequences fall on the credible intervals of the toxicity estimates, and they fall unevenly, because the assumed variability is too large at one end of the series and too small at the other. The <em>NSEC</em> is affected most, for the reason the binomial section gave: its reference is a quantile of the control posterior, and the width of that posterior is the variability the fit estimated at the control.</p>
<p>The <code>disp</code> term relaxes the assumption, letting the spread vary rather than taking one value for the whole series:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>) <span class="sc">+</span> <span class="fu">disp</span>(<span class="sc">~</span>x)         <span class="co"># varies along the predictor</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>) <span class="sc">+</span> <span class="fu">disp</span>(<span class="st">"power"</span>)    <span class="co"># varies with the fitted mean</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Reach for it when the check has failed rather than as a routine addition, and exclude three other explanations of the failure first. A variance function will absorb any cause of apparent heteroscedasticity and report a confident slope regardless. Substituted or censored values cluster at one end of the series and their spread is easily mistaken for changing variability. A misspecified family produces the same appearance, since a constant coefficient of variation is what a gamma already implies, so check the family before adding a term to repair it. And a curve that is systematically wrong in one region leaves large residuals there, which a variance function will describe as noise rather than as lack of fit.</p>
<section id="a-worked-case" class="level3">
<h3 class="anchored" data-anchor-id="a-worked-case">A worked case</h3>
<p>The beta example above is such a case, and it can be worked through on the data the course already ships. The observed coefficient of variation within a concentration is a property of the data alone, with no model involved:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>conc_breaks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.1</span>, <span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">100</span>)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>cv_by_conc <span class="ot">&lt;-</span> prop_data <span class="sc">|&gt;</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(raw_x) <span class="sc">|&gt;</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">cv =</span> <span class="fu">sd</span>(resp) <span class="sc">/</span> <span class="fu">mean</span>(resp), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cv_by_conc, <span class="fu">aes</span>(raw_x, cv)) <span class="sc">+</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">colour =</span> <span class="st">"#1b6ca8"</span>) <span class="sc">+</span></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">breaks =</span> conc_breaks, <span class="at">labels =</span> conc_breaks) <span class="sc">+</span></span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"concentration"</span>, <span class="at">y =</span> <span class="st">"coefficient of variation"</span>) <span class="sc">+</span></span>
<span id="cb92-12"><a href="#cb92-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-disp-cv" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disp-cv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-disp-cv-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disp-cv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Within-concentration coefficient of variation for <code>example_proportion.csv</code>, twenty replicates at each of eight concentrations. It runs from 0.043 at the control to 0.254 at the highest concentration, a six-fold change, so one dispersion parameter cannot describe the whole series.
</figcaption>
</figure>
</div>
</div>
</div>
<p><code>nec3param</code> holds 0.99 of the weight in the beta set above, so the comparison is made on that equation alone: one equation, one difference, and no reweighting to confound the two fits.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>exp_2_const <span class="ot">&lt;-</span> <span class="fu">bnec</span>(resp <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"nec3param"</span>),</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> prop_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>exp_2_disp <span class="ot">&lt;-</span> <span class="fu">bnec</span>(resp <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"nec3param"</span>) <span class="sc">+</span> <span class="fu">disp</span>(<span class="st">"power"</span>),</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> prop_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_2_const, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_2_const.RData"</span>)</span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_2_disp, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_2_disp.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_2_const.RData"</span>)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_2_disp.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_2_const)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-disp-fit-const" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disp-fit-const-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-disp-fit-const-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disp-fit-const-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: The constant-dispersion fit. The predictor is on the log scale, so the annotated <em>NEC</em> of 2.90 is a concentration of 18.1.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_2_disp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-disp-fit-power" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disp-fit-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-disp-fit-power-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disp-fit-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: The same equation with <code>disp("power")</code>. The <em>NEC</em> of 2.46 is a concentration of 11.7, and the credible band is narrower at the control and wider at the top of the series.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The curves are almost the same shape, and the band around them is not. Measured from the stored prediction grid, the 95% band on the mean is 0.024 wide at the lowest concentration and 0.044 at the highest under constant dispersion, a ratio of 1.9. Under <code>disp("power")</code> it is 0.017 and 0.068, a ratio of 4.0. The constant-dispersion fit splits the difference between the two ends of the series, which makes it too wide where the data are tight and too narrow where they are scattered.</p>
<p>That is why the constant-dispersion fit returns the higher <em>NEC</em> and the higher <em>NSEC</em>. Its credible band on the control mean is 40% wider than the <code>disp</code> fit’s, so the <em>NSEC</em> reference sits lower on the control posterior, and a lower reference is reached further along the curve.</p>
<p><code>autoplot()</code> draws the credible band on the fitted mean. The quantity the <code>disp</code> term acts on is the spread of the individual replicates around that mean, and simulating new observations from each fit shows it directly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>disp_grid <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">log.x =</span> <span class="fu">seq</span>(<span class="fu">min</span>(prop_data<span class="sc">$</span>log.x), <span class="fu">max</span>(prop_data<span class="sc">$</span>log.x),</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">length.out =</span> <span class="dv">100</span>))</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>pp_band <span class="ot">&lt;-</span> <span class="cf">function</span>(fit, label) {</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="fu">pull_brmsfit</span>(fit), <span class="at">newdata =</span> disp_grid)</span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">raw_x =</span> <span class="fu">exp</span>(disp_grid<span class="sc">$</span>log.x), <span class="at">fit =</span> label,</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">Estimate =</span> p[, <span class="st">"Estimate"</span>], <span class="at">Q2.5 =</span> p[, <span class="st">"Q2.5"</span>], <span class="at">Q97.5 =</span> p[, <span class="st">"Q97.5"</span>])</span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a>bands <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">pp_band</span>(exp_2_const, <span class="st">"constant dispersion"</span>),</span>
<span id="cb99-11"><a href="#cb99-11" aria-hidden="true" tabindex="-1"></a>               <span class="fu">pp_band</span>(exp_2_disp, <span class="st">"disp(</span><span class="sc">\"</span><span class="st">power</span><span class="sc">\"</span><span class="st">)"</span>))</span>
<span id="cb99-12"><a href="#cb99-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-13"><a href="#cb99-13" aria-hidden="true" tabindex="-1"></a>disp_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"constant dispersion"</span> <span class="ot">=</span> <span class="st">"#1b6ca8"</span>, <span class="st">"disp(</span><span class="sc">\"</span><span class="st">power</span><span class="sc">\"</span><span class="st">)"</span> <span class="ot">=</span> <span class="st">"#c1440e"</span>)</span>
<span id="cb99-14"><a href="#cb99-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-15"><a href="#cb99-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bands, <span class="fu">aes</span>(raw_x)) <span class="sc">+</span></span>
<span id="cb99-16"><a href="#cb99-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Q2<span class="fl">.5</span>, <span class="at">ymax =</span> Q97<span class="fl">.5</span>, <span class="at">fill =</span> fit), <span class="at">alpha =</span> <span class="fl">0.35</span>) <span class="sc">+</span></span>
<span id="cb99-17"><a href="#cb99-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Estimate, <span class="at">colour =</span> fit), <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb99-18"><a href="#cb99-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> prop_data, <span class="fu">aes</span>(<span class="at">y =</span> resp), <span class="at">size =</span> <span class="fl">1.2</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb99-19"><a href="#cb99-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">breaks =</span> conc_breaks, <span class="at">labels =</span> conc_breaks) <span class="sc">+</span></span>
<span id="cb99-20"><a href="#cb99-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> disp_cols) <span class="sc">+</span></span>
<span id="cb99-21"><a href="#cb99-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> disp_cols) <span class="sc">+</span></span>
<span id="cb99-22"><a href="#cb99-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"concentration"</span>, <span class="at">y =</span> <span class="st">"response"</span>, <span class="at">fill =</span> <span class="cn">NULL</span>, <span class="at">colour =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb99-23"><a href="#cb99-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb99-24"><a href="#cb99-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-disp-predict" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disp-predict-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-disp-predict-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disp-predict-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21: The 95% posterior predictive intervals of the two fits drawn together, with the observations. The interval is where a single replicate is expected to fall, rather than the interval on the fitted mean that <code>autoplot()</code> draws.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Under constant dispersion the 95% predictive interval is 0.240 wide at the lowest concentration and 0.234 at the highest, so it hardly changes across a series whose coefficient of variation changes six-fold. The twenty replicates at the lowest concentration cover a range of 0.103 and those at the highest a range of 0.265, so the single interval is too wide at the bottom of the series and too narrow at the top. With <code>disp("power")</code> the two widths are 0.171 and 0.463, and the band follows the data down the series. The two mean curves separate only around the break, at 18.1 against 11.7, so most of what the term changes here is the spread rather than the position.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check_fit</span>(exp_2_const))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-disp-checkfit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disp-checkfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-disp-checkfit-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disp-checkfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22: <code>check_fit()</code> on the constant-dispersion fit. Each point is one concentration group against the 95% span of what the fit simulates, with location and scale drawn separately.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">check_fit</span>(exp_2_disp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-disp-checkfit-power" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disp-checkfit-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-disp-checkfit-power-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disp-checkfit-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23: The same check on the <code>disp("power")</code> fit. Four of the eight groups now sit inside their bar on scale, against one of eight before.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Reading the two together:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>constant dispersion</th>
<th><code>disp("power")</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>groups flagged on spread, of 8</td>
<td>7</td>
<td>4</td>
</tr>
<tr class="even">
<td><code>sd_ratio</code> at the control, 1 expected</td>
<td>0.41</td>
<td>0.60</td>
</tr>
<tr class="odd">
<td><em>NEC</em>, back-transformed</td>
<td>18.1 (12.3–23.7)</td>
<td>11.7 (9.0–17.5)</td>
</tr>
<tr class="even">
<td><em>NSEC</em></td>
<td>20.2 (13.5–25.7)</td>
<td>12.9 (9.9–18.9)</td>
</tr>
<tr class="odd">
<td>ECNSEC</td>
<td>2.5% (0.4–4.5)</td>
<td>1.8% (0.3–3.2)</td>
</tr>
<tr class="even">
<td>EC10</td>
<td>28.9 (21.5–36.0)</td>
<td>21.7 (17.6–28.6)</td>
</tr>
</tbody>
</table>
<p>The constant-dispersion fit simulates about two and a half times the spread the data show at the control, which is the <code>sd_ratio</code> of 0.41. Nothing in its sampler diagnostics said so, and <code>check_sampling()</code> passes on both fits.</p>
<p>The <em>NSEC</em> falls from 20.2 to 12.9. A control posterior that is too wide places the significance reference too low, and a reference placed too low is crossed further along the curve, so the constant-dispersion fit reports the <strong>less protective</strong> of the two figures. This is the mechanism module 3 describes under the <em>NSEC</em>, measured on course data. The EC10 falls by a smaller proportion, from 28.9 to 21.7, because it is measured at a fixed fraction of the control mean rather than at a quantile of its posterior.</p>
<p>The sub-model does not repair this series. Four groups are still flagged on spread and the control is among them, so a power function of the mean is a better description of this variance than a constant but still not a good one. That is the more common outcome than a clean fix, and it is the reason to read the diagnostic rather than to assume the term has dealt with the problem. Reporting either fit here means reporting that the control spread is not reproduced.</p>
<p>For a case where the term does resolve the problem, the <code>bayesnec</code> documentation reports one plate of a bioluminescent bacterial copper series, 44 wells over 11 concentrations, where the observed coefficient of variation runs from 0.046 at the control to 1.271 at its largest. There <code>disp("power")</code> takes the groups flagged on spread from 7 of 11 to none, the control <code>sd_ratio</code> from 0.09 to 1.02, and halves the <em>NSEC</em>.</p>
</section>
</section>
<section id="open-questions" class="level2">
<h2 class="anchored" data-anchor-id="open-questions">Open questions</h2>
<p>The families implemented in <code>bayesnec</code> cover the common cases in concentration-response work.</p>
<p>The important practical point is the one at the top of this module: check which distribution was used, and check that it reproduces the variability in the data. The default inference is a convenience rather than a substitute for that judgement, and <code>check_fit()</code> is the function that makes it. Module 7 runs the same check inside a complete analysis and reports what it found.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-fisherfox2023" class="csl-entry" role="listitem">
Fisher, Rebecca, and David R. Fox. 2023. <span>“Introducing the No-Significant-Effect Concentration.”</span> <em>Environmental Toxicology and Chemistry</em> n/a (n/a). https://doi.org/<a href="https://doi.org/10.1002/etc.5610">https://doi.org/10.1002/etc.5610</a>.
</div>
<div id="ref-fisheretal2023" class="csl-entry" role="listitem">
Fisher, Rebecca, David R. Fox, Andrew P. Negri, Joost van Dam, Florita Flores, and Darren Koppel. 2023. <span>“Methods for Estimating No-Effect Toxicity Concentrations in Ecotoxicology.”</span> <em>Integrated Environmental Assessment and Management</em>, ahead of print. https://doi.org/<a href="https://doi.org/10.1002/ieam.4809">https://doi.org/10.1002/ieam.4809</a>.
</div>
<div id="ref-helsel2006" class="csl-entry" role="listitem">
Helsel, Dennis R. 2006. <span>“Fabricating Data: How Substituting Values for Nondetects Can Ruin Results, and What Can Be Done about It.”</span> <em>Chemosphere</em> 65 (11): 2434–39. <a href="https://doi.org/10.1016/j.chemosphere.2006.04.051">https://doi.org/10.1016/j.chemosphere.2006.04.051</a>.
</div>
<div id="ref-martin2005" class="csl-entry" role="listitem">
Martin, Tara G., Brendan A. Wintle, Jonathan R. Rhodes, et al. 2005. <span>“Zero Tolerance Ecology: Improving Ecological Inference by Modelling the Source of Zero Observations.”</span> <em>Ecology Letters</em> 8 (11): 1235–46. <a href="https://doi.org/10.1111/j.1461-0248.2005.00826.x">https://doi.org/10.1111/j.1461-0248.2005.00826.x</a>.
</div>
<div id="ref-oecd2026tg201" class="csl-entry" role="listitem">
OECD. 2026. <em>Test No. 201: Freshwater Alga and Cyanobacteria, Growth Inhibition Test</em>. OECD Guidelines for the Testing of Chemicals, Section 2. OECD Publishing. <a href="https://doi.org/10.1787/9789264069923-en">https://doi.org/10.1787/9789264069923-en</a>.
</div>
<div id="ref-Ritz2026" class="csl-entry" role="listitem">
Ritz, Christian, Daniel Gerhard, and Jens C. Streibig. 2026. <span>“<span class="nocase">Better alternatives than normalizing to control: case studies with algae toxicity and dose-response analysis</span>.”</span> <em>Environmental and Ecological Statistics</em> 33 (1): 35–55. <a href="https://doi.org/10.1007/s10651-025-00698-y">https://doi.org/10.1007/s10651-025-00698-y</a>.
</div>
<div id="ref-warton2005" class="csl-entry" role="listitem">
Warton, David I. 2005. <span>“Many Zeros Does Not Mean Zero Inflation: Comparing the Goodness-of-Fit of Parametric Models to Multivariate Abundance Data.”</span> <em>Environmetrics</em> 16 (3): 275–89. <a href="https://doi.org/10.1002/env.702">https://doi.org/10.1002/env.702</a>.
</div>
<div id="ref-Weimer2012" class="csl-entry" role="listitem">
Weimer, Marc, Xiaoqi Jiang, Oriana Ponta, Sven Stanzel, Alexius Freyberger, and Annette Kopp-Schneider. 2012. <span>“<span class="nocase">The impact of data transformations on concentration-response modeling</span>.”</span> <em>Toxicology Letters</em> 213 (2): 292–98. <a href="https://doi.org/10.1016/j.toxlet.2012.07.012">https://doi.org/10.1016/j.toxlet.2012.07.012</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/open-aims\.github\.io\/cr_modelling_training\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../vignettes/4Model_averaging_and_multimodel_inference.html" class="pagination-link" aria-label="4. Model averaging">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">4. Model averaging</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../vignettes/6Priors_and_Bayesian_inference.html" class="pagination-link" aria-label="6. Priors and Bayesian inference">
        <span class="nav-page-text">6. Priors and Bayesian inference</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Australian Institute of Marine Science</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/open-AIMS/cr_modelling_training/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>