<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Priors and Bayesian inference – Concentration-response modelling</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../vignettes/7Example_case_study.html" rel="next">
<link href="../vignettes/5Response_data_and_statistical_distributions.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8317e07c38846ddd92fb20fa66b3c33c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Concentration-response modelling</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/0Software-setup.html"> 
<span class="menu-text">Setup</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/1Software-stack.html"> 
<span class="menu-text">Modules</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/open-AIMS/cr_modelling_training/issues"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">Questions and corrections</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/1Software-stack.html">Modules</a></li><li class="breadcrumb-item"><a href="../vignettes/6Priors_and_Bayesian_inference.html">6. Priors and Bayesian inference</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Before you start</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/0Software-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Software setup</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Modules</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/1Software-stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. The software stack</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/2Fitting-a-CR-model-using-bayesnec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Fitting a single model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/3Toxicity_estimation_and_available_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Toxicity estimation and the model set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/4Model_averaging_and_multimodel_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Model averaging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/5Response_data_and_statistical_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Response data and distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/6Priors_and_Bayesian_inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">6. Priors and Bayesian inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/7Example_case_study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. A worked case study</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/8Factor_covariates_and_groupings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Factor covariates and groupings</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Frequentist comparison</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/drc-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting the same models with drc</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#estimating-uncertainty" id="toc-estimating-uncertainty" class="nav-link" data-scroll-target="#estimating-uncertainty">Estimating uncertainty</a></li>
  <li><a href="#the-posterior-sample" id="toc-the-posterior-sample" class="nav-link" data-scroll-target="#the-posterior-sample">The posterior sample</a></li>
  <li><a href="#sampling" id="toc-sampling" class="nav-link" data-scroll-target="#sampling">Sampling</a></li>
  <li><a href="#priors" id="toc-priors" class="nav-link" data-scroll-target="#priors">Priors</a></li>
  <li><a href="#priors-in-bayesnec" id="toc-priors-in-bayesnec" class="nav-link" data-scroll-target="#priors-in-bayesnec">Priors in <code>bayesnec</code></a></li>
  <li><a href="#limits-of-the-default-priors" id="toc-limits-of-the-default-priors" class="nav-link" data-scroll-target="#limits-of-the-default-priors">Limits of the default priors</a></li>
  <li><a href="#inspecting-the-priors" id="toc-inspecting-the-priors" class="nav-link" data-scroll-target="#inspecting-the-priors">Inspecting the priors</a></li>
  <li><a href="#specifying-priors" id="toc-specifying-priors" class="nav-link" data-scroll-target="#specifying-priors">Specifying priors</a>
  <ul class="collapse">
  <li><a href="#comparison-of-the-fits" id="toc-comparison-of-the-fits" class="nav-link" data-scroll-target="#comparison-of-the-fits">Comparison of the fits</a></li>
  </ul></li>
  <li><a href="#fixing-a-parameter" id="toc-fixing-a-parameter" class="nav-link" data-scroll-target="#fixing-a-parameter">Fixing a parameter</a>
  <ul class="collapse">
  <li><a href="#the-consequences-of-fixing-a-parameter" id="toc-the-consequences-of-fixing-a-parameter" class="nav-link" data-scroll-target="#the-consequences-of-fixing-a-parameter">The consequences of fixing a parameter</a></li>
  </ul></li>
  <li><a href="#using-posterior-distributions" id="toc-using-posterior-distributions" class="nav-link" data-scroll-target="#using-posterior-distributions">Using posterior distributions</a>
  <ul class="collapse">
  <li><a href="#comparing-whole-curves" id="toc-comparing-whole-curves" class="nav-link" data-scroll-target="#comparing-whole-curves">Comparing whole curves</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/open-AIMS/cr_modelling_training/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/1Software-stack.html">Modules</a></li><li class="breadcrumb-item"><a href="../vignettes/6Priors_and_Bayesian_inference.html">6. Priors and Bayesian inference</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Priors and Bayesian inference</h1>
<p class="subtitle lead">What the priors do, how <code>bayesnec</code> builds them, and how to change them</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>This course uses Bayesian methods throughout, and from the installation onwards that can look like an unnecessary complication, since frequentist solutions exist for most of it, <code>drc</code> among them. The extra overhead has probably held back the use of Bayesian methods for threshold derivation in ecotoxicology, where specialist statistical support is not usually available <span class="citation" data-cites="Fisher2019">(<a href="#ref-Fisher2019" role="doc-biblioref">R. Fisher et al. 2019</a>)</span>.</p>
<p>Three things justify the overhead: a stable and flexible fitting platform, estimates of uncertainty that mean what people assume they mean, and the posterior sample itself, which every estimate in this course is read from.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/bayesian_stats.JPG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</section>
<section id="estimating-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="estimating-uncertainty">Estimating uncertainty</h2>
<p>In Bayesian inference the parameters and their uncertainty are estimated as probability distributions. Uncertainty in a derived threshold is what makes it usable in risk assessment and formal decision frameworks <span class="citation" data-cites="fisher2018c">(<a href="#ref-fisher2018c" role="doc-biblioref">Fisher et al. 2018</a>)</span>, and Bayesian methods quantify it with a direct probabilistic meaning <span class="citation" data-cites="Ellison1996">(<a href="#ref-Ellison1996" role="doc-biblioref">Ellison 1996</a>)</span>.</p>
<p>The distinction between the two paradigms, in brief:</p>
<ul>
<li>Bayesian inference estimates the probability of the parameters, given the observed data and the prior information.</li>
<li>Frequentist inference estimates the probability of the data, given the parameters.</li>
</ul>
<p>That difference is why a Bayesian interval answers the question most people think a confidence interval answers. It holds provided the priors have been handled properly.</p>
<p>This introduction covers the principles without the mathematics:</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/0F0QoMCSKJ4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
<section id="the-posterior-sample" class="level2">
<h2 class="anchored" data-anchor-id="the-posterior-sample">The posterior sample</h2>
<p>A Bayesian fit returns draws from the joint posterior of every parameter, and what follows in an analysis is done on those draws rather than on a point estimate and a standard error.</p>
<p>A derived quantity is computed once per draw, so it arrives with an interval of its own. <code>ecx()</code>, <code>nsec()</code> and <code>ecnsec()</code> each evaluate the fitted curve draw by draw and return the distribution that results. The interval on the estimate therefore follows from the parameter draws with no separate approximation. Maximum likelihood needs the delta method or a bootstrap for the same interval, and the <a href="../vignettes/drc-reference.html"><code>drc</code> reference</a> page derives an <em>NSEC</em> that has no interval at all for that reason.</p>
<p>A question about two estimates becomes a proportion of draws. <code>compare_posterior()</code> pairs the draws of two fits and reports the probability that one estimate exceeds the other. <em>Using posterior distributions</em>, at the end of this module, works that through on two equations fitted to <code>nec_data</code>, and module 8 uses it to compare the toxicity of copper and zinc. The same count answers whether a threshold falls below a guideline value, which is the form a risk assessment usually needs <span class="citation" data-cites="fisher2018c">(<a href="#ref-fisher2018c" role="doc-biblioref">Fisher et al. 2018</a>)</span>.</p>
<p>Model averaging is done on the draws as well. <code>bnec()</code> weights the candidate equations by their leave-one-out predictive performance and draws from each in proportion to its weight, so an estimate taken from a model-averaged fit includes the uncertainty about which equation describes the data. Module 4 covers how the weights are computed.</p>
<p>The draws also travel into work downstream of the fit. A species sensitivity distribution fitted to point estimates treats each species value as known exactly, and fitting it to the draws instead propagates the uncertainty in each species into the hazard concentration that comes out <span class="citation" data-cites="Charles2020a Gottschalk2013">(<a href="#ref-Charles2020a" role="doc-biblioref">Charles et al. 2020</a>; <a href="#ref-Gottschalk2013" role="doc-biblioref">Gottschalk and Nowack 2013</a>)</span>.</p>
<p>None of this removes the overhead. A fit takes minutes rather than seconds and needs a working toolchain. The priors are a further assumption that a maximum likelihood fit does not make. Stating them, checking them and measuring how much they matter are covered from <em>Priors</em> to <em>Fixing a parameter</em>, and <em>Using posterior distributions</em> returns to the draws.</p>
</section>
<section id="sampling" class="level2">
<h2 class="anchored" data-anchor-id="sampling">Sampling</h2>
<p>The posterior combines a prior distribution for each parameter, <span class="math inline">\(p(\theta)\)</span>, with the likelihood of the observed data given those parameters, <span class="math inline">\(p(D | \theta)\)</span>:</p>
<p><span id="eq-bayes"><span class="math display">\[
p(\theta | D) = \frac{p(D | \theta)\, p(\theta)}{\int_{\theta} p(D | \theta)\, p(\theta)\, d\theta} \propto p(D | \theta)\, p(\theta)
\tag{1}\]</span></span></p>
<p>The denominator is usually analytically intractable, which is why Bayesian fitting relies on numerical approximation by Markov chain Monte Carlo.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/OTO1DygELpY" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>Many packages implement MCMC, among them <code>WinBUGS</code> <span class="citation" data-cites="Lunn2000">(<a href="#ref-Lunn2000" role="doc-biblioref">Lunn et al. 2000</a>)</span>, <code>JAGS</code> <span class="citation" data-cites="Plummer2003">(<a href="#ref-Plummer2003" role="doc-biblioref">Plummer 2003</a>)</span> and <code>Stan</code> <span class="citation" data-cites="Carpenter2017">(<a href="#ref-Carpenter2017" role="doc-biblioref">Carpenter et al. 2017</a>)</span>, reached from R through <code>R2WinBUGS</code>, <code>R2jags</code> <span class="citation" data-cites="Su2015">(<a href="#ref-Su2015" role="doc-biblioref">Su and Yajima 2015</a>)</span> and <code>rstan</code> <span class="citation" data-cites="rstan2021">(<a href="#ref-rstan2021" role="doc-biblioref">Stan Development Team 2021</a>)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/mctools.JPG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
<p>These require the model to be specified in a separate language, which is a real barrier. <code>brms</code> <span class="citation" data-cites="Burkner2017">(<a href="#ref-Burkner2017" role="doc-biblioref">Bürkner 2017</a>)</span> removes it for a wide range of models by generating that code from <code>lme4</code>-like formula syntax, fitting through <code>rstan</code> <span class="citation" data-cites="rstan2021">(<a href="#ref-rstan2021" role="doc-biblioref">Stan Development Team 2021</a>)</span> or <code>cmdstanr</code> <span class="citation" data-cites="cmdstanr2022">(<a href="#ref-cmdstanr2022" role="doc-biblioref">Gabry and Češnovar 2022</a>)</span>. Even so, automating Bayesian fits across arbitrary use cases is difficult, particularly the initial values and the priors, and extracting NEC or ECx estimates with their uncertainty from a set of posterior draws is cumbersome without dedicated code. Those are the gaps <code>bayesnec</code> fills, as module 1 described.</p>
<p><code>Stan</code> uses Hamiltonian Monte Carlo with the no-U-turn sampler, which sets the number of steps in each trajectory automatically <span class="citation" data-cites="hoffman2014">(<a href="#ref-hoffman2014" role="doc-biblioref">Hoffman and Gelman 2014</a>)</span>. The step size is tuned during warm-up towards a target acceptance rate, which <code>brms</code> exposes as <code>control = list(adapt_delta = ...)</code>.</p>
</section>
<section id="priors" class="level2">
<h2 class="anchored" data-anchor-id="priors">Priors</h2>
<p>A Bayesian analysis requires a prior probability density for every parameter.</p>
<p>Where real prior knowledge exists, such as pilot data or a previous experiment on the same response, the prior may reasonably be narrow, and will then be influential, especially if the new data are scarce or noisy. In ecology and ecotoxicology that situation is the exception.</p>
<p>Where no quantitative prior information exists it is common to use vague or weakly informative priors. The use of vague, diffuse or flat priors described as “uninformative” is no longer recommended <span class="citation" data-cites="Banner2020">(<a href="#ref-Banner2020" role="doc-biblioref">Banner et al. 2020</a>)</span>. Such priors are the default in many packages and are often used without evaluation, sometimes from a concern about appearing subjective <span class="citation" data-cites="Banner2020">(<a href="#ref-Banner2020" role="doc-biblioref">Banner et al. 2020</a>)</span>, and they can still influence the outcome substantially <span class="citation" data-cites="depaoli2020importance gelman2017entropy">(<a href="#ref-depaoli2020importance" role="doc-biblioref">Depaoli et al. 2020</a>; <a href="#ref-gelman2017entropy" role="doc-biblioref">Gelman et al. 2017</a>)</span>.</p>
<p>The current recommendation is weakly informative, generative priors: priors that interact sensibly with the likelihood to produce a plausible data-generating mechanism <span class="citation" data-cites="gelman2017entropy">(<a href="#ref-gelman2017entropy" role="doc-biblioref">Gelman et al. 2017</a>)</span>.</p>
</section>
<section id="priors-in-bayesnec" class="level2">
<h2 class="anchored" data-anchor-id="priors-in-bayesnec">Priors in <code>bayesnec</code></h2>
<p><code>bayesnec</code> builds weakly informative priors by algorithm, on two principles:</p>
<ul>
<li>use a statistical family appropriate to the parameter’s theoretical distribution;</li>
<li>use the observed data to centre the density near the plausible parameter space, and to constrain it to sensible bounds.</li>
</ul>
<p>The purpose is to keep the sampler away from values the researcher would regard as implausible, which is also where non-linear fits become unstable. For complex non-linear models this matters for convergence rather than only for inference. In comparisons against <code>drc</code>, <code>bayesnec</code> often finds a sensible fit where <code>drc</code> does not, and the bounds these priors place on the parameter space are part of the reason.</p>
<p>Priors of this kind describe the shape and bounds of a parameter’s density while staying broad enough not to determine its posterior, given a reasonable amount of data. Used that way they give results about as objective as the frequentist equivalent, while yielding intervals that can be read as probabilities.</p>
<p>They still need interrogating, by sensitivity analysis <span class="citation" data-cites="depaoli2020importance">(<a href="#ref-depaoli2020importance" role="doc-biblioref">Depaoli et al. 2020</a>)</span> and by checking they suit the data <span class="citation" data-cites="gelman2017entropy">(<a href="#ref-gelman2017entropy" role="doc-biblioref">Gelman et al. 2017</a>)</span>. As a rule the defaults behave well where there are enough data, which includes a reasonable number of treatment concentrations. Where data are sparse the defaults can be influential; but sparse data usually need informative priors to fit at all, and then the influence of prior knowledge should be acknowledged rather than avoided.</p>
<p>Two sets are supplied, <code>"uninformative"</code> and <code>"regularizing"</code>, and <code>prior_type</code> selects between them. Its default is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">formals</span>(bnec)<span class="sc">$</span>prior_type</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "uninformative"</code></pre>
</div>
</div>
<p><code>"uninformative"</code> is the default. <code>"regularizing"</code> is a deliberately narrower set, and it is the one to reach for where a default fit is unstable. The narrower set is not the default for a reason that has nothing to do with which performs better: <code>"uninformative"</code> reproduces the priors described in the paper documenting the package <span class="citation" data-cites="fisheretal2024">(<a href="#ref-fisheretal2024" role="doc-biblioref">Fisher et al. 2024</a>)</span>, so it is what a published <code>bayesnec</code> analysis was run under, and changing the default would silently change the result of re-running one.</p>
<p>On the evidence so far the narrower set is the better choice for a new analysis. The <code>bayesnec</code> NEWS file records 420 <code>top</code> and <code>bot</code> entries built from simulated responses across ten seeds, three designs and five families, on designs with complete effect at the highest concentration or a hurdle or zero-inflated response. The true value fell outside the central 95% of its own prior in 12 entries under the narrower set and in 127 under <code>"uninformative"</code>. Expect it to become the default in a later version, and state which set was used either way. One assumption is worth checking before selecting it: the rule assumes the lowest concentration tested sits at the level <code>top</code> describes and the highest sits at the level <code>bot</code> describes, so on a design whose decline is incomplete, use <code>"uninformative"</code>.</p>
<p>How each prior is constructed, parameter by parameter and family by family, is in the <a href="https://open-aims.github.io/bayesnec/dev/articles/example3.html"><code>bayesnec</code> priors article</a>. Two consequences of the construction reach how an analysis is run. The prior on <code>nec</code> is truncated to the observed range of the predictor, so an estimate sitting at the edge of the tested range should be treated with suspicion rather than reported. And its width is set by the two extreme concentrations, so it responds to what is entered for the control: on the <code>nassarius</code> contaminant A series the priors article reports a standard deviation of 2.30 with the control recorded as <code>0</code> and 6.11 with it recorded as <code>1e-6</code>. A control recorded as <code>0</code> is left out of the construction, while <code>1e-6</code> states that a concentration of <code>1e-6</code> was applied. Record a control as <code>0</code>.</p>
</section>
<section id="limits-of-the-default-priors" class="level2">
<h2 class="anchored" data-anchor-id="limits-of-the-default-priors">Limits of the default priors</h2>
<p>The defaults are data-dependent and are designed to be informative enough, relative to each parameter’s plausible region, to return fits without divergent transitions where the data are sufficient. <code>brms</code> provides no blanket defaults for non-linear models, and how vague a prior is depends on the likelihood in any case <span class="citation" data-cites="gelman2017entropy">(<a href="#ref-gelman2017entropy" role="doc-biblioref">Gelman et al. 2017</a>)</span>.</p>
<p>They can fail in three ways. They may be too informative, giving unreasonably tight bounds, which happens mainly with few data or few unique predictor values. They may be too vague, giving poor convergence. Or they may be of the wrong family, if the data did not contain enough information for <code>bayesnec</code> to infer the right one.</p>
</section>
<section id="inspecting-the-priors" class="level2">
<h2 class="anchored" data-anchor-id="inspecting-the-priors">Inspecting the priors</h2>
<p><code>get_priors()</code> builds the priors from a formula and a dataset without fitting anything, which is the order they are wanted in when a fit takes minutes:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(nec_data)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_priors</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec3param"</span>), <span class="at">data =</span> nec_data,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> <span class="fu">Beta</span>(<span class="at">link =</span> <span class="st">"identity"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           prior class coef group resp dpar
                                    normal(0, 5)     b                     
                                      beta(5, 2)     b                     
 lognormal(-0.132723577442522, 1.68292842267636)     b                     
 nlpar               lb               ub tag source
  beta             &lt;NA&gt;             &lt;NA&gt;       user
   top                0                1       user
   nec 0.03234801324009 3.22051966293556       user</code></pre>
</div>
</div>
<p>That is the set <code>bnec()</code> would use, and it can be edited and passed back through the <code>prior</code> argument, as <em>Fixing a parameter</em> does. For a model already fitted, <code>get_priors()</code> returns the priors it used in the same form. <code>pull_prior()</code> returns the whole <code>brmsprior</code> stored in the fit, <code>brms</code> defaults included, which is for inspection and is not accepted by <code>bnec(prior = )</code>.</p>
<p>A fitted model to work from:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(nec_data)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>bnec_fit <span class="ot">&lt;-</span> <span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec3param"</span>), <span class="at">data =</span> nec_data)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(bnec_fit, <span class="at">file =</span> <span class="st">"vignettes/fits/m6_bnec_fit.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m6_bnec_fit.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>sample_priors()</code> draws from the priors held in the <code>brms</code> fit, which shows their shape directly:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample_priors</span>(<span class="fu">pull_brmsfit</span>(bnec_fit)<span class="sc">$</span>prior)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-sample-priors" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sample-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="6Priors_and_Bayesian_inference_files/figure-html/fig-sample-priors-1.png" id="fig-sample-priors" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-sample-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<p><code>check_priors()</code>, which builds on the <code>hypothesis()</code> function of <code>brms</code>, plots the prior against the posterior for each parameter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_priors</span>(bnec_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required namespace: rstan</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-check-priors" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-check-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="6Priors_and_Bayesian_inference_files/figure-html/fig-check-priors-1.png" id="fig-check-priors" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-check-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read each panel as a pair of densities. A posterior concentrated well inside its prior was determined by the data; one that follows the shape of its prior was not. All three parameters here are determined by the data. Each posterior is a narrow spike, and each prior is broad beneath it: <code>nec</code> is located at about 1.5 under a prior spread across the whole tested range, and <code>top</code> at about 0.9 under a <code>beta(5, 2)</code> spanning most of the interval from 0.25 to 1. The <code>beta</code> panel is the one to read carefully, because its spike sits at about 0.5, close to the centre of its <code>normal(0, 5)</code> prior on the scale of the panel. Agreement between a posterior and the centre of its prior is not evidence that the prior determined it; what settles that is the width, and this posterior is narrower than its prior by more than an order of magnitude.</p>
<p><code>check_priors()</code> works on a <code>bayesmanecfit</code> as well, and takes a <code>filename</code> to write the plots for a whole set to a PDF rather than to the screen.</p>
<p>Two things the plot does not settle. A narrow interval is not evidence of a well-determined parameter: a parameter the likelihood is flat in will report a narrow posterior if its prior was narrow. <strong>Prior-to-posterior contraction</strong>, one minus the ratio of the posterior variance to the prior variance, distinguishes the two, and runs from 0 where the data added nothing to 1 where the posterior is far narrower than the prior. It is computed from <code>pull_prior()</code> and the posterior draws. And whether a <em>different</em> reasonable prior would have given a different answer is a question the plot cannot ask. <code>prior_type</code> makes that sensitivity analysis one argument:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>exmp_reg <span class="ot">&lt;-</span> <span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>), <span class="at">data =</span> nec_data,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> <span class="fu">Beta</span>(<span class="at">link =</span> <span class="st">"identity"</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">prior_type =</span> <span class="st">"regularizing"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>nec4param</code> is used rather than <code>nec3param</code> so that the comparison includes <code>bot</code>, which <code>nec3param</code> does not have. On <code>nec_data</code> the <code>"regularizing"</code> set narrows and relocates the priors on <code>top</code> and <code>bot</code> and narrows the one on <code>nec</code>, and leaves the prior on <code>beta</code> unchanged. Compare the result with the same equation fitted under the default set. Posteriors that agree between the two sets are being determined by the data. Posteriors that differ are being determined by the priors, and the influence of the prior then belongs in the reporting rather than being left implicit.</p>
</section>
<section id="specifying-priors" class="level2">
<h2 class="anchored" data-anchor-id="specifying-priors">Specifying priors</h2>
<p>The simplest way to write custom priors is to let <code>bnec</code> build its own first and then modify them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>exmp_a <span class="ot">&lt;-</span> <span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec3param"</span>), <span class="at">data =</span> nec_data,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">Beta</span>(<span class="at">link =</span> <span class="st">"identity"</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">iter =</span> <span class="fl">1e4</span>, <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exmp_a, <span class="at">file =</span> <span class="st">"vignettes/fits/m6_exmp_a.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m6_exmp_a.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>pull_prior()</code> reports what it chose:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pull_prior</span>(exmp_a)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
                                           prior class      coef group resp
                                    normal(0, 5)     b                     
                                    normal(0, 5)     b Intercept           
 lognormal(-0.132723577442522, 1.68292842267636)     b                     
 lognormal(-0.132723577442522, 1.68292842267636)     b Intercept           
                                      beta(5, 2)     b                     
                                      beta(5, 2)     b Intercept           
                               gamma(0.01, 0.01)   phi                     
 dpar nlpar               lb               ub tag       source
       beta                                               user
       beta                                       (vectorized)
        nec 0.03234801324009 3.22051966293556             user
        nec 0.03234801324009 3.22051966293556     (vectorized)
        top                0                1             user
        top                0                1     (vectorized)
                           0                           default</code></pre>
</div>
</div>
<p>The prior on <code>nec</code> is a lognormal, because <code>nec_data$x</code> is strictly positive. Suppose the predictor could in principle have been negative and simply was not in this dataset. A normal with a larger variance can be substituted:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>my_prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">prior_string</span>(<span class="st">"beta(5, 1)"</span>, <span class="at">nlpar =</span> <span class="st">"top"</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">prior_string</span>(<span class="st">"normal(1.3, 2.7)"</span>, <span class="at">nlpar =</span> <span class="st">"nec"</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">prior_string</span>(<span class="st">"gamma(0.5, 2)"</span>, <span class="at">nlpar =</span> <span class="st">"beta"</span>))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>exmp_b <span class="ot">&lt;-</span> <span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec3param"</span>), <span class="at">data =</span> nec_data,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">Beta</span>(<span class="at">link =</span> <span class="st">"identity"</span>), <span class="at">prior =</span> my_prior,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">iter =</span> <span class="fl">1e4</span>, <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exmp_b, <span class="at">file =</span> <span class="st">"vignettes/fits/m6_exmp_b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m6_exmp_b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Two things follow from that. Priors must be given for every parameter of the model, not only the ones being changed. And to find out what those parameters are before anything is fitted, use <code>show_params()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show_params</span>(<span class="at">model =</span> <span class="st">"nec3param"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
y ~ top * exp(-exp(beta) * (x - nec) * step(x - nec)) 
top ~ 1
beta ~ 1
nec ~ 1</code></pre>
</div>
</div>
<p>Where several equations are fitted together, <code>prior</code> takes a named list with one entry per equation, and equations left out of it get the defaults. <code>amend()</code> takes priors for the equation being added to a set. Both are set out in the <a href="https://open-aims.github.io/bayesnec/dev/articles/example3.html"><code>bayesnec</code> priors article</a>, with worked examples of each.</p>
<section id="comparison-of-the-fits" class="level3">
<h3 class="anchored" data-anchor-id="comparison-of-the-fits">Comparison of the fits</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(exmp_a<span class="sc">$</span>ne_posterior, <span class="at">main =</span> <span class="st">"Default priors"</span>, <span class="at">xlab =</span> <span class="st">"NEC"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(exmp_b<span class="sc">$</span>ne_posterior, <span class="at">main =</span> <span class="st">"User priors"</span>, <span class="at">xlab =</span> <span class="st">"NEC"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-compare-priors" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compare-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="6Priors_and_Bayesian_inference_files/figure-html/fig-compare-priors-1.png" id="fig-compare-priors" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-compare-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
</div>
</div>
<p>The posteriors are similar, with medians of 1.535 under the default priors and 1.533 under the user priors, which is what should happen when the data are informative enough that the priors are not driving the result. A large difference would be the signal to look harder.</p>
</section>
</section>
<section id="fixing-a-parameter" class="level2">
<h2 class="anchored" data-anchor-id="fixing-a-parameter">Fixing a parameter</h2>
<p>A parameter can be held at a known value rather than estimated, by giving it a <code>constant()</code> prior. This works wherever a user-specified prior works and needs no other change. <code>bayesnec</code> has no <code>fixed</code> argument of the kind <code>drc</code> provides, because a point-mass prior expresses the same thing through machinery that already exists.</p>
<p><code>avoid_data</code> stands for a two-choice avoidance dataset of your own; <code>bayesnec</code> does not ship one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fixed_prior <span class="ot">&lt;-</span> <span class="fu">get_priors</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec3param"</span>), <span class="at">data =</span> avoid_data,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> <span class="fu">Beta</span>(<span class="at">link =</span> <span class="st">"identity"</span>))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>fixed_prior<span class="sc">$</span>prior[fixed_prior<span class="sc">$</span>nlpar <span class="sc">==</span> <span class="st">"top"</span>] <span class="ot">&lt;-</span> <span class="st">"constant(0.5)"</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec3param"</span>), <span class="at">data =</span> avoid_data,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">family =</span> <span class="fu">Beta</span>(<span class="at">link =</span> <span class="st">"identity"</span>), <span class="at">prior =</span> fixed_prior)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Stan does not declare a parameter whose prior is constant, so <code>top</code> is reported with an estimate of exactly 0.5 and no error, because it was never sampled.</p>
<p>The case where this is defensible is an asymptote that is structural rather than measured. In a two-choice avoidance assay, animals are offered a treated and an untreated container, and the expected proportion in the treated container at zero dose is 0.5 <em>by design</em>, because at zero dose the two containers are identical.</p>
<section id="the-consequences-of-fixing-a-parameter" class="level3">
<h3 class="anchored" data-anchor-id="the-consequences-of-fixing-a-parameter">The consequences of fixing a parameter</h3>
<p>Two things, and both are easy to miss because the fit looks better rather than worse.</p>
<p>The first is a diagnostic. In the assay above, 0.5 is a null expectation rather than a design constant: it holds only if there is no baseline preference between the two containers arising from position, lighting, handling order or substrate. Fitting with <code>top</code> free gives a credible interval that either covers 0.5 or does not, and that is positive evidence about whether the assay was unbiased before the contaminant was involved. No other output of the model supplies it. Where a real baseline preference is present, fixing <code>top</code> at 0.5 produces a fit that looks exactly as sound as one where it is absent; the disagreement does not disappear when it is forbidden from appearing in <code>top</code>, but is absorbed into <code>beta</code> and <code>nec</code> instead, and so into the toxicity estimate.</p>
<p>The second is uncertainty. A constant asserts that the value is known exactly, so none of it propagates into an <strong>EC<sub>x</sub></strong> or the <em>NEC</em>, and the credible intervals narrow. That reads as a better analysis and is the opposite of one.</p>
<p>A tight informative prior is the better tool in most cases, because it states what is known while still letting the data revise the parameter and still propagating the uncertainty forward. <code>beta(6, 6)</code> has a mean of 0.5 and a standard deviation of 0.14, concentrating <code>top</code> around the design expectation without asserting it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fixed_prior<span class="sc">$</span>prior[fixed_prior<span class="sc">$</span>nlpar <span class="sc">==</span> <span class="st">"top"</span>] <span class="ot">&lt;-</span> <span class="st">"beta(6, 6)"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><span class="citation" data-cites="Weimer2012">Weimer et al. (<a href="#ref-Weimer2012" role="doc-biblioref">2012</a>)</span> reach the same conclusion from the frequentist side. A linear transformation of the data changes neither the EC50 nor the slope estimate, provided the fitting function is kept, but fixing parameters in a reduced model can produce erroneous estimates. Their case is data corrected for background and normalised to a control, then fitted with the response range fixed between 100% and 0%. Fix a parameter only where there is a compelling reason.</p>
<p>That case is the one to refuse outright. A response divided by its control mean has a maximum of 1 by construction, and fixing <code>top</code> at 1 is a common reflex. Normalising to an <em>estimated</em> control already discards the sampling variability of the divisor, as module 5 sets out, and fixing the asymptote afterwards makes that loss invisible rather than merely present, because the intervals it narrows were already too narrow.</p>
</section>
</section>
<section id="using-posterior-distributions" class="level2">
<h2 class="anchored" data-anchor-id="using-posterior-distributions">Using posterior distributions</h2>
<p>The posterior draws a Bayesian fit produces are useful well beyond a point estimate. They support the study of synergistic and antagonistic effects <span class="citation" data-cites="Fisher2019d flores2021">(<a href="#ref-Fisher2019d" role="doc-biblioref">Rebecca Fisher et al. 2019</a>; <a href="#ref-flores2021" role="doc-biblioref">Flores et al. 2021</a>)</span>, the propagation of endpoint uncertainty <span class="citation" data-cites="Charles2020a Gottschalk2013">(<a href="#ref-Charles2020a" role="doc-biblioref">Charles et al. 2020</a>; <a href="#ref-Gottschalk2013" role="doc-biblioref">Gottschalk and Nowack 2013</a>)</span>, and tests of hypotheses of no effect <span class="citation" data-cites="Thomas2006">(<a href="#ref-Thomas2006" role="doc-biblioref">Neal 2006</a>)</span>.</p>
<p>A comparison between two estimates is a count of draws rather than a test statistic, because both estimates arrive as whole distributions. <code>compare_posterior()</code> does this for a named list of fits, and returns both the posteriors it used and the probability that one estimate exceeds the other.</p>
<p>There is one fit so far, so the comparison needs a second. <code>ecxll3</code> is a smooth equation with three free parameters (<code>top</code>, <code>beta</code> and <code>ec50</code>), as <code>nec3param</code> has three (<code>top</code>, <code>beta</code> and <code>nec</code>), and the same lower asymptote fixed at zero, so the two fits differ in the shape of the curve rather than in what each is free to estimate.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>ecxll3_fit <span class="ot">&lt;-</span> <span class="fu">bnec</span>(y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"ecxll3"</span>), <span class="at">data =</span> nec_data)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(ecxll3_fit, <span class="at">file =</span> <span class="st">"vignettes/fits/m6_ecxll3_fit.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m6_ecxll3_fit.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Both equations support an <strong>EC<sub>x</sub></strong>, which is the estimate compared here. Their no-effect estimates are not the same quantity as each other, and module 3 covers that difference.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>post_comp <span class="ot">&lt;-</span> <span class="fu">compare_posterior</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"nec3param"</span> <span class="ot">=</span> bnec_fit, <span class="st">"ecxll3"</span> <span class="ot">=</span> ecxll3_fit),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">comparison =</span> <span class="st">"ecx"</span>, <span class="at">ecx_val =</span> <span class="dv">10</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(post_comp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "posterior_list" "posterior_data" "diff_list"      "diff_data"     
[5] "prob_diff"     </code></pre>
</div>
</div>
<p><code>posterior_data</code> holds the draws of both estimates in long form, which is what a figure is drawn from:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(post_comp<span class="sc">$</span>posterior_data, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">group =</span> model, <span class="at">colour =</span> model, <span class="at">fill =</span> model), <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Concentration"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-compare-post" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compare-post-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="6Priors_and_Bayesian_inference_files/figure-html/fig-compare-post-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-compare-post-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Posterior EC10 from two equations fitted to the same data. Each curve is the whole distribution of the estimate rather than a point and a standard error.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two densities overlap over a narrow region and neither is contained in the other, which is a statement a pair of point estimates could not make.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(post_comp<span class="sc">$</span>posterior_list, quantile, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      nec3param   ecxll3
2.5%   1.564392 1.433661
50%    1.596871 1.499401
97.5%  1.628092 1.560560</code></pre>
</div>
</div>
<p>The EC10 is 1.60 from the <code>nec3param</code> fit and 1.50 from the <code>ecxll3</code> fit, with the intervals above.</p>
<p><code>prob_diff</code> is the proportion of paired draws in which the first estimate exceeds the second, and <code>diff_list</code> holds the differences those proportions are taken from:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>post_comp<span class="sc">$</span>prob_diff</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        comparison     prob
1 nec3param-ecxll3 0.997625</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(post_comp<span class="sc">$</span>diff_list[[<span class="st">"nec3param-ecxll3"</span>]], <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2.5%        50%      97.5% 
0.02826888 0.09729338 0.16921034 </code></pre>
</div>
</div>
<p>The probability is 0.998, so the <code>nec3param</code> EC10 is the higher of the two in almost every paired draw. The difference is 0.10, with a 95% interval from 0.03 to 0.17, which is the size of the disagreement rather than the confidence in it. Read both: a probability near 1 on a difference of no practical consequence is a result a large sample can produce on its own.</p>
<section id="comparing-whole-curves" class="level3">
<h3 class="anchored" data-anchor-id="comparing-whole-curves">Comparing whole curves</h3>
<p><code>comparison = "fitted"</code> compares the curves themselves at a grid of concentrations across the range of the predictor, rather than one estimate read off each.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>post_fitted <span class="ot">&lt;-</span> <span class="fu">compare_posterior</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"nec3param"</span> <span class="ot">=</span> bnec_fit, <span class="st">"ecxll3"</span> <span class="ot">=</span> ecxll3_fit),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">comparison =</span> <span class="st">"fitted"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(post_fitted<span class="sc">$</span>posterior_data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> nec_data, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y), <span class="at">colour =</span> <span class="st">"grey60"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Q2<span class="fl">.5</span>, <span class="at">ymax =</span> Q97<span class="fl">.5</span>), <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Estimate), <span class="at">colour =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> model) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Concentration"</span>, <span class="at">y =</span> <span class="st">"Response"</span>) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-fitted-curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fitted-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="6Priors_and_Bayesian_inference_files/figure-html/fig-fitted-curves-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fitted-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: The two fitted curves over the observed data, each with its 95% credible interval, on the 50-point grid the comparison uses.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Both curves pass through the data. <code>nec3param</code> holds the control level flat to its threshold a little above 1.5 and turns sharply there; <code>ecxll3</code> has begun to decline before 1.5 and turns gradually, so it sits below <code>nec3param</code> just before the threshold and above it just after. Reading a separation off two panels stops at that description, and the difference below puts a number and an interval on it at every concentration.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(post_fitted<span class="sc">$</span>diff_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        comparison diff.Estimate   diff.Q2.5  diff.Q97.5          x
1 nec3param-ecxll3  -0.007756050 -0.02309775 0.007926149 0.03234801
2 nec3param-ecxll3  -0.007697805 -0.02302017 0.007976606 0.09741274
3 nec3param-ecxll3  -0.007593218 -0.02291801 0.008035863 0.16247747
4 nec3param-ecxll3  -0.007472640 -0.02277504 0.008140872 0.22754220
5 nec3param-ecxll3  -0.007321628 -0.02257281 0.008296343 0.29260692
6 nec3param-ecxll3  -0.007120775 -0.02228804 0.008472794 0.35767165</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(post_fitted<span class="sc">$</span>diff_data) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">ymin =</span> diff.Q2<span class="fl">.5</span>, <span class="at">ymax =</span> diff.Q97<span class="fl">.5</span>),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> diff.Estimate), <span class="at">colour =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Concentration"</span>, <span class="at">y =</span> <span class="st">"Difference in fitted response"</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-compare-fitted" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compare-fitted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="6Priors_and_Bayesian_inference_files/figure-html/fig-compare-fitted-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-compare-fitted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Difference between the two fitted curves across the concentration range, with its 95% credible interval. The difference is taken as <code>nec3param</code> minus <code>ecxll3</code>, so a positive value is a higher predicted response from the threshold equation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Where the band excludes zero the two curves differ at that concentration. These two agree from 0.03 to 1.14 and differ over 25 of the 50 grid points. The <code>nec3param</code> curve is the higher of the two from 1.20 to 1.53, the lower from 1.72 to 2.05, and the higher again from 2.44 to 3.22. The largest difference is 0.089 at a concentration of 1.85, on observed responses spanning 0.001 to 0.98. That is what the comparison achieved: it located the disagreement between the two equations on the concentration axis and bounded its size, where the EC10 comparison above gave only that one of them was larger.</p>
<p><code>nec_data</code> was simulated from a four-parameter threshold equation with its threshold set at 1.5, which <code>data-raw/nec_data.R</code> in the <code>bayesnec</code> sources records, and the pattern follows from that. The threshold equation holds the control level up to 1.5, where the log-logistic has already begun to decline, and then falls more steeply than the log-logistic immediately above it. Above 2.44 the log-logistic approaches zero the faster of the two.</p>
<p>Two readings of the same pair of fits therefore disagree on how far apart they are: the EC10 posteriors separate at a probability of 0.998, and the curves are indistinguishable over the lower third of the concentration range. A single estimate is one point on a curve, and which of the two answers the question depends on what is being reported.</p>
<p>The draws are paired at random, which approximates the difference of two independent posteriors. Both fits here are to the same 100 observations, so this comparison measures the difference between two equations rather than between two experiments. Module 4 covers averaging over the equations rather than choosing between them.</p>
<p>The comparison a real analysis makes is between fits to different data, such as two exposure durations or two levels of a factor. Module 8 does that with <code>bnec_group()</code>, through this same function. <code>comparison</code> also takes <code>"nec"</code>, <code>"nsec"</code> and <code>"n(s)ec"</code>, which compare the no-effect estimates module 3 covers.</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Banner2020" class="csl-entry" role="listitem">
Banner, Katharine M., Kathryn M. Irvine, and Thomas J. Rodhouse. 2020. <span>“The Use of <span>Bayesian</span> Priors in <span>Ecology</span>: <span>The</span> Good, the Bad and the Not Great.”</span> <em>Methods in Ecology and Evolution</em> 11: 882–89. <a href="https://doi.org/10.1111/2041-210X.13407">https://doi.org/10.1111/2041-210X.13407</a>.
</div>
<div id="ref-Burkner2017" class="csl-entry" role="listitem">
Bürkner, Paul Christian. 2017. <span>“<span class="nocase">brms: An R package for Bayesian multilevel models using Stan</span>.”</span> <em>Journal of Statistical Software</em> 80 (1): 1–28. <a href="https://doi.org/10.18637/jss.v080.i01">https://doi.org/10.18637/jss.v080.i01</a>.
</div>
<div id="ref-Carpenter2017" class="csl-entry" role="listitem">
Carpenter, Bob, Andrew Gelman, Matthew D. Hoffman, et al. 2017. <span>“: A Probabilistic Programming Language.”</span> <em>Journal of Statistical Software, Articles</em> 76 (1): 1–32. <a href="https://doi.org/10.18637/jss.v076.i01">https://doi.org/10.18637/jss.v076.i01</a>.
</div>
<div id="ref-Charles2020a" class="csl-entry" role="listitem">
Charles, Sandrine, Dan Wu, and Virginie Ducrot. 2020. <span>“How to Account for the Uncertainty from Standard Toxicity Tests in Species Sensitivity Distributions: An Example in Non-Target Plants.”</span> <em>bioRxiv</em>, ahead of print. <a href="https://doi.org/10.1101/2020.07.02.183863">https://doi.org/10.1101/2020.07.02.183863</a>.
</div>
<div id="ref-depaoli2020importance" class="csl-entry" role="listitem">
Depaoli, Sarah, Sonja D Winter, and Marieke Visser. 2020. <span>“The Importance of Prior Sensitivity Analysis in Bayesian Statistics: Demonstrations Using an Interactive Shiny App.”</span> <em>Frontiers in Psychology</em> 11: 608045.
</div>
<div id="ref-Ellison1996" class="csl-entry" role="listitem">
Ellison, Aaron M. 1996. <span>“An Introduction to <span>Bayesian</span> Inference for Ecological Research and Environmental Decision-Making.”</span> <em>Ecological Applications</em> 6 (4): 1036–46. <a href="https://doi.org/10.2307/2269588">https://doi.org/10.2307/2269588</a>.
</div>
<div id="ref-Fisher2019" class="csl-entry" role="listitem">
Fisher, R, R. A van Dam, G. E Batley, et al. 2019. <em>Key Issues in the Derivation of Water Quality Guideline Values: A Workshop Report.</em> Australian Institute of Marine Science Report, Crawley, WA, Australia. 57 pp. <a href="https://doi.org/10.13140/RG.2.2.29774.82241">https://doi.org/10.13140/RG.2.2.29774.82241</a>.
</div>
<div id="ref-fisheretal2024" class="csl-entry" role="listitem">
Fisher, Rebecca, Diego R. Barneche, Gerard F. Ricardo, and David R. Fox. 2024. <span>“<span class="nocase">bayesnec</span>: An <span>R</span> Package for Concentration-Response Modeling and Estimation of Toxicity Metrics.”</span> <em>Journal of Statistical Software</em> 110 (5): 1–41. <a href="https://doi.org/10.18637/jss.v110.i05">https://doi.org/10.18637/jss.v110.i05</a>.
</div>
<div id="ref-Fisher2019d" class="csl-entry" role="listitem">
Fisher, Rebecca, Pia Bessell-Browne, and Ross Jones. 2019. <span>“Synergistic and Antagonistic Impacts of Suspended Sediments and Thermal Stress on Corals.”</span> <em>Nature Communications</em>. <a href="https://doi.org/10.1038/s41467-019-10288-9">https://doi.org/10.1038/s41467-019-10288-9</a>.
</div>
<div id="ref-fisher2018c" class="csl-entry" role="listitem">
Fisher, Rebecca, Terry Walshe, Pia Bessell-Browne, and Ross Jones. 2018. <span>“Accounting for Environmental Uncertainty in the Management of Dredging Impacts Using Probabilistic Dose–Response Relationships and Thresholds.”</span> <em>Journal of Applied Ecology</em> 55 (1): 415–25. <a href="https://doi.org/10.1111/1365-2664.12936">https://doi.org/10.1111/1365-2664.12936</a>.
</div>
<div id="ref-flores2021" class="csl-entry" role="listitem">
Flores, F., J. A. Marques, S. Uthicke, et al. 2021. <span>“Combined Effects of Climate Change and the Herbicide Diuron on the Coral <em>Acropora Millepora</em>.”</span> <em>Marine Pollution Bulletin</em> 169: 112582. <a href="https://doi.org/10.1016/j.marpolbul.2021.112582">https://doi.org/10.1016/j.marpolbul.2021.112582</a>.
</div>
<div id="ref-cmdstanr2022" class="csl-entry" role="listitem">
Gabry, Jonah, and Rok Češnovar. 2022. <em>: Interface to </em>.
</div>
<div id="ref-gelman2017entropy" class="csl-entry" role="listitem">
Gelman, Andrew, Daniel Simpson, and Michael Betancourt. 2017. <span>“The Prior Can Often Only Be Understood in the Context of the Likelihood.”</span> <em>Entropy</em> 19 (10). <a href="https://doi.org/10.3390/e19100555">https://doi.org/10.3390/e19100555</a>.
</div>
<div id="ref-Gottschalk2013" class="csl-entry" role="listitem">
Gottschalk, Fadri, and Bernd Nowack. 2013. <span>“A Probabilistic Method for Species Sensitivity Distributions Taking into Account the Inherent Uncertainty and Variability of Effects to Estimate Environmental Risk.”</span> <em>Integrated Environmental Assessment and Management</em> 9 (1): 79–86.
</div>
<div id="ref-hoffman2014" class="csl-entry" role="listitem">
Hoffman, Matthew D., and Andrew Gelman. 2014. <span>“The No-u-Turn Sampler: Adaptively Setting Path Lengths in Hamiltonian Monte Carlo.”</span> <em>Journal of Machine Learning Research</em> 15 (47): 1593–623. <a href="http://jmlr.org/papers/v15/hoffman14a.html">http://jmlr.org/papers/v15/hoffman14a.html</a>.
</div>
<div id="ref-Lunn2000" class="csl-entry" role="listitem">
Lunn, David J., Andrew Thomas, Nicky Best, and David Spiegelhalter. 2000.<span>“ - a Bayesian Modelling Framework: Concepts, Structure, and Extensibility.”</span> <em>Statistics and Computing</em> 10 (4): 325–37. <a href="https://doi.org/10.1023/A:1008929526011">https://doi.org/10.1023/A:1008929526011</a>.
</div>
<div id="ref-Thomas2006" class="csl-entry" role="listitem">
Neal, Thomas. 2006. <span>“Hypothesis Testing and Bayesian Estimation Using a Sigmoid Emax Model Applied to Sparse Dose-Response Designs.”</span> <em>Journal of Biopharmaceutical Statistics</em> 16 (5): 657–77. <a href="https://doi.org/10.1080/10543400600860469">https://doi.org/10.1080/10543400600860469</a>.
</div>
<div id="ref-Plummer2003" class="csl-entry" role="listitem">
Plummer, Martyn. 2003. <span>“<span class="nocase">JAGS: A program for analysis of Bayesian graphical models using Gibbs sampling</span>.”</span> <em><span class="nocase">Proceedings of the 3rd International Workshop on Distributed Statistical Computing (DSC 2003)</span></em> (Technische Universität Wien, Vienna, Austria), 1–10.
</div>
<div id="ref-rstan2021" class="csl-entry" role="listitem">
Stan Development Team. 2021. <em>: The Interface to </em>. <a href="http://mc-stan.org/">http://mc-stan.org/</a>.
</div>
<div id="ref-Su2015" class="csl-entry" role="listitem">
Su, Yu-Sung, and Masanao Yajima. 2015. <em><span class="nocase">R2jags: Using R to Run ’JAGS’</span></em>. <a href="https://CRAN.R-project.org/package=R2jags">https://CRAN.R-project.org/package=R2jags</a>.
</div>
<div id="ref-Weimer2012" class="csl-entry" role="listitem">
Weimer, Marc, Xiaoqi Jiang, Oriana Ponta, Sven Stanzel, Alexius Freyberger, and Annette Kopp-Schneider. 2012. <span>“<span class="nocase">The impact of data transformations on concentration-response modeling</span>.”</span> <em>Toxicology Letters</em> 213 (2): 292–98. <a href="https://doi.org/10.1016/j.toxlet.2012.07.012">https://doi.org/10.1016/j.toxlet.2012.07.012</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/open-aims\.github\.io\/cr_modelling_training\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../vignettes/5Response_data_and_statistical_distributions.html" class="pagination-link" aria-label="5. Response data and distributions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">5. Response data and distributions</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../vignettes/7Example_case_study.html" class="pagination-link" aria-label="7. A worked case study">
        <span class="nav-page-text">7. A worked case study</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Australian Institute of Marine Science</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/open-AIMS/cr_modelling_training/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>