##############################################################################
# Module 1 -- The software stack
#
# Generated from vignettes/1Software-stack.qmd
# by scripts/generate_live_scripts.R on 2026-09-23.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/1Software-stack.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (!dir.exists("vignettes")) {
  stop("Open cr_modelling_training.Rproj first: every path below is ",
       "written from the project root, as vignettes/...")
}


# The working environment ----------------------------------------------------


# The dependency chain -------------------------------------------------------

#> backend
options(brms.backend = "cmdstanr")


# Package history ------------------------------------------------------------


# Versions -------------------------------------------------------------------

#> versions
for (p in c("bayesnec", "brms", "cmdstanr", "rstan", "posterior")) {
  cat(sprintf("%-10s %s\n", p, as.character(packageVersion(p))))
}
cat(sprintf("%-10s %s\n", "R", getRversion()))

