##############################################################################
# Module 1 -- The software stack
#
# Generated from vignettes/1Software-stack.qmd
# by scripts/generate_live_scripts.R on 2026-09-19.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/1Software-stack.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# A block that is commented out is one the page shows and does not run. Those
# are the model fits and the calls that are there to be read rather than
# executed. Below each fit is the load() that restores the saved object.
##############################################################################

if (basename(getwd()) != "vignettes") {
  if (dir.exists("vignettes")) {
    setwd("vignettes")
  } else {
    stop("Open the cr_modelling_training project first: every path below is ",
         "relative to its vignettes/ folder.")
  }
}


# The working environment ----------------------------------------------------


# The dependency chain -------------------------------------------------------

#> backend -- shown on the page and not run.
#> Remove the leading # from the lines below to run it yourself.
# options(brms.backend = "cmdstanr")


# Package history ------------------------------------------------------------


# Versions -------------------------------------------------------------------

#> versions
for (p in c("bayesnec", "brms", "cmdstanr", "rstan", "posterior")) {
  cat(sprintf("%-10s %s\n", p, as.character(packageVersion(p))))
}
cat(sprintf("%-10s %s\n", "R", getRversion()))

