##############################################################################
# Module 2 -- Fitting a single model
#
# Generated from vignettes/2Fitting-a-CR-model-using-bayesnec.qmd
# by scripts/generate_live_scripts.R on 2026-09-23.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/2Fitting-a-CR-model-using-bayesnec.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (!dir.exists("vignettes")) {
  stop("Open cr_modelling_training.Rproj first: every path below is ",
       "written from the project root, as vignettes/...")
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("vignettes/fetch_fits.R")
if (!length(list.files("vignettes/fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run ",
       "source(\"vignettes/fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
options(brms.backend = "cmdstanr")
options(mc.cores = 4)
set.seed(333)


# Background -----------------------------------------------------------------


# The example dataset --------------------------------------------------------

#> data
library(bayesnec)
data(nec_data)
head(nec_data)


# Reproducibility ------------------------------------------------------------

#> seed -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# set.seed(333)
# bnec_fit <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data, seed = 333)


# The `bnec` function --------------------------------------------------------


# The formula ----------------------------------------------------------------

#> formula-shape -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# y ~ crf(x, model = "modelname")

#> model-list
models()$all

#> model-groups
names(models())


# Calling `bnec` -------------------------------------------------------------

#> fit -- fits the model here, in about 38 s, most of it compiling.
set.seed(333)
bnec_fit <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data, seed = 333)

# save(bnec_fit, file = "vignettes/fits/m2_bnec_fit.RData")   # not run: it would overwrite the distributed fit

#> load-fit
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m2_bnec_fit.RData")

#> cores
options(mc.cores = 4)
options(brms.backend = "cmdstanr")


# Saving the fit -------------------------------------------------------------

#> save-demo
saveRDS(bnec_fit, "nec3param_fit.rds")
bnec_fit <- readRDS("nec3param_fit.rds")


# The summary ----------------------------------------------------------------

#> summary
summary(bnec_fit)


# The fitting record ---------------------------------------------------------

#> record
rec <- bnec_record(bnec_fit)
names(rec)

#> record-excluded
rec$excluded

#> record-subs
rec$substitutions


# Checking the fit -----------------------------------------------------------

#> check-sampling
check_sampling(bnec_fit)

#> check-fit
cf <- check_fit(bnec_fit)
plot(cf)

#> chains
brm_fit <- pull_brmsfit(bnec_fit)
plot(brm_fit)


# Inside the fitted object ---------------------------------------------------

#> names
names(bnec_fit)

#> predvals
head(bnec_fit$pred_vals$data)

#> ne-posterior
hist(bnec_fit$ne_posterior,
     main = "", xlab = "No-effect concentration", col = "grey80", border = "white")


# Plotting -------------------------------------------------------------------

#> autoplot
autoplot(bnec_fit) +
  ggplot2::xlab("Concentration")


# Toxicity estimates ---------------------------------------------------------

#> estimates
ecx(bnec_fit)
nec(bnec_fit)
nsec(bnec_fit)


# The parameters of the curve ------------------------------------------------

#> curve-params
curve_params(bnec_fit)

