##############################################################################
# Module 3 -- Toxicity estimation and the model set
#
# Generated from vignettes/3Toxicity_estimation_and_available_models.qmd
# by scripts/generate_live_scripts.R on 2026-09-22.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/3Toxicity_estimation_and_available_models.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (!dir.exists("vignettes")) {
  stop("Open cr_modelling_training.Rproj first: every path below is ",
       "written from the project root, as vignettes/...")
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("vignettes/fetch_fits.R")
if (!length(list.files("vignettes/fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run ",
       "source(\"vignettes/fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
library(ggplot2)

# args() returns a function whose body is NULL, which print() then shows on its
# own line. Deparsing and dropping that line gives the signature alone, which is
# what these sections are for.
signature <- function(fun, class = "bayesnecfit") {
  txt <- deparse(args(getS3method(fun, class)))
  cat(paste(utils::head(txt, -1), collapse = "\n"), "\n")
}


# Background -----------------------------------------------------------------


# The model set --------------------------------------------------------------

#> model-set
models()$all

#> model-groups
names(models())


# Parameter definitions ------------------------------------------------------


# Threshold models -----------------------------------------------------------


# Smooth models --------------------------------------------------------------


# The no-significant-effect concentration ------------------------------------


#   The effect size at the NSEC ----------------------------------------------

#> ecnsec-demo
#> bnec_fit comes from an earlier module. The page reads on from there; this line is added so the block runs.
load("vignettes/fits/m2_bnec_fit.RData")
nsec_value <- nsec(bnec_fit)
attr(nsec_value, "ecnsec_relativeP")

ecnsec(bnec_fit, nsec = nsec_value)


# The NSEC and the NOEC ------------------------------------------------------


# Choosing an estimate -------------------------------------------------------


# Hormesis -------------------------------------------------------------------

#> horme-nec
intersect(models()$hormesis, models()$nec)

#> horme-ecx
intersect(models()$hormesis, models()$ecx)


# Extracting estimates -------------------------------------------------------


#   `nec()` ------------------------------------------------------------------

#> nec-args
signature("nec")


#   `ecx()` ------------------------------------------------------------------

#> ecx-args
signature("ecx")

#> fig-ecx-types -- draws a figure on the page; the page shows the figure and not this code.
# The four panels are drawn from the equations as bayesnec writes them in
# pred_equations.R, at parameters chosen to make each comparison visible. No
# model is fitted: the point is the geometry of the four spans, which does not
# depend on any particular data set.
p_ecxll4 <- function(x, top = 1, bot = 0.3, ec50 = 3, beta = log(1.5)) {
  bot + (top - bot) / (1 + exp(exp(beta) * (x - ec50)))
}
p_ecxll3 <- function(x, top = 1, ec50 = 3, beta = log(1.5)) {
  top / (1 + exp(exp(beta) * (x - ec50)))
}
p_ecxhormebc4 <- function(x, top = 1, ec50 = 3, beta = log(1.5),
                          slope = log(0.3)) {
  (top + exp(slope) * x) / (1 + exp(exp(beta) * (x - ec50)))
}

# Every x at which the curve meets the target, interpolated within the grid
# interval, as crossing_x() does inside ecx(). All of them rather than the
# first, because a target taken from the curve maximum has two on a hormetic
# curve and that is what panel D is for.
meets <- function(x, y, target) {
  s <- sign(y - target)
  i <- which(s[-1] != s[-length(s)])
  x[i] + (y[i] - target) / (y[i] - y[i + 1]) * (x[i + 1] - x[i])
}

pct <- 10
panel_spans <- function(label, fun, xmax, bot, use) {
  x <- seq(0, xmax, length.out = 2000)
  y <- fun(x)
  upper <- c(absolute = y[1], relative = y[1], range = y[1], maximum = max(y))
  lower <- c(absolute = 0, relative = bot, range = min(y), maximum = 0)
  est <- do.call(rbind, lapply(seq_along(use), function(i) {
    s <- use[i]
    target <- upper[[s]] - (upper[[s]] - lower[[s]]) * pct / 100
    data.frame(panel = label, span = s, lower = lower[[s]],
               upper = upper[[s]], target = target,
               # each span's bracket gets its own x so that two of equal
               # length read as two lines rather than one
               bx = xmax * (0.74 + 0.07 * (i - 1)))
  }))
  cross <- do.call(rbind, lapply(seq_len(nrow(est)), function(i) {
    hit <- meets(x, y, est$target[i])
    data.frame(panel = label, span = est$span[i], x = hit,
               y = est$target[i])
  }))
  list(curve = data.frame(panel = label, x = x, y = y),
       ctrl = data.frame(panel = label, control = y[1], xmax = xmax),
       est = est, cross = cross)
}

parts <- list(
  panel_spans("A  a curve that reaches bot", p_ecxll4, 10, 0.3,
              c("absolute", "relative", "range")),
  panel_spans("B  the same curve, tested only to 3", p_ecxll4, 3, 0.3,
              c("absolute", "relative", "range")),
  panel_spans("C  an equation with no bot", p_ecxll3, 10, 0,
              c("absolute", "relative", "range")),
  panel_spans("D  a hormetic curve", p_ecxhormebc4, 10, 0,
              c("absolute", "maximum"))
)
curves <- do.call(rbind, lapply(parts, `[[`, "curve"))
ctrl <- do.call(rbind, lapply(parts, `[[`, "ctrl"))
est <- do.call(rbind, lapply(parts, `[[`, "est"))
cross <- do.call(rbind, lapply(parts, `[[`, "cross"))

# Two spans can end in the same place, which is what panels A and C are for.
# The wider line is drawn first and the narrower over it, and the "range"
# target is dashed, so a coincidence reads as two lines rather than one.
wid <- c(absolute = 1.4, relative = 0.75, range = 0.3, maximum = 0.75)
lty <- c(absolute = "longdash", relative = "dashed", range = "dotted",
         maximum = "longdash")
ord <- c(absolute = 1, relative = 2, maximum = 2, range = 3)
est <- est[order(ord[est$span]), ]
cross <- cross[order(ord[cross$span]), ]
est$w <- wid[est$span]
est$lt <- lty[est$span]
est$tlt <- ifelse(est$span == "range", "22", "solid")
cross$w <- wid[cross$span]

lab <- c(absolute = 'type = "absolute": control to 0',
         relative = 'type = "relative": control to bot',
         range = 'type = "range": control to the lowest response predicted',
         maximum = 'the reference before 2.2.0: curve maximum to 0')
cols <- c(absolute = "#1b6ca8", relative = "#c1440e",
          range = "#009E73", maximum = "#8a5fa8")

ggplot() +
  geom_hline(data = ctrl, aes(yintercept = control), colour = "grey55",
             linetype = "dotted") +
  geom_hline(data = est, aes(yintercept = lower, colour = span,
                             linetype = lt), linewidth = 0.45) +
  geom_hline(data = est, aes(yintercept = target, colour = span,
                             linewidth = w, linetype = tlt)) +
  geom_segment(data = cross, aes(x = x, xend = x, y = 0, yend = y,
                                 colour = span),
               linetype = "dotted", linewidth = 0.4) +
  geom_segment(data = est, aes(x = bx, xend = bx, y = lower, yend = upper,
                               colour = span), linewidth = 0.45,
               arrow = arrow(ends = "both", length = unit(0.05, "in"),
                             type = "closed")) +
  geom_line(data = curves, aes(x, y), linewidth = 0.8) +
  geom_point(data = cross, aes(x, y, colour = span, size = w)) +
  geom_text(data = ctrl, aes(x = xmax, y = control, label = "control"),
            hjust = 1, vjust = -0.6, size = 2.9, colour = "grey45") +
  facet_wrap(~panel, scales = "free_x") +
  scale_colour_manual(values = cols, labels = lab, breaks = names(lab),
                      name = NULL) +
  scale_linewidth_identity() +
  scale_linetype_identity() +
  scale_size_continuous(range = c(1.1, 2.3), guide = "none") +
  labs(x = "concentration", y = "response") +
  theme_classic() +
  theme(legend.position = "top", legend.direction = "vertical",
        legend.key.height = unit(0.85, "lines"))


#   `nsec()` -----------------------------------------------------------------

#> nsec-args
signature("nsec")

