##############################################################################
# Module 4 -- Model averaging and multi-model inference
#
# Generated from vignettes/4Model_averaging_and_multimodel_inference.qmd
# by scripts/generate_live_scripts.R on 2026-09-23.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/4Model_averaging_and_multimodel_inference.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (!dir.exists("vignettes")) {
  stop("Open cr_modelling_training.Rproj first: every path below is ",
       "written from the project root, as vignettes/...")
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("vignettes/fetch_fits.R")
if (!length(list.files("vignettes/fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run ",
       "source(\"vignettes/fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
options(brms.backend = "cmdstanr")
options(mc.cores = 4)
set.seed(333)
data(nec_data)


# Background -----------------------------------------------------------------


# Choosing among the equations -----------------------------------------------


# Multi-model inference ------------------------------------------------------


# Model averaging ------------------------------------------------------------


# The N(S)EC -----------------------------------------------------------------


# Model averaging in `bayesnec` ----------------------------------------------


# Combining single fits ------------------------------------------------------

#> fit-nec3param -- fits the model here, in about 38 s, most of it compiling.
set.seed(333)
data(nec_data)
bnec_fit <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data)

# save(bnec_fit, file = "vignettes/fits/m4_bnec_fit.RData")   # not run: it would overwrite the distributed fit

#> load-fit-nec3param
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m4_bnec_fit.RData")

#> fit-ecxll3 -- fits the model here, in about 37 s, most of it compiling.
set.seed(333)
bnec_fit_new <- bnec(y ~ crf(x, model = "ecxll3"), data = nec_data)

# save(bnec_fit_new, file = "vignettes/fits/m4_bnec_fit_new.RData")   # not run: it would overwrite the distributed fit

#> load-fit-ecxll3
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m4_bnec_fit_new.RData")

#> fig-ecxll3
autoplot(bnec_fit_new)

#> combine
bmanecfit <- c(bnec_fit_new, bnec_fit)

#> classes
class(bnec_fit_new)
class(bnec_fit)
class(bmanecfit)

#> amend -- fits the model here, in about 43 s, most of it compiling.
bmanecfit_more <- amend(bmanecfit, add = "ecxexp")

# save(bmanecfit_more, file = "vignettes/fits/m4_bmanecfit_more.RData")   # not run: it would overwrite the distributed fit

#> load-amend
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m4_bmanecfit_more.RData")


# Fitting a named set --------------------------------------------------------

#> fit-named-set -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# fit_set <- bnec(y ~ crf(x, model = "decline"), data = nec_data, seed = 333)

#> model-sets
models()


# Plotting an averaged fit ---------------------------------------------------

#> fig-manec
autoplot(bmanecfit_more)


# The summary ----------------------------------------------------------------

#> summary
summary(bmanecfit_more)


# The weighting method -------------------------------------------------------

#> loo-controls -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# bnec(y ~ crf(x, model = "decline"), data = nec_data,
#      loo_controls = list(weights = list(method = "stacking")))


# Elements of the fitted object ----------------------------------------------

#> modstats
bmanecfit_more$mod_stats

#> pullout
bmanec_ecxexp <- pull_out(bmanecfit_more, model = "ecxexp")

#> pullbest
best <- pull_best(bmanecfit_more)

#> curve-params-set
curve_params(bmanecfit_more)


# Every model in the set -----------------------------------------------------

#> fig-allmodels
autoplot(bmanecfit_more, all_models = TRUE)


# Fitting a set in parallel --------------------------------------------------

#> parallel-basic -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# library(future)
# plan(multisession, workers = 8)
# fit_par <- bnec(y ~ crf(x, model = "decline"), data = nec_data, seed = 322)
# plan(sequential)

#> parallel-nested -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# plan(multisession, workers = 5)
# fit_nested <- bnec(y ~ crf(x, model = "decline"), data = nec_data,
#                    cores = 4, seed = 322)
# plan(sequential)

