##############################################################################
# Module 5 -- Response data and statistical distributions
#
# Generated from vignettes/5Response_data_and_statistical_distributions.qmd
# by scripts/generate_live_scripts.R on 2026-09-19.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/5Response_data_and_statistical_distributions.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# A block that is commented out is one the page shows and does not run. Those
# are the model fits and the calls that are there to be read rather than
# executed. Below each fit is the load() that restores the saved object.
##############################################################################

if (basename(getwd()) != "vignettes") {
  if (dir.exists("vignettes")) {
    setwd("vignettes")
  } else {
    stop("Open the cr_modelling_training project first: every path below is ",
         "relative to its vignettes/ folder.")
  }
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("fetch_fits.R")
if (!length(list.files("fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run source(\"fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
library(dplyr)
library(ggplot2)
options(mc.cores = 4)
set.seed(333)


# Background -----------------------------------------------------------------


# Generalised modelling ------------------------------------------------------


# Families available in `brms` -----------------------------------------------


# Link functions -------------------------------------------------------------

#> links
bayesnec:::supported_links()


# Families implemented in `bayesnec` -----------------------------------------

#> families
names(bayesnec:::mod_fams)


# Default behaviour ----------------------------------------------------------


# Binomial -------------------------------------------------------------------

#> binom-data
binom_data <- read.csv("example_binomial.csv") |>
  mutate(log.x = log(raw_x))
summary(binom_data$raw_x)
head(binom_data)

#> binom-formula -- shown on the page and not run.
#> Remove the leading # from the lines below to run it yourself.
# suc | trials(tot) ~ crf(log.x, model = "your_model")

#> fit-binom-nec -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_1nec <- bnec(suc | trials(tot) ~ crf(log.x, model = "nec3param"),
#                  data = binom_data, seed = 333)
#
# save(exp_1nec, file = "fits/m5_exp_1nec.RData")

#> load-fit-binom-nec
load("fits/m5_exp_1nec.RData")

#> fig-binom-nec
autoplot(exp_1nec)


#   The dispersion screen ----------------------------------------------------

#> dispersion-binom
dispersion(exp_1nec, summary = TRUE)

#> fit-binom-ecx -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_1ecx <- bnec(suc | trials(tot) ~ crf(log.x, model = "ecxll3"),
#                  data = binom_data, seed = 333)
#
# save(exp_1ecx, file = "fits/m5_exp_1ecx.RData")

#> load-fit-binom-ecx
load("fits/m5_exp_1ecx.RData")

#> fig-binom-ecx
autoplot(exp_1ecx)


# Beta-binomial --------------------------------------------------------------

#> fit-betabinom -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_1b <- bnec(suc | trials(tot) ~ crf(log.x, model = c("ecxll3", "nec3param")),
#                data = binom_data, family = "beta_binomial", seed = 333)
#
# save(exp_1b, file = "fits/m5_exp_1b.RData")

#> load-fit-betabinom
load("fits/m5_exp_1b.RData")

#> fig-betabinom
autoplot(exp_1b, all_models = TRUE)


#   Checking the fit within concentrations -----------------------------------

#> check-fit-binom
cf_1nec <- check_fit(exp_1nec)
cf_1nec

#> fig-checkfit-binom
plot(cf_1nec)

#> check-fit-betabinom
cf_1b <- check_fit(exp_1b)
cf_1b

#> fig-checkfit-betabinom
plot(cf_1b)


# Beta -----------------------------------------------------------------------

#> beta-data
prop_data <- read.csv("example_proportion.csv") |>
  mutate(log.x = log(raw_x))

#> fit-beta -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_2 <- bnec(resp ~ crf(log.x, model = c("ecxll3", "nec3param")),
#               data = prop_data, seed = 333)
#
# save(exp_2, file = "fits/m5_exp_2.RData")

#> load-fit-beta
load("fits/m5_exp_2.RData")

#> fig-beta
autoplot(exp_2, all_models = TRUE)

#> beta-stats
exp_2$mod_stats

#> check-fit-beta
check_fit(exp_2)[, c("model", "wi", "group", "mean_ratio", "ppp_mean",
                     "sd_ratio", "ppp_sd", "control")]


#   Values on the boundary ---------------------------------------------------

#> subs-beta
bnec_record(exp_2)$substitutions


# Poisson --------------------------------------------------------------------

#> count-data
set.seed(333)
data(nec_data)
count_data <- nec_data |>
  mutate(
    y = (y * 100 + rnorm(nrow(nec_data), 0, 15)) |>
      round() |> as.integer() |> abs()
  )
str(count_data)

#> fit-pois -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_3 <- bnec(y ~ crf(x, model = c("ecxll3", "nec3param")), data = count_data)
#
# save(exp_3, file = "fits/m5_exp_3.RData")

#> load-fit-pois
load("fits/m5_exp_3.RData")

#> fig-pois
autoplot(exp_3, all_models = TRUE)

#> dispersion-pois
summary(exp_3)$mod_weights

#> fig-checkfit-pois
plot(check_fit(exp_3))


#   Counts observed over an exposure -----------------------------------------

#> rate-demo -- shown on the page and not run.
#> Remove the leading # from the lines below to run it yourself.
# y | rate(n_females) ~ crf(x, model = "nec4param")


# Negative binomial ----------------------------------------------------------

#> fit-negbin -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_3b <- bnec(y ~ crf(x, model = c("ecxll3", "nec3param")),
#                data = count_data, family = "negbinomial")
#
# save(exp_3b, file = "fits/m5_exp_3b.RData")

#> load-fit-negbin
load("fits/m5_exp_3b.RData")

#> fig-negbin
autoplot(exp_3b, all_models = TRUE)

#> fig-checkfit-negbin
plot(check_fit(exp_3b))


# Gamma ----------------------------------------------------------------------

#> gamma-data
data(nec_data)
measure_data <- nec_data |>
  mutate(measure = exp(y))

#> fit-gamma -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_4 <- bnec(measure ~ crf(x, model = c("ecxll3", "nec3param")),
#               data = measure_data)
#
# save(exp_4, file = "fits/m5_exp_4.RData")

#> load-fit-gamma
load("fits/m5_exp_4.RData")

#> fig-gamma
autoplot(exp_4, all_models = TRUE)


# Gaussian -------------------------------------------------------------------

#> gauss-data
gaussian_data <- prop_data |>
  mutate(y = car::logit(resp))

#> fit-gauss -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_5 <- bnec(y ~ crf(log.x, model = c("ecxll4", "nec4param")),
#               data = gaussian_data, seed = 333)
#
# save(exp_5, file = "fits/m5_exp_5.RData")

#> load-fit-gauss
load("fits/m5_exp_5.RData")

#> fig-gauss
autoplot(exp_5, all_models = TRUE)

#> check-fit-gauss
cf_5 <- check_fit(exp_5)
cf_5[, c("model", "wi", "group", "sd_ratio", "ppp_sd", "control")]

#> fig-checkfit-gauss
plot(cf_5)


#   Growth rates -------------------------------------------------------------


# Model suitability by response type -----------------------------------------

#> excluded
bnec_record(exp_2)$excluded


# Values that are not measurements -------------------------------------------


#   Censored values ----------------------------------------------------------

#> cens-demo -- shown on the page and not run.
#> Remove the leading # from the lines below to run it yourself.
# y | cens(censoring) ~ crf(x, model = "nec4param")


#   The limit of a censored likelihood ---------------------------------------


#   Zeros --------------------------------------------------------------------


#   Hurdle against zero-inflated ---------------------------------------------

#> hurdle-fams
names(bayesnec:::mod_fams)


# Preparing the response -----------------------------------------------------


#   The reason a divisor gets reached for ------------------------------------


# Dispersion that changes across the curve -----------------------------------

#> disp-demo -- shown on the page and not run.
#> Remove the leading # from the lines below to run it yourself.
# y ~ crf(x, model = "nec4param") + disp(~x)         # varies along the predictor
# y ~ crf(x, model = "nec4param") + disp("power")    # varies with the fitted mean


#   A worked case ------------------------------------------------------------

#> fig-disp-cv
conc_breaks <- c(0.01, 0.1, 1, 10, 100)

cv_by_conc <- prop_data |>
  group_by(raw_x) |>
  summarise(cv = sd(resp) / mean(resp), .groups = "drop")

ggplot(cv_by_conc, aes(raw_x, cv)) +
  geom_line(colour = "grey60") +
  geom_point(size = 2.5, colour = "#1b6ca8") +
  scale_x_log10(breaks = conc_breaks, labels = conc_breaks) +
  labs(x = "concentration", y = "coefficient of variation") +
  theme_classic()

#> fit-disp -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# exp_2_const <- bnec(resp ~ crf(log.x, model = "nec3param"),
#                     data = prop_data, seed = 333)
#
# exp_2_disp <- bnec(resp ~ crf(log.x, model = "nec3param") + disp("power"),
#                    data = prop_data, seed = 333)
#
# save(exp_2_const, file = "fits/m5_exp_2_const.RData")
# save(exp_2_disp, file = "fits/m5_exp_2_disp.RData")

#> load-fit-disp
load("fits/m5_exp_2_const.RData")
load("fits/m5_exp_2_disp.RData")

#> fig-disp-fit-const
autoplot(exp_2_const)

#> fig-disp-fit-power
autoplot(exp_2_disp)

#> fig-disp-predict
disp_grid <- data.frame(log.x = seq(min(prop_data$log.x), max(prop_data$log.x),
                                    length.out = 100))

pp_band <- function(fit, label) {
  p <- predict(pull_brmsfit(fit), newdata = disp_grid)
  data.frame(raw_x = exp(disp_grid$log.x), fit = label,
             Estimate = p[, "Estimate"], Q2.5 = p[, "Q2.5"], Q97.5 = p[, "Q97.5"])
}

bands <- rbind(pp_band(exp_2_const, "constant dispersion"),
               pp_band(exp_2_disp, "disp(\"power\")"))

disp_cols <- c("constant dispersion" = "#1b6ca8", "disp(\"power\")" = "#c1440e")

ggplot(bands, aes(raw_x)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5, fill = fit), alpha = 0.35) +
  geom_line(aes(y = Estimate, colour = fit), linewidth = 0.7) +
  geom_point(data = prop_data, aes(y = resp), size = 1.2, alpha = 0.6) +
  scale_x_log10(breaks = conc_breaks, labels = conc_breaks) +
  scale_fill_manual(values = disp_cols) +
  scale_colour_manual(values = disp_cols) +
  labs(x = "concentration", y = "response", fill = NULL, colour = NULL) +
  theme_classic() +
  theme(legend.position = "top")

#> fig-disp-checkfit
plot(check_fit(exp_2_const))

#> fig-disp-checkfit-power
plot(check_fit(exp_2_disp))

