##############################################################################
# Module 5 -- Response data and statistical distributions
#
# Generated from vignettes/5Response_data_and_statistical_distributions.qmd
# by scripts/generate_live_scripts.R on 2026-09-22.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/5Response_data_and_statistical_distributions.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (!dir.exists("vignettes")) {
  stop("Open cr_modelling_training.Rproj first: every path below is ",
       "written from the project root, as vignettes/...")
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("vignettes/fetch_fits.R")
if (!length(list.files("vignettes/fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run ",
       "source(\"vignettes/fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
library(dplyr)
library(ggplot2)
options(brms.backend = "cmdstanr")
options(mc.cores = 4)
set.seed(333)


# Background -----------------------------------------------------------------


# Generalised modelling ------------------------------------------------------


# Families available in `brms` -----------------------------------------------


# Link functions -------------------------------------------------------------

#> links
bayesnec:::supported_links()


# Families implemented in `bayesnec` -----------------------------------------

#> families
names(bayesnec:::mod_fams)


# Default behaviour ----------------------------------------------------------


# Binomial -------------------------------------------------------------------

#> binom-data
binom_data <- read.csv("vignettes/example_binomial.csv") |>
  mutate(log.x = log(raw_x))
summary(binom_data$raw_x)
head(binom_data)

#> binom-formula -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# suc | trials(tot) ~ crf(log.x, model = "your_model")

#> fit-binom-nec -- fits the model here, in about 36 s, most of it compiling.
set.seed(333)
exp_1nec <- bnec(suc | trials(tot) ~ crf(log.x, model = "nec3param"),
                 data = binom_data, seed = 333)

# save(exp_1nec, file = "vignettes/fits/m5_exp_1nec.RData")   # not run: it would overwrite the distributed fit

#> load-fit-binom-nec
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m5_exp_1nec.RData")

#> fig-binom-nec
autoplot(exp_1nec)


#   The dispersion screen ----------------------------------------------------

#> dispersion-binom
dispersion(exp_1nec, summary = TRUE)

#> fit-binom-ecx -- fits the model here, in about 36 s, most of it compiling.
set.seed(333)
exp_1ecx <- bnec(suc | trials(tot) ~ crf(log.x, model = "ecxll3"),
                 data = binom_data, seed = 333)

# save(exp_1ecx, file = "vignettes/fits/m5_exp_1ecx.RData")   # not run: it would overwrite the distributed fit

#> load-fit-binom-ecx
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m5_exp_1ecx.RData")

#> fig-binom-ecx
autoplot(exp_1ecx)


# Beta-binomial --------------------------------------------------------------

#> fit-betabinom -- not run here: fitting this takes about 76 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_1b <- bnec(suc | trials(tot) ~ crf(log.x, model = c("ecxll3", "nec3param")),
#                data = binom_data, family = "beta_binomial", seed = 333)
#
# save(exp_1b, file = "vignettes/fits/m5_exp_1b.RData")

#> load-fit-betabinom
load("vignettes/fits/m5_exp_1b.RData")

#> fig-betabinom
autoplot(exp_1b, all_models = TRUE)


# Checking the family reproduces the data ------------------------------------

#> check-fit-binom
cf_1nec <- check_fit(exp_1nec)
cf_1nec

#> fig-checkfit-binom
plot(cf_1nec)

#> check-fit-betabinom
cf_1b <- check_fit(exp_1b)
cf_1b

#> fig-checkfit-betabinom
plot(cf_1b)


# Beta -----------------------------------------------------------------------

#> beta-data
data(coral_pam)
pam_data <- subset(coral_pam, climate == "2018")
table(pam_data$diuron)
range(pam_data$yield)

#> beta-prep
pam_data$log.x <- log(pam_data$diuron +
                        min(pam_data$diuron[pam_data$diuron > 0]) / 10)

#> fit-beta -- not run here: fitting this takes about 80 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_2 <- bnec(yield ~ crf(log.x, model = c("ecxll3", "nec3param")),
#               data = pam_data, seed = 333)
#
# save(exp_2, file = "vignettes/fits/m5_exp_2.RData")

#> load-fit-beta
load("vignettes/fits/m5_exp_2.RData")

#> fig-beta
autoplot(exp_2, all_models = TRUE)

#> beta-stats
exp_2$mod_stats[, c("model", "waic", "wi")]

#> check-fit-beta
cf_2 <- check_fit(exp_2)
cf_2[, c("model", "wi", "group", "mean_ratio", "ppp_mean",
         "sd_ratio", "ppp_sd", "control")]

#> fig-checkfit-beta
plot(cf_2)


#   Values on the boundary ---------------------------------------------------

#> beta-zeros
tapply(pam_data$yield, pam_data$diuron, function(z) sum(z == 0))

#> subs-beta
bnec_record(exp_2)$substitutions


# Poisson --------------------------------------------------------------------

#> count-data
data(alga)
alga_data <- subset(alga, species == "c_proliferum" & contaminant == "A")
alga_data$log.x <- log(alga_data$dose +
                         min(alga_data$dose[alga_data$dose > 0]) / 10)
str(alga_data[, c("dose", "density", "sgr", "days")])

#> count-overdispersion
ctrl <- alga_data$density[alga_data$dose == 0]
c(mean = mean(ctrl), observed_sd = sd(ctrl), poisson_sd = sqrt(mean(ctrl)))

#> fit-pois -- not run here: fitting this takes about 73 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_3 <- bnec(density ~ crf(log.x, model = c("ecxll3", "nec3param")),
#               data = alga_data, family = "poisson", seed = 333)
#
# save(exp_3, file = "vignettes/fits/m5_exp_3.RData")

#> load-fit-pois
load("vignettes/fits/m5_exp_3.RData")

#> fig-pois
autoplot(exp_3, all_models = TRUE)

#> dispersion-pois
summary(exp_3)$mod_weights

#> fig-checkfit-pois
cf_3 <- check_fit(exp_3)
plot(cf_3)


#   Counts observed over an exposure -----------------------------------------

#> rate-demo -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# y | rate(n_females) ~ crf(x, model = "nec4param")


# Negative binomial ----------------------------------------------------------

#> fit-negbin -- not run here: fitting this takes about 76 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_3b <- bnec(density ~ crf(log.x, model = c("ecxll3", "nec3param")),
#                data = alga_data, family = "negbinomial", seed = 333)
#
# save(exp_3b, file = "vignettes/fits/m5_exp_3b.RData")

#> load-fit-negbin
load("vignettes/fits/m5_exp_3b.RData")

#> fig-negbin
autoplot(exp_3b, all_models = TRUE)

#> fig-checkfit-negbin
cf_3b <- check_fit(exp_3b)
plot(cf_3b)


# Gamma ----------------------------------------------------------------------

#> gamma-data
data(lum31)
lum_data <- subset(lum31, plate == "Zn 28Mar24 Rep1B")
lum_data$log.x <- log(lum_data$conc)
c(wells = nrow(lum_data), concentrations = length(unique(lum_data$conc)),
  min_rlu = min(lum_data$rlu), max_rlu = max(lum_data$rlu))

#> gamma-cv
lum_data |>
  group_by(conc) |>
  summarise(mean_rlu = round(mean(rlu)), cv = round(sd(rlu) / mean(rlu), 3),
            .groups = "drop") |>
  as.data.frame()

#> fit-gamma -- not run here: fitting this takes about 75 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_4 <- bnec(rlu ~ crf(log.x, model = c("ecxll3", "nec3param")),
#               data = lum_data, family = "Gamma", seed = 333)
#
# save(exp_4, file = "vignettes/fits/m5_exp_4.RData")

#> load-fit-gamma
load("vignettes/fits/m5_exp_4.RData")

#> fig-gamma
autoplot(exp_4, all_models = TRUE)

#> fig-checkfit-gamma
cf_4 <- check_fit(exp_4)
plot(cf_4)


# Gaussian -------------------------------------------------------------------

#> gauss-data
range(alga_data$sgr)
tapply(alga_data$sgr, alga_data$dose, function(z) round(mean(z), 3))

#> fit-gauss -- not run here: fitting this takes about 78 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_5 <- bnec(sgr ~ crf(log.x, model = c("ecxll4", "nec4param")),
#               data = alga_data, seed = 333)
#
# save(exp_5, file = "vignettes/fits/m5_exp_5.RData")

#> load-fit-gauss
load("vignettes/fits/m5_exp_5.RData")

#> fig-gauss
autoplot(exp_5, all_models = TRUE)

#> check-fit-gauss
cf_5 <- check_fit(exp_5)
cf_5[, c("model", "wi", "group", "sd_ratio", "ppp_sd", "control")]

#> fig-checkfit-gauss
plot(cf_5)


#   Growth rates -------------------------------------------------------------


# Model suitability by response type -----------------------------------------

#> excluded
bnec_record(exp_2)$excluded


# Censored values ------------------------------------------------------------

#> cens-demo -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# y | cens(censoring) ~ crf(x, model = "nec4param")


# Zeros ----------------------------------------------------------------------


# Hurdle and zero-inflated models --------------------------------------------

#> hurdle-fams
names(bayesnec:::mod_fams)


#   A hurdle gamma in practice -----------------------------------------------

#> nass-data
data(nassarius)
snail <- subset(nassarius, contaminant == "A")
str(snail)

#> nass-mortality
tapply(snail$alive, snail$dose, function(z) sprintf("%d of %d", sum(z), length(z)))

#> nass-prep
pos_min <- min(snail$growth[snail$growth > 0])
snail$growth <- ifelse(snail$alive == 1 & snail$growth <= 0, pos_min / 2,
                       snail$growth)

offset <- min(snail$dose[snail$dose > 0]) / 10
snail$log_dose <- log(snail$dose + offset)
back <- function(z) exp(z) - offset

#> fit-hurdle -- not run here: fitting this takes about 4 min.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_6 <- bnec_hurdle(growth ~ crf(log_dose, model = c("nec3param", "ecxll3")),
#                      data = snail, seed = 333,
#                      control = list(adapt_delta = 0.99))
#
# save(exp_6, file = "vignettes/fits/m5_exp_6.RData")

#> load-fit-hurdle
load("vignettes/fits/m5_exp_6.RData")

#> nass-summary
summary(exp_6, xform = back)

#> fig-nass
autoplot(exp_6, which = "all")


# Preparing the response -----------------------------------------------------


#   The reason a divisor gets reached for ------------------------------------


# Modelling dispersion -------------------------------------------------------

#> disp-demo -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# y ~ crf(x, model = "nec4param") + disp(~x)         # varies along the predictor
# y ~ crf(x, model = "nec4param") + disp("power")    # varies with the fitted mean


#   A worked case ------------------------------------------------------------

#> disp-baseline
exp_4_const <- pull_out(exp_4, "nec3param")

#> fit-disp -- fits the model here, in about 48 s, most of it compiling.
set.seed(333)
exp_4_disp <- bnec(rlu ~ crf(log.x, model = "nec3param") + disp("power"),
                   data = lum_data, family = "Gamma", seed = 333)

# save(exp_4_disp, file = "vignettes/fits/m5_exp_4_disp.RData")   # not run: it would overwrite the distributed fit

#> load-fit-disp
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m5_exp_4_disp.RData")

#> fig-disp-checkfit
cf_const <- check_fit(exp_4_const)
plot(cf_const)

#> fig-disp-checkfit-power
cf_disp <- check_fit(exp_4_disp)
plot(cf_disp)

#> disp-compare-table
# The `group` column holds the logged predictor, because that is the scale the
# model was fitted on. It is returned to concentrations here so the table can be
# read against the coefficients of variation above.
data.frame(
  conc = signif(exp(as.numeric(cf_const$group)), 3),
  obs_sd = round(cf_const$obs_sd),
  sim_sd_const = round(cf_const$sim_sd),
  sim_sd_disp = round(cf_disp$sim_sd),
  sd_ratio_const = round(cf_const$sd_ratio, 2),
  sd_ratio_disp = round(cf_disp$sd_ratio, 2))

#> disp-estimates
rbind(`constant dispersion` = nsec(exp_4_const, xform = exp),
      `disp("power")`       = nsec(exp_4_disp, xform = exp))

#> disp-estimates-2
rbind(`constant dispersion` = nec(exp_4_const, xform = exp),
      `disp("power")`       = nec(exp_4_disp, xform = exp))

