##############################################################################
# Module 5 -- Response data and statistical distributions
#
# Generated from vignettes/5Response_data_and_statistical_distributions.qmd
# by scripts/generate_live_scripts.R on 2026-09-21.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/5Response_data_and_statistical_distributions.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (!dir.exists("vignettes")) {
  stop("Open cr_modelling_training.Rproj first: every path below is ",
       "written from the project root, as vignettes/...")
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("vignettes/fetch_fits.R")
if (!length(list.files("vignettes/fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run ",
       "source(\"vignettes/fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
library(dplyr)
library(ggplot2)
options(brms.backend = "cmdstanr")
options(mc.cores = 4)
set.seed(333)


# Background -----------------------------------------------------------------


# Generalised modelling ------------------------------------------------------


# Families available in `brms` -----------------------------------------------


# Link functions -------------------------------------------------------------

#> links
bayesnec:::supported_links()


# Families implemented in `bayesnec` -----------------------------------------

#> families
names(bayesnec:::mod_fams)


# Default behaviour ----------------------------------------------------------


# Binomial -------------------------------------------------------------------

#> binom-data
binom_data <- read.csv("vignettes/example_binomial.csv") |>
  mutate(log.x = log(raw_x))
summary(binom_data$raw_x)
head(binom_data)

#> binom-formula -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# suc | trials(tot) ~ crf(log.x, model = "your_model")

#> fit-binom-nec -- fits the model here, in about 36 s, most of it compiling.
set.seed(333)
exp_1nec <- bnec(suc | trials(tot) ~ crf(log.x, model = "nec3param"),
                 data = binom_data, seed = 333)

# save(exp_1nec, file = "vignettes/fits/m5_exp_1nec.RData")   # not run: it would overwrite the distributed fit

#> load-fit-binom-nec
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m5_exp_1nec.RData")

#> fig-binom-nec
autoplot(exp_1nec)


#   The dispersion screen ----------------------------------------------------

#> dispersion-binom
dispersion(exp_1nec, summary = TRUE)

#> fit-binom-ecx -- fits the model here, in about 36 s, most of it compiling.
set.seed(333)
exp_1ecx <- bnec(suc | trials(tot) ~ crf(log.x, model = "ecxll3"),
                 data = binom_data, seed = 333)

# save(exp_1ecx, file = "vignettes/fits/m5_exp_1ecx.RData")   # not run: it would overwrite the distributed fit

#> load-fit-binom-ecx
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m5_exp_1ecx.RData")

#> fig-binom-ecx
autoplot(exp_1ecx)


# Beta-binomial --------------------------------------------------------------

#> fit-betabinom -- not run here: fitting this takes about 76 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_1b <- bnec(suc | trials(tot) ~ crf(log.x, model = c("ecxll3", "nec3param")),
#                data = binom_data, family = "beta_binomial", seed = 333)
#
# save(exp_1b, file = "vignettes/fits/m5_exp_1b.RData")

#> load-fit-betabinom
load("vignettes/fits/m5_exp_1b.RData")

#> fig-betabinom
autoplot(exp_1b, all_models = TRUE)


# Checking the family reproduces the data ------------------------------------

#> check-fit-binom
cf_1nec <- check_fit(exp_1nec)
cf_1nec

#> fig-checkfit-binom
plot(cf_1nec)

#> check-fit-betabinom
cf_1b <- check_fit(exp_1b)
cf_1b

#> fig-checkfit-betabinom
plot(cf_1b)


# Beta -----------------------------------------------------------------------

#> beta-data
prop_data <- read.csv("vignettes/example_proportion.csv") |>
  mutate(log.x = log(raw_x))

#> fit-beta -- not run here: fitting this takes about 80 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_2 <- bnec(resp ~ crf(log.x, model = c("ecxll3", "nec3param")),
#               data = prop_data, seed = 333)
#
# save(exp_2, file = "vignettes/fits/m5_exp_2.RData")

#> load-fit-beta
load("vignettes/fits/m5_exp_2.RData")

#> fig-beta
autoplot(exp_2, all_models = TRUE)

#> beta-stats
exp_2$mod_stats

#> check-fit-beta
cf_2 <- check_fit(exp_2)
cf_2[, c("model", "wi", "group", "mean_ratio", "ppp_mean",
         "sd_ratio", "ppp_sd", "control")]

#> fig-checkfit-beta
plot(cf_2)


#   Values on the boundary ---------------------------------------------------

#> subs-beta
bnec_record(exp_2)$substitutions


# Poisson --------------------------------------------------------------------

#> count-data
set.seed(333)
data(nec_data)
count_data <- nec_data |>
  mutate(
    y = (y * 100 + rnorm(nrow(nec_data), 0, 15)) |>
      round() |> as.integer() |> abs()
  )
str(count_data)

#> fit-pois -- not run here: fitting this takes about 73 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_3 <- bnec(y ~ crf(x, model = c("ecxll3", "nec3param")), data = count_data)
#
# save(exp_3, file = "vignettes/fits/m5_exp_3.RData")

#> load-fit-pois
load("vignettes/fits/m5_exp_3.RData")

#> fig-pois
autoplot(exp_3, all_models = TRUE)

#> dispersion-pois
summary(exp_3)$mod_weights

#> fig-checkfit-pois
plot(check_fit(exp_3))


#   Counts observed over an exposure -----------------------------------------

#> rate-demo -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# y | rate(n_females) ~ crf(x, model = "nec4param")


# Negative binomial ----------------------------------------------------------

#> fit-negbin -- not run here: fitting this takes about 75 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_3b <- bnec(y ~ crf(x, model = c("ecxll3", "nec3param")),
#                data = count_data, family = "negbinomial")
#
# save(exp_3b, file = "vignettes/fits/m5_exp_3b.RData")

#> load-fit-negbin
load("vignettes/fits/m5_exp_3b.RData")

#> fig-negbin
autoplot(exp_3b, all_models = TRUE)

#> fig-checkfit-negbin
plot(check_fit(exp_3b))


# Gamma ----------------------------------------------------------------------

#> gamma-data
data(nec_data)
measure_data <- nec_data |>
  mutate(measure = exp(y))

#> fit-gamma -- not run here: fitting this takes about 75 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_4 <- bnec(measure ~ crf(x, model = c("ecxll3", "nec3param")),
#               data = measure_data)
#
# save(exp_4, file = "vignettes/fits/m5_exp_4.RData")

#> load-fit-gamma
load("vignettes/fits/m5_exp_4.RData")

#> fig-gamma
autoplot(exp_4, all_models = TRUE)

#> fig-checkfit-gamma
cf_4 <- check_fit(exp_4)
plot(cf_4)

#> gamma-cv
cf_4b <- subset(as.data.frame(cf_4), model == "nec3param")
data.frame(group = cf_4b$group,
           observed_cv = round(cf_4b$obs_sd / cf_4b$obs_mean, 3),
           simulated_cv = round(cf_4b$sim_sd / cf_4b$sim_mean, 3),
           sd_ratio = round(cf_4b$sd_ratio, 2))


# Gaussian -------------------------------------------------------------------

#> gauss-data
gaussian_data <- prop_data |>
  mutate(y = car::logit(resp))

#> fit-gauss -- not run here: fitting this takes about 83 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_5 <- bnec(y ~ crf(log.x, model = c("ecxll4", "nec4param")),
#               data = gaussian_data, seed = 333)
#
# save(exp_5, file = "vignettes/fits/m5_exp_5.RData")

#> load-fit-gauss
load("vignettes/fits/m5_exp_5.RData")

#> fig-gauss
autoplot(exp_5, all_models = TRUE)

#> check-fit-gauss
cf_5 <- check_fit(exp_5)
cf_5[, c("model", "wi", "group", "sd_ratio", "ppp_sd", "control")]

#> fig-checkfit-gauss
plot(cf_5)


#   Growth rates -------------------------------------------------------------


# Model suitability by response type -----------------------------------------

#> excluded
bnec_record(exp_2)$excluded


# Censored values ------------------------------------------------------------

#> cens-demo -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# y | cens(censoring) ~ crf(x, model = "nec4param")


# Zeros ----------------------------------------------------------------------


# Hurdle and zero-inflated models --------------------------------------------

#> hurdle-fams
names(bayesnec:::mod_fams)


#   A hurdle gamma in practice -----------------------------------------------

#> nass-data
data(nassarius)
snail <- subset(nassarius, contaminant == "A")
str(snail)

#> nass-mortality
tapply(snail$alive, snail$dose, function(z) sprintf("%d of %d", sum(z), length(z)))

#> nass-prep
pos_min <- min(snail$growth[snail$growth > 0])
snail$growth <- ifelse(snail$alive == 1 & snail$growth <= 0, pos_min / 2,
                       snail$growth)

offset <- min(snail$dose[snail$dose > 0]) / 10
snail$log_dose <- log(snail$dose + offset)
back <- function(z) exp(z) - offset

#> fit-hurdle -- not run here: fitting this takes about 4 min.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_6 <- bnec_hurdle(growth ~ crf(log_dose, model = c("nec3param", "ecxll3")),
#                      data = snail, seed = 333,
#                      control = list(adapt_delta = 0.99))
#
# save(exp_6, file = "vignettes/fits/m5_exp_6.RData")

#> load-fit-hurdle
load("vignettes/fits/m5_exp_6.RData")

#> nass-summary
summary(exp_6, xform = back)

#> fig-nass
autoplot(exp_6, which = "all")


# Preparing the response -----------------------------------------------------


#   The reason a divisor gets reached for ------------------------------------


# Modelling dispersion -------------------------------------------------------

#> disp-demo -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# y ~ crf(x, model = "nec4param") + disp(~x)         # varies along the predictor
# y ~ crf(x, model = "nec4param") + disp("power")    # varies with the fitted mean


#   A worked case ------------------------------------------------------------

#> fig-disp-cv
conc_breaks <- c(0.01, 0.1, 1, 10, 100)

cv_by_conc <- prop_data |>
  group_by(raw_x) |>
  summarise(cv = sd(resp) / mean(resp), .groups = "drop")

ggplot(cv_by_conc, aes(raw_x, cv)) +
  geom_line(colour = "grey60") +
  geom_point(size = 2.5, colour = "#1b6ca8") +
  scale_x_log10(breaks = conc_breaks, labels = conc_breaks) +
  labs(x = "concentration", y = "coefficient of variation") +
  theme_classic()

#> fit-disp -- not run here: fitting this takes about 84 s.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exp_2_const <- bnec(resp ~ crf(log.x, model = "nec3param"),
#                     data = prop_data, seed = 333)
#
# exp_2_disp <- bnec(resp ~ crf(log.x, model = "nec3param") + disp("power"),
#                    data = prop_data, seed = 333)
#
# save(exp_2_const, file = "vignettes/fits/m5_exp_2_const.RData")
# save(exp_2_disp, file = "vignettes/fits/m5_exp_2_disp.RData")

#> load-fit-disp
load("vignettes/fits/m5_exp_2_const.RData")
load("vignettes/fits/m5_exp_2_disp.RData")

#> fig-disp-fit-const
autoplot(exp_2_const)

#> fig-disp-fit-power
autoplot(exp_2_disp)

#> fig-disp-predict
disp_grid <- data.frame(log.x = seq(min(prop_data$log.x), max(prop_data$log.x),
                                    length.out = 100))

pp_band <- function(fit, label) {
  p <- predict(pull_brmsfit(fit), newdata = disp_grid)
  data.frame(raw_x = exp(disp_grid$log.x), fit = label,
             Estimate = p[, "Estimate"], Q2.5 = p[, "Q2.5"], Q97.5 = p[, "Q97.5"])
}

bands <- rbind(pp_band(exp_2_const, "constant dispersion"),
               pp_band(exp_2_disp, "disp(\"power\")"))

disp_cols <- c("constant dispersion" = "#1b6ca8", "disp(\"power\")" = "#c1440e")

ggplot(bands, aes(raw_x)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5, fill = fit), alpha = 0.35) +
  geom_line(aes(y = Estimate, colour = fit), linewidth = 0.7) +
  geom_point(data = prop_data, aes(y = resp), size = 1.2, alpha = 0.6) +
  scale_x_log10(breaks = conc_breaks, labels = conc_breaks) +
  scale_fill_manual(values = disp_cols) +
  scale_colour_manual(values = disp_cols) +
  labs(x = "concentration", y = "response", fill = NULL, colour = NULL) +
  theme_classic() +
  theme(legend.position = "top")

#> fig-disp-checkfit
plot(check_fit(exp_2_const))

#> fig-disp-checkfit-power
plot(check_fit(exp_2_disp))

