##############################################################################
# Module 6 -- Priors and Bayesian inference
#
# Generated from vignettes/6Priors_and_Bayesian_inference.qmd
# by scripts/generate_live_scripts.R on 2026-09-19.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/6Priors_and_Bayesian_inference.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (basename(getwd()) != "vignettes") {
  if (dir.exists("vignettes")) {
    setwd("vignettes")
  } else {
    stop("Open the cr_modelling_training project first: every path below is ",
         "relative to its vignettes/ folder.")
  }
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("fetch_fits.R")
if (!length(list.files("fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run source(\"fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
library(brms)
library(ggplot2)
library(dplyr)
library(tidyr)
options(brms.backend = "cmdstanr")
options(mc.cores = 4)
set.seed(333)
data(nec_data)

# The prior figures below draw the densities `get_priors()` returns, rather than
# idealised curves, so that what is plotted is what a fit would actually use.
# sample_priors() returns a named list of draws with a `b_` prefix per parameter.
prior_draws <- function(priors, set) {
  sample_priors(priors, n_samples = 4000, plot = NA) |>
    data.frame() |>
    tidyr::pivot_longer(dplyr::everything(),
                        names_to = "parameter", values_to = "value") |>
    dplyr::mutate(parameter = sub("^b_", "", parameter), set = set)
}

prior_cols <- c("uninformative" = "#1b6ca8", "regularizing" = "#c1440e")


# Background -----------------------------------------------------------------


# Estimating uncertainty -----------------------------------------------------


# The posterior sample -------------------------------------------------------


# Sampling -------------------------------------------------------------------


# Priors ---------------------------------------------------------------------


# Priors in `bayesnec` -------------------------------------------------------


#   The available prior sets -------------------------------------------------

#> prior-types
formals(bnec)$prior_type

#> fig-prior-sets -- draws a figure on the page; the page shows the figure and not this code.
f_gauss <- bayesnecformula(y ~ crf(x, model = "nec4param"))
p_unin <- get_priors(f_gauss, data = nec_data, family = gaussian())
p_regl <- get_priors(f_gauss, data = nec_data, family = gaussian(),
                     prior_type = "regularizing")

sets <- bind_rows(prior_draws(p_unin, "uninformative"),
                  prior_draws(p_regl, "regularizing")) |>
  filter(parameter %in% c("top", "bot", "nec")) |>
  mutate(parameter = factor(parameter, c("top", "bot", "nec")))

observed <- data.frame(
  parameter = factor(c("top", "bot", "nec"), c("top", "bot", "nec")),
  lo = c(min(nec_data$y), min(nec_data$y), min(nec_data$x)),
  hi = c(max(nec_data$y), max(nec_data$y), max(nec_data$x)))

ggplot(sets, aes(value, colour = set, fill = set)) +
  geom_rect(data = observed, aes(xmin = lo, xmax = hi, ymin = -Inf, ymax = Inf),
            inherit.aes = FALSE, fill = "grey90", colour = NA) +
  geom_density(alpha = 0.25, linewidth = 0.6) +
  facet_wrap(~parameter, scales = "free", nrow = 1) +
  scale_colour_manual(values = prior_cols) +
  scale_fill_manual(values = prior_cols) +
  labs(x = NULL, y = "prior density", colour = NULL, fill = NULL) +
  theme_classic() +
  theme(legend.position = "top")


#   Response-scaled parameters -----------------------------------------------

#> fig-family-priors -- draws a figure on the page; the page shows the figure and not this code.
count_data <- nec_data |>
  mutate(y = abs(round(y * 100 + rnorm(nrow(nec_data), 0, 15))) |> as.integer())
binom_data <- read.csv("example_binomial.csv")

f_binom <- bayesnecformula(suc | trials(tot) ~ crf(raw_x, model = "nec4param"))

by_family <- bind_rows(
  prior_draws(get_priors(f_gauss, data = nec_data,   family = gaussian()), "gaussian"),
  prior_draws(get_priors(f_gauss, data = count_data, family = poisson()),  "poisson"),
  prior_draws(get_priors(f_binom, data = binom_data, family = binomial()), "binomial")) |>
  filter(parameter %in% c("top", "bot")) |>
  mutate(family = factor(set, c("gaussian", "poisson", "binomial")),
         parameter = factor(parameter, c("top", "bot")))

ggplot(by_family, aes(value, colour = parameter, fill = parameter)) +
  geom_density(alpha = 0.3, linewidth = 0.6) +
  facet_wrap(~family, scales = "free", nrow = 1) +
  scale_colour_manual(values = c(top = "#1b6ca8", bot = "#c1440e")) +
  scale_fill_manual(values = c(top = "#1b6ca8", bot = "#c1440e")) +
  labs(x = NULL, y = "prior density", colour = NULL, fill = NULL) +
  theme_classic() +
  theme(legend.position = "top")


#   Predictor-scaled parameters ----------------------------------------------

#> fig-nec-prior -- draws a figure on the page; the page shows the figure and not this code.
nec_prior <- get_priors(f_binom, data = binom_data, family = binomial())
pars <- as.numeric(strsplit(
  gsub("lognormal\\(|\\)", "", nec_prior$prior[nec_prior$nlpar == "nec"]),
  ", ")[[1]])
concs <- sort(unique(binom_data$raw_x))

# The axis is logarithmic, so the density is taken with respect to log(x);
# plotting dlnorm() against a log axis would distort the shape into a decay.
grid <- data.frame(x = exp(seq(log(min(concs)) - 2, log(max(concs)) + 4,
                               length.out = 600)))
grid$d <- dnorm(log(grid$x), pars[1], pars[2])

ggplot(grid, aes(x, d)) +
  geom_area(data = subset(grid, x >= min(concs) & x <= max(concs)),
            fill = "#1b6ca8", alpha = 0.25) +
  geom_line(colour = "#1b6ca8", linewidth = 0.7) +
  geom_vline(xintercept = range(concs), linetype = 2, colour = "grey40") +
  geom_rug(data = data.frame(x = concs), aes(x = x), inherit.aes = FALSE,
           length = unit(0.09, "npc"), linewidth = 0.8, colour = "#c1440e") +
  scale_x_log10() +
  labs(x = "concentration", y = "prior density") +
  theme_classic()


#   Other parameters ---------------------------------------------------------


# Limits of the default priors -----------------------------------------------


# Priors before a fit --------------------------------------------------------

#> get-priors
data(nec_data)
get_priors(y ~ crf(x, model = "nec3param"), data = nec_data,
           family = Beta(link = "identity"))


# Inspecting the priors ------------------------------------------------------

#> fit-base -- fits the model here, in about 38 s, most of it compiling.
set.seed(333)
data(nec_data)
bnec_fit <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data)

# save(bnec_fit, file = "fits/m6_bnec_fit.RData")   # not run: it would overwrite the distributed fit

#> load-fit-base
#> This restores the distributed object, so what follows matches the page.
load("fits/m6_bnec_fit.RData")

#> fig-sample-priors
sample_priors(pull_brmsfit(bnec_fit)$prior)

#> fig-check-priors
check_priors(bnec_fit)


# Specifying priors ----------------------------------------------------------

#> fit-a -- fits the model here, in about 45 s, most of it compiling.
set.seed(333)
exmp_a <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data,
               family = Beta(link = "identity"),
               iter = 1e4, control = list(adapt_delta = 0.99))

# save(exmp_a, file = "fits/m6_exmp_a.RData")   # not run: it would overwrite the distributed fit

#> load-fit-a
#> This restores the distributed object, so what follows matches the page.
load("fits/m6_exmp_a.RData")

#> pull-prior-a
pull_prior(exmp_a)

#> fit-b -- not run here: fitting this takes about 2 min.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# my_prior <- c(prior_string("beta(5, 1)", nlpar = "top"),
#               prior_string("normal(1.3, 2.7)", nlpar = "nec"),
#               prior_string("gamma(0.5, 2)", nlpar = "beta"))
# exmp_b <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data,
#                family = Beta(link = "identity"), prior = my_prior,
#                iter = 1e4, control = list(adapt_delta = 0.99))
#
# save(exmp_b, file = "fits/m6_exmp_b.RData")

#> load-fit-b
load("fits/m6_exmp_b.RData")

#> show-params
show_params(model = "nec3param")


#   Comparison of the fits ---------------------------------------------------

#> fig-compare-priors
par(mfrow = c(1, 2))
hist(exmp_a$ne_posterior, main = "Default priors", xlab = "NEC")
hist(exmp_b$ne_posterior, main = "User priors", xlab = "NEC")


# Priors for a model set -----------------------------------------------------

#> fit-c -- not run here: fitting this takes about 5 min.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# my_priors <- list(
#   nec3param = c(prior_string("beta(5, 1)", nlpar = "top"),
#                 prior_string("normal(1.3, 2.7)", nlpar = "nec"),
#                 prior_string("gamma(0.5, 2)", nlpar = "beta")),
#   nec4param = c(prior_string("beta(5, 1)", nlpar = "top"),
#                 prior_string("normal(1.3, 2.7)", nlpar = "nec"),
#                 prior_string("gamma(0.5, 2)", nlpar = "beta"),
#                 prior_string("beta(1, 5)", nlpar = "bot")))
# exmp_c <- bnec(y ~ crf(x, model = c("nec3param", "nec4param")), data = nec_data,
#                family = Beta(link = "identity"), prior = my_priors,
#                iter = 1e4, control = list(adapt_delta = 0.99))
#
# save(exmp_c, file = "fits/m6_exmp_c.RData")

#> load-fit-c
load("fits/m6_exmp_c.RData")

#> pull-prior-c
pull_prior(exmp_c)


#   Priors for part of a set -------------------------------------------------

#> fit-d -- not run here: fitting this takes about 3 min.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# exmp_d <- bnec(y ~ crf(x, model = c("nec3param", "nec4param")), data = nec_data,
#                family = Beta(link = "identity"), prior = my_priors[1],
#                iter = 1e4, control = list(adapt_delta = 0.99))
#
# save(exmp_d, file = "fits/m6_exmp_d.RData")

#> load-fit-d
load("fits/m6_exmp_d.RData")


#   Priors when extending a set ----------------------------------------------

#> fit-e -- not run here: fitting this takes about 5 min.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# necsigm_priors <- c(prior_string("beta(5, 1)", nlpar = "top"),
#                     prior_string("gamma(2, 6.5)", nlpar = "beta"),
#                     prior_string("normal(1.3, 2.7)", nlpar = "nec"),
#                     prior_string("normal(0, 2)", nlpar = "d"))
# exmp_e <- amend(exmp_d, add = "necsigm", priors = necsigm_priors)
#
# save(exmp_e, file = "fits/m6_exmp_e.RData")

#> load-fit-e
load("fits/m6_exmp_e.RData")


# Fixing a parameter ---------------------------------------------------------

#> constant-prior -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# fixed_prior <- get_priors(y ~ crf(x, model = "nec3param"), data = avoid_data,
#                           family = Beta(link = "identity"))
# fixed_prior$prior[fixed_prior$nlpar == "top"] <- "constant(0.5)"
#
# bnec(y ~ crf(x, model = "nec3param"), data = avoid_data,
#      family = Beta(link = "identity"), prior = fixed_prior)


#   The consequences of fixing a parameter -----------------------------------

#> tight-prior -- not run here: it refers to fixed_prior, which this script does not create.
#> Remove the leading # to run it against your own objects.
# fixed_prior$prior[fixed_prior$nlpar == "top"] <- "beta(6, 6)"


# Checking how much the priors matter ----------------------------------------

#> sensitivity -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# set.seed(333)
# exmp_reg <- bnec(y ~ crf(x, model = "nec4param"), data = nec_data,
#                  family = Beta(link = "identity"),
#                  prior_type = "regularizing",
#                  iter = 1e4, control = list(adapt_delta = 0.99))

