##############################################################################
# Module 6 -- Priors and Bayesian inference
#
# Generated from vignettes/6Priors_and_Bayesian_inference.qmd
# by scripts/generate_live_scripts.R on 2026-09-22.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/6Priors_and_Bayesian_inference.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (!dir.exists("vignettes")) {
  stop("Open cr_modelling_training.Rproj first: every path below is ",
       "written from the project root, as vignettes/...")
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("vignettes/fetch_fits.R")
if (!length(list.files("vignettes/fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run ",
       "source(\"vignettes/fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
library(brms)
library(ggplot2)
options(brms.backend = "cmdstanr")
options(mc.cores = 4)
set.seed(333)
data(nec_data)


# Background -----------------------------------------------------------------


# Estimating uncertainty -----------------------------------------------------


# The posterior sample -------------------------------------------------------


# Sampling -------------------------------------------------------------------


# Priors ---------------------------------------------------------------------


# Priors in `bayesnec` -------------------------------------------------------

#> prior-types
formals(bnec)$prior_type


# Limits of the default priors -----------------------------------------------


# Inspecting the priors ------------------------------------------------------

#> get-priors
data(nec_data)
get_priors(y ~ crf(x, model = "nec3param"), data = nec_data,
           family = Beta(link = "identity"))

#> fit-base -- fits the model here, in about 38 s, most of it compiling.
set.seed(333)
data(nec_data)
bnec_fit <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data)

# save(bnec_fit, file = "vignettes/fits/m6_bnec_fit.RData")   # not run: it would overwrite the distributed fit

#> load-fit-base
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m6_bnec_fit.RData")

#> fig-sample-priors
sample_priors(pull_brmsfit(bnec_fit)$prior)

#> fig-check-priors
check_priors(bnec_fit)

#> sensitivity -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# set.seed(333)
# exmp_reg <- bnec(y ~ crf(x, model = "nec4param"), data = nec_data,
#                  family = Beta(link = "identity"),
#                  prior_type = "regularizing")


# Specifying priors ----------------------------------------------------------

#> fit-a -- fits the model here, in about 45 s, most of it compiling.
set.seed(333)
exmp_a <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data,
               family = Beta(link = "identity"),
               iter = 1e4, control = list(adapt_delta = 0.99))

# save(exmp_a, file = "vignettes/fits/m6_exmp_a.RData")   # not run: it would overwrite the distributed fit

#> load-fit-a
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m6_exmp_a.RData")

#> pull-prior-a
pull_prior(exmp_a)

#> fit-b -- not run here: fitting this takes about 2 min.
#> Remove the leading # to fit it yourself; the load() below restores the saved object.
# set.seed(333)
# my_prior <- c(prior_string("beta(5, 1)", nlpar = "top"),
#               prior_string("normal(1.3, 2.7)", nlpar = "nec"),
#               prior_string("gamma(0.5, 2)", nlpar = "beta"))
# exmp_b <- bnec(y ~ crf(x, model = "nec3param"), data = nec_data,
#                family = Beta(link = "identity"), prior = my_prior,
#                iter = 1e4, control = list(adapt_delta = 0.99))
#
# save(exmp_b, file = "vignettes/fits/m6_exmp_b.RData")

#> load-fit-b
load("vignettes/fits/m6_exmp_b.RData")

#> show-params
show_params(model = "nec3param")


#   Comparison of the fits ---------------------------------------------------

#> fig-compare-priors
par(mfrow = c(1, 2))
hist(exmp_a$ne_posterior, main = "Default priors", xlab = "NEC")
hist(exmp_b$ne_posterior, main = "User priors", xlab = "NEC")


# Fixing a parameter ---------------------------------------------------------

#> constant-prior -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# fixed_prior <- get_priors(y ~ crf(x, model = "nec3param"), data = avoid_data,
#                           family = Beta(link = "identity"))
# fixed_prior$prior[fixed_prior$nlpar == "top"] <- "constant(0.5)"
#
# bnec(y ~ crf(x, model = "nec3param"), data = avoid_data,
#      family = Beta(link = "identity"), prior = fixed_prior)


#   The consequences of fixing a parameter -----------------------------------

#> tight-prior -- not run here: it refers to fixed_prior, which this script does not create.
#> Remove the leading # to run it against your own objects.
# fixed_prior$prior[fixed_prior$nlpar == "top"] <- "beta(6, 6)"


# Using posterior distributions ----------------------------------------------

#> fit-ecxll3 -- fits the model here, in about 38 s, most of it compiling.
set.seed(333)
ecxll3_fit <- bnec(y ~ crf(x, model = "ecxll3"), data = nec_data)

# save(ecxll3_fit, file = "vignettes/fits/m6_ecxll3_fit.RData")   # not run: it would overwrite the distributed fit

#> load-ecxll3
#> This restores the distributed object, so what follows matches the page.
load("vignettes/fits/m6_ecxll3_fit.RData")

#> compare
post_comp <- compare_posterior(
  list("nec3param" = bnec_fit, "ecxll3" = ecxll3_fit),
  comparison = "ecx", ecx_val = 10)

names(post_comp)

#> fig-compare-post
ggplot(post_comp$posterior_data, aes(x = value)) +
  geom_density(aes(group = model, colour = model, fill = model), alpha = 0.3) +
  labs(x = "Concentration", y = "Density") +
  theme_classic()

#> compare-quantiles
sapply(post_comp$posterior_list, quantile, c(0.025, 0.5, 0.975))

#> prob-diff
post_comp$prob_diff

quantile(post_comp$diff_list[["nec3param-ecxll3"]], c(0.025, 0.5, 0.975))


#   Comparing whole curves ---------------------------------------------------

#> compare-fitted
post_fitted <- compare_posterior(
  list("nec3param" = bnec_fit, "ecxll3" = ecxll3_fit),
  comparison = "fitted")

#> fig-fitted-curves
ggplot(post_fitted$posterior_data, aes(x = x)) +
  geom_point(data = nec_data, aes(x = x, y = y), colour = "grey60", size = 1) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), fill = "steelblue", alpha = 0.3) +
  geom_line(aes(y = Estimate), colour = "steelblue") +
  facet_wrap(~ model) +
  labs(x = "Concentration", y = "Response") +
  theme_classic()

#> diff-data
head(post_fitted$diff_data)

#> fig-compare-fitted
ggplot(post_fitted$diff_data) +
  geom_hline(yintercept = 0, linetype = 2, colour = "grey50") +
  geom_ribbon(aes(x = x, ymin = diff.Q2.5, ymax = diff.Q97.5),
              fill = "steelblue", alpha = 0.3) +
  geom_line(aes(x = x, y = diff.Estimate), colour = "steelblue") +
  labs(x = "Concentration", y = "Difference in fitted response") +
  theme_classic()

