##############################################################################
# Module 7 -- A worked case study
#
# Generated from vignettes/7Example_case_study.qmd
# by scripts/generate_live_scripts.R on 2026-09-19.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/7Example_case_study.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# A block that is commented out is one the page shows and does not run. Those
# are the model fits and the calls that are there to be read rather than
# executed. Below each fit is the load() that restores the saved object.
##############################################################################

if (basename(getwd()) != "vignettes") {
  if (dir.exists("vignettes")) {
    setwd("vignettes")
  } else {
    stop("Open the cr_modelling_training project first: every path below is ",
         "relative to its vignettes/ folder.")
  }
}

# The saved model objects. Sampling is what takes the minutes, so the fits
# are made once and loaded here. If this stops the script, fetch them:
#   source("fetch_fits.R")
if (!length(list.files("fits", pattern = "\\.RData$"))) {
  stop("No fitted objects in vignettes/fits/. Run source(\"fetch_fits.R\") first.")
}

#> setup -- the libraries and options the rest of the module runs under.
options(width = 100)
library(bayesnec)
library(ggplot2)


# Background -----------------------------------------------------------------


#   The assumptions the diagnostics test -------------------------------------


# The data -------------------------------------------------------------------

#> data
data(herbicide)
str(herbicide)
table(herbicide$herbicide)

#> ametryn-data
ametryn <- herbicide[herbicide$herbicide == "ametryn", ]
head(ametryn)


# 1. Data preparation and family choice --------------------------------------

#> fig-ametryn-raw
conc_breaks <- c(0.3, 1, 3, 10, 30, 100, 300)
ggplot(ametryn, aes(x = concentration, y = fvfm)) +
  geom_point(size = 2, alpha = 0.6) +
  scale_x_continuous(transform = "log", breaks = conc_breaks) +
  labs(x = expression(paste("Concentration (", mu, "g ", L^-1, ")")),
       y = "Maximum effective quantum yield") +
  theme_classic()


#   The scale of the response ------------------------------------------------

#> boundaries
range(ametryn$fvfm)

#> zeros-by-conc
tapply(ametryn$fvfm, ametryn$concentration, function(z) sum(z == 0))

#> family
fam <- Beta(link = "identity")


#   The scale of the predictor -----------------------------------------------

#> spacing
spacing_cv <- function(x) sd(diff(sort(x))) / mean(diff(sort(x)))
conc <- unique(ametryn$concentration)
round(c(linear = spacing_cv(conc), log = spacing_cv(log(conc))), 2)

#> scale-fit -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# set.seed(333)
# m7_scale_log <- bnec(fvfm ~ crf(log(concentration),
#                                 model = c("nec4param", "ecx4param", "ecxll4")),
#                      data = ametryn, seed = 333)
# save(m7_scale_log, file = "fits/m7_scale_log.RData")
#
# set.seed(333)
# m7_scale_raw <- bnec(fvfm ~ crf(concentration, model = "nec4param"),
#                      data = ametryn, seed = 333)
# save(m7_scale_raw, file = "fits/m7_scale_raw.RData")

#> scale-load
load("fits/m7_scale_log.RData")
load("fits/m7_scale_raw.RData")

#> scale-compare
elpd <- function(fit) {
  brms::loo(pull_brmsfit(fit))$estimates["elpd_loo", "Estimate"]
}

# The largest gap between the fitted mean and the observed mean at a tested
# concentration, which is the departure a plot of the curve would show.
max_departure <- function(fit) {
  by_conc <- aggregate(
    cbind(observed, fitted) ~ concentration,
    data.frame(concentration = ametryn$concentration,
               observed = ametryn$fvfm,
               fitted = fitted(pull_brmsfit(fit))[, "Estimate"]),
    mean)
  max(abs(by_conc$observed - by_conc$fitted))
}

scale_fits <- list(nec4param_raw = m7_scale_raw,
                   nec4param_log = pull_out(m7_scale_log, "nec4param"),
                   ecx4param_log = pull_out(m7_scale_log, "ecx4param"),
                   ecxll4_log    = pull_out(m7_scale_log, "ecxll4"))

data.frame(elpd_loo = round(sapply(scale_fits, elpd), 1),
           max_departure = round(sapply(scale_fits, max_departure), 3))


# 2. Fitting the candidate set -----------------------------------------------

#> fit-am-reduced -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# m7_am_reduced <- bnec(fvfm ~ crf(log(concentration), model = "decline"),
#                       data = ametryn, family = fam,
#                       iter = 4000, chains = 2, seed = 17)
#
# save(m7_am_reduced, file = "fits/m7_am_reduced.RData")

#> load-am-reduced
load("fits/m7_am_reduced.RData")


#   The set as fitted --------------------------------------------------------

#> record
rec <- bnec_record(m7_am_reduced)
rec$excluded
rec$attempted

#> failed-reduced
names(failed_models(m7_am_reduced))

#> substitutions
rec$substitutions


#   Model weights ------------------------------------------------------------

#> summary-reduced
summary(m7_am_reduced)


# 3. Sampler diagnostics and screening ---------------------------------------

#> sampling-reduced
check_sampling(m7_am_reduced)


#   Kinds of failure ---------------------------------------------------------

#> failure-kinds
cs <- check_sampling(m7_am_reduced)
cs[cs$failed, c("model", "max_rhat", "min_ess", "n_divergent")]

#> parameters
fitted_mods <- c(cs$model, names(failed_models(m7_am_reduced)))
n_par <- vapply(fitted_mods,
                function(m) length(names(show_params(m)[[1]]$pforms)),
                integer(1))
data.frame(model = fitted_mods, parameters = n_par,
           produced_draws = fitted_mods %in% cs$model,
           row.names = NULL)


#   Screening the model set --------------------------------------------------

#> screen-reduced
screened_reduced <- screen_models(m7_am_reduced)


#   Raising the settings -----------------------------------------------------

#> fit-am-default -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# m7_am_fit <- bnec(fvfm ~ crf(log(concentration), model = "decline"),
#                   data = ametryn, family = fam, seed = 17)
#
# save(m7_am_fit, file = "fits/m7_am_fit.RData")

#> load-am-default
load("fits/m7_am_fit.RData")

#> sampling-default
check_sampling(m7_am_fit)

#> failed-default
names(failed_models(m7_am_fit))

#> screen-default
fit_screened <- screen_models(m7_am_fit)


# 4. Fit diagnostics ---------------------------------------------------------

#> best-model
best_fit <- pull_best(fit_screened)

#> fig-ppcheck
pp_check(best_fit, type = "dens_overlay_grouped", group = "concentration")

#> checkfit-control
cf <- check_fit(fit_screened)
cf[cf$control, ]

#> checkfit-one
cf_best <- check_fit(best_fit)
cf_best

#> beta-variance
phi <- summary(pull_brmsfit(best_fit))$spec_pars["phi", "Estimate"]
data.frame(group = cf_best$group,
           sim_mean = round(cf_best$sim_mean, 3),
           obs_sd = round(cf_best$obs_sd, 4),
           sim_sd = round(cf_best$sim_sd, 4),
           beta_implied = round(sqrt(cf_best$sim_mean * (1 - cf_best$sim_mean) /
                                       (1 + phi)), 4))

#> top-conc-response
top <- ametryn[ametryn$concentration == max(ametryn$concentration), ]
c(zero = sum(top$fvfm == 0), above_zero = sum(top$fvfm > 0))
sort(round(top$fvfm, 3))

#> fig-checkfit
plot(cf_best)


#   Repairing the dispersion -------------------------------------------------

#> fit-am-disp -- the fit. Shown on the page and not run: it samples for minutes.
#> Remove the leading # from the lines below to run it yourself.
# m7_am_disp <- bnec(fvfm ~ crf(log(concentration), model = "ecxll4") +
#                      disp(~ log(concentration)),
#                    data = ametryn, family = fam, seed = 17)
#
# save(m7_am_disp, file = "fits/m7_am_disp.RData")

#> load-am-disp
load("fits/m7_am_disp.RData")

#> checkfit-disp
cf_disp <- check_fit(m7_am_disp)
cf_disp

#> fig-disp-compare
grid <- data.frame(
  concentration = exp(seq(log(min(ametryn$concentration)),
                          log(max(ametryn$concentration)), length.out = 100)))
# The formula term is log(concentration), which brms holds as its own column, so
# newdata has to supply it rather than leaving it to be derived.
grid[["log(concentration)"]] <- log(grid$concentration)

pp_band <- function(fit, label) {
  p <- predict(pull_brmsfit(fit), newdata = grid)
  data.frame(concentration = grid$concentration, fit = label,
             Estimate = p[, "Estimate"], Q2.5 = p[, "Q2.5"], Q97.5 = p[, "Q97.5"])
}

bands <- rbind(pp_band(best_fit, "constant dispersion"),
               pp_band(m7_am_disp, "disp(~ log(concentration))"))

ggplot(bands, aes(x = concentration)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), fill = "grey80") +
  geom_line(aes(y = Estimate)) +
  geom_point(data = ametryn, aes(y = fvfm), size = 1.2, alpha = 0.6) +
  facet_wrap(~ fit) +
  scale_x_continuous(transform = "log", breaks = conc_breaks) +
  labs(x = expression(paste("Concentration (", mu, "g ", L^-1, ")")),
       y = "Maximum effective quantum yield") +
  theme_classic()

#> nsec-comparison
rbind(`constant dispersion` = nsec(best_fit, xform = exp),
      `disp(~ log(concentration))` = nsec(m7_am_disp, xform = exp))


# 5. The reported estimates --------------------------------------------------

#> summary-screened
summary(fit_screened)


#   The scale an estimate is on ----------------------------------------------

#> report-scale
rbind(log_scale = nec(fit_screened),
      measured  = nec(fit_screened, xform = exp))


#   The parameters of the curve ----------------------------------------------

#> tbl-curveparams
curve_params(fit_screened, xform = exp)


#   Effect concentrations and censoring --------------------------------------

#> report-ecx
ecx(fit_screened, ecx_val = 10, xform = exp)
ecx(fit_screened, ecx_val = 50, xform = exp)


#   The estimate in a guideline derivation -----------------------------------

