##############################################################################
# Module 8 -- Factor covariates and groupings
#
# Generated from vignettes/8Factor_covariates_and_groupings.qmd
# by scripts/generate_live_scripts.R on 2026-09-21.
#
# Do not edit this file. Edit the module and run the generator again, or the
# script and the page will disagree.
#
# The page: https://open-aims.github.io/cr_modelling_training/vignettes/8Factor_covariates_and_groupings.html
#
# Lines beginning `#>` name the chunk each block came from, so a block here
# can be matched to the place on the page it is discussed.
#
# Every block runs unless the line above it says otherwise. A fit is
# commented out where it would take more than 50 seconds, and so is a
# block that refers to objects this script does not create; the line above
# each one says which, and gives the estimate for a fit.
#
# Where a fit does run, its save() is commented out so that the fits you
# downloaded are not overwritten, and the load() after it restores the
# distributed copy so the output below matches the page.
##############################################################################

if (!dir.exists("vignettes")) {
  stop("Open cr_modelling_training.Rproj first: every path below is ",
       "written from the project root, as vignettes/...")
}

#> setup -- the libraries and options the rest of the module runs under.
library(bayesnec)
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)
options(brms.backend = "cmdstanr")


# Background -----------------------------------------------------------------


# Pseudo-replication and hierarchical effects --------------------------------


#   Within-concentration groupings -------------------------------------------


#   Across-concentration groupings -------------------------------------------


# An introduction to mixed modelling -----------------------------------------


# Random effects for non-linear models ---------------------------------------


# Group-level terms in `bayesnec` --------------------------------------------

#> term-syntax -- the shape of the term. The names in it are stand-ins.
#> Remove the leading # to run it against your own objects.
# y ~ crf(x, model = "nec4param") + ogl(tank)        # the whole curve is displaced
# y ~ crf(x, model = "nec4param") + (top | tank)     # one named parameter varies
# y ~ crf(x, model = "nec4param") + pgl(plate)       # every parameter varies


#   Deviations that cannot leave the support ---------------------------------


#   Priors on the group-level terms ------------------------------------------


# Deviation on the intercept -------------------------------------------------

#> ogl-data
colour <- read.csv("vignettes/example_ogl.csv") |>
  mutate(y = Perc_change / 100,
         groupvar = factor(paste(Replicate, Treatment, sep = "_")),
         x = as.numeric(Treatment)) |>
  na.omit()
c(rows = nrow(colour), concentrations = n_distinct(colour$x),
  containers = n_distinct(colour$groupvar))

#> fig-ogl-raw
ggplot(colour, aes(x, y, colour = groupvar)) +
  geom_jitter(show.legend = FALSE) +
  labs(x = "Concentration", y = "Proportional change in colour index") +
  theme_classic()

#> ogl-fit -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# fit_plain <- bnec(y ~ crf(x, model = "ecxlin"), data = colour, seed = 70)
# fit_ogl   <- bnec(y ~ crf(x, model = "ecxlin") + ogl(groupvar),
#                   data = colour, seed = 70)

#> tbl-ogl-compare
read.csv("vignettes/data/grouping_ogl_compare.csv") |> kable()

#> fig-ogl-curves
ogl_curves <- read.csv("vignettes/data/grouping_ogl_curves.csv") |>
  mutate(fit = factor(fit, levels = c("no group term", "ogl(groupvar)")))

# ggbnec_data() returns three things in one frame and each layer takes the rows
# it needs. `y_ci` traces the credible band as a closed polygon, so it has twice
# as many rows as the curve does and `y_e` is NA on the return half; `x_r` and
# `y_r` hold the observations, on rows where the curve columns are NA. Passing
# the whole frame to every layer draws the right picture and fills the render
# with warnings about removed rows.
ogl_band <- filter(ogl_curves, !is.na(x_e))
ogl_line <- filter(ogl_curves, !is.na(y_e))
ogl_obs <- filter(ogl_curves, !is.na(x_r))

# The container means are drawn on both panels, so that the two panels differ in
# the fit and in nothing else. They are computed from the grouped fit, which is
# the one whose plot data carry the container each observation came from.
ogl_means <- ogl_obs |>
  filter(!is.na(group)) |>
  group_by(group) |>
  summarise(x_r = first(x_r), y_r = mean(y_r), .groups = "drop")

ggplot(ogl_band, aes(x = x_e)) +
  geom_polygon(aes(y = y_ci), fill = "grey80", colour = NA, alpha = 0.6) +
  geom_point(data = ogl_obs, aes(x = x_r, y = y_r), alpha = 0.3, size = 1) +
  geom_point(data = ogl_means, aes(x = x_r, y = y_r), shape = 23,
             fill = "white", size = 2.2) +
  geom_line(data = ogl_line, aes(y = y_e), colour = "#2c6a5a",
            linewidth = 0.8) +
  facet_wrap(~fit) +
  labs(x = "Concentration", y = "Proportional change in colour index") +
  theme_classic()


# Deviation on every parameter -----------------------------------------------


#   The assay ----------------------------------------------------------------

#> pgl-data
data(lum31)
cu15 <- droplevels(subset(lum31, toxicant == "Cu" & minutes == 15))
str(cu15)

#> fig-pgl-raw
ggplot(cu15, aes(x = conc, y = rlu_cens, group = plate)) +
  geom_point(alpha = 0.3, size = 1) +
  stat_summary(fun = mean, geom = "line", linewidth = 0.3) +
  scale_x_continuous(transform = "log10", labels = function(x) signif(x, 2)) +
  labs(x = "Dissolved copper (mg/L)", y = "Relative light units") +
  theme_classic()


#   Normalising to a control -------------------------------------------------

#> tbl-gain
cu15 |>
  group_by(plate) |>
  filter(conc == min(conc)) |>
  summarise(control_rlu = median(rlu_cens), .groups = "drop") |>
  summarise(plates = n(), lowest = min(control_rlu),
            highest = max(control_rlu),
            ratio = round(max(control_rlu) / min(control_rlu), 1)) |>
  kable()

#> tbl-halfctl
half_control <- cu15 |>
  mutate(rank = as.integer(sub(".*-c", "", as.character(conc_group)))) |>
  group_by(batch, plate, rank) |>
  summarise(conc = first(conc), m = mean(rlu_cens), .groups = "drop_last") |>
  mutate(rel = m / m[rank == 1]) |>
  summarise(half_ctl = {
    i <- which(rel < 0.5)[1]
    exp(log(conc[i - 1]) + (0.5 - rel[i - 1]) *
          (log(conc[i]) - log(conc[i - 1])) / (rel[i] - rel[i - 1]))
  }, .groups = "drop")

half_control |>
  group_by(batch) |>
  summarise(plates = n(), lowest = signif(min(half_ctl), 3),
            highest = signif(max(half_ctl), 3), .groups = "drop") |>
  kable()


#   Preparing the response ---------------------------------------------------

#> tbl-censoring
lum31 |>
  filter(toxicant == "Cu") |>
  group_by(minutes) |>
  summarise(readings = n(), left_censored = sum(censoring == "left"),
            per_cent = round(100 * mean(censoring == "left"), 1),
            .groups = "drop") |>
  kable()

#> tbl-cv
cu15 |>
  mutate(rank = as.integer(sub(".*-c", "", as.character(conc_group)))) |>
  group_by(rank, plate) |>
  summarise(conc = first(conc), mean_rlu = mean(rlu_cens),
            cv = sd(rlu_cens) / mean(rlu_cens), .groups = "drop_last") |>
  group_by(rank) |>
  summarise(median_conc = signif(median(conc), 3),
            mean_rlu = signif(mean(mean_rlu), 3),
            cv = round(median(cv), 3), .groups = "drop") |>
  kable()


#   The plate term compared --------------------------------------------------

#> plate-fits -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# plate_plain <- bnec(rlu_cens | cens(censoring) ~ crf(log(conc), "ecxll4") +
#                       disp("power"),
#                     data = cu15, family = Gamma(link = "identity"), seed = 70)
# plate_ogl   <- bnec(rlu_cens | cens(censoring) ~ crf(log(conc), "ecxll4") +
#                       ogl(plate) + disp("power"),
#                     data = cu15, family = Gamma(link = "identity"), seed = 70)
# plate_pgl   <- bnec(rlu_cens | cens(censoring) ~ crf(log(conc), "ecxll4") +
#                       pgl(plate) + disp("power"),
#                     data = cu15, family = Gamma(link = "identity"), seed = 70)
# plate_batch <- bnec(rlu_cens | cens(censoring) ~ crf(log(conc), "ecxll4") +
#                       ogl(plate) + (ec50 | batch) + disp("power"),
#                     data = cu15, family = Gamma(link = "identity"), seed = 70)

#> tbl-plate-compare
read.csv("vignettes/data/grouping_plate_compare.csv") |> kable()

#> fig-plate-curves
plate_levels <- c("no group term", "ogl(plate)", "pgl(plate)",
                  "ogl(plate) + (ec50 | batch)")
plate_curves <- read.csv("vignettes/data/grouping_plate_curves.csv") |>
  mutate(fit = factor(fit, levels = plate_levels))
plate_obs <- read.csv("vignettes/data/grouping_plate_obs.csv")
plate_nsec <- read.csv("vignettes/data/grouping_plate_estimates.csv") |>
  filter(estimate == "NSEC") |>
  mutate(fit = factor(fit, levels = plate_levels))

ggplot(plate_curves, aes(x = x)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), fill = "grey80", alpha = 0.6) +
  geom_point(data = plate_obs, aes(x = conc, y = rlu_cens), alpha = 0.25,
             size = 0.8) +
  geom_line(aes(y = Estimate), colour = "#2c6a5a", linewidth = 0.8) +
  geom_vline(data = plate_nsec, aes(xintercept = Q50), linetype = 2,
             colour = "grey40") +
  facet_wrap(~fit, ncol = 2) +
  scale_x_continuous(transform = "log10", labels = function(x) signif(x, 2)) +
  labs(x = "Dissolved copper (mg/L)", y = "Relative light units") +
  theme_classic()

#> tbl-plate-sd
read.csv("vignettes/data/grouping_plate_sd.csv") |> kable()

#> tbl-plate-estimates
read.csv("vignettes/data/grouping_plate_estimates.csv") |> kable()


#   The choice between the grouped forms -------------------------------------


# The number of levels a deviation needs -------------------------------------


# Factor covariates ----------------------------------------------------------


#   Fitting each level separately --------------------------------------------

#> tox-group-fit -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# zn_cu_15 <- droplevels(subset(lum31, minutes == 15))
#
# fits_tox <- bnec_group(
#   rlu_cens | cens(censoring) ~ crf(log(conc), "all") + ogl(plate) +
#     disp("power"),
#   data = zn_cu_15, group_var = "toxicant",
#   family = Gamma(link = "identity"),
#   chains = 4, iter = 5000, warmup = 4000, seed = 228,
#   control = list(adapt_delta = 0.99))

#> tbl-tox-weights
read.csv("vignettes/data/grouping_tox_weights.csv") |>
  pivot_wider(names_from = toxicant, values_from = wi) |>
  filter(if_any(-model, ~ .x >= 0.01)) |>
  kable()

#> fig-tox-curves
# The N(S)EC is taken from the estimates table rather than from the `nec_vals`
# column of the plot data, so that the line and the table are the same number.
# Both are posterior summaries of the same quantity, computed from different
# draws, and they differ in the third significant figure.
tox_nsec <- read.csv("vignettes/data/grouping_tox_estimates.csv") |>
  filter(estimate == "NSEC") |>
  rename(fit = toxicant)

tox_curves <- read.csv("vignettes/data/grouping_tox_curves.csv")

ggplot(filter(tox_curves, !is.na(x_e)), aes(x = x_e, colour = fit, fill = fit)) +
  geom_polygon(aes(y = y_ci), colour = NA, alpha = 0.3) +
  geom_point(data = filter(tox_curves, !is.na(x_r)), aes(x = x_r, y = y_r),
             alpha = 0.4, size = 1) +
  geom_line(data = filter(tox_curves, !is.na(y_e)), aes(y = y_e)) +
  geom_vline(data = tox_nsec, aes(xintercept = Q50), linetype = 2,
             colour = "grey40") +
  facet_wrap(~fit, ncol = 1, scales = "free") +
  scale_x_continuous(transform = "log10", labels = function(x) signif(x, 2)) +
  scale_colour_hue(guide = "none") +
  scale_fill_hue(guide = "none") +
  labs(x = "Dissolved metal (mg/L)", y = "Relative light units") +
  theme_classic()

#> tbl-tox-estimates
read.csv("vignettes/data/grouping_tox_estimates.csv") |> kable()

#> tox-compare -- not run here: it refers to fits_tox, which this script does not create.
#> Remove the leading # to run it against your own objects.
# cmp_tox <- compare_posterior(fits_tox, comparison = "nec")
# cmp_tox$prob_diff

#> fig-tox-posterior
read.csv("vignettes/data/grouping_tox_posterior.csv") |>
  ggplot(aes(x = value, group = model, colour = model, fill = model)) +
  geom_density(alpha = 0.3) +
  scale_x_continuous(transform = "log10", labels = function(x) signif(x, 2)) +
  labs(x = "Dissolved metal (mg/L)", y = "Density",
       colour = "Toxicant", fill = "Toxicant") +
  theme_classic()

#> tbl-tox-prob
read.csv("vignettes/data/grouping_tox_prob_diff.csv") |> kable()


#   An interaction on a single equation --------------------------------------

#> fi-data
zinc <- read.csv("vignettes/example_fi.csv") |>
  na.omit() |>
  mutate(y = (Pcon / max(Pcon) + 0.01) * 0.99,
         x = log(Mean.Zn),
         hardness = factor(round(Hardness))) |>
  select(x, y, hardness)

range(zinc$y)
table(zinc$hardness)

#> fig-fi-raw
ggplot(zinc, aes(x = x, y = y, colour = hardness)) +
  geom_jitter() +
  labs(x = "Log zinc concentration", y = "Response", colour = "Hardness") +
  theme_classic()

#> fi-fit-all -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# fit_all <- bnec(y ~ crf(x, model = "decline"), data = zinc, seed = 70)
# best <- pull_best(fit_all)

#> tbl-fi-weights
read.csv("vignettes/data/grouping_zinc_weights.csv") |>
  mutate(wi = round(wi, 3)) |>
  kable()

#> fi-extract -- not run here: it refers to best, which this script does not create.
#> Remove the leading # to run it against your own objects.
# best_brms <- pull_brmsfit(best)
# best_brms$formula
# priors <- brms::prior_summary(best_brms)

#> fi-brms
# The right-hand side of each parameter line is what changes: `~ 1` fits one
# value for every level, and `~ hardness` fits one per level.
bf_plain <- brms::bf(
  y ~ bot + (top - bot) * exp(-exp(exp(beta) * (x - ec50))),
  bot + ec50 + top + beta ~ 1, nl = TRUE)

bf_inter <- brms::bf(
  y ~ bot + (top - bot) * exp(-exp(exp(beta) * (x - ec50))),
  bot + ec50 + top + beta ~ hardness, nl = TRUE)

#> fi-priors
inter_priors <- c(
  # the intercept, as bayesnec set it
  prior(beta(5, 2), nlpar = "top",  coef = "Intercept"),
  prior(beta(2, 5), nlpar = "bot",  coef = "Intercept"),
  prior(normal(2.387, 24.803), nlpar = "ec50", coef = "Intercept"),
  prior(normal(0, 5), nlpar = "beta", coef = "Intercept"),
  # the differences between hardness levels
  prior(normal(0, 0.25), nlpar = "top"),   # a proportion
  prior(normal(0, 0.1),  nlpar = "bot"),   # a proportion, near zero
  prior(normal(0, 2),    nlpar = "ec50"),  # the log predictor scale
  prior(normal(0, 2),    nlpar = "beta"))  # a log slope

#> fi-brms-fit -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# fit_plain <- brms::brm(bf_plain, data = zinc, family = Beta(link = "identity"),
#                        prior = priors, iter = 5000, seed = 700,
#                        save_pars = brms::save_pars(all = TRUE))

#> fi-init -- not run here: it refers to fit_plain, which this script does not create.
#> Remove the leading # to run it against your own objects.
# fx <- brms::fixef(fit_plain)
# init_fun <- function() {
#   list(b_bot  = as.array(c(fx["bot_Intercept",  "Estimate"], 0, 0)),
#        b_ec50 = as.array(c(fx["ec50_Intercept", "Estimate"], 0, 0)),
#        b_top  = as.array(c(fx["top_Intercept",  "Estimate"], 0, 0)),
#        b_beta = as.array(c(fx["beta_Intercept", "Estimate"], 0, 0)))
# }

#> fi-brms-inter -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# fit_inter <- brms::brm(bf_inter, data = zinc, family = Beta(link = "identity"),
#                        prior = inter_priors, iter = 5000, seed = 700,
#                        init = init_fun, control = list(adapt_delta = 0.99),
#                        save_pars = brms::save_pars(all = TRUE))
#
# posterior::nchains(brms::as_draws_array(fit_inter))

#> fi-sampling -- draws a figure on the page; the page shows the figure and not this code.
cat(readLines("vignettes/data/grouping_zinc_inter_sampling.txt"), sep = "\n")

#> tbl-fi-interaction
read.csv("vignettes/data/grouping_zinc_model_weights.csv") |> kable()

#> fig-fi-curves
# read.csv() returns hardness as an integer, because the levels are numbers.
# The observations carry it as a factor, and ggplot cannot put a continuous and
# a discrete scale on one aesthetic, so it is made a factor here to match.
preds <- read.csv("vignettes/data/grouping_zinc_preds.csv") |>
  mutate(hardness = factor(hardness, levels = levels(zinc$hardness)))

ggplot(preds) +
  geom_ribbon(aes(x = x, ymin = Q2.5, ymax = Q97.5, fill = hardness),
              alpha = 0.3) +
  geom_line(aes(x = x, y = Estimate, colour = hardness)) +
  geom_jitter(data = zinc, aes(x = x, y = y, fill = hardness),
              pch = 21, size = 2, alpha = 0.6) +
  labs(x = "Log zinc concentration", y = "Response",
       colour = "Hardness", fill = "Hardness") +
  theme_classic()


#   The hardness levels fitted separately ------------------------------------

#> zinc-group-fit -- not run here: this samples, and is not among the fits that were timed.
#> Remove the leading # to fit it yourself, and expect to wait.
# zinc_group <- bnec_group(y ~ crf(x, model = "decline"), data = zinc,
#                          group_var = "hardness", seed = 70)

#> tbl-zinc-group-weights
read.csv("vignettes/data/grouping_zinc_group_weights.csv") |>
  mutate(hardness = paste0("H", hardness)) |>
  pivot_wider(names_from = hardness, values_from = wi) |>
  filter(if_any(-model, ~ .x >= 0.01)) |>
  kable()

#> tbl-zinc-group-estimates
read.csv("vignettes/data/grouping_zinc_group_estimates.csv") |> kable()

#> fig-zinc-group-curves
# The level names are numbers, so read.csv() returns them as integers and ggplot
# maps them to a continuous colour scale. As a factor they take the same
# discrete scale the interaction figure uses, and `geom_polygon()` gets one
# closed band per level rather than one polygon over all three.
zinc_group_curves <- read.csv("vignettes/data/grouping_zinc_group_curves.csv") |>
  mutate(fit = factor(fit, levels = levels(zinc$hardness)))

ggplot(filter(zinc_group_curves, !is.na(x_e)),
       aes(x = x_e, colour = fit, fill = fit, group = fit)) +
  geom_polygon(aes(y = y_ci), colour = NA, alpha = 0.3) +
  geom_line(data = filter(zinc_group_curves, !is.na(y_e)), aes(y = y_e)) +
  geom_point(data = filter(zinc_group_curves, !is.na(x_r)),
             aes(x = x_r, y = y_r), alpha = 0.6, size = 1.5) +
  labs(x = "Log zinc concentration", y = "Response",
       colour = "Hardness", fill = "Hardness") +
  theme_classic()


# Comparing levels -----------------------------------------------------------

#> compare-shown -- not run here: it refers to zinc_group, which this script does not create.
#> Remove the leading # to run it against your own objects.
# post_comp <- compare_posterior(zinc_group, comparison = "n(s)ec")
# post_fitted <- compare_posterior(zinc_group, comparison = "fitted")

#> fig-compare-nec
# compare_posterior() returns the level names as data frame column names, which
# R prefixes with "X" where they begin with a digit. Stripped here so the legend
# reads as the hardness values the experiment used.
read.csv("vignettes/data/grouping_zinc_ne_posterior.csv") |>
  mutate(model = sub("^X", "", model)) |>
  ggplot(aes(x = value, group = model, colour = model, fill = model)) +
  geom_density(alpha = 0.3) +
  labs(x = "Log zinc concentration", y = "Density",
       colour = "Hardness", fill = "Hardness") +
  theme_classic()

#> tbl-compare-prob
read.csv("vignettes/data/grouping_zinc_prob_diff.csv") |>
  separate(col = comparison, into = c("hardness", "against"), sep = "-") |>
  pivot_wider(names_from = against, values_from = prob) |>
  kable()

#> fig-compare-fitted
read.csv("vignettes/data/grouping_zinc_diff.csv") |>
  ggplot() +
  geom_hline(yintercept = 0, linetype = 2, colour = "grey50") +
  geom_ribbon(aes(x = x, ymin = diff.Q2.5, ymax = diff.Q97.5,
                  fill = comparison), alpha = 0.3) +
  geom_line(aes(x = x, y = diff.Estimate, colour = comparison)) +
  labs(x = "Log zinc concentration", y = "Posterior difference") +
  theme_classic()


# Provenance of these fits ---------------------------------------------------

#> provenance -- draws a figure on the page; the page shows the figure and not this code.
cat(readLines("vignettes/data/grouping_provenance.txt"), sep = "\n")

