{
  "hash": "3fd068f08a69bd63d8b943e96739d55d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Fitting the same models with `drc`\"\nsubtitle: \"A frequentist engine asked the same questions, and where its answers differ\"\nbibliography: bayesnec.bib\n---\n\n\n\n## Scope\n\nThis page is supplied for interest and is not taught.\n\n`drc` [@Ritz2015] fits concentration-response models by maximum likelihood. It\nis mature, widely used, and contains a great deal more than is shown here. What\nfollows asks it the questions the course asks of `bayesnec`, and sets out where\nthe two engines answer the same question and where they answer different ones.\n\nBetter sources exist for `drc` itself:\n\n- Christian Ritz's [dose-response site](https://bioassay.dk/)\n- the `drc` paper in *PLoS ONE* and its supplement of worked examples\n  [@Ritz2015]\n- community material at [rstats4ag.org](https://rstats4ag.org/dose-response-curves.html)\n\n## Fitting a curve\n\n`drm()` takes a formula, the data, and a mean function through `fct`. This is\nthe dataset from module 2, fitted with a four-parameter log-logistic curve.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(nec_data)\nmodel_LL4 <- drm(y ~ x, data = nec_data, fct = LL.4())\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(nec_data, aes(x, y)) +\n  geom_point(alpha = 0.5, size = 1) +\n  geom_line(data = curve_data(model_LL4, min(nec_data$x), max(nec_data$x)),\n            aes(x, fit), linewidth = 0.8, colour = \"steelblue\") +\n  scale_x_continuous(trans = \"log\", breaks = c(0.1, 0.3, 1, 3)) +\n  labs(x = \"Concentration\", y = \"Response\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![A four-parameter log-logistic curve fitted to `nec_data`.](drc-reference_files/figure-html/fig-ll4-1.png){#fig-ll4 width=672}\n:::\n:::\n\n\nThe curve declines from about 0.9 at the lowest concentrations to near zero at\nthe highest, with the steep part between roughly 1 and 3.\n\n## Reading the fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_LL4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel fitted: Log-logistic (ED50 as parameter) (4 parms)\n\nParameter estimates:\n\n                Estimate Std. Error  t-value p-value    \nb:(Intercept) 7.8488e+00 6.4920e-01  12.0898  <2e-16 ***\nc:(Intercept) 2.0154e-05 4.3897e-02   0.0005  0.9996    \nd:(Intercept) 8.9732e-01 6.0071e-03 149.3778  <2e-16 ***\ne:(Intercept) 1.9950e+00 3.5440e-02  56.2917  <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error:\n\n 0.04775948 (96 degrees of freedom)\n```\n\n\n:::\n:::\n\n\nA four-parameter `drc` model reports parameters named `b`, `c`, `d` and `e`:\n\n| | meaning | `bayesnec` equivalent |\n|---|---|---|\n| `b` | slope, sometimes the hill slope | `beta`, which the `bayesnec` equations use as `exp(beta)` |\n| `c` | lower asymptote | `bot` |\n| `d` | upper asymptote | `top` |\n| `e` | the concentration halfway between `d` and `c` | `ec50` |\n\nThe estimates above are a slope of 7.85, a lower asymptote indistinguishable\nfrom zero, an upper asymptote of 0.897, and `e` at 1.995. `e` is always the\nconcentration at which the response is halfway between `d` and `c`. Where `c`\nis zero, as here, it is also the concentration at which the response has fallen\nto half its control level.\n\nEach parameter comes with a test of whether it differs from zero. That test is\nseldom the question of interest. A lower asymptote indistinguishable from zero,\nas here, is a reason to consider a three-parameter model with the lower limit\nfixed at zero. It says nothing about toxicity.\n\nFor a continuous response fitted with a Gaussian error the residuals should be\napproximately normal, and that can be checked. For binomial or count data they\nare not expected to be normal, so a normality test does not apply:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(r = residuals(model_LL4)), aes(r)) +\n  geom_histogram(bins = 20, fill = \"grey80\", colour = \"white\") +\n  labs(x = \"Residual\", y = \"Count\") +\n  theme_classic()\nshapiro.test(residuals(model_LL4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(model_LL4)\nW = 0.98855, p-value = 0.5498\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](drc-reference_files/figure-html/fig-resid-1.png){#fig-resid width=672}\n:::\n:::\n\n\nThe residuals are roughly symmetric about zero and the Shapiro-Wilk test returns\na p-value of 0.55, so there is no evidence against normality for this fit.\n\n## Threshold models\n\n`drc` provides threshold mean functions as well as smooth ones: `NEC.2`, `NEC.3`\nand `NEC.4`. These estimate a breakpoint directly, in the same sense as the\n`nec` equations of `bayesnec`, so a *NEC* is available from either engine.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_NEC3 <- drm(y ~ x, data = nec_data, fct = NEC.3())\nsummary(model_NEC3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel fitted: NEC with lower limit at 0 (3 parms)\n\nParameter estimates:\n\n               Estimate Std. Error t-value   p-value    \nb:(Intercept) 1.5672051  0.0726125  21.583 < 2.2e-16 ***\nd:(Intercept) 0.8902215  0.0048855 182.217 < 2.2e-16 ***\ne:(Intercept) 1.5228700  0.0142273 107.039 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error:\n\n 0.04145488 (97 degrees of freedom)\n```\n\n\n:::\n:::\n\n\nThe threshold is the `e` parameter, estimated at 1.523, with `d` the response\nlevel at concentrations below it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model_NEC3)[\"e:(Intercept)\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   2.5 %   97.5 % \n1.494633 1.551107 \n```\n\n\n:::\n:::\n\n\nModule 2 fitted `nec3param` to these same data with `bayesnec` and reported a\n*NEC* of 1.54 with a 95% credible interval of 1.50 to 1.57. The `drc` threshold\nabove is 1.52 with a confidence interval of 1.49 to 1.55. The two engines are\nestimating the same quantity here and they agree to within about one per cent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(nec_data, aes(x, y)) +\n  geom_point(alpha = 0.5, size = 1) +\n  geom_line(data = curve_data(model_NEC3, min(nec_data$x), max(nec_data$x)),\n            aes(x, fit), linewidth = 0.8, colour = \"firebrick\") +\n  geom_vline(xintercept = coef(model_NEC3)[[\"e:(Intercept)\"]],\n             linetype = 2, colour = \"firebrick\") +\n  scale_x_continuous(trans = \"log\", breaks = c(0.1, 0.3, 1, 3)) +\n  labs(x = \"Concentration\", y = \"Response\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![`NEC.3` fitted to the same data. The dashed line is the estimated threshold.](drc-reference_files/figure-html/fig-nec3-1.png){#fig-nec3 width=672}\n:::\n:::\n\n\nThe fitted curve holds flat at 0.890 until the threshold and declines\nexponentially after it, which is the shape `nec3param` also fits.\n\n## Effect concentrations\n\n`ED()` returns effect concentrations, and two of its arguments determine what is\ncomputed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nED(model_LL4, c(10, 50))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEstimated effective doses\n\n       Estimate Std. Error\ne:1:10 1.507871   0.023089\ne:1:50 1.995000   0.035440\n```\n\n\n:::\n:::\n\n\n### The basis of the percentage\n\nFor `type = \"relative\"`, which is the default, the percentage is a fraction of\nthe fitted response range, measured from the upper asymptote `d` down to the\nlower asymptote `c`. This can be checked directly against the curve:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf <- coef(model_LL4)\nc_lo <- cf[[\"c:(Intercept)\"]]\nd_hi <- cf[[\"d:(Intercept)\"]]\n\nec10 <- ED(model_LL4, 10, display = FALSE)[1, 1]\nec50 <- ED(model_LL4, 50, display = FALSE)[1, 1]\n\nc(response_at_EC10 = predict(model_LL4, data.frame(x = ec10)),\n  d_minus_10pc_of_range = d_hi - 0.10 * (d_hi - c_lo),\n  response_at_EC50 = predict(model_LL4, data.frame(x = ec50)),\n  midpoint_of_range = c_lo + (d_hi - c_lo) / 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nresponse_at_EC10.Prediction       d_minus_10pc_of_range \n                  0.8075928                   0.8075928 \nresponse_at_EC50.Prediction           midpoint_of_range \n                  0.4486716                   0.4486716 \n```\n\n\n:::\n:::\n\n\nThe response at `ED10` is 0.8076, which is exactly `d` minus a tenth of the\nrange, and the response at `ED50` is 0.4487, exactly the midpoint. The\npercentage is therefore a percentage of `d − c`.\n\nBoth ends of that range are fitted parameters. `d` is the level the curve\napproaches as concentration falls, whether or not anything was measured there,\nand `c` is the level it approaches as concentration rises, which may lie beyond\nthe highest concentration tested. A design that does not reach either plateau\nestimates that end by extrapolation, and every ECx inherits it.\n\n`bayesnec` anchors differently. Its `ecx()` measures the decline from the\ncontrol, defined as the predicted mean at the lowest observed concentration,\nwhich is a point inside the data rather than a fitted limit.\n\n### The `reference` argument\n\nThe name suggests `reference` chooses the anchor. It does not. Its only effect\nis a direction convention for increasing curves:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincreasing <- transform(nec_data, y = 1 - y)\nmodel_up <- drm(y ~ x, data = increasing, fct = LL.4())\n\nrbind(\n  decreasing = c(control = ED(model_LL4, 10, reference = \"control\", display = FALSE)[1, 1],\n                 upper   = ED(model_LL4, 10, reference = \"upper\",   display = FALSE)[1, 1]),\n  increasing = c(control = ED(model_up,  10, reference = \"control\", display = FALSE)[1, 1],\n                 upper   = ED(model_up,  10, reference = \"upper\",   display = FALSE)[1, 1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            control    upper\ndecreasing 1.507871 1.507871\nincreasing 1.511092 2.494251\n```\n\n\n:::\n:::\n\n\nOn the decreasing curve both settings return 1.508. On the increasing curve they\nreturn 1.511 and 2.494. For an ordinary concentration-response curve, which\ndeclines, changing `reference` changes nothing.\n\n### Values of `type` in each package\n\n`bayesnec::ecx()` also takes a `type` argument and its values do not line up\nwith `drc`'s.\n\n| `drc` `type` | what it means | nearest `bayesnec` `type` |\n|---|---|---|\n| `\"relative\"` (default) | percentage of the fitted range `d − c` | `\"relative\"`, from the control to the `bot` parameter |\n| `\"absolute\"` | an absolute response value | `\"direct\"` |\n| — | percentage of the span from the control to the lowest predicted response | `\"range\"` |\n| — | percentage decline from the control to zero | `\"absolute\"` (default) |\n\n`drc`'s `\"absolute\"` asks for the concentration at which the response equals the\nnumber supplied, so `ED(model_LL4, 10, type = \"absolute\")` asks where the\nresponse equals 10. This response is bounded near 1, so no such concentration\nexists, and the call returns `NaN` with a warning:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nED(model_LL4, 10, type = \"absolute\", display = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in log(exp(-tempVal/parmVec[5]) - 1): NaNs produced\n```\n\n\n:::\n:::\n\n\nA missing value is the correct result. It is shown because the same word is the\ndefault in `bayesnec` and means a percentage there, so translating\n`ecx(fit, type = \"absolute\")` into `ED(m, 10, type = \"absolute\")` changes the\nquestion being asked.\n\n### Agreement between the engines\n\nWhere the fitted lower asymptote is zero and the curve is flat across the lowest\nconcentrations tested, the fitted range and the distance from the control to\nzero are the same interval, and the two engines estimate the same quantity.\n`nec_data` satisfies both conditions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nbnec_ecx4 <- bnec(y ~ crf(x, model = \"ecx4param\"), data = nec_data)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  quantity = c(\"EC10\", \"EC50\"),\n  drc_relative = c(ED(model_LL4, 10, display = FALSE)[1, 1],\n                   ED(model_LL4, 50, display = FALSE)[1, 1]),\n  bayesnec_range = c(ecx(bnec_ecx4, ecx_val = 10, type = \"range\")[1],\n                     ecx(bnec_ecx4, ecx_val = 50, type = \"range\")[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  quantity drc_relative bayesnec_range\n1     EC10     1.507871       1.513310\n2     EC50     1.995000       1.995123\n```\n\n\n:::\n:::\n\n\nThe EC50 estimates differ by less than 0.001. The EC10 estimates differ by\nabout half a per cent, and the `drc` estimate falls inside the `bayesnec`\ncredible interval. The two fits differ in more than their method. `LL.4` is\nlogistic in log concentration and `ecx4param` is logistic in concentration, and\n`drc` fits a Gaussian error where `bnec()` chose a beta family for these\nproportions. They still return the same estimates to the precision that would be\nreported.\n\n### Divergence between the engines\n\nGive the response a floor that is not zero and the fitted range is no longer the\ndistance from the control to zero. The two anchors then measure different\nthings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfloored <- transform(nec_data, y = 0.3 + 0.6 * y)\nmodel_floor <- drm(y ~ x, data = floored, fct = LL.4())\n\ncf_f <- coef(model_floor)\nc_f <- cf_f[[\"c:(Intercept)\"]]\nd_f <- cf_f[[\"d:(Intercept)\"]]\n\n# A 10% decline from the control, expressed as the percentage of the fitted\n# range that drc needs, so that both quantities come from the same fit.\nlevel_from_control <- 100 * (0.10 * d_f) / (d_f - c_f)\n\nc(fitted_lower = c_f,\n  fitted_upper = d_f,\n  EC10_of_the_range = ED(model_floor, 10, display = FALSE)[1, 1],\n  EC10_from_control = ED(model_floor, level_from_control, display = FALSE)[1, 1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     fitted_lower      fitted_upper EC10_of_the_range EC10_from_control \n        0.3443691         0.8376138         1.5110272         1.6199901 \n```\n\n\n:::\n:::\n\n\nThe fitted range runs from 0.344 to 0.838. A decline of ten per cent of that\nrange reaches a response of 0.789 and is met at a concentration of 1.511. A\ndecline of ten per cent from the control reaches 0.754 and is met at 1.620, some\nseven per cent higher.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngr <- curve_data(model_floor, min(floored$x), max(floored$x))\nec_range <- ED(model_floor, 10, display = FALSE)[1, 1]\nec_ctrl  <- ED(model_floor, level_from_control, display = FALSE)[1, 1]\n\nggplot(floored, aes(x, y)) +\n  geom_point(alpha = 0.4, size = 1) +\n  geom_line(data = gr, aes(x, fit), linewidth = 0.8, colour = \"steelblue\") +\n  geom_hline(yintercept = d_f - 0.10 * (d_f - c_f), linetype = 2, colour = \"grey40\") +\n  geom_hline(yintercept = d_f - 0.10 * d_f, linetype = 2, colour = \"firebrick\") +\n  geom_vline(xintercept = ec_range, linetype = 3, colour = \"grey40\") +\n  geom_vline(xintercept = ec_ctrl,  linetype = 3, colour = \"firebrick\") +\n  annotate(\"text\", x = min(floored$x), y = c_f + 0.01,\n           label = \"fitted lower asymptote\", hjust = 0, size = 3, colour = \"grey40\") +\n  scale_x_continuous(trans = \"log\", breaks = c(0.1, 0.3, 1, 3)) +\n  labs(x = \"Concentration\", y = \"Response\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![The same fitted curve, with the two targets a ten per cent effect can mean. The upper dashed line is ten per cent of the fitted range below the control; the lower is ten per cent below the control.](drc-reference_files/figure-html/fig-anchors-1.png){#fig-anchors width=672}\n:::\n:::\n\n\nBoth estimates are correct, and they answer different questions. The\nrange-referenced EC10 is the concentration at which the response has fallen by a\ntenth of the range the fitted curve spans, from its upper asymptote to its\nlower. The control-referenced EC10 is the concentration at which the response has\nfallen to nine tenths of its control level. Where a guideline value is being derived the second is normally what is\nmeant, and it is what `bayesnec` returns by default.\n\nThe practical rule when comparing an `ED()` result against an `ecx()` result is\nto establish that both are anchored the same way, and to record in the write-up\nwhich convention was used.\n\n## A no-significant-effect concentration\n\nThe *NSEC* is defined from the fitted curve and the variability of the control\nrather than from a model parameter [@fisherfox2023], so it can be derived from a\nfrequentist fit. Take the control level and a lower bound on it, then find the\nconcentration at which the curve crosses that bound.\n\nFor the threshold model the control level is the `d` parameter, and its standard\nerror is reported in the summary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsig_val <- 0.01\npars <- summary(model_NEC3)$coefficients\nd_est <- pars[\"d:(Intercept)\", \"Estimate\"]\nd_se  <- pars[\"d:(Intercept)\", \"Std. Error\"]\n\n# One-sided lower bound on the control at the 1 - sig_val level. This is the\n# frequentist counterpart of the control posterior quantile bayesnec uses.\nlower_bound <- d_est - qnorm(1 - sig_val) * d_se\n\ncrossing <- function(z) predict(model_NEC3, data.frame(x = z)) - lower_bound\nnsec <- uniroot(crossing, interval = range(nec_data$x))$root\n\nc(control = d_est, control_se = d_se, lower_bound = lower_bound, NSEC = nsec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    control  control_se lower_bound        NSEC \n0.890221527 0.004885504 0.878856146 1.531069897 \n```\n\n\n:::\n:::\n\n\nThe control is estimated at 0.8902 with a standard error of 0.0049, giving a\nlower 99 per cent bound of 0.8789. The curve crosses that bound at 1.531, which\nis the *NSEC*. The threshold estimated by the same model is 1.523, slightly\nlower, because the curve has to decline a little past the threshold before it\nfalls below the control's lower bound.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(nec_data, aes(x, y)) +\n  geom_point(alpha = 0.4, size = 1) +\n  geom_line(data = curve_data(model_NEC3, min(nec_data$x), max(nec_data$x)),\n            aes(x, fit), linewidth = 0.8, colour = \"firebrick\") +\n  geom_hline(yintercept = lower_bound, linetype = 2, colour = \"grey30\") +\n  geom_vline(xintercept = nsec, linetype = 3, colour = \"grey30\") +\n  scale_x_continuous(trans = \"log\", breaks = c(0.1, 0.3, 1, 3)) +\n  labs(x = \"Concentration\", y = \"Response\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![The derived NSEC. The horizontal line is the lower bound on the control and the vertical line marks where the curve crosses it.](drc-reference_files/figure-html/fig-nsec-1.png){#fig-nsec width=672}\n:::\n:::\n\n\nThe derivation above reads the control's uncertainty off the `d` parameter\nbecause `predict(model_NEC3, se.fit = TRUE)` returns no standard error for this\nfit. `NEC.3()` supplies no derivatives of its mean function, and without them\n`predict()` returns the fitted values alone, with no warning.\n\nTwo things separate this from the `bayesnec` *NSEC*. The bound here is a normal\napproximation built from the standard error of `d`, where `bayesnec` takes a\nquantile of the control posterior. And there is no interval on the result, because propagating\nthe uncertainty in both the control and the curve through the crossing would\nrequire the delta method or a bootstrap.\n\n## Model averaging\n\n`mselect()` ranks candidate mean functions by an information criterion, AIC by\ndefault:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmselect(model_LL4, list(LL.3(), W1.4(), W2.4()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       logLik        IC Lack of fit     Res var\nW2.4 174.0792 -338.1584          NA 0.001875953\nLL.3 164.3041 -320.6081          NA 0.002257496\nLL.4 164.3050 -318.6100          NA 0.002280968\nW1.4 157.1969 -304.3938          NA 0.002629416\n```\n\n\n:::\n:::\n\n\n`W2.4` has the lowest information criterion at −338.2, followed by `LL.3` at\n−320.6.\n\n`maED()` averages effect concentrations over the candidates using Akaike\nweights. A Buckland unconditional interval is available through\n`interval = \"buckland\"`; the default, used here, returns no interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaED(model_LL4, list(LL.3(), LL.4(), W1.4(), W2.4()), 10, display = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Estimate\ne:1:10 1.564547\n```\n\n\n:::\n:::\n\n\nThe averaged EC10 is 1.565. The four candidates individually give 1.508, 1.508,\n1.462 and 1.565, so the average sits at the value from `W2.4`, which took\nalmost all of the Akaike weight because its information criterion is 17.6 units\nbelow the next.\n\nTwo properties of `maED()` are visible in `drc::maED` itself and matter before\nrelying on it. It takes `na.rm = FALSE` and threads that through every `sum()`,\nso one candidate whose root-finder fails renders every averaged value missing\nrather than being dropped. And it forms weights as `exp(-AIC/2)` without\ncentring on the minimum AIC, so once AIC reaches a few thousand every term\nunderflows to zero in double precision and the weights become `0/0`. Centring on\nthe minimum resolves this and changes nothing where the uncentred form works.\n\nBoth packages can fit one equation or average over several, and they differ in\nthe default. `bayesnec` averages unless asked to fit a single equation; `drc` fits one\nequation unless asked to average, and the uncertainty in which equation was\nselected does not appear in the interval of a single selected fit.\n\n## Comparing groups\n\n`EDcomp()` compares effect concentrations between curves fitted with `curveid`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(daphnids)\ndaphnids.m1 <- drm(no / total ~ dose, weights = total, curveid = time,\n                   data = daphnids, fct = LL.2(), type = \"binomial\")\nEDcomp(daphnids.m1, c(50, 50))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEstimated ratios of effect doses\n\n               Estimate Std. Error   t-value   p-value\n24h/48h:50/50 3.4021279  0.8182594 2.9356556 0.0033284\n```\n\n\n:::\n:::\n\n\nThe ratio of the two EC50 values is 3.40 with a p-value of 0.003 against a\nratio of one, so the 24-hour and 48-hour EC50 values differ. `bayesnec` answers\nthe same question by comparing posteriors and returns a probability that one\nestimate is lower than the other, which module 8 covers.\n\n## Agreement and divergence\n\n| | `drc` | `bayesnec` |\n|---|---|---|\n| Estimation | maximum likelihood | Bayesian, HMC via Stan |\n| Interval | confidence interval, delta method | credible interval from the posterior |\n| Threshold equations | `NEC.2`, `NEC.3`, `NEC.4` | the ten `nec` equations |\n| *NSEC* | derived by hand, as above | `nsec()`, with an interval |\n| ECx anchor | the fitted range, `d` to `c` | the control, at the lowest observed concentration |\n| Candidate set | one selected by AIC, or averaged with `maED()` | averaged by default |\n| Group comparison | ratio, confidence interval, p-value | probability of difference from the posteriors |\n\nA confidence interval and a credible interval are not the same quantity. A\ncredible interval states where the parameter lies with a given probability,\ngiven the data, the model and the priors. A confidence interval states that the\nprocedure producing it would contain the true value in that proportion of\nrepeated experiments. A risk assessment usually wants to state that there is a\n95 per cent probability the *NEC* lies between two values, and that statement\nfollows from the first and not from the second. Both are abbreviated CI, and\n`brms` prints `l-95% CI`, so name the interval type in a results table.\n\nThe distributional assumptions differ and the point estimates will differ with\nthem. A continuous positive response will commonly be fitted Gaussian in `drc`\nwhere `bayesnec` selects a gamma, and the Gaussian fit is influenced more by the\nhigh-response observations. A difference between the engines is not by itself\nevidence that either is wrong.\n\n`drc` intervals can be too narrow, or missing. Under `type = \"Poisson\"` the\nvariance is fixed equal to the mean, so an overdispersed count response gets\nintervals narrower than the data support by roughly the square root of the\ndispersion; report the dispersion alongside the interval rather than rescaling\nit, since changing the variance assumption changes the model. Separately, the\ndelta-method standard error is `NaN` wherever the variance calculation goes\nnegative, which is neither rare nor confined to poor fits, and each occurrence\narrives as its own `\"NaNs produced\"` warning. Where standard errors feed a model average, dropping candidates\nas their errors become unavailable changes what the average is an average of, so\nfix the candidate set for the whole curve rather than point by point.\n\n## Choosing between them\n\nFor a well-determined monotonic curve with adequate replication, fitted with the\nsame distribution in both, the two engines return much the same answer, and\n`drc` returns it in seconds rather than minutes. The EC50 comparison above\nagreed even with a Gaussian error in `drc` and a beta family in `bayesnec`.\n\nThe longer run time of a Bayesian fit is justified where the problem is harder: where priors\nare needed to stabilise a non-linear fit, where the candidate set does not\nidentify one curve, where an interval is wanted on a derived quantity such as\nthe *NSEC*, or where the posterior itself is needed to propagate uncertainty\ninto a species sensitivity distribution or to state the probability that one\nsubstance is more toxic than another.\n\n## Provenance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (p in c(\"drc\", \"bayesnec\", \"brms\")) {\n  cat(sprintf(\"%-10s %s\\n\", p, as.character(packageVersion(p))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndrc        3.0.1\nbayesnec   2.1.3.39\nbrms       2.23.0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"%-10s %s\\n\", \"R\", getRversion()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR          4.6.1\n```\n\n\n:::\n:::\n\n\nEvery number and figure on this page is produced when it is built.\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "drc-reference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}