{
  "hash": "f9fd5c61648038a404dab84feb7923bd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A worked case study\"\nsubtitle: \"Estimating and comparing the toxicity of seven herbicides\"\nbibliography: bayesnec.bib\n---\n\n\n\n## Background\n\nEarlier modules each covered one part of the workflow: what the model set is,\nhow a model average is formed, how a family is chosen, how priors are built.\nThis module runs one analysis from data to reportable estimate, in the order the\nsteps occur, and then applies the same workflow to seven herbicides so their\ntoxicity can be compared.\n\nThe workflow is:\n\n1. Prepare the data and choose the family.\n2. Fit the candidate set.\n3. Check the sampler, and screen out the models that did not sample adequately.\n4. Check the fit of the models that remain.\n5. Report.\n\nA prior check belongs between steps 2 and 3, and module 6 covers `check_priors()`\nand the construction of the defaults.\n\nThe posterior draws a Bayesian fit produces are useful well beyond a point\nestimate. They support the study of synergistic and antagonistic effects\n[@Fisher2019d; @flores2021], the propagation of endpoint uncertainty\n[@Charles2020a; @Gottschalk2013], and tests of hypotheses of no effect\n[@Thomas2006]. `compare_posterior()` uses them to compare fits, and the\ncomparison across the seven herbicides at the end of this module is what it is\nfor.\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![](images/dredging_effects.JPG){#fig-context-1 width=48%}\n:::\n\n::: {.cell-output-display}\n![](images/herbicides_climate.JPG){#fig-context-2 width=48%}\n:::\n:::\n\n\n### The assumptions the diagnostics test\n\nConvergence is what a Bayesian fit is usually judged on, and it is not the only\nthing that can be wrong. `rhat()`, `check_chains()` and `check_sampling()` ask\nwhether the sampler explored the posterior. `loo` and `waic` rank the candidate\nequations against one another. None of them asks whether the variability the\nfitted model implies matches the variability in the data, and a threshold\nestimate depends on that assumption more than on any other.\n\nThe *NSEC* depends on it most directly. `nsec()` sets its reference at a quantile\nof the posterior of the control mean, and the width of that posterior is set by\nthe dispersion the fit estimated at the control. A model simulating more\nvariability at the control than the data show places the reference lower, so the\ncurve crosses it further along and the reported concentration is higher and less\nprotective. A model simulating less variability places the reference higher and\nreturns a lower concentration. The direction is not known in advance, and no\nconvergence diagnostic reveals it. An **EC~x~** depends on it less: it is\nmeasured from the same control mean, but at a fixed fraction of that mean rather\nthan at a quantile of its posterior, so an error in the variance widens or\nnarrows its interval rather than relocating the reference.\n\nOne ratio statistic for the whole fit does not detect this. Every family with a\nfree dispersion parameter, which is `gaussian`, `Gamma`, `negbinomial`, `Beta`\nand `beta_binomial`, estimates that parameter from the same residuals such a\nstatistic summarises. The parameter absorbs the discrepancy, so the fit reports a\nratio near 1 while simulating the wrong spread at the concentrations that\ndetermine the estimate. The check is therefore made within concentration groups,\nwhich is what `check_fit()` does, and step 4 runs it.\n\n## The data\n\nThe data are from @jones2003meps and ship with `bayesnec`, so nothing has to be\nread from a file.\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![](images/jonesnkerswell.jpg){#fig-source-1 width=48%}\n:::\n\n::: {.cell-output-display}\n![](images/s_hystrix.jpg){#fig-source-2 width=48%}\n:::\n:::\n\n\nThe response is the maximum effective quantum yield, $\\Delta F / Fm'$, of\nsymbiotic dinoflagellates in the tissue of the coral *Seriatopora hystrix*,\ncalculated from chlorophyll fluorescence measured with a DIVING-PAM fluorometer\n[@jones2003meps; @jones2003effects]. Corals were exposed for 10 hours to eight\nherbicides at concentrations from 0.3 to 1000 $\\mu g L^{-1}$. Ioxynil is excluded\nhere because it produced no adequate response at the highest concentration,\nleaving seven. `?herbicide` documents the columns and the provenance of the\nresponse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(herbicide)\nstr(herbicide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t580 obs. of  3 variables:\n $ herbicide    : chr  \"irgarol\" \"diuron\" \"ametryn\" \"tebuthiuron\" ...\n $ concentration: num  0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 ...\n $ fvfm         : num  0.63 0.68 0.68 0.73 0.64 0.69 0.67 0.64 0.71 0.68 ...\n - attr(*, \"na.action\")= 'omit' Named int [1:176] 26 505 506 510 512 513 517 519 520 524 ...\n  ..- attr(*, \"names\")= chr [1:176] \"26\" \"505\" \"506\" \"510\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(herbicide$herbicide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    ametryn    atrazine      diuron  hexazinone     irgarol    simazine tebuthiuron \n         96          84          72          76          72          72         108 \n```\n\n\n:::\n:::\n\n\nAmetryn is the series worked through steps 1 to 5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nametryn <- herbicide[herbicide$herbicide == \"ametryn\", ]\nhead(ametryn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   herbicide concentration fvfm\n3    ametryn           0.1 0.68\n10   ametryn           0.1 0.68\n17   ametryn           0.1 0.67\n24   ametryn           0.1 0.65\n31   ametryn           0.1 0.67\n38   ametryn           0.1 0.67\n```\n\n\n:::\n:::\n\n\n## 1. Data preparation and family choice\n\nLook at the data before fitting anything.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconc_breaks <- c(0.3, 1, 3, 10, 30, 100, 300)\nggplot(ametryn, aes(x = concentration, y = fvfm)) +\n  geom_point(size = 2, alpha = 0.6) +\n  scale_x_continuous(transform = \"log\", breaks = conc_breaks) +\n  labs(x = expression(paste(\"Concentration (\", mu, \"g \", L^-1, \")\")),\n       y = \"Maximum effective quantum yield\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![The ametryn series, on a logarithmic concentration axis.](7Example_case_study_files/figure-html/fig-ametryn-raw-1.png){#fig-ametryn-raw width=672}\n:::\n:::\n\n\nThe response is flat across the lowest concentrations and then declines. The\nseries has 8 distinct concentrations,\nwhich is the number of points from which a curve's shape has to be identified,\nand it is a constraint on which equations the design can support. Mean yield is\n0.013\nat the highest concentration against\n0.678\nat the lowest.\n\n### The scale of the response\n\nChoosing a family is a statement about what kind of quantity the response is:\nthe values it can take, the bounds it cannot cross, and how its variance behaves\nas its mean changes. Module 5 sets out the families `bayesnec` supports and what\neach assumes.\n\n`fvfm` is a ratio of chlorophyll fluorescence yields. It is bounded by 0 and 1\nand it is continuous, which is the `Beta` case rather than the `binomial` one: a\nproportion of this kind is not a count of successes out of a known number of\ntrials, and there is no denominator to supply.\n\n`Beta` estimates a dispersion parameter, `phi`, from the data, so there is no\nover-dispersion decision to take here. The family already has a free parameter\nfor the spread and the fit will estimate it. `dispersion()` is defined only for\n`poisson` and `binomial`, the two families whose variance is fixed by the mean,\nwhich is why module 5 runs that screen and this module does not.\n\nWhat has to be checked is the one thing `Beta` cannot accommodate, which is a\nvalue outside its support. The family is supported on the open interval (0, 1),\nso a value recorded as exactly 0 or 1 lies outside it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(ametryn$fvfm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0 0.7\n```\n\n\n:::\n:::\n\n\nAmetryn reaches neither boundary. Several of the other herbicides do:\n10 of irgarol's\nreadings are exactly zero, so the family cannot be chosen without inspecting the\nresponse. `bayesnec` substitutes for both bounds, a zero becoming one tenth of\nthe smallest non-zero value and a one being reduced by an absolute 0.001, and\n`bnec_record()` reports after the fit whether anything was altered. A series with\nseveral concentrations at a boundary is then being modelled through that\nsubstitution rather than as recorded. Where zeros are part of the process rather\nthan a recording floor, module 5 covers the hurdle and zero-inflated families\nthat model them explicitly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfam <- Beta(link = \"identity\")\n```\n:::\n\n\n`bnec()` sets `link = \"identity\"` by default on every family, so that `top`,\n`bot` and `nec` are estimated on the scale of the response and remain directly\ninterpretable. It is written out here for clarity. Supplying a family with a\ndifferent link overrides that default, and the model then fits a non-linear curve\nto the transformed mean rather than to the mean, with the parameters no longer on\nthe response scale.\n\n### The scale of the predictor\n\nThe concentrations run from 0.1 to\n300, a factor of\n3000, in roughly\neven steps on a logarithmic scale. The predictor is logged in the formula.\n\nThe predictor enters the equations directly, so a transform changes the shape\nbeing fitted and not merely the axis: the same equation describes a different\ncurve in `concentration` and in `log(concentration)`. The default priors are also\nscaled from the predictor, so a transform rescales them. Neither consideration\nsettles the question in general, and which scale samples better on a given\ndataset is an empirical matter. Here the series was designed as a logarithmic\ndilution, and a logarithm is what makes its steps even.\n\nA logged predictor spanning -2.3 to\n5.7 takes negative values, which\nexcludes the equations that raise the predictor to a fractional power. Every\nestimate is returned on the logged scale unless `xform` is supplied, and step 5\nreturns them.\n\n## 2. Fitting the candidate set\n\nThe whole `decline` set is fitted in one call, under the family chosen in step 1.\n`model = \"decline\"` requests the equations that describe a declining response, of\nwhich there are 14 currently in `bayesnec`. The\nremaining equations describe hormesis, a response that rises above the control\nbefore it falls, and there is no evidence of hormesis in these data.\n\nThe settings below are deliberately *under* `bnec()`'s defaults, and that is a\ndecision made for this module rather than advice. These data are well behaved at\nthe defaults and every equation the design supports passes the screen there, so a\nfit made at the defaults produces no screen failure to examine. Running short\nguarantees that some equations fail, which is what makes steps 3 and 5 a\ndemonstration rather than an assertion. The settings are raised in step 3, and\nevery estimate reported in step 5 comes from the fit made there.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm7_am_reduced <- bnec(fvfm ~ crf(log(concentration), model = \"decline\"),\n                      data = ametryn, family = fam,\n                      iter = 4000, chains = 2, seed = 17)\n\nsave(m7_am_reduced, file = \"fits/m7_am_reduced.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"fits/m7_am_reduced.RData\")\n```\n:::\n\n\nCompare the retained draws and not `iter`. `iter` counts warmup as well as\nsampling, and the fraction discarded is a choice each package makes for itself.\n`bayesnec` takes `chains = 4` and `iter = 1e4`, and sets `warmup` to\n`floor(iter / 5) * 4`, discarding four fifths and retaining 8000 draws. The call\nabove sets `iter` to 4000 with two chains, and the same warmup rule leaves\n1600. For comparison, `brms` discards half rather\nthan four fifths, so its own defaults of `iter = 2000` over four chains retain\n4000, which is more than this call from a quarter of the iterations. A number of\niterations means nothing until the warmup rule and the chain count are stated\nbeside it.\n\nWhere a fit is genuinely marginal, two arguments are the ones to reach for.\n`iter` and `warmup` come first when Rhat is marginal or the effective sample size\nis low, because a model with a poorly identified parameter may need more draws.\n`control = list(adapt_delta = 0.99, max_treedepth = 12)` comes next: raise\n`adapt_delta` when there are divergent transitions and `max_treedepth` when the\nsampler reports hitting it. Both increase runtime and neither corrects a\nmisspecified model.\n\n### The set as fitted\n\nTwo mechanisms reduce the requested set. Some equations are excluded before\nfitting, because they are invalid for the family or the predictor. Others are\nattempted and fail to fit, which happens with complex non-linear models and\nparticularly with those that have many parameters. `bnec_record()` reports both,\nso neither has to be reconstructed from the fitted object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec <- bnec_record(m7_am_reduced)\nrec$excluded\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    model\n1  neclin\n2  ecxlin\n3 ecxsigm\n                                                                                        reason\n1         decays by subtraction, so its mean is unbounded below for beta with an identity link\n2         decays by subtraction, so its mean is unbounded below for beta with an identity link\n3 raises the predictor to a fractional power, which is undefined for negative predictor values\n```\n\n\n:::\n\n```{.r .cell-code}\nrec$attempted\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"nec3param\" \"nec4param\" \"ecxexp\"    \"ecx4param\" \"ecxwb1\"    \"ecxwb2\"    \"ecxwb1p3\"  \"ecxwb2p3\" \n [9] \"ecxll5\"    \"ecxll4\"    \"ecxll3\"   \n```\n\n\n:::\n:::\n\n\n`requested` is partitioned exactly by `attempted` and `excluded$model`. An\nequation that was attempted and failed to fit stays in `attempted`.\n\nTwo rules apply here. `neclin` and `ecxlin` decay by subtraction rather than by an\nexponential factor, so their fitted mean is unbounded below and cannot be held\ninside the (0, 1) interval a `Beta` mean occupies under an identity link. And the\npredictor is `log(concentration)`, which is negative below a concentration of 1,\nso the equations that raise the predictor to a fractional power cannot be\nevaluated. `?models` sets out these rules and the others.\n\n`failed_models()` names the equations that were attempted and did not fit, and\nrecords the priors and initial values each was given, which are built inside\n`bnec()` and otherwise unrecoverable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(failed_models(m7_am_reduced))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ecxll5\"\n```\n\n\n:::\n:::\n\n\n`substitutions` reports the changes `check_data()` made to the response because\nthe family cannot represent a value as recorded.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec$substitutions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     variable             rule n_rows from    to                                      reason\nzero response shifted off zero     12    0 0.001 a beta distribution cannot represent a zero\n                   remedy\nzero zero_inflated_beta()\n```\n\n\n:::\n:::\n\n\nThis is the evidence for the boundary check in step 1: on a series that does\nreach 0 or 1 this element names each altered value, so a methods section can\nstate what was modelled rather than leaving a reader to assume it was the data as\nmeasured.\n\n### Model weights\n\n`summary()` reports the set as a whole.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m7_am_reduced)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required namespace: rstan\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObject of class bayesmanecfit\n\n Family: beta  \n  Links: mu = identity  \n\nNumber of posterior draws per model:  1600\n\nModel weights (Method: pseudobma_bb_weights):\n             waic   wi\nnec3param -451.02 0.03\nnec4param -456.61 0.04\necxexp    -320.58 0.00\necx4param -465.16 0.41\necxwb1    -443.23 0.01\necxwb2    -461.28 0.11\necxwb1p3  -323.21 0.00\necxwb2p3  -446.88 0.01\necxll4    -465.05 0.38\necxll3    -432.45 0.00\n\n\nSummary of weighted N(S)EC posterior estimates:\nNB: Model set contains a combination of ECx and NEC\n    models, and is therefore a model averaged\n    combination of NEC and NSEC estimates.\n       Estimate  Q2.5 Q97.5\nN(S)EC    -1.65 -2.15 -0.45\n\n\nBayesian R2 estimates:\n          Estimate Est.Error Q2.5 Q97.5\nnec3param     0.99      0.00 0.99  0.99\nnec4param     0.99      0.00 0.99  0.99\necxexp        0.89      0.01 0.87  0.91\necx4param     0.99      0.00 0.99  0.99\necxwb1        0.99      0.00 0.98  0.99\necxwb2        0.99      0.00 0.99  0.99\necxwb1p3      0.93      0.01 0.90  0.96\necxwb2p3      0.99      0.00 0.99  0.99\necxll4        0.99      0.00 0.99  0.99\necxll3        0.99      0.00 0.98  0.99\n\n\n1 model(s) failed to fit: ecxll5\nSee ?failed_models for the priors and initial values used.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in print.manecsummary(x): control observed/simulated ratio beyond 1.15 (see ?check_fit):\n  -  nec3param\n  -  nec4param\n  -  ecxexp\n  -  ecx4param\n  -  ecxwb1\n  -  ecxwb2\n  -  ecxwb1p3\n  -  ecxwb2p3\n  -  ecxll4\n  -  ecxll3\nThis is a modelling result rather than a fault; inspect with check_fit().\n```\n\n\n:::\n:::\n\n\n`wi` is the model weight: the share of the model-averaged prediction each\ncandidate contributes, summing to one across the set. The weights come from\nPSIS-LOO, with `loo_model_weights()` consuming the `loo` objects `brms` computes\nfor each fit. Where a model reports Pareto *k* values above 0.7 for a few\nobservations, `brms` warns, and the weights remain usable while the estimates\nbehind them are flagged as unreliable at those points. That belongs in a methods\nstatement alongside the weights themselves.\n\n## 3. Sampler diagnostics and screening\n\nEvery equation in the fitted set produced draws; the ones that did not are in\n`failed_models()`. The diagnostics here establish whether those draws describe\nthe posterior adequately. Whether a model fits the data is a separate question,\nanswered in step 4.\n\n`check_sampling()` reports per candidate model, so the whole set is screened in\none call rather than model by model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_sampling(m7_am_reduced)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       model max_rhat  min_ess min_ess_ratio n_divergent failed\n1  nec3param 1.004253 727.6289     0.4547681           0  FALSE\n2  nec4param 1.009106 368.7366     0.2304604           0   TRUE\n3     ecxexp 1.006067 624.6060     0.3903788           0  FALSE\n4  ecx4param 1.003113 630.7977     0.3942486           0  FALSE\n5     ecxwb1 1.002677 344.1262     0.2150789           0   TRUE\n6     ecxwb2 1.004520 644.1353     0.4025846           0  FALSE\n7   ecxwb1p3 1.007203 656.2184     0.4101365           0  FALSE\n8   ecxwb2p3 1.001966 500.2253     0.3126408           0  FALSE\n9     ecxll4 1.005335 643.2938     0.4020586           0  FALSE\n10    ecxll3 1.007635 521.2024     0.3257515           0  FALSE\n```\n\n\n:::\n:::\n\n\nThe table gives one row per fitted model with three diagnostics: the largest\nRhat, the smallest effective sample size, and the number of divergent\ntransitions. Each is compared against a cutoff, and `failed` is `TRUE` where any\nof the three is missed.\n\nThe cutoffs are arguments to `check_sampling()` and can be changed. The Rhat\ndefault of 1.01 and the ESS default of 400 follow published recommendations\n[@Vehtari2021]; the divergence default of 10 does not. Stan's own guidance is\nthat *any* divergence means the sampler failed to explore the posterior. The\ndefault of ten is a package convention rather than a published recommendation,\nbecause these non-linear models commonly produce a small number of divergent\ntransitions near a parameter boundary, as `?check_sampling` describes.\n\nRead `min_ess` rather than `min_ess_ratio` when deciding. The 400 is an absolute\nfloor, below which the Rhat and ESS estimates are themselves unreliable, and it\ncorresponds to 100 draws per chain at the four chains `bnec()` fits by default.\nBoth the ESS and the divergence cutoffs are absolute counts, and the number of\ndraws changes what each of them demands, in opposite directions. At the\n1600 draws retained here a model must reach an\nefficiency ratio of\n0.250 to clear 400,\nagainst 0.050 at the default 8000, so the ESS cutoff is\nharder to clear at these settings. Ten divergent transitions, on the other hand,\nis 0.62 per cent of\nthe retained draws here and 0.125 per cent at the\ndefault, so at an equal divergence rate the same fit produces more of them at the\ndefaults and that cutoff is harder to clear there. Neither setting is uniformly\nstricter, and a screen result is therefore a property of the settings as much as\nof the model. State the settings used.\n\n### Kinds of failure\n\nThe three kinds of failure are distinguished by which thresholds an equation\nmissed, and whether divergent transitions are among them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncs <- check_sampling(m7_am_reduced)\ncs[cs$failed, c(\"model\", \"max_rhat\", \"min_ess\", \"n_divergent\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      model max_rhat  min_ess n_divergent\n2 nec4param 1.009106 368.7366           0\n5    ecxwb1 1.002677 344.1262           0\n```\n\n\n:::\n:::\n\n\nAn equation that misses the effective sample size or Rhat threshold with no\ndivergent transitions has been sampled from a posterior the sampler could\ntraverse. It was not sampled for long enough to describe that posterior, and both\ndiagnostics are themselves estimated less precisely from fewer draws. Refitting\nwith a higher `iter` is what such an equation needs, and it is expected to pass\nonce it has them, so excluding it on this evidence would be premature.\n\nDivergent transitions are different, because they describe the posterior rather\nthan the run. A divergence is recorded when the sampler's trajectory through\nparameter space goes numerically unstable, which happens where the posterior has\ncurvature too sharp for the step size adapted during warmup. Taking more draws\nsamples the same surface for longer and does not smooth it. Where such an\nequation is also the most heavily parameterised in the set, the usual explanation\nis that the design does not support it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted_mods <- c(cs$model, names(failed_models(m7_am_reduced)))\nn_par <- vapply(fitted_mods,\n                function(m) length(names(show_params(m)[[1]]$pforms)),\n                integer(1))\ndata.frame(model = fitted_mods, parameters = n_par,\n           produced_draws = fitted_mods %in% cs$model,\n           row.names = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       model parameters produced_draws\n1  nec3param          3           TRUE\n2  nec4param          4           TRUE\n3     ecxexp          2           TRUE\n4  ecx4param          4           TRUE\n5     ecxwb1          4           TRUE\n6     ecxwb2          4           TRUE\n7   ecxwb1p3          3           TRUE\n8   ecxwb2p3          3           TRUE\n9     ecxll4          4           TRUE\n10    ecxll3          3           TRUE\n11    ecxll5          5          FALSE\n```\n\n\n:::\n:::\n\n\n`check_sampling()` reports only the equations that produced draws, so\necxll5 is added above\nfrom `failed_models()`: it is the equation with the most curve parameters in the\nset, at 5 against\n4\nfor any equation that did fit.\n\nThe series has 8 distinct\nconcentrations, and an equation with more curve parameters than the design can\ndetermine has a posterior that is flat in some direction. Sampling a flat\ndirection for longer does not locate a maximum that is not there. Adjusting the\nsettings to retain an equation in that position does not address the problem:\nthe fit is not failing because it was run badly, but because the experiment does\nnot contain the information the equation needs. Report it as excluded, and say\nwhy.\n\nWhere an equation's Rhat or effective sample size sits at the threshold, which\nside of it the equation falls on is sensitive to the seed, and another run may\nplace it on the other side. Any threshold applied to an estimated quantity\nbehaves this way. It is why the thresholds have to be reported with the result,\nand why the screen names every threshold an equation missed rather than only the\nfirst.\n\n### Screening the model set\n\nOnly models that pass the sampler diagnostics are retained. The screen reads the\nsampler and nothing else: whether an equation reproduces the data is a separate\nquestion, and removing an equation for that silently would hide the discrepancies\nthe fit checks exist to show.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscreened_reduced <- screen_models(m7_am_reduced)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDropping 2 of 10 candidate models that failed the sampler screen:\n  -  nec4param: ESS 368.7\n  -  ecxwb1: ESS 344.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFitted models are: nec3param ecxexp ecx4param ecxwb2 ecxwb1p3 ecxwb2p3 ecxll4 ecxll3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: \n2 (2.1%) p_waic estimates greater than 0.4. We recommend trying loo instead.\nWarning: \n2 (2.1%) p_waic estimates greater than 0.4. We recommend trying loo instead.\nWarning: \n2 (2.1%) p_waic estimates greater than 0.4. We recommend trying loo instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: \n3 (3.1%) p_waic estimates greater than 0.4. We recommend trying loo instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: \n2 (2.1%) p_waic estimates greater than 0.4. We recommend trying loo instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: \n3 (3.1%) p_waic estimates greater than 0.4. We recommend trying loo instead.\n```\n\n\n:::\n:::\n\n\n`screen_models()` runs the same diagnostics as `check_sampling()`, drops what\nfailed, and reports which models were removed and why, one line per model naming\nevery threshold it missed. An exclusion step that leaves no record is not\nreproducible, which is why the message is on by default and why `quiet = TRUE`\nshould not be used in an analysis that will be reported.\n\nIf every candidate fails, `screen_models()` stops with an error listing the\nreasons rather than returning a meaningless average, which signals a return to\nstep 2 rather than a loosened threshold. If none fails, it says so and returns the\nset unchanged.\n\n`amend()` does the work, and it is the only route by which a model leaves a\n`bayesmanecfit`. The weights of a screened set therefore have to be read from the\nscreened fit rather than rescaled by hand.\n\n### Raising the settings\n\nThe screen has identified the equations that did not sample adequately. For those\nthat reported no divergent transitions, the remedy is the one step 2 deferred:\nfit again at `bnec()`'s defaults.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm7_am_fit <- bnec(fvfm ~ crf(log(concentration), model = \"decline\"),\n                  data = ametryn, family = fam, seed = 17)\n\nsave(m7_am_fit, file = \"fits/m7_am_fit.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"fits/m7_am_fit.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_sampling(m7_am_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       model max_rhat  min_ess min_ess_ratio n_divergent failed\n1  nec3param 1.001291 3050.015     0.3812519           0  FALSE\n2  nec4param 1.001129 3409.846     0.4262307           0  FALSE\n3     ecxexp 1.000652 3303.686     0.4129608           0  FALSE\n4  ecx4param 1.002316 3121.923     0.3902404           0  FALSE\n5     ecxwb1 1.002164 2217.522     0.2771902           0  FALSE\n6     ecxwb2 1.001493 3521.173     0.4401466           0  FALSE\n7   ecxwb1p3 1.001576 3320.889     0.4151112           0  FALSE\n8   ecxwb2p3 1.001623 3330.871     0.4163589           0  FALSE\n9     ecxll4 1.000870 3320.101     0.4150126           0  FALSE\n10    ecxll3 1.001059 2532.767     0.3165959           0  FALSE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(failed_models(m7_am_fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ecxll5\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_screened <- screen_models(m7_am_fit)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nAll 10 candidate models passed the sampler screen (Rhat <= 1.01, ESS >= 400, divergences <= 10).\n```\n\n\n:::\n:::\n\n\nThe comparison between the two runs is the point of having made both. Every\nequation the screen removed at the reduced settings\n(nec4param, ecxwb1) passes here, on the same data\nand the same priors, because it was given more draws. Both had missed the\neffective sample size threshold with no divergent transitions, which is the first\nkind of failure, and more draws corrected them as that diagnosis predicted.\n`ecxwb1` rose from an effective sample size of\n344 to\n2218.\n\nNo equation in either run recorded a divergent transition, so the second kind of\nfailure does not arise on these data. Where it does, more sampling does not\nchange the curvature the sampler could not traverse, and because the divergence\ncutoff is an absolute count, a longer run reports proportionally more divergences\nat an unchanged rate. Raising the settings makes that failure easier to see, not\nharder.\n\necxll5 still fails to fit at\nall, which is the third kind and the one the parameter count anticipated. More\nsampling did not make it fit and would not be expected to.\n\nThe priors and initial values a failed equation was given are retained on the\nfailed fit and are the starting point for an adjustment if one is wanted, as\n`?failed_models` sets out.\n\n## 4. Fit diagnostics\n\nThe sampler diagnostics indicate whether the sampler explored the posterior\nadequately. They say nothing about whether the model fits. Two checks answer\ndifferent questions: `pp_check()` overall, and `check_fit()` within concentration\ngroups.\n\nBoth are applied to the highest-weighted model of the screened set, which\ncontributes most to the reported estimate and is therefore the one whose fit\nmatters most. `pull_best()` returns it as a `bayesnecfit`, and returns a\n`bayesnecfit` unchanged, so a set the screen reduced to a single equation needs no\nseparate handling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest_fit <- pull_best(fit_screened)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nHighest-weighted model is ecxll4, holding 0.417 of the weight of 10 candidate models.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPulling out model(s): ecxll4\n```\n\n\n:::\n:::\n\n\nThe weight is reported with the number of candidates it was selected from,\nbecause the two together are what say whether the selection means anything. The\nhighest weight of a flat set of ten is little more than the equal share of 0.1,\nand one such equation describes the model-averaged estimate hardly at all. Read\nit against the weights `summary()` reported in step 2.\n\n`pp_check()` asks whether data simulated from the fitted model resemble the data\nobserved. Pooled over the whole dataset the comparison is weak for\nconcentration-response data, because a model can match the pooled distribution\nwhile being wrong at every concentration, so it is grouped by the predictor here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(best_fit, type = \"dens_overlay_grouped\", group = \"concentration\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nUsing 10 posterior draws for ppc type 'dens_overlay_grouped' by default.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Observed and simulated response densities within each concentration.](7Example_case_study_files/figure-html/fig-ppcheck-1.png){#fig-ppcheck width=672}\n:::\n:::\n\n\nThe dark line is the observed density of the response within each concentration\ngroup and the light lines are the same quantity simulated from the fit. The\nresponse is continuous, so a density overlay is the appropriate display; a\ndiscrete response takes `type = \"bars_grouped\"` instead, which is what module 5\nuses for its count example.\n\nLocation is reproduced: each observed density sits within the spread of the\nsimulated ones, and its position follows the decline across the series. The\nobserved curves are the more irregular of the two, because a kernel density\nestimated from\n12 observations\nresolves individual values as separate modes, and that is a property of the\ndisplay rather than evidence against the fit.\n\nWidth is the other thing to read, and it is where these data depart from the\nfit. The simulated densities are visibly the wider at the low concentrations and\nthe narrower at the high ones. Judging that by eye from\n12 observations is\nunreliable, which is what `check_fit()` puts a number on.\n\n`check_fit()` tests something narrower: whether the model reproduces the observed\nvariability and the observed level *locally*, within each concentration group,\nwith the control flagged.\n\nThe control is the lowest value of the predictor, which is `bayesnec`'s\nconvention throughout. Both estimators read their reference from the posterior of\nthe fitted mean there: `nsec()` sets its significance reference from it, and every\n**EC~x~** is measured from it as well. Control variability therefore propagates\ninto every threshold the analysis reports, not only the no-effect concentration.\nAn experiment whose lowest treatment is not a control is being analysed on that\nassumption and should say so.\n\nIdentifying the control by position rather than by value keeps the convention\nintact under a common preparation. Analysis is often done on a log scale, and a\nsmall constant is added to the concentrations so that a zero control can be\nplotted and fitted. Whether the control is entered as 0, or as 0.001, or as one\ntenth of the lowest exposure, it remains the lowest value in the series and is\ntherefore still the control. These data have no zero concentration, so the\nquestion does not arise and the lowest tested concentration is the reference.\n\nFor a `bayesmanecfit` it returns every group of every candidate model, which is\nmore than can be read at once. Two views are useful. The first is the control row\nof each model, which is the row both estimators read their reference from.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf <- check_fit(fit_screened)\ncf[cf$control, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       model    wi group  n obs_mean sim_mean mean_ratio ppp_mean obs_sd sim_sd sd_ratio ppp_sd\n1  nec3param 0.033   0.1 12    0.678    0.647      1.049    0.035  0.014  0.046    0.305  1.000\n9  nec4param 0.035   0.1 12    0.678    0.647      1.048    0.039  0.014  0.047    0.300  1.000\n17    ecxexp 0.000   0.1 12    0.678    0.758      0.895    0.969  0.014  0.098    0.143  1.000\n25 ecx4param 0.379   0.1 12    0.678    0.681      0.996    0.562  0.014  0.043    0.323  0.999\n33    ecxwb1 0.012   0.1 12    0.678    0.695      0.975    0.826  0.014  0.049    0.289  1.000\n41    ecxwb2 0.106   0.1 12    0.678    0.659      1.030    0.131  0.014  0.045    0.311  1.000\n49  ecxwb1p3 0.000   0.1 12    0.678    0.636      1.067    0.066  0.014  0.080    0.175  1.000\n57  ecxwb2p3 0.018   0.1 12    0.678    0.672      1.009    0.394  0.014  0.044    0.317  1.000\n65    ecxll4 0.417   0.1 12    0.678    0.680      0.998    0.535  0.014  0.044    0.322  1.000\n73    ecxll3 0.000   0.1 12    0.678    0.694      0.977    0.814  0.014  0.045    0.315  1.000\n   control\n1     TRUE\n9     TRUE\n17    TRUE\n25    TRUE\n33    TRUE\n41    TRUE\n49    TRUE\n57    TRUE\n65    TRUE\n73    TRUE\n\nThe control group is flagged. nsec() reads its reference from the \ncontrol, so this is the row most likely to move a reported \nno-effect concentration. See ?check_fit.\n```\n\n\n:::\n:::\n\n\nA continuous response has genuine residual variability at every concentration, so\n`obs_sd`, `sim_sd` and the ratio between them are all finite and informative, and\n`ppp_sd` is not forced to 0 or 1 by construction as it can be for a binomial\nresponse near total mortality.\n\nRead `ppp_mean` and `ppp_sd` rather than the ratios. The posterior predictive\np-value is `mean(sim >= obs)`, so a value near 0.5 says the observed statistic\nsits in the middle of what the model simulates and a value near 0 or 1 says it\nsits in a tail. `?check_fit` records the case in which a model holds high weight\nbecause it fits the bulk of the curve while fitting the control badly, which is\nwhat this view is for, and it is the case these data present.\n\nThe second view is the full table for a single model, read when one candidate is\nin question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_best <- check_fit(best_fit)\ncf_best\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  group  n obs_mean sim_mean mean_ratio ppp_mean obs_sd sim_sd sd_ratio ppp_sd control\n1   0.1 12    0.678    0.680      0.998    0.535  0.014  0.044    0.322  1.000    TRUE\n2   0.3 12    0.616    0.615      1.001    0.486  0.019  0.046    0.409  0.998   FALSE\n3     1 12    0.434    0.421      1.032    0.206  0.037  0.047    0.787  0.827   FALSE\n4     3 12    0.167    0.188      0.887    0.947  0.013  0.037    0.355  1.000   FALSE\n5    10 12    0.068    0.056      1.210    0.083  0.014  0.021    0.663  0.929   FALSE\n6    30 12    0.020    0.021      0.980    0.555  0.013  0.013    0.969  0.531   FALSE\n7   100 12    0.016    0.011      1.412    0.092  0.015  0.009    1.585  0.094   FALSE\n8   300 12    0.013    0.009      1.442    0.136  0.017  0.008    1.982  0.020   FALSE\n\nThe control group is flagged. nsec() reads its reference from the \ncontrol, so this is the row most likely to move a reported \nno-effect concentration. See ?check_fit.\n```\n\n\n:::\n:::\n\n\nLocation is reproduced at every concentration: `mean_ratio` runs from\n0.887 to\n1.442 and no `ppp_mean` is near either\nbound. The departure is entirely in scale, and it is systematic rather than\nconfined to one group. `obs_sd` is close to constant across the series, from\n0.013 to\n0.037, while `sim_sd` falls steadily from\n0.044 at the control to\n0.008 at the highest concentration.\n\nThat pattern is a property of the family. A `Beta` variance is\n$\\mu(1-\\mu)/(1+\\phi)$ with a single `phi` estimated for the whole fit, so the\nsimulated spread is largest where the mean is near the middle of the range and\nshrinks as the mean approaches zero. The observed spread does not behave that\nway here, so one `phi` cannot match both ends of the series: the fit oversimulates\nvariability at the low concentrations and undersimulates it at the high ones.\nModule 5 covers the dispersion sub-model, written as a term in the formula, which\nis what lets the spread vary with the predictor instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cf_best)\n```\n\n::: {.cell-output-display}\n![Observed statistics against the 95% span of what the fitted model simulates, by concentration.](7Example_case_study_files/figure-html/fig-checkfit-1.png){#fig-checkfit width=672}\n:::\n:::\n\n\nThe plot shows what the table does not: the magnitude and direction of the\ndiscrepancy. Each panel gives the observed statistic against the 95% span of what\nthe model simulates, and a point outside its bar is a group the model does not\nreproduce. Location and scale are separate panels because they fail\nindependently, and that is what has happened here: every point in the mean panel\nsits inside its bar while several in the standard deviation panel do not.\n\nThe control row is the one the Overview singled out, and on these data it is the\nworst of the series rather than the best. The model simulates a standard\ndeviation of 0.044 against an\nobserved 0.014, a `sd_ratio` of\n0.322, and a `ppp_sd` of\n1.000, meaning that essentially\nevery simulated draw was more variable than the data.\n\nThat has a direction, and it is the one the Overview set out. `nsec()` reads its\nreference from the posterior of the control mean, and a fit simulating more\nvariability there than the data show gives that posterior too much width. The\nreference is placed lower, the curve crosses it further along, and the reported\nno-effect concentration is **higher than the data warrant, and so less\nprotective**. An analysis reporting the *N(S)EC* for these data should state this\ncheck and its result, and should consider the dispersion sub-model before the\nestimate is used.\n\nA group can fall beyond the message's criterion and inside the plot's bar,\nbecause the two differ: the message flags a posterior predictive p-value outside\n[0.05, 0.95] and the bars are the 95% span, which is [0.025, 0.975]. Read the\nmessage as a prompt to look at the group rather than as a verdict.\n\n## 5. The reported estimates\n\n`summary()` returns the retained equations with their weights and the\nmodel-averaged estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_screened)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObject of class bayesmanecfit\n\n Family: beta  \n  Links: mu = identity  \n\nNumber of posterior draws per model:  8000\n\nModel weights (Method: pseudobma_bb_weights):\n             waic   wi\nnec3param -451.06 0.03\nnec4param -456.69 0.04\necxexp    -320.44 0.00\necx4param -465.13 0.38\necxwb1    -443.63 0.01\necxwb2    -461.34 0.11\necxwb1p3  -323.16 0.00\necxwb2p3  -447.00 0.02\necxll4    -465.27 0.42\necxll3    -432.21 0.00\n\n\nSummary of weighted N(S)EC posterior estimates:\nNB: Model set contains a combination of ECx and NEC\n    models, and is therefore a model averaged\n    combination of NEC and NSEC estimates.\n       Estimate  Q2.5 Q97.5\nN(S)EC    -1.66 -2.14 -0.45\n\n\nBayesian R2 estimates:\n          Estimate Est.Error Q2.5 Q97.5\nnec3param     0.99      0.00 0.99  0.99\nnec4param     0.99      0.00 0.99  0.99\necxexp        0.89      0.01 0.87  0.91\necx4param     0.99      0.00 0.99  0.99\necxwb1        0.99      0.00 0.98  0.99\necxwb2        0.99      0.00 0.99  0.99\necxwb1p3      0.94      0.01 0.90  0.96\necxwb2p3      0.99      0.00 0.99  0.99\necxll4        0.99      0.00 0.99  0.99\necxll3        0.99      0.00 0.98  0.99\n\n\n1 model(s) failed to fit: ecxll5\nSee ?failed_models for the priors and initial values used.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in print.manecsummary(x): control observed/simulated ratio beyond 1.15 (see ?check_fit):\n  -  nec3param\n  -  nec4param\n  -  ecxexp\n  -  ecx4param\n  -  ecxwb1\n  -  ecxwb2\n  -  ecxwb1p3\n  -  ecxwb2p3\n  -  ecxll4\n  -  ecxll3\nThis is a modelling result rather than a fault; inspect with check_fit().\n```\n\n\n:::\n:::\n\n\nThe set mixes threshold and smooth equations, so that estimate is a mixture of\n*NEC* and *NSEC* draws, which is the *N(S)EC* module 3 defined, and it should not\nbe reported as a *NEC*.\n\n### The scale an estimate is on\n\nThe predictor was logged in the formula, so the threshold is returned on that\nscale. `nec()`, `nsec()` and `ecx()` all take an `xform` argument to put it back\non the measured one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(log_scale = nec(fit_screened),\n      measured  = nec(fit_screened, xform = exp))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis bayesmanecfit contains smooth (ecx) models, which have no threshold parameter, so the returned estimate is a weighted mixture of NEC and NSEC draws -- the model-averaged N(S)EC rather than a NEC. See ?nec and summary(), which labels it.\nThis bayesmanecfit contains smooth (ecx) models, which have no threshold parameter, so the returned estimate is a weighted mixture of NEC and NSEC draws -- the model-averaged N(S)EC rather than a NEC. See ?nec and summary(), which labels it.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Q50      Q2.5      Q97.5\nlog_scale -1.663466 -2.136800 -0.4513908\nmeasured   0.189481  0.118032  0.6367419\n```\n\n\n:::\n:::\n\n\nOnly the second row is on the measured scale. The first is its natural logarithm,\nand the two are easy to confuse, because a logged value can land in the same\nnumeric range as a concentration: the median of the first row would pass\nunremarked in a series running from 0.1 to\n300. Reporting a logged value as a concentration\nunderstates the threshold by a factor of 2.7 for every unit on\nthe logged scale. Where the logarithm is negative the value is not a\nconcentration at all, which is the one case in which the error announces itself.\nA reported value has to state the scale it is on.\n\n### The parameters of the curve\n\n`summary()` does not report the parameters of the curve itself. `curve_params()`\nreturns them, one row per parameter per equation, with the model weight beside\neach row.\n\n\n::: {#tbl-curveparams .cell tbl-cap='Fitted curve parameters for ametryn, with the weight of the equation each came from.'}\n\n```{.r .cell-code}\ncurve_params(fit_screened, xform = exp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       model           wi dpar     link parameter     Estimate         Q2.5        Q97.5\n1     ecxll4 4.171951e-01   mu identity       top  0.702409905  0.673394325  0.734096045\n2     ecxll4 4.171951e-01   mu identity       bot  0.008783056  0.005583625  0.012614853\n3     ecxll4 4.171951e-01   mu identity      beta  0.261975790  0.158569725  0.369138372\n4     ecxll4 4.171951e-01   mu identity      ec50  1.339670878  1.163794144  1.514585592\n5  ecx4param 3.789986e-01   mu identity       top  0.702825640  0.674081856  0.735037377\n6  ecx4param 3.789986e-01   mu identity       bot  0.008722921  0.005553338  0.012550562\n7  ecx4param 3.789986e-01   mu identity      beta  0.259280400  0.157464315  0.363335727\n8  ecx4param 3.789986e-01   mu identity      ec50  1.336456743  1.165854729  1.509917935\n9     ecxwb2 1.063291e-01   mu identity       top  0.657772365  0.635584658  0.681120591\n10    ecxwb2 1.063291e-01   mu identity       bot  0.007184491  0.003900357  0.011204553\n11    ecxwb2 1.063291e-01   mu identity      beta  0.073426013 -0.028279881  0.183671755\n12    ecxwb2 1.063291e-01   mu identity      ec50  1.006751328  0.872931746  1.140887354\n13 nec4param 3.505118e-02   mu identity       top  0.646677760  0.626747534  0.666520058\n14 nec4param 3.505118e-02   mu identity       bot  0.006002212  0.002421994  0.010312821\n15 nec4param 3.505118e-02   mu identity      beta -0.101976870 -0.195718516 -0.004062701\n16 nec4param 3.505118e-02   mu identity       nec  0.645714912  0.580452402  0.710416713\n17 nec3param 3.289193e-02   mu identity       top  0.646568460  0.626932821  0.665982123\n18 nec3param 3.289193e-02   mu identity      beta -0.215918675 -0.284870326 -0.149748667\n19 nec3param 3.289193e-02   mu identity       nec  0.599591188  0.532975125  0.659955924\n20  ecxwb2p3 1.777026e-02   mu identity       top  0.672578515  0.649397042  0.697433147\n21  ecxwb2p3 1.777026e-02   mu identity      beta -0.088891064 -0.162322028 -0.020640148\n22  ecxwb2p3 1.777026e-02   mu identity      ec50  0.904889374  0.786859125  1.028684621\n23    ecxwb1 1.170612e-02   mu identity       top  0.837314370  0.765456546  0.923267105\n24    ecxwb1 1.170612e-02   mu identity       bot  0.012660553  0.009054751  0.017073639\n25    ecxwb1 1.170612e-02   mu identity      beta -0.520960155 -0.670037248 -0.356916938\n26    ecxwb1 1.170612e-02   mu identity      ec50  1.662894071  1.302567708  2.064801398\n27    ecxll3 5.773357e-05   mu identity       top  0.753593625  0.717594232  0.797983157\n28    ecxll3 5.773357e-05   mu identity      beta  0.018692647 -0.068720950  0.095071287\n29    ecxll3 5.773357e-05   mu identity      ec50  1.122455622  0.928137965  1.316125299\n30    ecxexp 2.780574e-26   mu identity       top  0.284262570  0.263211954  0.307728245\n31    ecxexp 2.780574e-26   mu identity      beta -0.857620450 -0.945975046 -0.779282778\n32  ecxwb1p3 1.200741e-27   mu identity       top  0.975830205  0.924418251  0.996332442\n33  ecxwb1p3 1.200741e-27   mu identity      beta -1.083427950 -1.178969405 -1.003794850\n34  ecxwb1p3 1.200741e-27   mu identity      ec50  1.245739968  1.023567903  1.579278091\n```\n\n\n:::\n:::\n\n\nThe equations of a set do not share a parameter list, which is why nothing is\naveraged across them: only the threshold equations estimate `nec`, and the\nthree-parameter equations have no `bot`. Averaging a parameter over whichever\nequations happen to estimate it would average over a different subset for each\nparameter. The weight beside each row is what makes the table readable, since a\nrow holding a thousandth of the weight describes the averaged curve hardly at\nall.\n\n`xform` reaches `nec` and `ec50` and no other parameter, because those two are on\nthe scale of the predictor while `top`, `bot` and `beta` are levels of the\nresponse or shape parameters.\n\n### Effect concentrations and censoring\n\nThe other commonly required endpoint is an **EC~x~**, read from the same\nscreened set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\necx(fit_screened, ecx_val = 10, xform = exp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Q50      Q2.5     Q97.5 \n0.3797423 0.3627844 0.4000171 \nattr(,\"resolution\")\n[1] 200\nattr(,\"ecx_val\")\n[1] 10\nattr(,\"toxicity_estimate\")\n[1] \"ecx\"\n```\n\n\n:::\n\n```{.r .cell-code}\necx(fit_screened, ecx_val = 50, xform = exp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Q50     Q2.5    Q97.5 \n1.498711 1.413922 1.600085 \nattr(,\"resolution\")\n[1] 200\nattr(,\"ecx_val\")\n[1] 50\nattr(,\"toxicity_estimate\")\n[1] \"ecx\"\n```\n\n\n:::\n:::\n\n\nBoth are model-averaged over the screened set. Every **EC~x~** and *NSEC* is\nmeasured from the control, which is the predicted mean at the lowest\nconcentration in the series, taken per posterior draw. `type` sets what the\ndecline is measured against: `\"absolute\"`, the default, takes it against 0, and\n`\"range\"` takes it against the lowest response the curve predicts. The two answer\ndifferent questions and give different numbers, so the value used has to be\nstated. `?ecx` sets out all four values and what each measures against.\n\nA target the curve never reaches within the tested range returns `NA` for the\naffected draws, with a warning naming how many. That is a reportable outcome\nrather than a failure: it says the design did not reach the effect size asked\nfor. An **EC~x~** summarised over the remaining draws is a **censored** estimate\nand has to be reported as one, naming how many draws were excluded and that the\nvalue is bounded below by the highest concentration tested. Reported without that\nlabel it reads as an ordinary estimate and understates the true value.\n\n## The complete set of herbicides\n\nSteps 1 to 5 covered one series. The same call is applied to each herbicide in\nturn, and the seven results are then compared.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmanecfit <- herbicide |>\n  mutate(concentration = log(concentration)) |>\n  split(f = ~ herbicide) |>\n  purrr::map(function(x) {\n    bnec(fvfm ~ crf(concentration, model = \"decline\"), data = x, seed = 17)\n  })\n\nsampling <- purrr::imap_dfr(manecfit, function(fit, nm) {\n  check_sampling(fit) |> mutate(herbicide = nm, .before = 1)\n})\n\ncleaned_fits <- purrr::map(manecfit, screen_models)\n```\n:::\n\n\nSeven herbicides against the `decline` set is 14\nequations each and takes hours, so these fits are not run when this page is\nbuilt. They are produced by `scripts/generate_herbicide_fits.R`, which writes the\ncompact results the rest of this module reads, and the fitted objects themselves\nare too large to keep: the 2023 equivalent was 451 MB. The code shown is the code\nthat was run.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerated by scripts/generate_herbicide_fits.R\ndate: 2026-09-17 00:45:30\nelapsed: 43.9 mins\nseed: 17\nR: 4.6.1\nbayesnec: 2.1.3.35\nbrms: 2.23.0\ncmdstanr: 0.9.0\nmodel set: decline, 14 equations\nsampler screen: rhat <= 1.01, ess >= 400, divergences <= 10\nherbicides: ametryn, atrazine, diuron, hexazinone, irgarol, simazine, tebuthiuron\n```\n\n\n:::\n:::\n\n\n### Screening the model sets\n\nEach of the seven sets is screened on all three sampler diagnostics before it is\nused, exactly as step 3 screened the ametryn set. The full table is kept rather\nthan only the failures, because the thresholds applied are part of what has to be\nreported.\n\n\n::: {#tbl-sampling .cell tbl-cap='Number of equations fitted and removed by the sampler screen, per herbicide.'}\n\n```{.r .cell-code}\nsampling <- read.csv(\"data/herbicide_sampling.csv\")\n\nsampling |>\n  summarise(equations = dplyr::n(),\n            removed = sum(failed),\n            .by = herbicide) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|herbicide   | equations| removed|\n|:-----------|---------:|-------:|\n|ametryn     |        10|       0|\n|atrazine    |        10|       0|\n|diuron      |        10|       0|\n|hexazinone  |        10|       0|\n|irgarol     |        10|       0|\n|simazine    |        10|       0|\n|tebuthiuron |        10|       0|\n\n\n:::\n:::\n\n\n\n::: {#tbl-screened .cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nNo equation failed the sampler screen.\n```\n\n\n:::\n:::\n\n\nEquations that produced no draws at all are the separate failure step 3\ndistinguished, and are reported by `failed_models()`.\n\n\n::: {#tbl-neverfit .cell}\n::: {.cell-output-display}\n\n\nTable: Equations that failed to fit at all.\n\n|herbicide   |model  |\n|:-----------|:------|\n|ametryn     |ecxll5 |\n|atrazine    |ecxll5 |\n|diuron      |ecxll5 |\n|hexazinone  |ecxll5 |\n|irgarol     |ecxll5 |\n|simazine    |ecxll5 |\n|tebuthiuron |ecxll5 |\n\n\n:::\n:::\n\n\nDo not reach for `rhat(fit)$failed` in place of `check_sampling()`: `rhat()` on a\n`bayesmanecfit` returns a list keyed by model name, each element holding the Rhat\nvalues and a logical `failed`, so `$failed` on the list itself is `NULL` and\nsilently drops nothing. An earlier version of this module had that defect.\n\n### Model weights across herbicides\n\n\n::: {#tbl-weights .cell tbl-cap='Fitted equations and their relative weights, for the effect of seven herbicides on the maximum effective quantum yield of symbiotic dinoflagellates of *Seriatopora hystrix*.'}\n\n```{.r .cell-code}\nmodstats <- read.csv(\"data/herbicide_mod_stats.csv\")\n\nmodstats |>\n  mutate(wi = round(wi, 3)) |>\n  select(herbicide, model, wi) |>\n  pivot_wider(names_from = herbicide, values_from = wi) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|model     | ametryn| atrazine| diuron| hexazinone| irgarol| simazine| tebuthiuron|\n|:---------|-------:|--------:|------:|----------:|-------:|--------:|-----------:|\n|nec3param |   0.032|    0.001|  0.000|      0.000|   0.001|    0.001|       0.014|\n|nec4param |   0.033|    0.002|  0.000|      0.000|   0.001|    0.000|       0.003|\n|ecxexp    |   0.000|    0.000|  0.000|      0.000|   0.000|    0.000|       0.000|\n|ecx4param |   0.409|    0.193|  0.336|      0.126|   0.314|    0.240|       0.004|\n|ecxwb1    |   0.012|    0.613|  0.198|      0.001|   0.307|    0.117|       0.000|\n|ecxwb2    |   0.109|    0.002|  0.000|      0.018|   0.031|    0.020|       0.298|\n|ecxwb1p3  |   0.000|    0.000|  0.000|      0.013|   0.000|    0.017|       0.000|\n|ecxwb2p3  |   0.018|    0.002|  0.000|      0.063|   0.002|    0.061|       0.676|\n|ecxll4    |   0.387|    0.187|  0.354|      0.130|   0.345|    0.188|       0.005|\n|ecxll3    |   0.000|    0.000|  0.111|      0.649|   0.000|    0.355|       0.000|\n\n\n:::\n:::\n\n\nThe best-fitting equations differ substantially between herbicides. Few show much\nweight on the threshold models. Among the smooth equations the weights vary\nwidely, with support for more than one in every case.\n\nThat is the argument for model averaging in a sentence: there is no single\nequation that is right for these data, the best one differs by herbicide, and\nselecting one would discard the uncertainty about which. Averaging propagates it\ninto the estimates instead.\n\n### The fitted curves\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds <- read.csv(\"data/herbicide_pred_vals.csv\")\nobs   <- read.csv(\"data/herbicide_observations.csv\")\n\nggplot(preds, aes(x = concentration)) +\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), fill = \"grey80\") +\n  geom_line(aes(y = Estimate)) +\n  geom_point(data = obs, aes(y = fvfm), size = 0.6, alpha = 0.5) +\n  facet_wrap(~ herbicide, ncol = 2) +\n  scale_x_continuous(trans = \"log\", breaks = c(0.3, 3, 30, 300)) +\n  labs(x = expression(\"Concentration (\"*mu*\"g/L)\"),\n       y = expression(Delta*\"F/Fm'\")) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Model-averaged concentration-response curves for seven herbicides, with 95% credible intervals and the observations.](7Example_case_study_files/figure-html/fig-all-herbicides-1.png){#fig-all-herbicides width=672}\n:::\n:::\n\n\n### The toxicity estimates\n\nThe value reported for each herbicide is the model-averaged posterior combining\nthe *NEC* parameter from the threshold equations with the *NSEC* from the smooth\nones, which is the *N(S)EC* step 5 reported for ametryn.\n\n\n::: {#tbl-estimates .cell tbl-cap='Model-averaged no-effect estimates, back-transformed to concentration.'}\n\n```{.r .cell-code}\nread.csv(\"data/herbicide_estimates.csv\") |>\n  transmute(Herbicide = herbicide,\n            `Estimate` = signif(estimate, 3),\n            `Lower 95%` = signif(lower, 3),\n            `Upper 95%` = signif(upper, 3)) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Herbicide   | Estimate| Lower 95%| Upper 95%|\n|:-----------|--------:|---------:|---------:|\n|ametryn     |    0.193|     0.120|     0.636|\n|atrazine    |    1.150|     0.290|     2.620|\n|diuron      |    0.155|     0.110|     0.199|\n|hexazinone  |    0.633|     0.232|     1.620|\n|irgarol     |    0.136|     0.107|     0.172|\n|simazine    |    4.340|     1.040|    11.500|\n|tebuthiuron |   11.300|     7.200|    14.000|\n\n\n:::\n:::\n\n\nThese are the estimates that would enter a guideline derivation. In Australia\nthat is the Australian and New Zealand Water Quality Guidelines [@anzg]. The\n*NEC* has been the established preference for some time [@Warne2015; @warne2018],\nand the 2025 revision of the derivation method [@warne2025] places the *NSEC*\nalongside it: the two are now the most preferred statistical estimates, with an\n**EC~x~** at *x* of 10 or less in the tier below them.\n\nThat has a practical consequence for a table like the one above. Because the\n*NSEC* sits in the preferred tier, the condition attached to it applies, and an\n*NSEC* whose measured effect size exceeds 20% should probably not be used to\nderive a guideline value. Module 3 covers the ECNSEC, which is the quantity that\nmeasures it, and an analysis reporting an N(S)EC for guideline use should report\nthat alongside.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/NSEC_ieam.jpg){#fig-nsecieam fig-align='center' width=100%}\n:::\n:::\n\n\n## Comparing the posteriors\n\n`compare_posterior()` extracts the weighted posterior for each fit so they can be\ncompared directly, rather than by asking whether intervals overlap.\n\n`comparison` names the quantity compared, and takes `\"nec\"`, `\"n(s)ec\"`,\n`\"nsec\"`, `\"ecx\"` or `\"fitted\"`. `\"n(s)ec\"` is used here because these sets mix\nthreshold and smooth equations, so the weighted no-effect posterior is a mixture\nof both kinds of estimate. Asking for `\"nec\"` would compare the threshold\nparameter alone, over the equations that have one, which is a different quantity\nand would be a different table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_comp <- compare_posterior(cleaned_fits, comparison = \"n(s)ec\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost <- read.csv(\"data/herbicide_ne_posterior.csv\")\n\nggplot(post, aes(x = concentration, group = model,\n                 colour = model, fill = model)) +\n  geom_density(alpha = 0.3) +\n  scale_x_continuous(trans = \"log\", breaks = c(0.3, 1, 3, 10, 30),\n                     labels = c(0.3, 1, 3, 10, 30)) +\n  labs(x = expression(\"Concentration (\"*mu*\"g/L)\"), y = \"Density\",\n       colour = \"Herbicide\", fill = \"Herbicide\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Posterior densities of the N(S)EC estimate for each herbicide.](7Example_case_study_files/figure-html/fig-posteriors-1.png){#fig-posteriors width=672}\n:::\n:::\n\n\nIrgarol, diuron and ametryn are the most toxic and are similar to one another,\ntheir densities overlapping substantially. Tebuthiuron is the least toxic,\nfollowed by simazine and atrazine, with hexazinone intermediate.\n\n## Probabilities of difference\n\nOverlapping densities are a visual impression. `compare_posterior()` also returns\nthe probability that one estimate is lower than another, computed from the draws.\n\n\n::: {#tbl-probdiff .cell tbl-cap='Probability of difference in no-effect toxicity between herbicides, from the overlap in their posterior densities.'}\n\n```{.r .cell-code}\nread.csv(\"data/herbicide_prob_diff.csv\") |>\n  separate(col = comparison, into = c(\"herbicide\", \"against\"), sep = \"-\") |>\n  pivot_wider(names_from = against, values_from = prob) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|herbicide  |  atrazine|    diuron| hexazinone|   irgarol|  simazine| tebuthiuron|\n|:----------|---------:|---------:|----------:|---------:|---------:|-----------:|\n|ametryn    | 0.0217554| 0.8103276|  0.0531383| 0.9192298| 0.0112528|   0.0096274|\n|atrazine   |        NA| 0.9864966|  0.8344586| 0.9878720| 0.0447612|   0.0100025|\n|diuron     |        NA|        NA|  0.0150038| 0.7325581| 0.0107527|   0.0093773|\n|hexazinone |        NA|        NA|         NA| 0.9866217| 0.0165041|   0.0097524|\n|irgarol    |        NA|        NA|         NA|        NA| 0.0107527|   0.0096274|\n|simazine   |        NA|        NA|         NA|        NA|        NA|   0.0435109|\n\n\n:::\n:::\n\n\nThis is the practical advantage of having the posterior rather than an interval.\nThe question of whether A is more toxic than B is answered with a probability\ncomputed from the draws, without a significance test, and it propagates the\nuncertainty in the curve shape as well as in the parameters.\n\n## Reporting the analysis\n\nThe estimates above are the output. What follows is what has to accompany them,\nbecause almost every number in this module is a property of a decision as much as\nof the data.\n\nState **the data as analysed**: the response, the bounds of its distribution, and\nany value altered to bring it inside the family's support. `bnec_record()`\nreports the last of these in its `substitutions` element.\n\nState **the family and how it was chosen**. Here a continuous response bounded by\n0 and 1 gives the `Beta` family, with the boundary check of step 1 as the\nevidence. For a count out of a total, report the dispersion screen of module 5 and\nthe probability it returned.\n\nState **the candidate set as fitted**: the set requested, the equations excluded\nbefore fitting and why, and any equation that failed to fit at all.\n`bnec_record()` returns the first three and `failed_models()` the last.\n\nState **the sampler settings**, including the number of retained draws rather\nthan `iter` alone, because two of the three diagnostic cutoffs are absolute\ncounts read against them.\n\nState **the diagnostic thresholds**, all three of them. They are choices, they\ndetermine what was excluded, and `check_sampling()` allows each to be changed.\n\nState **which equations were excluded and why**, naming the threshold each\nfailed, and distinguishing an equation that would pass with more draws from one\nthe design cannot support. Step 3 separated the three kinds.\n\nState **the fit checks and what they showed**, not only the sampler\ndiagnostics. `check_fit()` reports whether the model reproduces the observed\nvariability within each concentration, and the control row is the one both\n`nsec()` and `ecx()` read their reference from. Where the check shows a\ndiscrepancy, state its direction, because that determines whether the reported\nestimate is conservative or not. On the ametryn series above the fit\noversimulates variability at the control, which makes the *N(S)EC* less\nprotective rather than more.\n\nState **the estimate settings**: `sig_val`, which sets the *NSEC* reference and\ndefaults to 0.01; `type`, which sets what an **EC~x~** is measured against and\ndefaults to `\"absolute\"`; `resolution`, the number of grid points a crossing is\ninterpolated on, which defaults to 200; and any `xform` used to return an\nestimate to the measured scale.\n\nState **the estimates with their intervals and the weights** of the retained\nequations, and **the parameters of the fitted curve** that the estimates were\nread from, which `curve_params()` returns.\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "7Example_case_study_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}