{
  "hash": "0e981b7559bdc84bffbc391bb3782baf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Fitting a single model\"\nsubtitle: \"One concentration-response model in `bayesnec`, start to finish\"\nbibliography: bayesnec.bib\n---\n\n\n\n## Background\n\n`bayesnec` fits concentration-response curves to toxicity data and derives\nno-effect concentration (*NEC*), no-significant-effect concentration (*NSEC*,\n@fisherfox2023) and effect concentration (**EC~x~**) estimates from non-linear\nmodels fitted by Bayesian Hamiltonian Monte Carlo, via `brms`\n[@Burkner2017; @Burkner2018] and Stan. It is an extension of `jagsNEC`\n[@Fisher2020].\n\nThis module fits one model to one dataset and works through everything that can\nbe done with the result: checking that it converged, looking inside the fitted\nobject, plotting it, and extracting toxicity estimates. Later modules cover the\nfull model set, model averaging, the choice of statistical distribution, and\npriors.\n\nIf you have not yet installed R, a C++ compiler, CmdStan and `bayesnec`, work\nthrough the [software setup](0Software-setup.qmd) first. Nothing in this module\nwill run without them.\n\n## The example dataset\n\n`bayesnec` supplies a small example dataset, `nec_data`, with two columns: `x`,\nthe concentration, and `y`, the response.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bayesnec)\ndata(nec_data)\nhead(nec_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          x         y\n1 1.0187462 0.8602703\n2 0.8157475 0.9102426\n3 0.3713305 0.8485031\n4 0.4008323 0.9226047\n5 1.2945451 0.8657107\n6 1.3897943 0.9163264\n```\n\n\n:::\n:::\n\n\nThe response here is a proportion bounded by zero and one, which matters for the\nstatistical distribution used to model it. `bayesnec` will choose a distribution\nfrom the characteristics of the data unless told otherwise, and module 5 covers\nthat choice in more detail.\n\n## Preparing the response\n\nSupply the response as it was measured. Do not convert it to percent inhibition,\npercent of control, or percent of the observed maximum before calling `bnec()`.\n\nNormalising to the control is conventional in ecotoxicology, usually as\n$y^0_i = 1 - y_i / \\bar{y}_{con}$, where $\\bar{y}_{con}$ is the mean of three to\nsix control replicates. @Ritz2026 measured what it does. Every observation is\ndivided by the *same random quantity*, so the normalised values are correlated\nand the sampling variability of the divisor is discarded. Because the expected\nvalue of a reciprocal is not the reciprocal of an expected value, the inhibition\ntrend is biased downwards and the effect concentrations read off it are biased\nupwards.\n\nThe size of that error, from their simulation of an ED10 with six control\nreplicates: normalising gave a bias of 6.8% and a coefficient of variation of\n26.4%, against 2.1% and 12.7% for the same quantity estimated from the raw\nresponse, and nominal 95% intervals covered at 90% rather than 95%. With a single\ncontrol replicate the coverage of the normalised analysis fell to 57%.\n\nNothing is lost by not normalising. The concentration at which inhibition rises\nby $x$ per cent is the concentration at which the response falls by $x$ per cent,\nso the two analyses answer the same question. The second is what `ecx()` returns\nby default, as a decline relative to the *fitted* control rather than to an\nobserved control mean, and because it is evaluated separately within every\nposterior draw the uncertainty about the control level propagates into the\ncredible interval instead of being thrown away.\n\nDividing by the observed maximum instead of the control mean is worse, on three\ncounts. An extreme order statistic is more variable and more biased than a mean\nof three to six values. The divisor then depends on every treatment rather than\non the controls alone, so treated groups partly determine their own denominator.\nAnd it forces exactly one observation to exactly 1, which is outside the open\ninterval a beta distribution is defined on, so `bnec()` has to shift it off the\nboundary.\n\n`bnec()` looks for both practices and reports them. Dividing by the observed\nmaximum leaves a maximum of exactly 1 attained by exactly one observation, and\ndividing by the control mean leaves the control observations averaging to exactly\n1. The first check is suppressed where the response lies on a rational grid,\nbecause a genuine count-derived proportion such as 19 of 20 surviving routinely\nproduces a single observation at 1 and is not evidence of anything.\n\nWhere a divisor is unavoidable, as it is for a response above 1 that has to be\nmodelled with a beta distribution, it must be a constant fixed in advance of the\nanalysis: a physiological or design ceiling, or a value from accumulated\nhistorical controls. @Ritz2026 are explicit that the problem is dividing by\nsomething *random* rather than dividing as such. An **EC~x~** is unaffected by\nthe choice of a constant divisor, because it is a relative decline from the\nfitted `top`, and the same holds for any linear rescaling of the response\n[@Weimer2012].\n\nMany proportional responses need no divisor at all. The maximum quantum yield\nused in module 7 is a genuine physical proportion, as is a survival fraction or a\nbleached-area fraction, and these are modelled as they stand.\n\n### The reason a divisor gets reached for\n\nDividing by the observed maximum is often done for a reason that has nothing to\ndo with normalisation. A response on an arbitrary scale, such as a luminescence\nreading or a cell count, is divided to put it between 0 and 1 so that a beta\ndistribution can be used, because the beta accommodates variability that changes\nwith the mean and a Gaussian does not.\n\nThat reasoning identifies a real problem and answers it indirectly. The problem\nis that replicate variability at the high concentrations is not the same as at\nthe control. The direct answer is to keep the response on its own scale,\nchoose the family that suits it, and model the variability explicitly where it\nchanges. Module 5 covers both halves: the choice of family, and the `disp` term\nfor a dispersion that varies across the series.\n\nDoing it that way keeps `top`, `bot` and `nec` in the units the experiment was\nmeasured in, avoids the bias @Ritz2026 measured, and states the change in\nvariability as something estimated from the data rather than absorbed by a\ntransformation. It also avoids forcing an observation onto the boundary of the\nbeta's support, which division by a maximum does by construction.\n\n## Reproducibility\n\nA Bayesian model is fitted by drawing samples (which I will explain in more detail in Module 6), \nso running the same code twice\ngives slightly different numbers unless the random number generator is set to a\nknown state.\n\nTwo generators are involved and both have to be fixed. `bnec()` searches for\nvalid starting values in R before it calls Stan, and that search draws from R's\nown generator, which `set.seed()` fixes. Stan then samples using a generator of\nits own, which the `seed` argument fixes. Setting one and not the other leaves\nthe fit irreproducible, so every fit in this course sets both.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nbnec_fit <- bnec(y ~ crf(x, model = \"nec3param\"), data = nec_data, seed = 333)\n```\n:::\n\n\nThe estimates below will not match yours to the last decimal place unless you\nuse the same seed, the same number of chains and the same version of the\npackage. They should match to within the width of the credible intervals, and if\nthey do not, that is worth investigating rather than accepting.\n\n## The `bnec` function\n\n`bnec` is the working function of the package. It assembles the non-linear model\nformula, generates priors and initial values, and calls `brms`. It is designed\nfor an R user who is comfortable with model-fitting syntax but is not a\nspecialist in non-linear or Bayesian modelling.\n\nRun `?bnec` for the full argument list. Beyond the formula and the data, the\narguments fall into four groups: the model or model set to fit (`model`); how\ntoxicity estimates are computed from the fit (`x_range`, `resolution`,\n`sig_val`); how the response and predictor are identified when the formula alone\nis not enough (`x_var`, `y_var`, `trials_var`); and how priors are set (`prior`,\n`prior_type`).\n\nAnything else is passed through to `brms::brm()` by `...`, so the full `brm`\nargument list is available. Three `brm` arguments are worth knowing about\nbecause `bayesnec` sets them differently from `brms`. It generates its own\n`family` and `prior` values rather than using the `brms` defaults, and it raises\nthe number of iterations from 2,000 to 10,000, with a correspondingly longer\nwarm-up, because the non-linear models here often need it.\n\nCompare the **retained** draws rather than `iter`, because the fraction discarded\nduring warm-up is a choice each package makes for itself. `bayesnec` fits four\nchains at `iter = 1e4` and sets `warmup` to `floor(iter / 5) * 4`, so it discards\nfour fifths and retains 8,000 draws. `brms` discards half, so its own defaults of\n`iter = 2000` over four chains retain 4,000. A number of iterations means nothing\nuntil the warm-up rule and the chain count are stated beside it, which matters\nhere because two of the diagnostics in the next section are counts read against\nthe retained draws.\n\nTwo arguments are the ones to reach for when a fit is marginal. Raise `iter` and\n`warmup` where the convergence diagnostic is borderline or the effective sample\nsize is low. Pass `control = list(adapt_delta = 0.99, max_treedepth = 12)` where\nthe sampler reports divergent transitions or reports hitting the maximum tree\ndepth. Both increase the run time, and neither corrects a model that does not\nsuit the data.\n\n## The formula\n\nA `bayesnec` formula takes the form:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny ~ crf(x, model = \"modelname\")\n```\n:::\n\n\nThe left-hand side is the response, exactly as in `brms`. The right-hand side\nuses `crf()`, a function specific to `bayesnec`, which stands for\n**c**oncentration-**r**esponse **f**unction. It takes the predictor and the name\nof the model to fit, and it accepts a transformation of the predictor, such as\n`crf(log(x), ...)`.\n\nTerm names must match the columns of the data frame exactly, as in any R\nformula.\n\nThe available models are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels()$all\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"nec3param\"     \"nec4param\"     \"nechorme\"      \"nechorme4\"    \n [5] \"necsigm\"       \"neclin\"        \"neclinhorme\"   \"nechormepwr\"  \n [9] \"nechorme4pwr\"  \"nechormepwr01\" \"ecxlin\"        \"ecxexp\"       \n[13] \"ecxsigm\"       \"ecx4param\"     \"ecxwb1\"        \"ecxwb2\"       \n[17] \"ecxwb1p3\"      \"ecxwb2p3\"      \"ecxll5\"        \"ecxll4\"       \n[21] \"ecxll3\"        \"ecxhormebc4\"   \"ecxhormebc5\"  \n```\n\n\n:::\n:::\n\n\nThese fall into named groups, which is how a set of models is requested rather\nthan a single one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(models())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"nec\"          \"ecx\"          \"all\"          \"bot_free\"     \"zero_bounded\"\n[6] \"decline\"      \"hormesis\"    \n```\n\n\n:::\n:::\n\n\nModule 3 describes what each model is and which toxicity estimates can be derived from\nit. Module 4 covers fitting a set of models rather than a single model.\n\n## The scale of the predictor\n\nThe predictor enters the equations directly, so the scale it is supplied on\nchanges the curve being fitted rather than only the axis it is drawn against.\n`bnec()` takes the concentration exactly as it is given and does not make this\ndecision for you.\n\nSettle it before fitting anything, because it generally matters more than the\nchoice of equation. On one algal dataset, fitting `nec4param` on `log(dose)`\nrather than on the raw dose axis reduced the largest departure of the fitted mean\nfrom the observed mean from 0.2115 to 0.0676, on a response spanning about 0.7,\nwhile five different equations fitted on the log axis all landed within 1.2\n`elpd_loo` of one another.\n\nConcentration-response experiments are usually laid out as a dilution series, in\nwhich each concentration is a fixed multiple of the one below it. On a linear\naxis such a design crushes the low concentrations together and spreads the high\nones out, so the equation spends its flexibility at the top of the range, where\nthe response is often already flat.\n\nRead the spacing of the **design** rather than the shape of the response.\nConcentrations that are near evenly spaced after a logarithmic transformation\nwere laid out on a log scale, and are usually best modelled there:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspacing_cv <- function(x) sd(diff(sort(x))) / mean(diff(sort(x)))\n\n# a three-fold dilution series\nconc <- c(0.01, 0.3, 1, 3, 10, 30, 100, 300)\nround(c(linear = spacing_cv(conc), log = spacing_cv(log(conc))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlinear    log \n  1.72   0.58 \n```\n\n\n:::\n:::\n\n\nThe coefficient of variation of the gaps is much smaller on the log scale, which\nis the signature of a series designed on that scale.\n\nA transformation is written directly inside `crf()`, as\n`crf(log(x), model = \"nec4param\")`. Three consequences follow.\n\nThe transformation is evaluated before `bayesnec` inspects the predictor, so a\ncontrol recorded as `0` arrives at the data check as `log(0)` and the fit stops,\nreporting a predictor that is not finite. `bayesnec` does not correct a zero on\nthe predictor axis: a concentration of zero is an ordinary control, and no\nresponse distribution constrains the values a predictor may take. Choose the\noffset yourself and add it to the data first, as `log(x + 1)` or a smaller\nconstant suited to the series.\n\nToxicity estimates are then returned on the transformed scale, so `nec()`,\n`ecx()` and `nsec()` need back-transforming through their `xform` argument, which\n`autoplot()` also takes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\necx(fit, xform = function(x) exp(x) - 1)\nautoplot(fit, xform = function(x) exp(x) - 1)\n```\n:::\n\n\nA value reported on the fitted scale reads as a concentration and is not one.\nReporting a logged value as a concentration understates the threshold by a factor\nof e for every unit on the logged scale, and only a negative logarithm announces\nthe error. State the scale alongside any value you report.\n\n`nec_data` is left on the linear scale throughout this course, and deliberately\nso. It is simulated as 100 random draws rather than as a designed series, and the\ntrue curve is defined as a function of linear `x`, so logging it would distort the\ngenerating scale rather than reveal it. The difference between this example and a\nreal dilution series is the design rather than the package.\n\n## Calling `bnec`\n\nSupplying a formula and a data frame is the minimum reqired to fit a `bayesnec` model; \neverything else is supplied by a default setting. You should always understand\nwhat these default settings are and if they are adequate for your data, but for this example they are.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nbnec_fit <- bnec(y ~ crf(x, model = \"nec3param\"), data = nec_data, seed = 333)\n\nsave(bnec_fit, file = \"fits/m2_bnec_fit.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"fits/m2_bnec_fit.RData\")\n```\n:::\n\n\nThe first thing that happens is compilation. Stan models are written in the Stan\nlanguage, translated to C++ and compiled to a shared object, which R then loads\nand runs. This is why the first fit of a session is slower than later ones, and\nwhy a compiler is needed at all.\n\nSampling follows. How long the whole thing takes depends on the machine, the\nnumber of chains and the number of iterations. The fit above took a little over\ntwo minutes on four cores.\n\nA model is fitted by running several chains, and those chains are independent of\none another until the results are combined. Run in **series** they wait their\nturn and the fit takes as long as all of them added together; run in\n**parallel** they run at the same time on different processor cores and the fit\ntakes about as long as the slowest one. Setting `mc.cores` is what allows the\nsecond, so use at least as many cores as you have chains:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(mc.cores = 4)\n```\n:::\n\n\nMore cores than chains gives no benefit here, because there is nothing else to\nrun at the same time. There is a second level of parallelism once a *set* of\nmodels is being fitted rather than one — the models can run alongside each other\nas well as the chains within them — and module 4 covers it.\n\nWhen the fit completes, `bayesnec` reports which model was fitted and which\nstatistical distribution was used. Here it is a `nec3param` model with a beta\ndistribution.\n\nWarnings may also appear. The two above concern the Pareto *k* diagnostic and\n`p_waic`, both of which relate to the leave-one-out cross-validation used to\ncompute model weights. Weights are irrelevant when a single model has been\nfitted, and module 4 returns to them when they are not. \n\n## Saving the fit\n\nA fitted model takes minutes of compute to produce and seconds to store, so save\nit as soon as\nit finishes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(bnec_fit, \"nec3param_fit.rds\")\nbnec_fit <- readRDS(\"nec3param_fit.rds\")\n```\n:::\n\n\nBe deliberate about where. This is one of the smallest fits in the course and the\nobject is 1.3 Mb, because it stores\nevery posterior draw for every parameter. A model-averaged set of all\n23 models is very much larger, and a fit to real data with\na grouping variable larger again. A folder synchronised by\nOneDrive or a similar service is a poor choice: the upload is slow, and on some\nconfigurations it interferes with writing the file at all.\n\n### Fit once, then load\n\nEvery module in this course follows the same three steps, and they are the steps\na real analysis follows rather than a convenience invented for teaching.\n\nThe model is fitted, and the fit is saved:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nbnec_fit <- bnec(y ~ crf(x, model = \"nec3param\"), data = nec_data, seed = 333)\n\nsave(bnec_fit, file = \"fits/m2_bnec_fit.RData\")\n```\n:::\n\n\nThat chunk is shown rather than run. Then the saved object is loaded, and it is\nthe loading that runs when you work through the page:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"fits/m2_bnec_fit.RData\")\n```\n:::\n\n\n`load()` restores the object under the name it was saved with, so `bnec_fit`\nexists from that point on exactly as though it had just been fitted.\n\nThis is worth adopting in your own work for the reason the paragraph above\ngives: sampling is what takes the minutes, and it never needs repeating. Fit in\none script, save, and load in the script that plots, summarises and extracts\nestimates. A fit that is never saved is refitted every time a figure changes.\n\nThe workshop distributes these saved objects, so the modules load in seconds\nrather than sampling for minutes. The [software setup](0Software-setup.qmd)\ncovers retrieving them. Fitting the models yourself works and is slower, which\nis worth doing at least once to see how long it takes.\n\n## The summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bnec_fit)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required namespace: rstan\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObject of class bayesnecfit containing the nec3param model\n\n Family: beta \n  Links: mu = identity \nFormula: y ~ top * exp(-exp(beta) * (x - nec) * step(x - nec)) \n         top ~ 1\n         beta ~ 1\n         nec ~ 1\n   Data: data (Number of observations: 100) \n  Draws: 4 chains, each with iter = 10000; warmup = 8000; thin = 1;\n         total post-warmup draws = 8000\n\nRegression Coefficients:\n     Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\ntop      0.89      0.01     0.88     0.90 1.00     7194     5302\nbeta     0.54      0.06     0.43     0.65 1.00     5471     5257\nnec      1.54      0.02     1.50     1.57 1.00     5408     4826\n\nFurther Distributional Parameters:\n    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nphi    51.89      7.48    38.30    68.06 1.00     6057     4992\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n\n    Estimate Q2.5 Q97.5\nNEC     1.54 1.50  1.57\n\n\nBayesian R2 estimates:\n   Estimate Est.Error Q2.5 Q97.5\nR2     0.96      0.00 0.96  0.97\n```\n\n\n:::\n:::\n\n\nThere is a lot here, so we'll go through each part.\n\nThe object is of class `bayesnecfit`, containing the `nec3param` model.\n`bayesnec` returns a `bayesnecfit` when one model is fitted, and a\n`bayesmanecfit` when a set is fitted.\n\nThe family is the beta distribution with an **identity link**. This will only mean\nsomething to those familiar with generalised linear models, as they are usually parameterised\nfor linear modelling. This is\ndeliberate and it is not the `brms` default, which for a beta response is the\nlogit. `bayesnec` uses the identity link for every family, so that the `top`,\n`bot` and `nec` parameters stay on the scale of the response and remain directly\ninterpretable. It matters if you ever compare a `bayesnec` fit against a `brm`\nmodel you have written yourself: unless you pass the link explicitly, the two\nare different models.\n\nThe `brms` formula that was fitted is printed. For `nec3param` it is a\nconstant `top` until the concentration reaches `nec`, followed by exponential\ndecay, with the switch implemented by `step()`. Module 3 sets out the equations.\n\n*Rhat* is a convergence diagnostic and should be close to 1. All three\nparameters here are at 1.00, and the effective sample sizes are in the\nthousands, both of which indicate the sampler explored the posterior properly.\n\nThe *NEC* estimate is given below the coefficients, as a median with a 95%\ncredible interval, and the Bayesian R² gives an indication of fit. The value here\nis high, as you would expect of a simulated example where the curve is\nwell-determined; real data rarely look this tidy.\n\n## The fitting record\n\n`bnec()` reports what it did as it goes, through messages. A knitted document or\na call wrapped in `suppressMessages()` keeps none of them, so the same\ninformation is stored on the fitted object and read back with `bnec_record()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec <- bnec_record(bnec_fit)\nnames(rec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"requested\"     \"attempted\"     \"excluded\"      \"substitutions\"\n```\n\n\n:::\n:::\n\n\n`requested` is the model or set you asked for, and it is divided exactly between\n`attempted` and `excluded`. An equation is excluded before fitting where it is\ninvalid for the family or the predictor, and `excluded` gives the reason for\neach. An equation that was attempted and then failed to fit stays in `attempted`,\nand module 4 covers how to find it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec$excluded\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] model  reason\n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n:::\n\n\nNothing was excluded here, because one model was requested and it is valid for a\nbeta response.\n\n`substitutions` records any value `bayesnec` altered because the family cannot\nrepresent it as recorded. A beta distribution is defined on the open interval\nbetween 0 and 1, so a response of exactly 0 or exactly 1 lies outside it.\n`bayesnec` replaces a zero with one tenth of the smallest non-zero value, and\nreduces a one by 0.001.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec$substitutions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n:::\n\n\n`NULL` means the response was fitted as recorded. Where it is not `NULL`, the\nanalysis was run on the substituted values and a methods section has to say so.\nModule 5 returns to this, because a series with several concentrations sitting at\na boundary is being modelled through the substitution rather than as measured.\n\n## Checking the sampler\n\n`brms` offers a range of diagnostics, and the `brms` documentation covers them\nfar better than this course can. Extract the underlying model with\n`pull_brmsfit()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrm_fit <- pull_brmsfit(bnec_fit)\n```\n:::\n\n\nPlotting it gives the marginal posterior of each parameter beside its trace:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(brm_fit)\n```\n\n::: {.cell-output-display}\n![](2Fitting-a-CR-model-using-bayesnec_files/figure-html/chains-1.png){width=672}\n:::\n:::\n\n\nRead the traces from left to right. Four chains that overlap, with no drift and\nno sustained excursion, indicate the chains have converged on the same\ndistribution. Chains that separate into bands, or wander, indicate they have\nnot, and the estimates should not be used.\n\nReading plots does not scale beyond a handful of parameters, and it will not\nscale at all to the model sets of module 4. `check_sampling()` puts the same\njudgement on three numbers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_sampling(bnec_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      model max_rhat  min_ess min_ess_ratio n_divergent failed\n1 nec3param 1.000764 3702.317     0.4627896           0  FALSE\n```\n\n\n:::\n:::\n\n\nEach is compared against a cutoff, and `failed` is `TRUE` where any of the three\nis missed.\n\n`max_rhat` is the largest R-hat over the parameters, and the cutoff is 1.01\nfollowing @Vehtari2021. R-hat compares the variation within each chain against\nthe variation between chains, so a value near 1 says the chains are describing\nthe same distribution.\n\n`min_ess` is the smallest effective sample size, and the cutoff is 400. Draws\nfrom a Markov chain are correlated, so 8,000 of them hold less information than\n8,000 independent draws would; the effective sample size is how many independent\ndraws they are worth. The floor of 400 is an absolute one, below which the R-hat\nand effective sample size estimates are themselves unreliable, and it corresponds\nto 100 draws per chain at the four chains `bnec()` fits. Decide on `min_ess` and\nread `min_ess_ratio` beside it: the ratio separates a model that cleared 400\nbecause a great many draws were taken from one that cleared it efficiently.\n\n`n_divergent` is the number of divergent transitions, and the cutoff is 10. A\ndivergent transition is recorded when the sampler's path through parameter space\ngoes numerically unstable, which happens where the posterior has curvature too\nsharp for the step size chosen during warm-up. This one is a `bayesnec`\nconvention rather than a published recommendation: Stan's own guidance is that\nany divergence means the sampler failed to explore the posterior, and the\nallowance of ten reflects that these non-linear models commonly produce a few\nnear a parameter boundary.\n\nThe two counts are absolute, so the number of retained draws changes what each\none demands, and it changes them in opposite directions. A longer run makes the\neffective sample size cutoff easier to clear and the divergence cutoff harder,\nbecause at an unchanged divergence rate more draws produce more divergences. A\nscreen result is therefore a property of the settings as much as of the model,\nand the settings belong in the write-up beside it. All three cutoffs are\narguments to `check_sampling()` and can be changed, which is a further reason to\nreport the values used.\n\n## Checking the fit against the data\n\nEverything above asks whether the sampler explored the posterior. None of it asks\nwhether the fitted model reproduces the data, and those are different questions:\na model can converge perfectly onto a description of the data that is wrong.\n\nThe distinction matters most for the *NSEC*, which module 3 introduces.\n`nsec()` sets its reference at a quantile of the posterior of the control mean,\nand the width of that posterior is the variability the fit estimated at the\ncontrol. A model simulating more variability at the control than the data show\nplaces that reference lower, so the curve crosses it further along and the\nreported concentration is higher and less protective. A model simulating less\nvariability returns a lower one. The direction is not known in advance, and no\nconvergence diagnostic reveals it.\n\nOne number for the whole fit will not detect this. Every family with a free\ndispersion parameter estimates that parameter from the same residuals such a\nnumber would summarise, so the parameter absorbs the discrepancy: the fit reports\nclose agreement overall while simulating the wrong spread at the concentrations\nthat determine the estimate. The check is therefore made within groups of the\npredictor, which is what `check_fit()` does.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf <- check_fit(bnec_fit)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The predictor has unreplicated values, so it has been cut into 10 bins\nto give check_fit something to group by. A bin is not a design point: pass\n`group` explicitly if the binning is not what you want, and treat any single\nrow as indicative.\n```\n\n\n:::\n\n```{.r .cell-code}\ncf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            group  n obs_mean sim_mean mean_ratio ppp_mean obs_sd sim_sd\n1  [0.0323,0.235] 10    0.901    0.890      1.013    0.239  0.041  0.041\n2   (0.235,0.378] 10    0.888    0.889      0.998    0.545  0.043  0.041\n3   (0.378,0.562] 10    0.874    0.889      0.983    0.845  0.025  0.041\n4   (0.562,0.726] 10    0.878    0.890      0.987    0.779  0.038  0.040\n5   (0.726,0.876] 10    0.916    0.890      1.028    0.027  0.034  0.041\n6    (0.876,1.17] 10    0.892    0.889      1.003    0.422  0.044  0.041\n7     (1.17,1.45] 10    0.883    0.890      0.992    0.691  0.034  0.041\n8     (1.45,1.72] 10    0.774    0.787      0.984    0.716  0.035  0.053\n9     (1.72,2.07] 10    0.539    0.509      1.059    0.111  0.057  0.066\n10    (2.07,3.22] 10    0.245    0.231      1.059    0.257  0.049  0.053\n   sd_ratio ppp_sd control\n1     0.996  0.504    TRUE\n2     1.060  0.423   FALSE\n3     0.609  0.945   FALSE\n4     0.944  0.580   FALSE\n5     0.837  0.734   FALSE\n6     1.062  0.398   FALSE\n7     0.835  0.741   FALSE\n8     0.663  0.933   FALSE\n9     0.870  0.700   FALSE\n10    0.934  0.600   FALSE\n\nOne or more groups show a posterior predictive p-value beyond \n[0.05, 0.95]. See ?check_fit.\n```\n\n\n:::\n:::\n\n\nThe predictor in `nec_data` is continuous, with a different value for every\nobservation, so there are no repeated concentrations to group by and\n`check_fit()` cuts the range into bins and says so. A bin is not a design point.\nOn a real dilution series the groups are the tested concentrations and no binning\nhappens.\n\nEach row compares a statistic computed from the observations in that group\nagainst the same statistic computed from data simulated by the fitted model.\n`mean_ratio` and `sd_ratio` are the observed values divided by the simulated\nones. `ppp_mean` and `ppp_sd` are posterior predictive p-values, each the\nproportion of simulated datasets in which the simulated statistic was at least as\nlarge as the observed one, so a value near 0.5 says the observed statistic sits\nin the middle of what the model produces and a value near 0 or 1 says it sits in\na tail.\n\nRead the p-values rather than the ratios, because a ratio says nothing about how\nwell determined it is. The `control` column flags the lowest value of the\npredictor, which is the group both `nsec()` and `ecx()` read their reference\nfrom, so that row is the one to look at first.\n\nFor this fit the control row agrees closely: a `sd_ratio` of 0.996 and a `ppp_sd`\nof 0.50, meaning the observed spread at the control is what the model produces.\nThe assumption the *NSEC* depends on most is supported at the concentration where\nit matters. Across the ten bins the means are reproduced throughout, with\n`mean_ratio` between 0.98 and 1.06, and one bin returns a `ppp_mean` of 0.03,\nwhich is what triggers the message. Ten observations is few for a group mean, and\nthe departure sits inside the 95% span in the plot below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cf)\n```\n\n::: {.cell-output-display}\n![](2Fitting-a-CR-model-using-bayesnec_files/figure-html/check-fit-plot-1.png){width=672}\n:::\n:::\n\n\nEach panel shows the observed statistic against the 95% span of what the model\nsimulates, with location and scale drawn separately because they fail\nindependently: a model can reproduce every group's mean while simulating far too\nmuch spread. A point outside its bar is a group the model does not reproduce.\nEvery posterior predictive p-value in the table above lies inside 0.025 to 0.975,\nso no point falls outside its bar in either panel, although the bin flagged by\nthe message sits close to the edge of one.\n\nThe message and the bars use different criteria, so they can disagree. The\nmessage flags a p-value outside 0.05 to 0.95 and the bars are the 95% span, which\nis 0.025 to 0.975. A group can fall beyond the first and inside the second. Read\nthe message as a prompt to look at that group rather than as a verdict on the\nfit.\n\nModule 4 applies both of these to a set of models rather than to one, and module\n7 shows what they contribute to a written analysis.\n\n## Inside the fitted object\n\nA `bayesnecfit` is a list holding the `brms` fit and a set of derived quantities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(bnec_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"fit\"             \"model\"           \"init\"            \"bayesnecformula\"\n [5] \"pred_vals\"       \"top\"             \"beta\"            \"ne\"             \n [9] \"f\"               \"bot\"             \"d\"               \"slope\"          \n[13] \"ec50\"            \"dispersion\"      \"predicted_y\"     \"residuals\"      \n[17] \"ne_posterior\"    \"ne_type\"        \n```\n\n\n:::\n:::\n\n\n`pred_vals` holds fitted values across the range of the predictor, which is what\nthe plotting methods use and what you would use for a custom figure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(bnec_fit$pred_vals$data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           x  Estimate      Q2.5     Q97.5\n1 0.03234801 0.8890196 0.8788117 0.8984557\n2 0.03553938 0.8890196 0.8788117 0.8984557\n3 0.03873074 0.8890196 0.8788117 0.8984557\n4 0.04192210 0.8890196 0.8788117 0.8984557\n5 0.04511347 0.8890196 0.8788117 0.8984557\n6 0.04830483 0.8890196 0.8788117 0.8984557\n```\n\n\n:::\n:::\n\n\nEvery fitted model holds a posterior for the no-effect estimate, in\n`ne_posterior`, with `ne_type` recording what kind of estimate it is. For models\nin the `nec` group this is the posterior of the `nec` parameter itself. For\nmodels in the `ecx` group, which have no threshold parameter, it is the\nposterior of the *NSEC* [@fisherfox2023]. Module 3 explains why those are\ndifferent things.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bnec_fit$ne_posterior,\n     main = \"\", xlab = \"No-effect concentration\", col = \"grey80\", border = \"white\")\n```\n\n::: {.cell-output-display}\n![](2Fitting-a-CR-model-using-bayesnec_files/figure-html/ne-posterior-1.png){width=672}\n:::\n:::\n\n\n## Plotting\n\n`plot()` extends the base method and `autoplot()` extends the `ggplot2` method.\nBoth take arguments controlling what is drawn; see `?autoplot.bayesnecfit`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(bnec_fit) +\n  ggplot2::xlab(\"Concentration\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](2Fitting-a-CR-model-using-bayesnec_files/figure-html/autoplot-1.png){width=672}\n:::\n:::\n\n\nThe result is a `ggplot` object, so it composes with `+` in the usual way, and\nmost `ggplot2` functions will work on it.\n\nBy default the plot is annotated with the fitted no-effect estimate and its 95%\ncredible interval, and labelled with the model that was fitted. The annotation\nis labelled NEC, because for a `nec3param` model the no-effect estimate is the *NEC*. We will discuss this in more \ndetail in module 3, and how these are handled in model averaging in module 4.\n\n## Toxicity estimates\n\nThree functions extract estimates from a fitted model: `ecx()`, `nec()` and\n`nsec()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\necx(bnec_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Q50     Q2.5    Q97.5 \n1.596696 1.564458 1.626689 \nattr(,\"resolution\")\n[1] 200\nattr(,\"ecx_val\")\n[1] 10\nattr(,\"toxicity_estimate\")\n[1] \"ecx\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnec(bnec_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Q50     Q2.5    Q97.5 \n1.535280 1.498376 1.569226 \nattr(,\"toxicity_estimate\")\n[1] \"nec\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnsec(bnec_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Q50     Q2.5    Q97.5 \n1.542506 1.501780 1.575577 \nattr(,\"resolution\")\n[1] 200\nattr(,\"sig_val\")\n[1] 0.01\nattr(,\"toxicity_estimate\")\n[1] \"nsec\"\nattr(,\"ecnsec_relativeP\")\n      50%      2.5%     97.5% \n1.3607025 0.2149438 2.3966669 \n```\n\n\n:::\n:::\n\n\nEach returns a median and a 95% probability interval by default, and each\nrecords how it was computed in the attributes of the returned object: `ecx()`\nreturns an **EC10** unless told otherwise, and `nsec()` uses a significance\nvalue of 0.01.\n\nFor this dataset the three estimates are close together, which happens when the\ncurve declines sharply from a well-defined threshold. They are not\ninterchangeable, and on other data they can differ. Module 3 covers what\neach of them measures and when each is appropriate.\n\n## The parameters of the curve\n\n`summary()` reports the toxicity estimate and the fit statistics, and for a\nsingle model the parameters are reachable through the underlying `brmsfit`.\n`curve_params()` returns them directly, and returns them for a model-averaged set\nas well, which nothing else does:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve_params(bnec_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      model wi dpar     link parameter  Estimate      Q2.5     Q97.5\n1 nec3param  1   mu identity       top 0.8890196 0.8788117 0.8984557\n2 nec3param  1   mu identity      beta 0.5423672 0.4261439 0.6548448\n3 nec3param  1   mu identity       nec 1.5352804 1.4983762 1.5692257\n```\n\n\n:::\n:::\n\n\nThese are the quantities the toxicity estimates are read from, and they belong in\na methods section beside them. `top` is the control level the curve is referenced\nto, `beta` is the decay rate, and `nec` is the threshold. A four-parameter\nequation would add `bot`, the lower asymptote.\n\n`xform` applies to `nec` and `ec50` and to no other parameter, because those two\nare measured on the predictor axis while `top`, `bot` and `beta` are levels of\nthe response or shape parameters, on which a transformation of the predictor has\nno meaning.\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "2Fitting-a-CR-model-using-bayesnec_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}