{
  "hash": "e75927b1aa56281a3d4d5aac5e29fe1f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Factor covariates and groupings\"\nsubtitle: \"Non-independence, grouped designs, and comparing curves between levels\"\nbibliography: bayesnec.bib\n---\n\n\n\n## Background\n\nConcentration-response designs are often more complicated than one response\nmeasured once at each of several concentrations. Replicates are housed together\nin tanks, a whole experiment is repeated on a second plate, fragments of one\ncoral colony are spread across the treatments, or the same test is run under\nseveral water chemistries. Each of those puts structure into the data that the\nmodules so far have ignored.\n\nThis module covers two different problems that the same syntax can address, and\nthe distinction between them decides almost everything else.\n\nA **grouping** is a factor whose levels are not of interest in themselves. Tanks,\nvials, plates and genotypes are groupings: you are not trying to estimate the\ntoxicity of tank 7, you are trying to stop the tank structure from making your\nintervals too narrow.\n\nA **factor covariate** is one whose levels *are* of interest. Water hardness,\ntemperature and exposure duration are factor covariates: the question is how\ntoxicity changes across them, and an estimate is wanted for each level.\n\n## Pseudo-replication and hierarchical effects\n\nMost ecotoxicological experiments contain grouping elements, such as tanks, vials\nor batches, that hold multiple measurements that cannot be treated as strictly\nindependent. These are pseudo-replicates. They are handled in ecological\nstatistics with mixed, hierarchical or random effects.\n\nIn concentration-response modelling they arise in two settings, and the\ndifference is fundamental to how each is handled.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/psuedoreps1.JPG){#fig-pr1 width=38%}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/psuedoreps2.JPG){#fig-pr2 width=48%}\n:::\n:::\n\n\n### Within-concentration groupings\n\nTank and vial effects. Several individual organisms are housed together, and the\ncontainer has a single concentration. The non-independence occurs *within* a\nconcentration and does not extend across the concentration range, because a tank\ncannot hold two concentrations at once.\n\nTo avoid the criticism of pseudo-replication, it is common practice to pool such\nobservations and model the group mean. That has two disadvantages. It discards\nthe within-group information, including the within-group variance. And where the\nnumber of observations per group varies, it weights every group mean equally even\nthough some rest on far fewer observations than others. In a growth experiment\nwith some mortality, the number of individuals measured differs between\ntreatments, and a group mean ignores that some groups hold a great deal of\ninformation and others very little.\n\n### Across-concentration groupings\n\nData also arise from repeated experiments, or from groupings within an experiment\nsuch as genotype or plate, that span the full range of the predictor. A\nwithin-group mean cannot be taken here, because a group is not at one\nconcentration.\n\nStrategies we have seen include ignoring the non-independence, fitting many\nindependent datasets and then aggregating the threshold estimates afterwards, or\nnormalising each experiment and ignoring the within-group correlation. Fitting\nseparately is undesirable in that each fit rests on fewer data and returns a\nwider interval, though it is sometimes the right answer for the reasons set out\nbelow. Normalising each experiment to its own control has the problems module 2\ndescribes.\n\n## An introduction to mixed modelling\n\nMixed effects models are common in ecology and are theoretically the right way to\nhandle non-independence in an experimental design. A full treatment is beyond\nthis course, and the short video below introduces the concepts non-technically.\nThe example is a field study, and the ideas transfer directly.\n\n{{< video https://www.youtube.com/watch?v=eFT8aIBaeGU >}}\n\n## Random effects for non-linear models\n\nOne distinction from the video matters here: the difference between a random\n**intercept** model and a random **slope and intercept** model.\n\nTwo things make this harder in a non-linear setting than in the linear models the\nvideo uses.\n\nA non-linear model does not have a slope and an intercept. It has `top`, `bot`,\n`nec`, `beta`, `ec50` and others, and a deviation can be placed on any of them.\n\nAnd `bayesnec` fits on an identity link, so the mean is on the scale of the\nresponse. Most of the families appropriate to this work are bounded at 0, at 1,\nor at both. A deviation that pushes the mean outside those bounds describes an\nimpossible response, which matters below.\n\nThe choice between the two follows directly from the distinction above.\nWithin-concentration groupings take a deviation on the intercept alone, because a\ntank sits at one concentration and the data contain no information about how the\nrest of the curve varies between tanks. Across-concentration groupings can take a\ndeviation on the whole curve, because each level spans the concentration range.\n\n## Group-level terms in `bayesnec`\n\nThree forms are available, and they differ in how much of the curve is allowed to\nvary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny ~ crf(x, model = \"nec4param\") + ogl(tank)        # the whole curve is displaced\ny ~ crf(x, model = \"nec4param\") + (top | tank)     # one named parameter varies\ny ~ crf(x, model = \"nec4param\") + pgl(plate)       # every parameter varies\n```\n:::\n\n\n`ogl()` adds an **o**ffset at the **g**roup **l**evel: the whole fitted curve is\ndisplaced up or down for each level, keeping its shape. `(par | group)` uses the\nordinary `brms` syntax to place a deviation on one named parameter. `pgl()`\nplaces a deviation on every **p**arameter of the equation at the **g**roup\n**l**evel, which fits a separate curve shape for each level.\n\n### Deviations that cannot leave the support\n\nThis is the part that differs from a grouped model fitted directly in `brms`, and\nit governs how any output below should be read.\n\n`brms` declares a group-level deviation unconstrained, which is correct for a\nGaussian response on an identity link and wrong for every other family here. A\ndeviation added to `top` on a response bounded by 0 and 1 can put the mean\nabove 1, which no beta distribution can represent, and Stan rejects the proposal\nand records a divergent transition. On a boundary-adjacent parameter, most\nproposals are rejected and the fit is unusable.\n\n`bayesnec` therefore applies the deviation **multiplicatively** wherever it acts\non the whole curve or on `top` or `bot`. On a 0 to 1 response the deviation\nscales the odds of the mean; on a positive response it scales the mean itself. A\ndeviation of zero leaves the curve exactly as it was, so `top`, `bot`, `nec` and\n`beta` keep their meanings, while the mean can no longer leave its support\nhowever far a proposal travels.\n\nThe difference is large. On a simulated beta-binomial design across three seeds,\nthe multiplicative form gave no divergent transitions at all, against 70 to 95\nper cent of transitions diverging under the additive form on the same data, and\nit sampled about twice as fast. On the `herbicide` data with a `nec4param`\nequation, a `(bot | herbicide)` term gave 51 divergent transitions of 2,000 under\nthe additive form at `adapt_delta = 0.95`, and none at Stan's default of 0.8\nunder the multiplicative one.\n\nA deviation on `nec`, `ec50`, `beta`, `slope`, `d` or `f` is still added\ndirectly, because none of those is bounded by the likelihood: `nec` and `ec50`\nare on the predictor axis, and the rest are estimated on a log scale.\n\nOne restriction remains. The transformation of the mean is defined only where the\nmean is provably inside its range, so `ogl()` is not used for `neclin`,\n`neclinhorme` and `ecxlin`, whose mean is unbounded below, nor for the hormesis\nequations, whose mean can reach or exceed 1.\n\n### Priors on the group-level terms\n\nA group-level term adds a standard deviation for each parameter it applies to,\nand `ogl()` adds an offset as well. Module 6 describes how `bayesnec` builds its\npriors, and these follow the same three-way split.\n\nA group-level standard deviation is given `student_t(3, 0, s)`, where *s* is one\ntenth of the observed range of the scale the parameter lives on: the response\nrange for `top`, `bot` and the `ogl` offset, the predictor range for `nec` and\n`ec50`, and a fixed value for the parameters estimated on a log scale. Under that\nprior there is a probability of about 0.39 that the group-level standard\ndeviation exceeds *s*, so it is weakly informative rather than tight.\n\nNote that *s* comes from the data rather than from the spread of the parameter's\nown prior. The two are different quantities, and deliberately so: a prior\nstandard deviation of 2.5 times that of the response is a reasonable statement of\nignorance about a *level*, and a poor one about the *deviation around* that\nlevel.\n\n## Deviation on the intercept\n\nThe common case in ecotoxicology is replicate tanks or vials holding several\norganisms each, which is the within-concentration grouping above.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/tank_offset.JPG){#fig-tanks width=60%}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/experimental_setup.JPG){#fig-experiment width=39%}\n:::\n:::\n\n\nThe example is an exposure of small *Acropora millepora* colonies, about 11 mm\nfragments, to 1-methylnaphthalene in replicated flow-through exposures. Partial\ncolony mortality was measured daily for seven days and again after a further\nseven days in clean seawater. Colour score is used here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolour <- read.csv(\"example_ogl.csv\") |>\n  mutate(y = Perc_change / 100,\n         groupvar = factor(paste(Replicate, Treatment, sep = \"_\")),\n         x = as.numeric(Treatment)) |>\n  na.omit()\nhead(colour)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Nominal Treatment Replicate Tile.colour T0_Colour_index T7_Colour_index\n1       0         0         A        red            6.280           4.841\n2       0         0         A       green           5.102           3.297\n3       0         0         A        grey           5.735           4.407\n4       0         0         A      purple           5.965           4.253\n5       0         0         A        blue           5.361           3.374\n6       0         0         B        red            6.557           4.919\n  Perc_change         y groupvar x\n1    22.91401 0.2291401      A_0 0\n2    35.37828 0.3537828      A_0 0\n3    23.15606 0.2315606      A_0 0\n4    28.70075 0.2870075      A_0 0\n5    37.06398 0.3706398      A_0 0\n6    24.98094 0.2498094      B_0 0\n```\n\n\n:::\n:::\n\n\nThe response is the proportional change in colour index and the predictor is the\ntreatment concentration. The grouping combines the replicate and the treatment,\nso that each container is uniquely identified; replicates are commonly labelled 1\nto 5 within each treatment and are not unique across treatments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(colour, aes(x, y, colour = groupvar)) +\n  geom_jitter(show.legend = FALSE) +\n  labs(x = \"Concentration\", y = \"Proportional change in colour index\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](8Factor_covariates_and_groupings_files/figure-html/fig-ogl-raw-1.png){#fig-ogl-raw width=672}\n:::\n:::\n\n\nA deviation on the intercept is what suits this design. The same fit is made with\nand without it, so the two can be compared.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_plain <- bnec(y ~ crf(x, model = \"ecxlin\"), data = colour, seed = 70)\nfit_ogl   <- bnec(y ~ crf(x, model = \"ecxlin\") + ogl(groupvar),\n                  data = colour, seed = 70)\n```\n:::\n\n\n`ecxlin` is used rather than a full model set, to keep the example to two fits.\nIt is a linear decline, so this is a simple linear regression with a group-level\noffset.\n\n`ogl(groupvar)` is preferred here to `(top | groupvar)`. Both displace the curve,\nand the first states that intention directly and is applied on a scale the mean\ncannot leave.\n\n\n::: {#tbl-ogl-compare .cell tbl-cap='The intercept-only deviation compared against the same equation fitted without it.'}\n\n```{.r .cell-code}\nread.csv(\"data/grouping_ogl_compare.csv\") |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|fit           | weight| elpd_diff| se_diff|\n|:-------------|------:|---------:|-------:|\n|no group term |  0.178|      -2.4|     2.2|\n|ogl(groupvar) |  0.822|       0.0|     0.0|\n\n\n:::\n:::\n\n\nThe comparison is by leave-one-out cross-validation, as module 4 describes.\nWeight on the grouped fit is evidence that the container structure is real and\nthat ignoring it would have produced intervals narrower than the data support.\n\n## Deviation on every parameter\n\nWhere a grouping spans the whole concentration range, the curve itself can vary\nbetween levels, and `pgl()` fits that.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](images/microtox.JPG){#fig-microtox width=40%}\n:::\n:::\n\n\nThe example is a bioluminescent bacterial assay developed at AIMS for tropical\nmarine conditions [@luter2025]. The whole concentration series runs on a single\nplate, and the plate is repeated across several experiments on the same\ncontaminant, so each level of the grouping covers the full predictor range.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplates <- read.csv(\"example_pgl.csv\")\nhead(plates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  X     log_x           plateRep         y\n1 1 -2.407946 Lum_27C_rep1_qtoxB 0.8410503\n2 2 -2.407946 Lum_27C_rep1_qtoxB 0.8401287\n3 3 -2.407946 Lum_27C_rep1_qtoxB 0.9221791\n4 4 -2.407946 Lum_27C_rep1_qtoxB 0.9521653\n5 5 -1.714798 Lum_27C_rep1_qtoxB 0.8128610\n6 6 -1.714798 Lum_27C_rep1_qtoxB 0.8927248\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(plates, aes(log_x, y, colour = plateRep)) +\n  geom_jitter(show.legend = FALSE) +\n  labs(x = \"Log concentration\", y = \"Response\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](8Factor_covariates_and_groupings_files/figure-html/fig-pgl-raw-1.png){#fig-pgl-raw width=672}\n:::\n:::\n\n\nThe plot shows clear differences between plates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_plain <- bnec(y ~ crf(log_x, model = \"nechorme\"), data = plates, seed = 70)\nfit_pgl   <- bnec(y ~ crf(log_x, model = \"nechorme\") + pgl(plateRep),\n                  data = plates, seed = 70)\n```\n:::\n\n\n`nechorme` is used because the plot shows an initial rise before the decline,\nwhich is hormesis. Expect the fitting messages to look alarming: these models are\ncomplex and finding initial values that do not error takes `bayesnec` several\nattempts.\n\n\n::: {#tbl-pgl-compare .cell tbl-cap='The all-parameter deviation compared against the same equation fitted without it.'}\n\n```{.r .cell-code}\nread.csv(\"data/grouping_pgl_compare.csv\") |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|fit           | weight| elpd_diff| se_diff|\n|:-------------|------:|---------:|-------:|\n|no group term |      0|     -56.3|    11.5|\n|pgl(plateRep) |      1|       0.0|     0.0|\n\n\n:::\n:::\n\n\nTwo things to read from the fits themselves. The credible bands of the grouped\nfit are far wider than those of the fit that assumes independence, which is the\npoint of fitting it: the narrow bands were an artefact of treating 60\nobservations from six plates as 60 independent ones. And the convergence\ndiagnostics for the group-level standard deviations are the ones to check\nhardest, because those parameters are the least well determined in the model.\n\n## The number of levels a deviation needs\n\nA group-level standard deviation is estimated from the variation between levels,\nso it needs levels to estimate it from. The consensus is that five should be\ntreated as a minimum, and Stan may want more.\n\nThat minimum is easy to reach for tank effects, where there are usually several\ntanks per concentration and often twenty or thirty in total. It is rarely reached\nfor across-concentration groupings, where six plates or four genotypes is a\ntypical design. This is the practical reason to consider the alternative below,\nrather than a statistical preference for it.\n\n## Factor interaction covariates\n\nWhere the levels are of interest in themselves, a deviation is the wrong tool\nentirely. A group-level term marginalises over the levels and returns one curve;\na factor covariate asks for a curve, and a toxicity estimate, for each level.\n\n`bnec()` does not support an interaction with a fixed factor inside its own\nformula. Adding an interaction term to a single non-linear equation is\nstraightforward and may be added in a future release. Supporting it across the\nwhole model set is not, because the functional form of the response may itself\nchange between levels, and defining every non-linear combination at every level\nis a much larger problem.\n\nTwo routes are available in the meantime, and they answer different questions.\n\n### Fitting each level separately\n\n`bnec_group()` fits the model set independently within each level of a factor.\nEach level gets its own model averaging, so the *shape* of the curve is free to\ndiffer between levels, which is the assumption a single interaction model cannot\nmake.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_hardness <- bnec_group(y ~ crf(x, model = \"decline\"),\n                           data = zinc, group_var = \"hardness\", seed = 70)\n```\n:::\n\n\nThis is what the earlier version of this module did with a hand-written loop over\n`unique(dat$hardness)`. `bnec_group()` does the same thing and adds three things\na loop does not. It gives each level its own seed, realised in the calling\nsession and stored on the returned object as `level_seeds`, so a grouped call\nrepeats exactly. It records which models failed at which level. And it can use a\n`future` plan across either the levels or the models within a level, choosing\nwhichever arrangement takes fewer rounds and reporting which it took; module 4\ncovers the plans.\n\nThe price is run time. A set of fourteen equations across three levels is\nforty-two fits, and this is the point at which fitting stops being something done\nat render time.\n\n### An interaction on a single equation\n\nThe alternative estimates the parameters of a *single* equation separately for\neach level, which is fewer parameters than a deviation on each and does not need\nfive levels to work. `bayesnec` is used to choose the equation and to build the\npriors, and `brms` fits the interaction directly.\n\nThe case study is a subset of the data behind\n[doi:10.1039/D2EM00063F](https://doi.org/10.1039/D2EM00063F), describing zinc\ntoxicity to a freshwater micro-alga at three water hardnesses, at a fixed pH of\n8.3. The response is population growth rate as a percentage of the control growth\nrate for each experiment. The data were supplied by Gwil Price.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzinc <- read.csv(\"example_fi.csv\") |>\n  na.omit() |>\n  mutate(y = (Pcon / max(Pcon) + 0.01) * 0.99,\n         x = log(Mean.Zn),\n         hardness = factor(round(Hardness))) |>\n  select(x, y, hardness)\n\nrange(zinc$y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0099 0.9999\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(zinc$hardness)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  5  30 406 \n 50  51  50 \n```\n\n\n:::\n:::\n\n\nTwo preparation decisions are worth naming, because module 2 argues against one\nof them.\n\nThe concentrations span five orders of magnitude and are logged, which is the\ndecision module 2 covers.\n\nThe response is divided by the maximum observed value and then shifted off 0 and\n1. This is exactly the practice module 2 recommends against, and it is done here\nbecause these are the data as supplied: the response is already a percentage of\neach experiment's own control, so the sampling variability of that control has\nalready been discarded before the analysis began. Where you have the underlying\ngrowth rates, model those instead and read the decline from the fitted control.\nThe shift off the boundaries is needed because `brms` is called directly below\nand does not make the adjustment `bnec()` makes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(zinc, aes(x = x, y = y, colour = hardness)) +\n  geom_jitter() +\n  labs(x = \"Log zinc concentration\", y = \"Response\", colour = \"Hardness\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](8Factor_covariates_and_groupings_files/figure-html/fig-fi-raw-1.png){#fig-fi-raw width=672}\n:::\n:::\n\n\nThe effect of hardness on toxicity is clear.\n\nWhich equation to use is not, so the whole `decline` set is fitted to the pooled\ndata and the best-supported equation taken from it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_all <- bnec(y ~ crf(x, model = \"decline\"), data = zinc, seed = 70)\nbest <- pull_best(fit_all)\n```\n:::\n\n\n\n::: {#tbl-fi-weights .cell tbl-cap='Model weights for the pooled zinc data.'}\n\n```{.r .cell-code}\nread.csv(\"data/grouping_zinc_weights.csv\") |>\n  mutate(wi = round(wi, 3)) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|model     |      waic|    wi|\n|:---------|---------:|-----:|\n|nec3param | -254.2199| 0.000|\n|nec4param | -251.3739| 0.000|\n|ecxwb1    | -306.1118| 0.902|\n|ecxwb1p3  | -293.8985| 0.093|\n|ecxwb2p3  | -281.6038| 0.001|\n|ecxll3    | -293.3476| 0.003|\n\n\n:::\n:::\n\n\n`pull_best()`, from module 4, returns the highest-weighted equation and reports\nthe weight alongside the number of candidates, which is what says whether the\nselection means anything. On these data it returns `ecxwb1` with a weight of\n0.902 out of six candidates, so one equation holds almost all the weight and the\nrest of this section is about that equation rather than about the set.\n\nThe `brms` formula and the priors are then read off that fit:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest_brms <- pull_brmsfit(best)\nbest_brms$formula\npriors <- brms::prior_summary(best_brms)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The right-hand side of each parameter line is what changes: `~ 1` fits one\n# value for every level, and `~ hardness` fits one per level.\nbf_plain <- brms::bf(\n  y ~ bot + (top - bot) * exp(-exp(exp(beta) * (x - ec50))),\n  bot + ec50 + top + beta ~ 1, nl = TRUE)\n\nbf_inter <- brms::bf(\n  y ~ bot + (top - bot) * exp(-exp(exp(beta) * (x - ec50))),\n  bot + ec50 + top + beta ~ hardness, nl = TRUE)\n```\n:::\n\n\nThe priors need one change before the interaction can be fitted, and it is the\nstep most easily missed. `bayesnec` writes each parameter's prior with no `coef`,\nso it applies to every population-level coefficient belonging to that parameter.\nUnder `~ 1` that is the intercept alone, and the prior is exactly what was\nintended. Under `~ hardness` it is the intercept plus one coefficient per\nnon-reference level, and each of those would take a prior written to describe\nthe parameter's own value rather than a difference between levels. For `ecxwb1`\nthat puts `beta(5, 2)` on the `top` differences, and a beta density is zero\noutside (0, 1), so no level could have a `top` below the reference level's.\n\nSet the intercept and the level differences separately. The intercept keeps\nwhatever `bayesnec` chose; the differences are centred on zero, meaning no\ndifference between levels, and scaled to what the parameter measures:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninter_priors <- c(\n  # the intercept, as bayesnec set it\n  prior(beta(5, 2), nlpar = \"top\",  coef = \"Intercept\"),\n  prior(beta(2, 5), nlpar = \"bot\",  coef = \"Intercept\"),\n  prior(normal(2.387, 24.803), nlpar = \"ec50\", coef = \"Intercept\"),\n  prior(normal(0, 5), nlpar = \"beta\", coef = \"Intercept\"),\n  # the differences between hardness levels\n  prior(normal(0, 0.25), nlpar = \"top\"),   # a proportion\n  prior(normal(0, 0.1),  nlpar = \"bot\"),   # a proportion, near zero\n  prior(normal(0, 2),    nlpar = \"ec50\"),  # the log predictor scale\n  prior(normal(0, 2),    nlpar = \"beta\"))  # a log slope\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_plain <- brms::brm(bf_plain, data = zinc, family = Beta(link = \"identity\"),\n                       prior = priors, iter = 5000, seed = 700,\n                       save_pars = brms::save_pars(all = TRUE))\n```\n:::\n\n\n`fit_plain` keeps the priors as read, because under `~ 1` they are already\nright. Only the interaction needs the replacement, and it needs one more thing:\nsomewhere to start. Each parameter starts at its pooled estimate and each level\ndifference starts at zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfx <- brms::fixef(fit_plain)\ninit_fun <- function() {\n  list(b_bot  = as.array(c(fx[\"bot_Intercept\",  \"Estimate\"], 0, 0)),\n       b_ec50 = as.array(c(fx[\"ec50_Intercept\", \"Estimate\"], 0, 0)),\n       b_top  = as.array(c(fx[\"top_Intercept\",  \"Estimate\"], 0, 0)),\n       b_beta = as.array(c(fx[\"beta_Intercept\", \"Estimate\"], 0, 0)))\n}\n```\n:::\n\n\nLeave that out and three of the four chains fail before they start. The Beta\nfamily with an identity link requires the fitted mean to lie inside (0, 1) at\nevery observation, and a randomly chosen starting point does not. `bnec()`\nsupplies starting values of its own, which is why the model set fitted earlier\ngave no trouble; a formula handed straight to `brm()` does not inherit them.\n`brms` returns whichever chains survived, so check how many there are rather\nthan reading the summary and assuming four.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_inter <- brms::brm(bf_inter, data = zinc, family = Beta(link = \"identity\"),\n                       prior = inter_priors, iter = 5000, seed = 700,\n                       init = init_fun, control = list(adapt_delta = 0.99),\n                       save_pars = brms::save_pars(all = TRUE))\n\nposterior::nchains(brms::as_draws_array(fit_inter))\n```\n:::\n\n\nAll four chains finish, and the largest rhat is 1.0017. The fit still reports\n323 divergent transitions in 10000 draws, well above the threshold of ten that\n`check_sampling()` applies in module 4. Raising `adapt_delta` further does not\nremove them, and the estimates are the same with and without the ones that\nremain. `bot` is estimated at 0.025, close to the boundary the identity link\nimposes, and that is where the divergences arise. Fitting the levels separately,\nbelow, does not meet the problem at all.\n\nWhether the interaction is supported at all is the first thing to read, and\nleave-one-out weights answer it on the same footing module 4 used:\n\n\n::: {#tbl-fi-interaction .cell tbl-cap='The interaction model against the same equation fitted without it.'}\n\n```{.r .cell-code}\nread.csv(\"data/grouping_zinc_model_weights.csv\") |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|fit                  | weight|\n|:--------------------|------:|\n|no interaction       |  0.018|\n|hardness interaction |  0.982|\n\n\n:::\n:::\n\n\nWeight on the interaction says the levels differ by more than one shared curve\ndescribes; weight on the simpler fit says one curve is enough. Here the\ninteraction takes 0.982 against 0.018, so hardness changes the response by more\nthan a single curve accounts for.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read.csv() returns hardness as an integer, because the levels are numbers.\n# The observations carry it as a factor, and ggplot cannot put a continuous and\n# a discrete scale on one aesthetic, so it is made a factor here to match.\npreds <- read.csv(\"data/grouping_zinc_preds.csv\") |>\n  mutate(hardness = factor(hardness, levels = levels(zinc$hardness)))\n\nggplot(preds) +\n  geom_ribbon(aes(x = x, ymin = Q2.5, ymax = Q97.5, fill = hardness),\n              alpha = 0.3) +\n  geom_line(aes(x = x, y = Estimate, colour = hardness)) +\n  geom_jitter(data = zinc, aes(x = x, y = y, fill = hardness),\n              pch = 21, size = 2, alpha = 0.6) +\n  labs(x = \"Log zinc concentration\", y = \"Response\",\n       colour = \"Hardness\", fill = \"Hardness\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![The interaction model, one curve per hardness level, with the observations.](8Factor_covariates_and_groupings_files/figure-html/fig-fi-curves-1.png){#fig-fi-curves width=672}\n:::\n:::\n\n\nThat figure shows what this route assumes, and it is the reason the two\napproaches are both presented. Fitting an interaction this way holds the\nfunctional form the same at every level and lets only the parameter values\ndiffer, so a level whose response has a different shape cannot be accommodated.\n\nOn these data that assumption is tenable. Residuals about each level's own curve\nhave a root mean square of 0.068, 0.052 and 0.057 at hardness 5, 30 and 406, on a\nresponse scaled to roughly 0 to 1, so no level stands out as badly described and\nit is the lowest hardness rather than the highest that fits least well.\n\nWhere the shape does differ between levels, fit them separately with\n`bnec_group()`, which lets the shape differ, and compare the results as below. The alternative, generalised\nadditive models with a factor interaction term, is outside this course.\n\n## Comparing levels\n\n`compare_posterior()` takes a named list of fits and returns the posteriors on a\ncommon footing, the differences between them, and the probability that one\nexceeds another. Module 7 uses it across substances; here it is used across\nlevels of a factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_comp <- compare_posterior(fit_hardness, comparison = \"n(s)ec\")\npost_fitted <- compare_posterior(fit_hardness, comparison = \"fitted\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compare_posterior() returns the level names as data frame column names, which\n# R prefixes with \"X\" where they begin with a digit. Stripped here so the legend\n# reads as the hardness values the experiment used.\nread.csv(\"data/grouping_zinc_ne_posterior.csv\") |>\n  mutate(model = sub(\"^X\", \"\", model)) |>\n  ggplot(aes(x = value, group = model, colour = model, fill = model)) +\n  geom_density(alpha = 0.3) +\n  labs(x = \"Log zinc concentration\", y = \"Density\",\n       colour = \"Hardness\", fill = \"Hardness\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Posterior densities of the no-effect estimate at each hardness.](8Factor_covariates_and_groupings_files/figure-html/fig-compare-nec-1.png){#fig-compare-nec width=672}\n:::\n:::\n\n\n\n::: {#tbl-compare-prob .cell tbl-cap='Probability that the no-effect estimate at one hardness is lower than at another.'}\n\n```{.r .cell-code}\nread.csv(\"data/grouping_zinc_prob_diff.csv\") |>\n  separate(col = comparison, into = c(\"hardness\", \"against\"), sep = \"-\") |>\n  pivot_wider(names_from = against, values_from = prob) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|hardness |        30|       406|\n|:--------|---------:|---------:|\n|5        | 0.3179545| 0.0145036|\n|30       |        NA| 0.0165041|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread.csv(\"data/grouping_zinc_diff.csv\") |>\n  ggplot() +\n  geom_hline(yintercept = 0, linetype = 2, colour = \"grey50\") +\n  geom_ribbon(aes(x = x, ymin = diff.Q2.5, ymax = diff.Q97.5,\n                  fill = comparison), alpha = 0.3) +\n  geom_line(aes(x = x, y = diff.Estimate, colour = comparison)) +\n  labs(x = \"Log zinc concentration\", y = \"Posterior difference\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Difference between the fitted curves across the concentration range, with the 95% credible interval of each difference.](8Factor_covariates_and_groupings_files/figure-html/fig-compare-fitted-1.png){#fig-compare-fitted width=672}\n:::\n:::\n\n\nA difference band that excludes zero over part of the concentration range says\nthe curves differ there, and one that contains zero throughout says they do not.\nThis answers the question a factor covariate is asked for, as a probability\ncomputed from the draws rather than as a significance test, and it does so\nwithout requiring the levels to share a curve shape.\n\n## Provenance of these fits\n\nNone of the fitting above runs when this page is built. The `bnec_group()` call\nalone is dozens of fits, and the interaction models are slow enough that a\nparticipant would be waiting rather than learning.\n\nThey are produced by `scripts/generate_grouping_fits.R`, which writes the compact\nresults this module reads into `vignettes/data/`. The code shown is the code that\nwas run.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerated by scripts/generate_grouping_fits.R\ndate: 2026-09-17 08:51:44\nelapsed: 1.9 mins\nseed: 70\nR: 4.6.1\nbayesnec: 2.1.3.35\nbrms: 2.23.0\ncmdstanr: 0.9.0\npooled zinc set: decline, 14 equations\nbest pooled equation: ecxwb1\nhardness levels: 5, 30, 406\nsampler screen: rhat <= 1.01, ess >= 400, divergences <= 10\n```\n\n\n:::\n:::\n\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "8Factor_covariates_and_groupings_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}