# ---------------------------------------------------------------------------
# Fits the seven herbicide concentration-response curves used by module 7 and
# writes the compact artefacts that module reads.
#
# Seven herbicides by the fourteen equations of the `decline` set is 98 model
# fits and takes hours. It is therefore run deliberately, not at render time,
# and only its outputs are committed. The fitted objects themselves are far too
# large for a public repository: the equivalent from 2023 was 451 MB.
#
# Run with:
#   Rscript scripts/generate_herbicide_fits.R
# ---------------------------------------------------------------------------

suppressMessages({
  library(bayesnec)
  library(dplyr)
  library(purrr)
  library(tidyr)
})

options(mc.cores = 4)
out_dir <- "vignettes/data"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

SEED <- 17

message("fitting: ", format(Sys.time()))
t0 <- Sys.time()

data(herbicide)

# The predictor is logged before fitting, as in the published analysis. Every
# estimate returned is therefore on the log scale and is back-transformed with
# xform = exp where it is reported.
manecfit <- herbicide |>
  mutate(concentration = log(concentration)) |>
  split(f = ~ herbicide) |>
  map(function(x) {
    bnec(fvfm ~ crf(concentration, model = "decline"), data = x, seed = SEED)
  })

message("fitted in ", format(round(difftime(Sys.time(), t0), 1)))

# --- drop any model that failed the convergence criterion --------------------
# rhat() on a bayesmanecfit returns a list keyed by model name, each element
# holding rhat_vals and a logical `failed`. The 2023 version of module 7 used
# `rhat(x)$failed`, which is NULL on that structure, so its cleaning step
# silently dropped nothing. The default cutoff is 1.01, not the 1.05 that module
# stated.
failed_models <- function(fit) {
  r <- rhat(fit)
  names(which(vapply(r, function(z) isTRUE(z$failed), logical(1))))
}

failed <- imap_dfr(manecfit, function(fit, nm) {
  bad <- failed_models(fit)
  if (length(bad) == 0) return(NULL)
  data.frame(herbicide = nm, model = bad)
})
write.csv(failed, file.path(out_dir, "herbicide_rhat_failed.csv"),
          row.names = FALSE)

cleaned_fits <- map(manecfit, function(fit) {
  bad <- failed_models(fit)
  if (length(bad) > 0) amend(fit, drop = bad) else fit
})

# --- model weights ----------------------------------------------------------
imap_dfr(cleaned_fits, function(fit, nm) {
  fit$mod_stats |>
    select(model, waic, wi) |>
    mutate(herbicide = nm, .before = 1)
}) |>
  write.csv(file.path(out_dir, "herbicide_mod_stats.csv"), row.names = FALSE)

# --- fitted curves, for the panel figure ------------------------------------
# The predictor is returned on the fitted (log) scale and is exponentiated here,
# so the module plots concentrations directly.
imap_dfr(cleaned_fits, function(fit, nm) {
  fit$w_pred_vals$data |>
    mutate(herbicide = nm, concentration = exp(x), .before = 1) |>
    select(herbicide, concentration, Estimate, Q2.5, Q97.5)
}) |>
  write.csv(file.path(out_dir, "herbicide_pred_vals.csv"), row.names = FALSE)

# --- the observations, so the figure can show the data ----------------------
herbicide |>
  select(herbicide, concentration, fvfm) |>
  write.csv(file.path(out_dir, "herbicide_observations.csv"), row.names = FALSE)

# --- no-effect posteriors and their pairwise comparison ---------------------
post_comp <- compare_posterior(cleaned_fits, comparison = "nec")

post_comp$posterior_data |>
  mutate(concentration = exp(value)) |>
  select(model, value, concentration) |>
  write.csv(file.path(out_dir, "herbicide_ne_posterior.csv"), row.names = FALSE)

write.csv(post_comp$prob_diff,
          file.path(out_dir, "herbicide_prob_diff.csv"), row.names = FALSE)

# --- summarised estimates ---------------------------------------------------
imap_dfr(cleaned_fits, function(fit, nm) {
  q <- quantile(fit$w_ne_posterior, probs = c(0.5, 0.025, 0.975))
  data.frame(herbicide = nm,
             log_estimate = q[[1]], log_lower = q[[2]], log_upper = q[[3]],
             estimate = exp(q[[1]]), lower = exp(q[[2]]), upper = exp(q[[3]]))
}) |>
  write.csv(file.path(out_dir, "herbicide_estimates.csv"), row.names = FALSE)

# --- provenance -------------------------------------------------------------
writeLines(c(
  "Generated by scripts/generate_herbicide_fits.R",
  paste("date:", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
  paste("elapsed:", format(round(difftime(Sys.time(), t0), 1))),
  paste("seed:", SEED),
  paste("R:", getRversion()),
  paste("bayesnec:", as.character(packageVersion("bayesnec"))),
  paste("brms:", as.character(packageVersion("brms"))),
  paste("cmdstanr:", as.character(packageVersion("cmdstanr"))),
  paste("model set: decline,", length(models()$decline), "equations"),
  paste("herbicides:", paste(names(cleaned_fits), collapse = ", "))
), file.path(out_dir, "herbicide_provenance.txt"))

message("done: ", format(Sys.time()))
message("wrote to ", out_dir)
