# ---------------------------------------------------------------------------
# Rebuilds vignettes/fits/PROVENANCE.txt from the objects actually on disk.
#
# That file travels inside the distributed archive and is the only record a
# participant receives of what produced the fits they are loading. It was kept
# by hand until 2026-09-22 and had drifted badly: it listed 26 objects, named
# four that no longer existed and omitted seven that did, because three
# different scripts write into vignettes/fits/ and each revision changed the
# set.
#
# Generating it removes the drift. Every fitted object records the versions it
# was built under in its brmsfit `version` slot, so those are read from the
# objects rather than from the session, and are correct even for an object
# fitted weeks earlier. The bayesnec version is not stored on the object, so
# the modification date is reported instead and the session's own version is
# recorded separately.
#
# Run after any rebuild of the fits, before scripts/bundle_fits.R:
#   Rscript scripts/write_provenance.R
# ---------------------------------------------------------------------------

suppressMessages(library(bayesnec))

fit_dir <- file.path("vignettes", "fits")
stopifnot(dir.exists(fit_dir))

`%||%` <- function(a, b) if (is.null(a)) b else a

# The brmsfit inside a fit of any of the classes these scripts save, or NULL.
#
# pull_brmsfit() is not used. On a bayesmanecfit it returns a character vector
# rather than a fit, and a `prebayesnecfit` -- which is what a set holds in
# `mod_fits` -- carries its brmsfit in `$fit` directly. Reaching for the slot
# is what works across all three classes.
first_brmsfit <- function(x) {
  if (inherits(x, c("bayesnechurdlefit", "bayesnecjointfit"))) x <- x$growth
  if (inherits(x, "bayesmanecfit")) x <- x$mod_fits[[1]]
  b <- if (inherits(x, "brmsfit")) x else x$fit
  if (inherits(b, "brmsfit")) b else NULL
}

versions_of <- function(x) {
  v <- first_brmsfit(x)$version
  if (is.null(v)) return(c(brms = NA_character_, cmdstan = NA_character_))
  c(brms = as.character(v$brms %||% NA),
    cmdstan = as.character(v$cmdstan %||% NA))
}

# print() wraps at getOption("width"), which would split the table across
# several blocks in the written file.
withr_width <- function(w, expr) {
  old <- options(width = w)
  on.exit(options(old), add = TRUE)
  force(expr)
}

rows <- list()
for (f in sort(list.files(fit_dir, pattern = "\\.RData$"))) {
  path <- file.path(fit_dir, f)
  e <- new.env()
  nms <- load(path, envir = e)
  x <- get(nms[1], envir = e)
  v <- versions_of(x)
  rows[[length(rows) + 1L]] <- data.frame(
    file = f,
    object = nms[1],
    class = class(x)[1],
    fitted = format(file.mtime(path), "%Y-%m-%d"),
    brms = unname(v["brms"]),
    cmdstan = unname(v["cmdstan"]),
    MB = round(file.size(path) / 1024^2, 1),
    stringsAsFactors = FALSE)
  rm(e)
}
tab <- do.call(rbind, rows)

# Which script owns each object, so a rebuild can be aimed at the right one.
# Every fit is made by exactly one of the three, by module number.
owner <- function(f) {
  if (grepl("^m5_", f)) "scripts/generate_module5_fits.R"
  else if (grepl("^m7_", f)) "scripts/generate_module7_walkthrough.R"
  else "scripts/generate_taught_fits.R"
}
tab$built_by <- vapply(tab$file, owner, character(1))

lines <- c(
  "Generated by scripts/write_provenance.R. Do not edit by hand.",
  paste("written:", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
  "",
  paste("objects:", nrow(tab)),
  paste("total MB:", round(sum(tab$MB), 1)),
  "",
  "The versions below are read from each object's own brmsfit record, so they",
  "are what fitted that object rather than what is installed now. The bayesnec",
  "version is not stored on a fitted object; the date each object was written",
  "is given instead, and the session that generated this file reports:",
  paste("  bayesnec:", as.character(packageVersion("bayesnec"))),
  paste("  R:       ", as.character(getRversion())),
  "",
  "Formula environments are reset after fitting; see the note in",
  "scripts/generate_taught_fits.R for why and what it is worth.",
  "",
  strrep("-", 100),
  withr_width(100, capture.output(
    print(tab[, c("file", "object", "class", "fitted",
                  "brms", "cmdstan", "MB")], row.names = FALSE))),
  strrep("-", 100),
  "",
  "Built by:",
  unlist(lapply(sort(unique(tab$built_by)), function(s) {
    c(paste0("  ", s), paste0("    ", paste(tab$file[tab$built_by == s], collapse = " ")))
  }))
)

writeLines(lines, file.path(fit_dir, "PROVENANCE.txt"))
message(nrow(tab), " objects recorded in ", file.path(fit_dir, "PROVENANCE.txt"))
