<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Response data and statistical distributions – Concentration-response modelling (in development)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../vignettes/6Priors_and_Bayesian_inference.html" rel="next">
<link href="../vignettes/4Model_averaging_and_multimodel_inference.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8317e07c38846ddd92fb20fa66b3c33c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Concentration-response modelling (in development)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/0Software-setup.html"> 
<span class="menu-text">Setup</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/1Software-stack.html"> 
<span class="menu-text">Modules</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/open-AIMS/cr_modelling_training/issues"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">Questions and corrections</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/1Software-stack.html">Modules</a></li><li class="breadcrumb-item"><a href="../vignettes/5Response_data_and_statistical_distributions.html">5. Response data and distributions</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Before you start</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/0Software-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Software setup</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Modules</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/1Software-stack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. The software stack</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/2Fitting-a-CR-model-using-bayesnec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Fitting a single model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/3Toxicity_estimation_and_available_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Toxicity estimation and the model set</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/4Model_averaging_and_multimodel_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Model averaging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/5Response_data_and_statistical_distributions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">5. Response data and distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/6Priors_and_Bayesian_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Priors and Bayesian inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/7Example_case_study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. A worked case study</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/8Factor_covariates_and_groupings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Factor covariates and groupings</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Frequentist comparison</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/drc-reference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting the same models with drc</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#generalised-modelling" id="toc-generalised-modelling" class="nav-link" data-scroll-target="#generalised-modelling">Generalised modelling</a></li>
  <li><a href="#families-available-in-brms" id="toc-families-available-in-brms" class="nav-link" data-scroll-target="#families-available-in-brms">Families available in <code>brms</code></a></li>
  <li><a href="#link-functions" id="toc-link-functions" class="nav-link" data-scroll-target="#link-functions">Link functions</a></li>
  <li><a href="#families-implemented-in-bayesnec" id="toc-families-implemented-in-bayesnec" class="nav-link" data-scroll-target="#families-implemented-in-bayesnec">Families implemented in <code>bayesnec</code></a></li>
  <li><a href="#default-behaviour" id="toc-default-behaviour" class="nav-link" data-scroll-target="#default-behaviour">Default behaviour</a></li>
  <li><a href="#binomial" id="toc-binomial" class="nav-link" data-scroll-target="#binomial">Binomial</a>
  <ul class="collapse">
  <li><a href="#the-dispersion-screen" id="toc-the-dispersion-screen" class="nav-link" data-scroll-target="#the-dispersion-screen">The dispersion screen</a></li>
  </ul></li>
  <li><a href="#beta-binomial" id="toc-beta-binomial" class="nav-link" data-scroll-target="#beta-binomial">Beta-binomial</a></li>
  <li><a href="#checking-the-fit-against-the-data" id="toc-checking-the-fit-against-the-data" class="nav-link" data-scroll-target="#checking-the-fit-against-the-data">Checking the fit against the data</a></li>
  <li><a href="#beta" id="toc-beta" class="nav-link" data-scroll-target="#beta">Beta</a>
  <ul class="collapse">
  <li><a href="#values-on-the-boundary" id="toc-values-on-the-boundary" class="nav-link" data-scroll-target="#values-on-the-boundary">Values on the boundary</a></li>
  </ul></li>
  <li><a href="#poisson" id="toc-poisson" class="nav-link" data-scroll-target="#poisson">Poisson</a>
  <ul class="collapse">
  <li><a href="#counts-observed-over-an-exposure" id="toc-counts-observed-over-an-exposure" class="nav-link" data-scroll-target="#counts-observed-over-an-exposure">Counts observed over an exposure</a></li>
  </ul></li>
  <li><a href="#negative-binomial" id="toc-negative-binomial" class="nav-link" data-scroll-target="#negative-binomial">Negative binomial</a></li>
  <li><a href="#gamma" id="toc-gamma" class="nav-link" data-scroll-target="#gamma">Gamma</a></li>
  <li><a href="#gaussian" id="toc-gaussian" class="nav-link" data-scroll-target="#gaussian">Gaussian</a>
  <ul class="collapse">
  <li><a href="#growth-rates" id="toc-growth-rates" class="nav-link" data-scroll-target="#growth-rates">Growth rates</a></li>
  </ul></li>
  <li><a href="#model-suitability-by-response-type" id="toc-model-suitability-by-response-type" class="nav-link" data-scroll-target="#model-suitability-by-response-type">Model suitability by response type</a></li>
  <li><a href="#censored-values" id="toc-censored-values" class="nav-link" data-scroll-target="#censored-values">Censored values</a></li>
  <li><a href="#zeros" id="toc-zeros" class="nav-link" data-scroll-target="#zeros">Zeros</a></li>
  <li><a href="#hurdle-and-zero-inflated-models" id="toc-hurdle-and-zero-inflated-models" class="nav-link" data-scroll-target="#hurdle-and-zero-inflated-models">Hurdle and zero-inflated models</a>
  <ul class="collapse">
  <li><a href="#a-hurdle-gamma-in-practice" id="toc-a-hurdle-gamma-in-practice" class="nav-link" data-scroll-target="#a-hurdle-gamma-in-practice">A hurdle gamma in practice</a></li>
  </ul></li>
  <li><a href="#preparing-the-response" id="toc-preparing-the-response" class="nav-link" data-scroll-target="#preparing-the-response">Preparing the response</a>
  <ul class="collapse">
  <li><a href="#the-motive-for-a-divisor" id="toc-the-motive-for-a-divisor" class="nav-link" data-scroll-target="#the-motive-for-a-divisor">The motive for a divisor</a></li>
  </ul></li>
  <li><a href="#modelling-dispersion" id="toc-modelling-dispersion" class="nav-link" data-scroll-target="#modelling-dispersion">Modelling dispersion</a>
  <ul class="collapse">
  <li><a href="#a-worked-case" id="toc-a-worked-case" class="nav-link" data-scroll-target="#a-worked-case">A worked case</a></li>
  </ul></li>
  <li><a href="#open-questions" id="toc-open-questions" class="nav-link" data-scroll-target="#open-questions">Open questions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/open-AIMS/cr_modelling_training/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<div style="background:#fdf6ec;border-left:4px solid #d9822b;padding:0.6rem 0.9rem;margin-bottom:1rem;font-size:0.9rem;">
  <strong>Development build.</strong> These pages are being revised and have not
  been reviewed. The current course material is at
  <a href="https://open-aims.github.io/cr_modelling_training/">open-aims.github.io/cr_modelling_training</a>.
</div>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/1Software-stack.html">Modules</a></li><li class="breadcrumb-item"><a href="../vignettes/5Response_data_and_statistical_distributions.html">5. Response data and distributions</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Response data and statistical distributions</h1>
<p class="subtitle lead">Matching the statistical family to the response being modelled</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>Concentration-response data are of varied kinds, and the measured response follows a correspondingly wide range of natural distributions. The examples below are drawn at random to show the shape of each.</p>
<p><strong>Binary</strong>, modelled by the binomial or beta-binomial. Individual survival, 0 0 1 1 0 1 1 0 0 0, or counts of survivors out of a total.</p>
<p><strong>Bounded continuous</strong>, modelled by the beta. Proportions or ratios that are not counts out of a total: 0.458 0.861 0.246 0.043 0.1 0.697 0.232 0.74 0.866 0.704.</p>
<p><strong>Counts</strong>, modelled by the Poisson or negative binomial. Numbers of whole animals: 7 2 3 3 3 8 6 4 3 1.</p>
<p><strong>Positive continuous</strong>, modelled by the gamma. Growth where shrinkage is not possible: 0.92 5.11 0.46 5.13 1.67 8.9 0.66 0.62 0.82 1.43.</p>
<p><strong>Unbounded continuous</strong>, modelled by the Gaussian. Growth where shrinkage is possible: 0.08 -0.22 -0.94 0.04 -0.12 0.16 -0.8 -0.09 0.88 0.06.</p>
</section>
<section id="generalised-modelling" class="level2">
<h2 class="anchored" data-anchor-id="generalised-modelling">Generalised modelling</h2>
<p>Generalised modelling fits data with a statistical distribution matched to the natural range and scaling of the response, rather than assuming one.</p>
<p>Fitting a linear model with <code>lm()</code> assumes a Gaussian distribution, and so do many non-linear routines such as <code>nls()</code>. The normality assumption familiar from analysis of variance is the most common case of non-generalised modelling. It is sometimes reasonable, but it was adopted largely because it makes the mathematics of fitting and interval estimation tractable.</p>
<p>That constraint no longer applies. Matching the response to an appropriate statistical family is now standard practice, and the theory is covered well elsewhere; this module is concerned with making the right choice in <code>bayesnec</code> rather than with the underlying mathematics.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/glmbooks.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</section>
<section id="families-available-in-brms" class="level2">
<h2 class="anchored" data-anchor-id="families-available-in-brms">Families available in <code>brms</code></h2>
<p><code>brms</code> supports many families, including most of those in the base <code>stats</code> package that other R fitting routines use:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/statsfams.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
<p>and a number that are specific to it:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/brmsfams.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</section>
<section id="link-functions" class="level2">
<h2 class="anchored" data-anchor-id="link-functions">Link functions</h2>
<p>Every statistical family has a link function. A generalised linear model relates the linear predictor to the response through it: a logit link, for example, maps the probabilities of a binary response onto an unbounded continuous scale. Generalised linear models were formulated by Nelder and Wedderburn as a unification of linear regression, logistic regression and Poisson regression, with maximum likelihood estimation of the parameters. Logistic regression is the familiar case.</p>
<p>The native link for a family (logit for the binomial, log for the Poisson) imposes a non-linear transformation. Concentration-response models are already non-linear and do not use linear predictors, so any further non-linearity from a link changes the model being fitted.</p>
<p><code>bayesnec</code> therefore assigns the identity link to every family. The Bayesian machinery makes this possible, because the parameters can be estimated without mapping the response onto an unbounded scale. It keeps <code>top</code>, <code>bot</code> and <code>nec</code> on the scale of the response, where they are directly interpretable. A log or logit link is used only where it is supplied in a family object passed to <code>bnec()</code>, which is why three links are listed below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>bayesnec<span class="sc">:::</span><span class="fu">supported_links</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "identity" "log"      "logit"   </code></pre>
</div>
</div>
<p>This matters when comparing a <code>bayesnec</code> fit against a <code>brms</code> model written by hand. <code>brms</code> defaults to logit for a beta response and log for a Poisson, so unless the link is passed explicitly the two are different models. ECx and NSEC estimates from a fit using any link other than the identity may not behave as expected.</p>
</section>
<section id="families-implemented-in-bayesnec" class="level2">
<h2 class="anchored" data-anchor-id="families-implemented-in-bayesnec">Families implemented in <code>bayesnec</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bayesnec<span class="sc">:::</span>mod_fams)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "gaussian"                  "Gamma"                    
 [3] "poisson"                   "negbinomial"              
 [5] "bernoulli"                 "binomial"                 
 [7] "beta_binomial"             "beta"                     
 [9] "hurdle_gamma"              "zero_inflated_beta"       
[11] "zero_inflated_poisson"     "zero_inflated_negbinomial"
[13] "hurdle_poisson"            "hurdle_negbinomial"       </code></pre>
</div>
</div>
<p>The first eight are the ordinary families, and all of them except <code>bernoulli</code> are covered below. The last six (<code>hurdle_gamma</code>, <code>hurdle_poisson</code>, <code>hurdle_negbinomial</code> and the three zero-inflated families) handle responses with an excess of zeros, which <em>Hurdle and zero-inflated models</em> below introduces.</p>
<p>Adding a family is not trivial, because <code>bayesnec</code> generates priors and initial values by algorithms specific to each one. Requests go to the <a href="https://github.com/open-AIMS/bayesnec/issues">issue tracker</a>.</p>
</section>
<section id="default-behaviour" class="level2">
<h2 class="anchored" data-anchor-id="default-behaviour">Default behaviour</h2>
<p>With default settings <code>bnec</code> infers the most likely distribution from the response. That inference must be checked rather than trusted. Two questions decide whether a distribution is adequate:</p>
<ul>
<li>does it capture the variability present in the data?</li>
<li>does it produce sensibly shaped credible bounds across the whole curve?</li>
</ul>
<p>Getting the dispersion right matters directly for toxicity estimates, because it sets the width of their intervals. It matters most for the <em>NSEC</em>, which is defined against the estimated variability in the control: overstate that variability and the estimate becomes less conservative <span class="citation" data-cites="fisheretal2023 fisherfox2023">(<a href="#ref-fisheretal2023" role="doc-biblioref">Fisher et al. 2023</a>; <a href="#ref-fisherfox2023" role="doc-biblioref">Fisher and Fox 2023</a>)</span>.</p>
<p>The sections below fit a threshold and a smooth model to each of several response types. Every one uses measured data: the binomial pair come from <a href="https://github.com/gerard-ricardo/NECs/blob/master/NECs">Gerard Ricardo’s repository</a> and the rest are published datasets shipping with <code>bayesnec</code>, which <code>?alga</code>, <code>?coral_pam</code> and <code>?lum31</code> document. Nothing below is simulated, and that matters for what the checks show: a constructed response passes or fails its own family for reasons of the construction, and tells a participant nothing about the data they will bring.</p>
<p>One result runs through all of them. Choosing the family from the kind of quantity the response is gets the <em>mean</em> of the curve right, and that is what the family is for. It does not follow that the family describes the <em>spread</em>, because every one of these families ties the spread it simulates to the mean through at most one parameter, held constant across the series, and a real concentration series is rarely that tidy. <em>Modelling dispersion</em>, at the end of the module, is the general repair, and most of the sections below hand to it.</p>
<p><em>Preparing the response</em>, near the end of the module, covers what to do where a response has already been divided by its control mean or by its observed maximum.</p>
</section>
<section id="binomial" class="level2">
<h2 class="anchored" data-anchor-id="binomial">Binomial</h2>
<p>A response is binomial when it is a count out of a total, such as the number of survivors out of a number exposed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>binom_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"vignettes/example_binomial.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log.x =</span> <span class="fu">log</span>(raw_x))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(binom_data<span class="sc">$</span>raw_x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.10   10.94   37.50   99.23  125.00  400.00 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(binom_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  raw_x suc tot     log.x
1   0.1 101 175 -2.302585
2   0.1 106 112 -2.302585
3   0.1 102 103 -2.302585
4   0.1 112 114 -2.302585
5   0.1  58  69 -2.302585
6   0.1 158 165 -2.302585</code></pre>
</div>
</div>
<p>The predictor runs from 0.1 to 400 and is strongly right skewed, which is typical of a dilution series. Transforming the predictor, usually by a logarithm, often makes fitting more stable, and the design is generally logarithmic in any case, so this example is fitted on <code>log.x</code>. Estimates then come back on the log scale and are returned to concentrations with the <code>xform</code> argument of <code>nec()</code>, <code>nsec()</code> and <code>ecx()</code>, which module 7 works through.</p>
<p><code>suc</code> holds the number of successes and <code>tot</code> the number of trials.</p>
<p>For a binomial or beta-binomial response the formula takes a <code>trials</code> term, exactly as in <code>brms</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>suc <span class="sc">|</span> <span class="fu">trials</span>(tot) <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"your_model"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The column to the left of the <code>|</code> holds the successes (survivors, fertilised eggs) and the one inside <code>trials()</code> the total associated with each. The names are whatever they are in your data frame.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>exp_1nec <span class="ot">&lt;-</span> <span class="fu">bnec</span>(suc <span class="sc">|</span> <span class="fu">trials</span>(tot) <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"nec3param"</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> binom_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_1nec, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_1nec.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_1nec.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_1nec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting all 'trials' variables to 1 by default if not specified otherwise.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-binom-nec" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binom-nec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-binom-nec-1.png" id="fig-binom-nec" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-binom-nec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<p>The credible bounds are very tight. The threshold model itself fits reasonably and the <em>NEC</em> is in a plausible place.</p>
<section id="the-dispersion-screen" class="level3">
<h3 class="anchored" data-anchor-id="the-dispersion-screen">The dispersion screen</h3>
<p>Bounds that look too tight are a judgement by eye, and the judgement can be made properly. <code>dispersion()</code> compares the variability in the data against the variability the fitted model implies:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dispersion</span>(exp_1nec, <span class="at">summary =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimate     Q2.5    Q97.5    P(&gt;1) 
17.56449 11.99124 27.08505  1.00000 </code></pre>
</div>
</div>
<p>For each posterior draw it forms the ratio of the observed to the simulated sum of squared Pearson residuals, and summarises those ratios to a median, a 95% interval, and <code>P(&gt;1)</code>, the posterior probability that the ratio exceeds 1. A value near 1 means the family’s variance assumption holds. A value well above 1 means the data are more variable than the model allows, which is <strong>over-dispersion</strong>.</p>
<p>Read <code>P(&gt;1)</code> rather than the median, because a point estimate says nothing about how well determined it is. The statistic is symmetric, so <code>1 - P(&gt;1)</code> is the posterior probability of under-dispersion, which nothing else reports.</p>
<p>Here the ratio is about 18 with a 95% interval well clear of 1, and <code>P(&gt;1)</code> is 1. The data are roughly eighteen times more variable than a binomial allows, which is why the credible bounds above are as narrow as they are. The eye was right in this case, and the number is what would be reported.</p>
<p>Two limitations apply. Each draw compares one observed residual sum against a single simulated replicate, so the spread of the result is dominated by simulation noise rather than by uncertainty about a dispersion parameter; on a small design it will detect gross over-dispersion and little else. And the screen is conditional on the model it was computed from, because a dispersion ratio cannot distinguish genuine over-dispersion from a shape that fits badly. Check that the screening fit sampled adequately, with <code>check_sampling()</code>, before relying on the number it reports.</p>
<p><code>dispersion()</code> is defined for the binomial and Poisson families only, and returns an empty vector for any other. Those two are the families whose variance is fixed by their mean, so they are the only ones for which over-dispersion is a question about the family rather than a parameter the fit estimates.</p>
<p>Fitting a smooth curve to the same data instead:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>exp_1ecx <span class="ot">&lt;-</span> <span class="fu">bnec</span>(suc <span class="sc">|</span> <span class="fu">trials</span>(tot) <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"ecxll3"</span>),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> binom_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_1ecx, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_1ecx.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_1ecx.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_1ecx)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting all 'trials' variables to 1 by default if not specified otherwise.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-binom-ecx" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binom-ecx-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-binom-ecx-1.png" id="fig-binom-ecx" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-binom-ecx-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="beta-binomial" class="level2">
<h2 class="anchored" data-anchor-id="beta-binomial">Beta-binomial</h2>
<p>The bounds above are implausibly narrow for data of this kind. A binomial distribution has a single parameter, so its variance is fixed by its mean. Real counts out of a total are usually more variable than that, because the individuals within a replicate are not independent: a batch of eggs shares a parent, a container shares its conditions. This is over-dispersion.</p>
<p>The beta-binomial adds a second parameter and estimates the extra variation rather than assuming it away.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>exp_1b <span class="ot">&lt;-</span> <span class="fu">bnec</span>(suc <span class="sc">|</span> <span class="fu">trials</span>(tot) <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ecxll3"</span>, <span class="st">"nec3param"</span>)),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> binom_data, <span class="at">family =</span> <span class="st">"beta_binomial"</span>, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_1b, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_1b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_1b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_1b, <span class="at">all_models =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting all 'trials' variables to 1 by default if not specified otherwise.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"
Setting all 'trials' variables to 1 by default if not specified otherwise.

Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-betabinom" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-betabinom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-betabinom-1.png" id="fig-betabinom" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-betabinom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
</div>
</div>
<p>The bounds are now much wider, and they are a better description of the scatter in the data.</p>
<p>The beta-binomial mixes the success probability over a beta distribution, and mixing can only <em>add</em> variance. It therefore addresses over-dispersion and does nothing for the opposite case. A screen pointing below 1 is telling you something about the fit, the design or the process that generated the data, rather than about the family.</p>
<p><code>bayesnec</code> once supplied this as a custom family called <code>beta_binomial2</code>, because <code>brms</code> did not provide one natively. It does now, and the family is named <code>beta_binomial</code>; code written against <code>beta_binomial2</code> will no longer run.</p>
</section>
<section id="checking-the-fit-against-the-data" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-fit-against-the-data">Checking the fit against the data</h2>
<p>The two sections above chose between two families by eye and then by a dispersion ratio. Neither generalises: the eye is unreliable, and <code>dispersion()</code> is defined for the binomial and Poisson alone. <code>check_fit()</code> is the check that applies to every family, and it is what the rest of this module uses.</p>
<p>A dispersion ratio is one number for the whole fit, and one number can hide a model that is right on average and wrong where it matters. <code>check_fit()</code>, named in module 2, makes the same comparison within concentration groups, and on a model set it reports every equation separately.</p>
<p>What it compares is the observed mean within each group of the predictor, and the standard deviation of the residuals about the fitted curve, against the same two statistics computed from datasets simulated by the fitted model. A family that cannot reproduce those two numbers across the concentration range is the wrong family for the response, whatever it says about the kind of quantity the response is. The control group matters most, because both <code>nsec()</code> and <code>ecx()</code> read their reference from the fitted mean there, so an error in the control propagates into every estimate the analysis reports.</p>
<p>Run on the binomial fit from the section above:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>cf_1nec <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_1nec)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>cf_1nec</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              group n obs_mean sim_mean mean_ratio ppp_mean obs_sd sim_sd
1 -2.30258509299405 6  106.167  102.000      1.041    0.010 24.642  3.861
2  1.83258146374831 6  103.667  100.167      1.035    0.031 14.344  3.939
3  2.52572864430826 6   72.833   77.500      0.940    0.999 24.383  3.345
4   3.2188758248682 6   85.167   81.333      1.047    0.012 11.478  3.451
5  3.91202300542815 6   75.500   82.833      0.911    1.000 20.819  3.497
6  4.60517018598809 6   61.500   60.500      1.017    0.371 29.085  4.782
7  5.29831736654804 6   19.500   22.333      0.873    0.906 13.147  3.975
8  5.99146454710798 6    9.167    7.667      1.196    0.158  3.973  2.464
  sd_ratio ppp_sd control
1    6.383  0.000    TRUE
2    3.641  0.000   FALSE
3    7.289  0.000   FALSE
4    3.326  0.000   FALSE
5    5.953  0.000   FALSE
6    6.082  0.000   FALSE
7    3.308  0.000   FALSE
8    1.612  0.062   FALSE

The control group is flagged. nsec() reads its reference from the 
control, so this is the row most likely to move a reported 
no-effect concentration. See ?check_fit.</code></pre>
</div>
</div>
<p><code>obs_sd</code> and <code>sim_sd</code> are the observed and simulated residual spread within a group, and <code>ppp_sd</code> is the proportion of simulated datasets in which the simulated spread was at least as large as the observed one. Read the p-values rather than the ratios, and read the <code>control</code> row first, because both <code>nsec()</code> and <code>ecx()</code> take their reference from the fitted mean there.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_1nec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-binom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-binom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-binom-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-binom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: <code>check_fit()</code> on the binomial fit. Each point is the observed statistic for one concentration group against the 95% span of what the fit simulates, with location and scale drawn separately.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The groups are labelled on the logged scale, because that is the scale the model was fitted on: -2.30 is the 0.1 control and 5.99 the highest dose of 400. Seven of the eight points on the scale panel sit above their bar, <code>sd_ratio</code> runs from 1.6 to 7.3, and <code>ppp_sd</code> is 0.000 in seven groups. Four of the eight points on the location panel sit outside their bar as well, because a variance held too low leaves the simulated mean too tightly determined to contain the observed one. This is the dispersion ratio of about 18 seen group by group.</p>
<p>The same check on the beta-binomial fit of the same data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>cf_1b <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_1b)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>cf_1b</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       model    wi             group n obs_mean sim_mean mean_ratio ppp_mean
1     ecxll3 0.656 -2.30258509299405 6  106.167  107.500      0.988    0.577
2     ecxll3 0.656  1.83258146374831 6  103.667  105.167      0.986    0.576
3     ecxll3 0.656  2.52572864430826 6   72.833   80.500      0.905    0.860
4     ecxll3 0.656   3.2188758248682 6   85.167   81.500      1.045    0.258
5     ecxll3 0.656  3.91202300542815 6   75.500   74.000      1.020    0.420
6     ecxll3 0.656  4.60517018598809 6   61.500   57.667      1.066    0.367
7     ecxll3 0.656  5.29831736654804 6   19.500   31.333      0.622    0.903
8     ecxll3 0.656  5.99146454710798 6    9.167   11.333      0.809    0.623
9  nec3param 0.344 -2.30258509299405 6  106.167  104.167      1.019    0.407
10 nec3param 0.344  1.83258146374831 6  103.667  102.833      1.008    0.467
11 nec3param 0.344  2.52572864430826 6   72.833   79.667      0.914    0.831
12 nec3param 0.344   3.2188758248682 6   85.167   83.000      1.026    0.364
13 nec3param 0.344  3.91202300542815 6   75.500   81.833      0.923    0.750
14 nec3param 0.344  4.60517018598809 6   61.500   54.333      1.132    0.263
15 nec3param 0.344  5.29831736654804 6   19.500   28.833      0.676    0.839
16 nec3param 0.344  5.99146454710798 6    9.167   14.833      0.618    0.766
   obs_sd sim_sd sd_ratio ppp_sd control
1  25.398 14.435    1.759  0.096    TRUE
2  15.212 14.271    1.066  0.444   FALSE
3  24.582 11.892    2.067  0.058   FALSE
4  11.497 13.376    0.860  0.647   FALSE
5  20.153 16.183    1.245  0.285   FALSE
6  29.205 20.566    1.420  0.116   FALSE
7  14.449 19.532    0.740  0.754   FALSE
8   3.550 12.559    0.283  0.962   FALSE
9  24.874 16.227    1.533  0.149    TRUE
10 14.658 15.962    0.918  0.578   FALSE
11 24.475 12.224    2.002  0.057   FALSE
12 11.373 12.790    0.889  0.594   FALSE
13 20.758 14.383    1.443  0.165   FALSE
14 29.356 20.897    1.405  0.123   FALSE
15 14.110 19.492    0.724  0.772   FALSE
16  3.475 14.184    0.245  0.984   FALSE

One or more groups show a posterior predictive p-value beyond 
[0.05, 0.95]. See ?check_fit.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_1b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-betabinom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-betabinom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-betabinom-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-betabinom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: The same check on the beta-binomial fit, reported for each equation in the set.
</figcaption>
</figure>
</div>
</div>
</div>
<p>No group is flagged on the mean for either equation. On spread, only the highest concentration is flagged, where the fit simulates three to four times the observed variability. Six replicates at a success proportion below one in ten supply very little information about spread, so this is what the top of a series usually looks like rather than a fault in the family.</p>
<p><code>brms::pp_check()</code> shows the same comparison as distributions rather than as summary statistics, and module 7 uses it on a continuous response. The grouped form is the one to use, <code>type = "dens_overlay_grouped"</code> for a continuous response and <code>type = "bars_grouped"</code> for a discrete one: pooled over the whole dataset a model can match the overall distribution while being wrong at every concentration.</p>
</section>
<section id="beta" class="level2">
<h2 class="anchored" data-anchor-id="beta">Beta</h2>
<p>A response bounded between 0 and 1 that is not a count out of a total is modelled by the beta distribution. Effective quantum yield from PAM fluorometry is the common example in coral work: the proportion of absorbed light used in photosynthesis, with no underlying trials to count.</p>
<p><code>coral_pam</code> ships with <code>bayesnec</code> and holds yields for the coral <em>Acropora millepora</em> exposed to diuron under three climate scenarios <span class="citation" data-cites="flores2021">(<a href="#ref-flores2021" role="doc-biblioref">Flores et al. 2021</a>)</span>. The 2018 scenario is used here; module 8 is where a factor covariate of this kind is fitted rather than subset away.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(coral_pam)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>pam_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(coral_pam, climate <span class="sc">==</span> <span class="st">"2018"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pam_data<span class="sc">$</span>diuron)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0 0.29 0.96  2.9  9.6   29 
  24   24   24   24   24   18 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(pam_data<span class="sc">$</span>yield)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000 0.711</code></pre>
</div>
</div>
<p>Six concentrations, each with three chambers of four fragments read twice, so twenty-four readings at each concentration and eighteen at the highest. The control is recorded as <code>0</code>, which is correct and which <code>log()</code> cannot take, so an offset is added to the data before fitting, as <em>The scale of the predictor</em> in module 7 sets out. One decade below the lowest exposure is the convention used throughout this course.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>pam_data<span class="sc">$</span>log.x <span class="ot">&lt;-</span> <span class="fu">log</span>(pam_data<span class="sc">$</span>diuron <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">min</span>(pam_data<span class="sc">$</span>diuron[pam_data<span class="sc">$</span>diuron <span class="sc">&gt;</span> <span class="dv">0</span>]) <span class="sc">/</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>exp_2 <span class="ot">&lt;-</span> <span class="fu">bnec</span>(yield <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ecxwb1"</span>, <span class="st">"nec3param"</span>)),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> pam_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_2, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_2.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_2.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_2, <span class="at">all_models =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"
Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-beta" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-beta-1.png" id="fig-beta" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>exp_2<span class="sc">$</span>mod_stats[, <span class="fu">c</span>(<span class="st">"model"</span>, <span class="st">"waic"</span>, <span class="st">"wi"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              model      waic         wi
ecxwb1       ecxwb1 -476.7734 0.99024653
nec3param nec3param -421.4259 0.00975347</code></pre>
</div>
</div>
<p>The smooth equation takes almost all of the weight, which is what a yield series declining from the lowest exposure looks like: there is no flat region for a threshold to sit at the end of. The dispersion columns of <code>mod_stats</code>, left out above, hold <code>NA</code> for this fit. <code>dispersion()</code> is defined for the binomial and Poisson alone, because those are the families whose variance is fixed by their mean; a beta estimates a precision parameter of its own, so over-dispersion is not a question about the family here.</p>
<p>That does not mean the spread is described correctly, and <code>check_fit()</code> is what settles it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>cf_2 <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_2)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>cf_2[, <span class="fu">c</span>(<span class="st">"model"</span>, <span class="st">"wi"</span>, <span class="st">"group"</span>, <span class="st">"mean_ratio"</span>, <span class="st">"ppp_mean"</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">"sd_ratio"</span>, <span class="st">"ppp_sd"</span>, <span class="st">"control"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       model   wi               group mean_ratio ppp_mean sd_ratio ppp_sd
1     ecxwb1 0.99   -3.54045944899566      1.002    0.462    0.560  0.999
2     ecxwb1 0.99   -1.14256417619729      1.009    0.373    0.381  1.000
3     ecxwb1 0.99 -0.0110609473594249      0.986    0.663    0.407  1.000
4     ecxwb1 0.99     1.0746610678456      1.004    0.470    0.471  1.000
5     ecxwb1 0.99    2.26477937825815      1.460    0.011    2.343  0.000
6     ecxwb1 0.99    3.36829533031956      1.520    0.073    2.177  0.007
7  nec3param 0.01   -3.54045944899566      1.043    0.081    0.430  1.000
8  nec3param 0.01   -1.14256417619729      0.964    0.863    0.303  1.000
9  nec3param 0.01 -0.0110609473594249      0.959    0.801    0.319  1.000
10 nec3param 0.01     1.0746610678456      1.372    0.000    0.418  1.000
11 nec3param 0.01    2.26477937825815      0.851    0.848    1.404  0.058
12 nec3param 0.01    3.36829533031956      1.241    0.235    1.573  0.084
   control
1     TRUE
2    FALSE
3    FALSE
4    FALSE
5    FALSE
6    FALSE
7     TRUE
8    FALSE
9    FALSE
10   FALSE
11   FALSE
12   FALSE

The control group is flagged. nsec() reads its reference from the 
control, so this is the row most likely to move a reported 
no-effect concentration. See ?check_fit.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-beta" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-beta-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: <code>check_fit()</code> on the beta fit of PAM yield. The six concentrations are design points with twenty-four readings at most, so no binning is needed.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read <code>ecxwb1</code>, which holds 0.99 of the weight. The location panel is inside its bars at every concentration except the second highest, where the observed mean is about one and a half times the fitted one. The scale panel misses at every concentration, and in both directions. <code>sd_ratio</code> runs from 0.38 to 2.34 across the series, and at the control it is 0.56, so the fit simulates about twice the variability the control fragments show and about half the variability at the two highest concentrations.</p>
<p>The cause is structural rather than a fault in the fitting. A beta holds one precision parameter for the whole series, and a beta’s variance is <span class="math inline">\(\mu(1-\mu)/(1+\phi)\)</span>, which is largest at a mean of 0.5 and shrinks towards either bound. These yields fall from 0.67 at the control to 0.027 at the highest concentration, so the spread the fit is obliged to simulate changes across the series whether or not the data’s does. Near zero, where some fragments had stopped photosynthesising and others had not, the observed spread is larger than a beta with the precision the rest of the series needs can produce.</p>
<p>No choice of equation repairs this. <code>ecxwb1</code> was chosen by fitting every equation <code>bnec()</code> admits for these data (<code>model = "all"</code>), and every one of them missed on scale at four or more of the six concentrations (<code>scripts/screen_module5_models.R</code>). The repair is to let the precision vary, which <code>disp()</code> does and <em>Modelling dispersion</em> below describes. Here the precision is modelled as a function of the fitted mean:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>exp_2_disp <span class="ot">&lt;-</span> <span class="fu">bnec</span>(yield <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"ecxwb1"</span>) <span class="sc">+</span> <span class="fu">disp</span>(<span class="st">"power"</span>),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> pam_data, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_2_disp, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_2_disp.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_2_disp.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>cf_2d <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_2_disp)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_2d)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-beta-disp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-beta-disp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-beta-disp-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-beta-disp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: <code>check_fit()</code> on the beta fit of PAM yield with <code>disp("power")</code>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>With the precision free to change along the series, the location panel is inside its bars at every concentration, and 2 of the six fall outside on scale, against six without it. <code>sd_ratio</code> now runs from 0.69 to 1.37. The remaining misses are at the control and at the fourth concentration, and both lie close to the edge of their bar. This is the fit to report an <em>NSEC</em> from, rather than <code>exp_2</code>.</p>
<p>The predictor was logged in the formula, as in the binomial example above. Estimates returned by <code>nec()</code>, <code>nsec()</code> and <code>ecx()</code> are then on the log scale, and <code>xform</code> returns them to concentrations, remembering that the offset added above has to be subtracted as part of it.</p>
<section id="values-on-the-boundary" class="level3">
<h3 class="anchored" data-anchor-id="values-on-the-boundary">Values on the boundary</h3>
<p>A beta distribution is defined on the <em>open</em> interval between 0 and 1, so a response recorded as exactly 0 or exactly 1 lies outside it. This is common: complete mortality at the highest concentration, or complete survival in the controls, both produce boundary values. These data have them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(pam_data<span class="sc">$</span>yield, pam_data<span class="sc">$</span>diuron, <span class="cf">function</span>(z) <span class="fu">sum</span>(z <span class="sc">==</span> <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0 0.29 0.96  2.9  9.6   29 
   0    0    0    0    3    5 </code></pre>
</div>
</div>
<p><code>bayesnec</code> shifts them rather than refusing the fit. A zero becomes one tenth of the smallest non-zero value in the response, which scales with the data, and a one is reduced by an absolute 0.001. <code>bnec_record()</code> names every value it altered, and the fit reports the same thing as a message when it runs:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bnec_record</span>(exp_2)<span class="sc">$</span>substitutions</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     variable             rule n_rows from    to
zero response shifted off zero      8    0 7e-04
                                          reason               remedy
zero a beta distribution cannot represent a zero zero_inflated_beta()</code></pre>
</div>
</div>
<p>The <code>remedy</code> column is the point. Eight readings of exactly zero were shifted to 7e-04, and every one of them is at the two highest concentrations, where photosynthesis had stopped. Those are measurements at a boundary rather than values too small to record, so the analysis above is fitted to shifted data and a methods section has to say so. Where the boundary values mean something different from a very small response, <code>zero_inflated_beta()</code> models them as what they are, and the section on zeros below covers the choice.</p>
</section>
</section>
<section id="poisson" class="level2">
<h2 class="anchored" data-anchor-id="poisson">Poisson</h2>
<p>Counts of whole things (individuals, cells) are theoretically Poisson distributed: integers from zero upwards. The Poisson has one parameter, so its variance equals its mean, and whether real counts obey that is a question rather than an assumption.</p>
<p><code>alga</code> ships with <code>bayesnec</code> and holds final cell density and growth rate for two marine microalgae against two contaminants, from growth inhibition tests with five replicate cultures per exposure level. The test used here has ten at the control. The symbiotic dinoflagellate <em>Cladocopium proliferum</em> against contaminant B is used here and in the Gaussian example below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(alga)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>alga_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(alga, species <span class="sc">==</span> <span class="st">"c_proliferum"</span> <span class="sc">&amp;</span> contaminant <span class="sc">==</span> <span class="st">"B"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>alga_data<span class="sc">$</span>log.x <span class="ot">&lt;-</span> <span class="fu">log</span>(alga_data<span class="sc">$</span>dose <span class="sc">+</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">min</span>(alga_data<span class="sc">$</span>dose[alga_data<span class="sc">$</span>dose <span class="sc">&gt;</span> <span class="dv">0</span>]) <span class="sc">/</span> <span class="dv">10</span>)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(alga_data[, <span class="fu">c</span>(<span class="st">"dose"</span>, <span class="st">"density"</span>, <span class="st">"sgr"</span>, <span class="st">"days"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   70 obs. of  4 variables:
 $ dose   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ density: int  27380 26070 29480 29670 29010 28490 26940 29920 30170 27450 ...
 $ sgr    : num  0.164 0.157 0.175 0.175 0.172 0.17 0.162 0.177 0.178 0.164 ...
 $ days   : int  7 7 7 7 7 7 7 7 7 7 ...</code></pre>
</div>
</div>
<p>Thirteen dose levels, the control included, over seven days, with cell densities in the tens of thousands. The arithmetic that makes this a Poisson problem can be done before any model is fitted:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> alga_data<span class="sc">$</span>density[alga_data<span class="sc">$</span>dose <span class="sc">==</span> <span class="dv">0</span>]</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(ctrl), <span class="at">observed_sd =</span> <span class="fu">sd</span>(ctrl), <span class="at">poisson_sd =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(ctrl)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mean observed_sd  poisson_sd 
  28458.000    1417.061     168.695 </code></pre>
</div>
</div>
<p>A Poisson with that mean would produce a standard deviation of about 169. The ten control cultures show 1417, about 8 times as much. Culture-to-culture variation in an inoculum is not counting noise, and no count of this kind ever is; the Poisson is fitted here to show what that looks like rather than because it is expected to hold.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>exp_3 <span class="ot">&lt;-</span> <span class="fu">bnec</span>(density <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"ecxwb1"</span>),</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> alga_data, <span class="at">family =</span> <span class="st">"poisson"</span>, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_3, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_3.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_3.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-pois" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pois-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-pois-1.png" id="fig-pois" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-pois-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9
</figcaption>
</figure>
</div>
</div>
</div>
<p>The credible bounds are so narrow that they are hard to see against the curve, which is the visual signature of the arithmetic above.</p>
<p>The dispersion screen applies here for the reason it applied to the binomial: a Poisson has one parameter, so its variance is fixed by its mean.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dispersion</span>(exp_3, <span class="at">summary =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Estimate      Q2.5     Q97.5     P(&gt;1) 
111.89968  81.10404 157.89680   1.00000 </code></pre>
</div>
</div>
<p>The dispersion estimate is about 112, with <code>P(&gt;1)</code> of 1. These counts are two orders of magnitude more variable than a Poisson allows, not the modest factor the binomial example showed.</p>
<p>The equation, <code>ecxwb1</code>, is the best supported of those <code>bnec()</code> admits for these counts; every equation fitted under a Poisson returns the same failure (<code>scripts/screen_module5_models.R</code>). A dispersion computed for an equation that fits badly counts the variation its curve cannot describe as dispersion, so where a model set is fitted, read each equation’s dispersion against its weight.</p>
<p><code>check_fit()</code> shows where that extra variation sits. The doses are design points with five replicates each and ten at the control, so no binning is needed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>cf_3 <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_3)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-pois" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-pois-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-pois-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-pois-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: <code>check_fit()</code> on the Poisson fit of the algal cell counts. Every point falls outside its bar on the scale panel, and most on the location panel.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Both panels fail, and the location panel fails <em>because</em> the scale panel does. A variance held at a hundredth of the truth leaves the simulated mean far too tightly determined, so the observed mean lands outside an interval that should have contained it easily. <code>sd_ratio</code> runs from 2.8 to 15.6: the data are between 3 and 16 times more variable than the fit simulates, in every group.</p>
<p>This is what a wrong family looks like. It is a different failure from the ones the other sections show, where the family is defensible and only the spread is misdescribed.</p>
<section id="counts-observed-over-an-exposure" class="level3">
<h3 class="anchored" data-anchor-id="counts-observed-over-an-exposure">Counts observed over an exposure</h3>
<p>A count is very often observed over an exposure that differs between replicates: offspring counted where the number of fecund adults differs, cells counted over different areas, events counted over different lengths of time. The <code>rate</code> term declares that exposure, and is available for the Poisson and negative binomial families:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>y <span class="sc">|</span> <span class="fu">rate</span>(n_females) <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The raw counts are passed to <code>bnec()</code> unchanged, so a replicate with twenty females contributes more information than one with eight. Fitting <code>y / n_females</code> as a continuous response would discard exactly that.</p>
<p>Because <code>bayesnec</code> uses an identity link, <code>brms</code> applies the denominator multiplicatively on the response scale rather than as a log offset on a linear predictor. The fitted mean therefore <em>is</em> the rate, and <code>top</code>, <code>bot</code> and <code>nec</code> are directly interpretable as offspring per female. The prediction grid holds the denominator at 1, and <code>autoplot()</code> divides the observed counts through to match.</p>
<p>One caveat decides whether <code>rate</code> is the right tool. Where the exposure varies for reasons unrelated to the treatment, because a replicate simply received fewer animals, <code>rate</code> does what is wanted. Where the exposure is itself an effect of the treatment, as it would be if the denominator were the number of females <em>surviving</em> to the point of counting, the endpoint has quietly changed from reproductive output to fecundity conditional on survival. Both are legitimate endpoints and they will not return the same <em>NEC</em>.</p>
</section>
</section>
<section id="negative-binomial" class="level2">
<h2 class="anchored" data-anchor-id="negative-binomial">Negative binomial</h2>
<p>The Poisson has one parameter, so like the binomial its variance is determined by its mean. Counts that are more variable than that need the negative binomial, which estimates the additional variation as a parameter of its own. It is the count analogue of the beta-binomial above.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>exp_3b <span class="ot">&lt;-</span> <span class="fu">bnec</span>(density <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"ecxwb1"</span>),</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> alga_data, <span class="at">family =</span> <span class="st">"negbinomial"</span>, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_3b, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_3b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_3b.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_3b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-negbin" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-negbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-negbin-1.png" id="fig-negbin" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-negbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11
</figcaption>
</figure>
</div>
</div>
</div>
<p>The bounds widen to something a reader can see, as they did for the beta-binomial, and for the same reason.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>cf_3b <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_3b)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_3b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-negbin" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-negbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-negbin-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-negbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: <code>check_fit()</code> on the negative binomial fit of the same counts.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Both panels are repaired, with the same equation and the same data; only the family has changed. Groups falling outside their bar on the mean drop from 9 of 13 under the Poisson to 2 here, and on spread from 13 to 1. <code>sd_ratio</code> runs from 0.34 to 1.28, and at the control it is 0.70. With five cultures at most concentrations a ratio between about a third and one and a half is within what sampling alone produces, which is what the bars show.</p>
<p>This is what the family is for. With the variance free to be estimated, the fit stops being forced into a certainty the data do not support, and one additional parameter is enough on these counts because their coefficient of variation stays between about 0.02 and 0.09 across the series.</p>
<p>The equation matters as well as the family. Fitted to the same counts under the same family, <code>nec3param</code> falls outside its bar on spread at seven of the thirteen concentrations, because a threshold followed by an exponential decline does not follow the shape of this curve and the dispersion parameter absorbs the difference (<code>scripts/screen_module5_models.R</code>).</p>
</section>
<section id="gamma" class="level2">
<h2 class="anchored" data-anchor-id="gamma">Gamma</h2>
<p>A continuous response that cannot be negative (a length, a mass, a light reading, a rate where shrinkage is impossible) is modelled by the gamma. Like the beta and the negative binomial it estimates a spread parameter of its own, so it is not the fixed-variance case the Poisson and binomial are. What it does fix is the <em>relative</em> spread: a gamma holds the coefficient of variation constant, so the standard deviation it simulates is a fixed fraction of the fitted mean. That assumption is the one to check.</p>
<p><code>lum31</code> ships with <code>bayesnec</code> and holds luminescence readings from the bioluminescent bacterium <em>Vibrio azureus</em> strain Lum-31 exposed to copper and zinc across thirty-three plates <span class="citation" data-cites="luter2025">(<a href="#ref-luter2025" role="doc-biblioref">Luter et al. 2025</a>)</span>. Module 8 models the plate-to-plate structure; one plate is enough here, and a zinc plate is used because every reading on it is positive, which a gamma requires.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(lum31)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>lum_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(lum31, plate <span class="sc">==</span> <span class="st">"Zn 28Mar24 Rep1B"</span> <span class="sc">&amp;</span> minutes <span class="sc">==</span> <span class="dv">15</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>lum_data<span class="sc">$</span>log.x <span class="ot">&lt;-</span> <span class="fu">log</span>(lum_data<span class="sc">$</span>conc)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">wells =</span> <span class="fu">nrow</span>(lum_data), <span class="at">concentrations =</span> <span class="fu">length</span>(<span class="fu">unique</span>(lum_data<span class="sc">$</span>conc)),</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_rlu =</span> <span class="fu">min</span>(lum_data<span class="sc">$</span>rlu), <span class="at">max_rlu =</span> <span class="fu">max</span>(lum_data<span class="sc">$</span>rlu))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         wells concentrations        min_rlu        max_rlu 
            44             11          16320         883163 </code></pre>
</div>
</div>
<p>Eleven concentrations with four wells each. Every well was read at 15 and at 30 minutes, and only the 15-minute reading is used: the two readings of one well are not independent replicates, and pooling them would mix the effect of exposure time into the spread at each concentration. The control is recorded at its measured dissolved zinc concentration rather than at zero, so the predictor is logged without an offset. The coefficient of variation within each concentration is a property of the data alone, with no model involved:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>lum_data <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(conc) <span class="sc">|&gt;</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_rlu =</span> <span class="fu">round</span>(<span class="fu">mean</span>(rlu)), <span class="at">cv =</span> <span class="fu">round</span>(<span class="fu">sd</span>(rlu) <span class="sc">/</span> <span class="fu">mean</span>(rlu), <span class="dv">3</span>),</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          conc mean_rlu    cv
1   0.00650000   797369 0.040
2   0.03599876   831733 0.038
3   0.06385870   793908 0.022
4   0.12121739   817449 0.040
5   0.23593478   866316 0.023
6   0.46700838   754955 0.072
7   0.92915558   673048 0.038
8   1.85017235   451252 0.032
9   3.69384469   163056 0.170
10  7.38118939    76659 0.174
11 14.75587877    18934 0.210</code></pre>
</div>
</div>
<p>It stays between about 0.02 and 0.07 over the first eight concentrations and rises to between 0.17 and 0.21 over the top three, where the luminescence has fallen to a fifth of the control or less. A gamma asserts that it is constant. The fit can be made anyway, and the check reports what the assumption does to the fit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>exp_4 <span class="ot">&lt;-</span> <span class="fu">bnec</span>(rlu <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"ecxll3"</span>),</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> lum_data, <span class="at">family =</span> <span class="st">"Gamma"</span>, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_4, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_4.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_4.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-gamma" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gamma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-gamma-1.png" id="fig-gamma" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gamma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>cf_4 <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_4)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-gamma" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-gamma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-gamma-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-gamma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: <code>check_fit()</code> on the gamma fit of one zinc plate.
</figcaption>
</figure>
</div>
</div>
</div>
<p><code>ecxll3</code> is the best supported of the equations <code>bnec()</code> admits for these data (<code>scripts/screen_module5_models.R</code>). Location is reproduced: the number of concentrations outside their bar on the mean is 1 of 11. The curve is right.</p>
<p>Scale is not, although fewer points fall outside their bars than the ratios suggest, because four wells give a wide bar. On spread the number outside is 2 of 11, and the pattern of <code>sd_ratio</code> follows the coefficients of variation above. Over the first eight concentrations it lies between 0.19 and 0.65, so the fit simulates between one and a half and five times the observed spread; over the top three it lies between 1.29 and 1.87, so it simulates too little. The fit estimates one coefficient of variation and settles between the two parts of the series.</p>
<p>This is the clearest case in the module of a family that is right about the response and wrong about the spread. The response is a positive continuous measurement, a gamma is the family for that, and nothing about the choice is mistaken. <em>Modelling dispersion</em> below takes this fit and repairs it.</p>
</section>
<section id="gaussian" class="level2">
<h2 class="anchored" data-anchor-id="gaussian">Gaussian</h2>
<p>A continuous response that can take negative values is modelled by the Gaussian. A growth rate is the usual case, because a population can decline as well as grow, and no family bounded below at zero can represent that.</p>
<p><code>alga</code> supplies one directly. Alongside the cell counts fitted above it holds <code>sgr</code>, the average specific growth rate over the exposure, for the same cultures.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(alga_data<span class="sc">$</span>sgr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.310  0.183</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(alga_data<span class="sc">$</span>sgr, alga_data<span class="sc">$</span>dose, <span class="cf">function</span>(z) <span class="fu">round</span>(<span class="fu">mean</span>(z), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     0      1     10     30     60    100    140    200    280    360    420 
 0.169  0.158  0.167  0.162  0.162  0.173  0.156  0.155  0.110  0.089  0.050 
   600   1000 
-0.040 -0.297 </code></pre>
</div>
</div>
<p>The growth rate falls from about 0.169 at the control to -0.30 at a dose of 1000, and 10 of the 70 cultures are negative: those populations shrank over the seven days rather than growing slowly. A gamma or a lognormal cannot represent those observations at all, and neither can an equation whose lower asymptote is fixed at zero. <code>ecxwb1</code> estimates its lower asymptote, <code>bot</code>, and is the best supported of the equations <code>bnec()</code> admits for these data (<code>scripts/screen_module5_models.R</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>exp_5 <span class="ot">&lt;-</span> <span class="fu">bnec</span>(sgr <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"ecxwb1"</span>),</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> alga_data, <span class="at">seed =</span> <span class="dv">333</span>,</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_5, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_5.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_5.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>adapt_delta</code> is raised from its default of 0.8 because at the default this equation returns divergent transitions on these data, and at 0.99 it returns none. Module 7 describes what a divergent transition is and why a smaller step size removes it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "NA"
• colour : "NA"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-gauss" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gauss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-gauss-1.png" id="fig-gauss" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gauss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>cf_5 <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_5)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>cf_5[, <span class="fu">c</span>(<span class="st">"group"</span>, <span class="st">"mean_ratio"</span>, <span class="st">"ppp_mean"</span>, <span class="st">"sd_ratio"</span>, <span class="st">"ppp_sd"</span>, <span class="st">"control"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                group mean_ratio ppp_mean sd_ratio ppp_sd control
1   -2.30258509299405      1.016    0.248    0.703  0.891    TRUE
2  0.0953101798043249      0.947    0.955    0.673  0.820   FALSE
3    2.31253542384721      1.003    0.458    0.360  0.972   FALSE
4    3.40452517175483      0.975    0.778    0.889  0.605   FALSE
5    4.09600984154116      0.981    0.731    1.210  0.313   FALSE
6    4.60616968632117      1.071    0.010    1.249  0.274   FALSE
7    4.94235645334296      0.999    0.513    1.245  0.272   FALSE
8    5.29881724158969      1.077    0.011    0.353  0.986   FALSE
9    5.63514668226606      0.917    0.979    0.989  0.510   FALSE
10   5.88638177065483      1.018    0.357    0.551  0.897   FALSE
11   6.04049277817534      0.866    0.941    0.460  0.963   FALSE
12   6.39709630799547      0.855    0.116    1.269  0.271   FALSE
13   6.90785527398247      1.003    0.578    1.120  0.369   FALSE

One or more groups show a posterior predictive p-value beyond 
[0.05, 0.95]. See ?check_fit.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-checkfit-gauss" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-checkfit-gauss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-gauss-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-checkfit-gauss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: <code>check_fit()</code> on the Gaussian fit of the algal growth rate.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The fit reproduces these data. 3 of the 13 concentrations fall outside their bar on the mean and 1 on spread, and <code>sd_ratio</code> runs from 0.35 to 1.27, the range sampling alone produces from five cultures. A Gaussian assumes the residual standard deviation is the same at every concentration, and on these growth rates it is: the control cultures agree with one another to 0.007, and the cultures at the highest dose, which all shrank, to 0.011.</p>
<p>A Gaussian is the one family whose constant-variance assumption is usually stated out loud, because it is the assumption analysis of variance rests on. Where it fails, <code>disp()</code> relaxes it, as <em>Modelling dispersion</em> below shows on the gamma fit.</p>
<p>Transforming a bounded response onto an unbounded scale and modelling it as Gaussian is the other way this family gets used: it was standard practice for proportion data before generalised methods were routine. Modelling the response on its own scale with the beta, as above, is preferable. It keeps the parameters interpretable as proportions, and it does not require the transformation to have made the variance constant, which is the very thing this section has just shown is not safe to assume.</p>
<section id="growth-rates" class="level3">
<h3 class="anchored" data-anchor-id="growth-rates">Growth rates</h3>
<p>The two <code>alga</code> endpoints fitted above are a worked instance of a naming convention worth getting right. OECD Test Guideline 201 <span class="citation" data-cites="oecd2026tg201">(<a href="#ref-oecd2026tg201" role="doc-biblioref">OECD 2026</a>)</span> distinguishes two response variables from the same algal growth inhibition experiment, and this dataset holds both for the same cultures. The average specific growth rate is the logarithmic increase in biomass over the exposure period, which is <code>sgr</code>, and an effect concentration derived from it is written <strong>ErC<sub>x</sub></strong>. Yield is the biomass at the end of the period minus the biomass at the start, which <code>density</code> and <code>density_initial</code> give, and its effect concentration is written <strong>EyC<sub>x</sub></strong>.</p>
<p>The guideline states that an ErC<sub>x</sub> will generally be higher than the corresponding EyC<sub>x</sub>, and that growth rate is the scientifically preferred basis; yield is retained to satisfy current regulatory requirements in some countries. An estimate reported without one of those prefixes has not said which quantity it describes, and the two sections above show why that matters beyond nomenclature: the same cultures gave a count response needing a negative binomial and a rate response needing a Gaussian, so the family, the candidate set and the estimate all differ between them.</p>
<p>The <code>bayesnec</code> article on growth data and other potentially negative responses covers the consequences of a response that can go below zero, which reach the choice of both the family and the candidate set.</p>
</section>
</section>
<section id="model-suitability-by-response-type" class="level2">
<h2 class="anchored" data-anchor-id="model-suitability-by-response-type">Model suitability by response type</h2>
<p>Not every equation suits every family. A model predicting negative values cannot be used with a response that must be positive, and <code>bayesnec</code> discards any model in a requested set that is unsuitable for the distribution of the response. This is why a set of twenty-three may return fewer than twenty-three fits, and why the <code>zero_bounded</code> set exists.</p>
<p>Three rules account for most of the exclusions.</p>
<p>Equations with no <code>bot</code> parameter, the <code>zero_bounded</code> set, approach zero and cannot go below it. <code>bnec()</code> excludes them under a log or logit link. They also cannot describe a Gaussian response that falls below zero, although <code>bnec()</code> does not exclude them for the Gaussian, so that choice is yours.</p>
<p>Equations with a linear decay, whose names contain <code>lin</code>, decline without limit, so they cannot describe a response bounded below at zero under an identity link. That covers the gamma, Poisson, negative binomial, binomial, beta and beta-binomial families.</p>
<p>Equations that raise the predictor to a fractional power cannot be evaluated where the predictor is negative, which a logged concentration series is wherever the concentration falls below 1.</p>
<p>You do not have to apply these yourself. <code>bnec()</code> excludes what it cannot fit and reports the reason, and <code>bnec_record()</code> keeps that reason on the fitted object:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bnec_record</span>(exp_2)<span class="sc">$</span>excluded</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] model  reason
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<p>No rows, because that fit named two equations explicitly and both are valid for a beta response on an identity link. A set requested as <code>"all"</code> on the same data returns several rows, with the rule each equation failed against.</p>
</section>
<section id="censored-values" class="level2">
<h2 class="anchored" data-anchor-id="censored-values">Censored values</h2>
<p>Everything above assumes each recorded value is a measurement of the response. In real datasets some are not. A value below a detection limit and a zero that marks a death are both written down as numbers and neither is a measurement of the response, and the two need different treatment from one another. This section and the two that follow take them in turn.</p>
<p>A value is <strong>censored</strong> when the truth is known to lie in an interval rather than at a point: a concentration below a limit of detection, a cell count below the resolution of the counting method, a value rounded at the precision it was recorded to. The number written down is a <em>bound</em> rather than a measurement.</p>
<p>The usual treatments are to substitute something for it, commonly half the detection limit, or to delete the row. <span class="citation" data-cites="helsel2006">Helsel (<a href="#ref-helsel2006" role="doc-biblioref">2006</a>)</span> reviewed two decades of work on both and is blunt about the first: substituted values using any fraction between 0 and 0.99 of the detection limit are “equivalently arbitrary, equivalently precise, equivalently wrong”. Deleting is worse, because it removes the observations at the low end and biases every subsequent estimate of location upwards.</p>
<p><code>bayesnec</code> passes through the <code>cens()</code> term from <code>brms</code>, so the bound can be declared instead of disguised:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>y <span class="sc">|</span> <span class="fu">cens</span>(censoring) <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>censoring</code> is a column in the data rather than a constant, because in a concentration-response dataset only some rows are censored. It takes the values <code>"none"</code>, <code>"left"</code>, <code>"right"</code> or <code>"interval"</code>. Interval censoring takes a second argument giving the upper bound, as <code>cens(censoring, upper)</code>.</p>
<p>The response column holds the bound. On a left-censored row, the number in the response column is the value the truth is known to be at or below, rather than zero and rather than a guess at the unknown truth.</p>
<p>What this changes is the contribution each row makes to the likelihood. An ordinary row contributes a density at a point, which falls away as the fitted curve departs from it, so a substituted value actively pulls the curve back towards the number that was substituted. A censored row instead contributes the probability of falling at or below the bound. As the curve descends past the bound that probability rises towards 1 and then <em>saturates</em>: the curve is neither rewarded for passing further below nor penalised for it.</p>
</section>
<section id="zeros" class="level2">
<h2 class="anchored" data-anchor-id="zeros">Zeros</h2>
<p>A zero needs a different treatment depending on what produced it, and the three cases are distinguishable from the design rather than from the data.</p>
<p>A zero that is a measurement below the resolution of the method is censored, and belongs in the previous section.</p>
<p>A zero that marks a distinct event is <strong>structural</strong>. An organism that died did not grow slowly; its growth is undefined rather than small. A response of this kind has two processes behind it, one deciding whether the event occurred and one generating the response when it did not, and a <strong>two-block</strong> model fits both.</p>
<p>A zero that is an ordinary draw from a distribution admitting zeros is not evidence of anything at all. <span class="citation" data-cites="warton2005">Warton (<a href="#ref-warton2005" role="doc-biblioref">2005</a>)</span> makes the point directly: many zeros does not mean zero inflation, and a Poisson or negative binomial with a low mean produces plenty of them. Fit the simpler family and check it before reaching for a two-block model. <span class="citation" data-cites="martin2005">Martin et al. (<a href="#ref-martin2005" role="doc-biblioref">2005</a>)</span> sets out how to decide which of the three you are looking at, from what the experiment did rather than from a test.</p>
</section>
<section id="hurdle-and-zero-inflated-models" class="level2">
<h2 class="anchored" data-anchor-id="hurdle-and-zero-inflated-models">Hurdle and zero-inflated models</h2>
<p>Both names describe a two-block model and they are not interchangeable. The distinction is whether the zeros are <strong>observed</strong> or <strong>latent</strong>, and it decides whether the second block is worth interpreting.</p>
<p>Under a <strong>hurdle</strong> the zeros are observed to be structural. The individual died, or the replicate failed, and you know which observations those are. The likelihood then separates exactly into a block for whether the event occurred and a block for the response given that it did not, and both blocks describe a curve you can read a threshold from.</p>
<p>Under <strong>zero inflation</strong> a zero could have come from either component, and nothing in the data says which. The two are therefore weakly separated precisely where the ordinary component is small, which is the high-concentration end that determines the <em>NEC</em>. A threshold fitted to the zero-inflation component there describes a class of observation nobody measured.</p>
<p>The practical rule follows from the design rather than from the data. Where you recorded <em>why</em> each zero occurred, a hurdle is available and its second block means something. Where you did not, zero inflation is the description the data support, and the second block should not be read as a concentration-response curve.</p>
<p><code>bayesnec</code> supplies <code>hurdle_gamma</code> for a positive continuous response with structural zeros, <code>hurdle_poisson</code> and <code>hurdle_negbinomial</code> for counts, and the zero-inflated beta, Poisson and negative binomial:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bayesnec<span class="sc">:::</span>mod_fams)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "gaussian"                  "Gamma"                    
 [3] "poisson"                   "negbinomial"              
 [5] "bernoulli"                 "binomial"                 
 [7] "beta_binomial"             "beta"                     
 [9] "hurdle_gamma"              "zero_inflated_beta"       
[11] "zero_inflated_poisson"     "zero_inflated_negbinomial"
[13] "hurdle_poisson"            "hurdle_negbinomial"       </code></pre>
</div>
</div>
<p><code>bnec_hurdle()</code> and <code>bnec_joint()</code> fit the two blocks. The worked example below fits one; the <a href="https://open-aims.github.io/bayesnec/dev/articles/example6.html"><code>bayesnec</code> article on hurdle and zero-inflated models</a> covers the rest, including the crossed weights of the two model sets and when the joint form is needed rather than the factorised one.</p>
<p>One trap is worth naming even though it is not taught. Fitting the positive part of a count response by dropping the zeros and using an ordinary Poisson is not the same model: with the zeros removed the remaining counts follow a <em>zero-truncated</em> Poisson, so an untruncated fit estimates the wrong quantity. The error grows as the mean falls towards zero, which is the high-concentration end that an <em>NEC</em> or an EC<sub>x</sub> is read from. The equivalent construction for <code>hurdle_gamma</code> is exact, because a gamma distribution has no mass at zero to begin with, which is why the problem appears only for counts.</p>
<section id="a-hurdle-gamma-in-practice" class="level3">
<h3 class="anchored" data-anchor-id="a-hurdle-gamma-in-practice">A hurdle gamma in practice</h3>
<p>The <code>nassarius</code> dataset ships with <code>bayesnec</code> and holds chronic toxicity tests on the tropical marine snail <em>Nassarius dorsatus</em>, one row per individual snail that entered the experiment. The contaminants are anonymised as A to D and the dose units are not stated, so only the relative spacing of doses is preserved, which is all a toxicity estimate depends on. Contaminant A is used here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(nassarius)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>snail <span class="ot">&lt;-</span> <span class="fu">subset</span>(nassarius, contaminant <span class="sc">==</span> <span class="st">"A"</span>)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(snail)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   204 obs. of  6 variables:
 $ contaminant: Factor w/ 4 levels "A","B","C","D": 1 1 1 1 1 1 1 1 1 1 ...
 $ dose       : num  0 0 0 0 0 0 0 0 0 0 ...
 $ tank       : chr  "A-1" "A-1" "A-1" "A-1" ...
 $ alive      : int  1 1 1 1 1 0 1 1 1 1 ...
 $ growth     : num  8.72 28.17 27.28 15.86 19.02 ...
 $ record     : Factor w/ 5 levels "measured","sentinel_code",..: 1 1 1 1 1 2 1 1 1 1 ...</code></pre>
</div>
</div>
<p>The response is growth, which is positive and continuous, so the survivors are a gamma. <code>alive</code> records which snails died, so the zeros are observed rather than inferred and a hurdle is available.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(snail<span class="sc">$</span>alive, snail<span class="sc">$</span>dose, <span class="cf">function</span>(z) <span class="fu">sprintf</span>(<span class="st">"%d of %d"</span>, <span class="fu">sum</span>(z), <span class="fu">length</span>(z)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         0       0.01       0.02       0.04       0.08       0.16       0.31 
"21 of 24" "17 of 18" "18 of 18" "17 of 18" "18 of 18" "18 of 18" "18 of 18" 
      0.63       1.25        2.5         20 
"18 of 18" "18 of 18"  "3 of 18"  "0 of 18" </code></pre>
</div>
</div>
<p>Mortality is concentrated in the top two doses, which hold 33 of the 38 deaths, and is complete at the highest. That is what makes the endpoint worth fitting as two blocks rather than one. A survivors-only analysis of these data would contain 166 snails of the 204 exposed, and the dose of 20 would not appear in it at all, because a dose at which nothing survived contributes no rows. The dose that killed every animal is the most informative one in the experiment and it is the one that dropping the dead removes.</p>
<p>Two preparation steps are needed and both are stated rather than done quietly. The assay references each snail to a baseline mean rather than to its own starting size, so a few survivors are recorded at or below zero; those are measurement noise around a true value near zero rather than deaths, and they are nudged to half the smallest positive growth in the test. And the doses span several orders of magnitude, so the fit is on a log scale, which needs the control placed somewhere other than <code>log(0)</code>: one decade below the lowest tested dose is far enough to read as a control and close enough not to stretch the fitted range.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>pos_min <span class="ot">&lt;-</span> <span class="fu">min</span>(snail<span class="sc">$</span>growth[snail<span class="sc">$</span>growth <span class="sc">&gt;</span> <span class="dv">0</span>])</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>snail<span class="sc">$</span>growth <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(snail<span class="sc">$</span>alive <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> snail<span class="sc">$</span>growth <span class="sc">&lt;=</span> <span class="dv">0</span>, pos_min <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>                       snail<span class="sc">$</span>growth)</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>offset <span class="ot">&lt;-</span> <span class="fu">min</span>(snail<span class="sc">$</span>dose[snail<span class="sc">$</span>dose <span class="sc">&gt;</span> <span class="dv">0</span>]) <span class="sc">/</span> <span class="dv">10</span></span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>snail<span class="sc">$</span>log_dose <span class="ot">&lt;-</span> <span class="fu">log</span>(snail<span class="sc">$</span>dose <span class="sc">+</span> offset)</span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a>back <span class="ot">&lt;-</span> <span class="cf">function</span>(z) <span class="fu">exp</span>(z) <span class="sc">-</span> offset</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>bnec_hurdle()</code> takes the formula for the growth block and fits a survival block alongside it. The same model set is used for both here, and <code>adapt_delta</code> is raised because the survival curve is determined mostly by two doses and samples awkwardly at the default.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>exp_6 <span class="ot">&lt;-</span> <span class="fu">bnec_hurdle</span>(growth <span class="sc">~</span> <span class="fu">crf</span>(log_dose, <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"nec3param"</span>, <span class="st">"ecxll3"</span>)),</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> snail, <span class="at">seed =</span> <span class="dv">333</span>,</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>))</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_6, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_6.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_6.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp_6, <span class="at">xform =</span> back)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Object of class bayesnechurdlefit

   204 individuals exposed; 38 recorded as zero ( 18.6% )

  growth   : gamma -- nec3param, ecxll3 
  survival : bernoulli -- nec3param, ecxll3 

No-effect toxicity estimates
                   Q50 Q2.5 Q97.5
combined (N(S)EC) 0.56 0.21  0.75
growth (N(S)EC)   0.56 0.23  0.75
survival (N(S)EC) 1.72 1.09  2.41

NSEC values appear where a model set contains smooth (ECx) models, which
carry no threshold parameter; N(S)EC is a model-averaged combination
of the two (Fisher et al. 2023).

The combined endpoint is the expected response per individual exposed,
i.e. growth * survival. Use which = to select a component.</code></pre>
</div>
</div>
<p>Three estimates are reported rather than one. <strong>Growth</strong> is the response of the snails that lived, which is what a survivors-only analysis would return. <strong>Survival</strong> is the probability of living to be measured. <strong>Combined</strong> is the expected growth per individual <em>exposed</em>, which is growth multiplied by survival, and it is the endpoint a risk assessment asks about, because an individual that died did not grow.</p>
<p>Growth and survival separate: growth declines from a no-effect estimate of about 0.56 while survival holds to about 1.72, a factor of three. The combined estimate follows growth here, because growth is the more sensitive of the two and the combined endpoint is bounded by whichever declines first.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(exp_6, <span class="at">which =</span> <span class="st">"all"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-nass" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-nass-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Contaminant A as three curves: the combined endpoint, the growth of survivors, and the probability of survival. The predictor is on the log dose scale the fit used.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The right-hand panel is the one a survivors-only analysis cannot produce at any level of effort. Its shape comes almost entirely from the two doses where most snails died, and the highest of those contributes no rows to a dataset of survivors.</p>
<p>The growth block reproduces the mean at every dose and not the spread. Run <code>check_fit()</code> on <code>exp_6$growth</code> and the observed standard deviation is between about 0.4 and 0.65 of the simulated one at the lower doses, and about twice it at the two highest, which is the pattern <em>Modelling dispersion</em> below repairs on a gamma fit. That repair is not yet available here, because <code>bnec_hurdle()</code> copies a <code>disp()</code> term into the survival block as well, where a Bernoulli response has no dispersion parameter for it to model (<a href="https://github.com/open-AIMS/bayesnec/issues/410"><code>bayesnec</code> #410</a>).</p>
</section>
</section>
<section id="preparing-the-response" class="level2">
<h2 class="anchored" data-anchor-id="preparing-the-response">Preparing the response</h2>
<p>Supply the response as it was measured, and match a statistical family to it. The common alternative is to convert it first, to percent inhibition, percent of control or percent of the observed maximum. That conversion introduces error, and the family choice set out above avoids it.</p>
<p>Normalising to the control is conventional in ecotoxicology, usually as <span class="math inline">\(y^0_i = 1 - y_i / \bar{y}_{con}\)</span>, where <span class="math inline">\(\bar{y}_{con}\)</span> is the mean of three to six control replicates. <span class="citation" data-cites="Ritz2026">Ritz et al. (<a href="#ref-Ritz2026" role="doc-biblioref">2026</a>)</span> measured what it does.</p>
<div id="fig-ritz" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ritz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Ritz_etal2026.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ritz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Ritz, Gerhard and Streibig (2026), the source of the measurements in this section.
</figcaption>
</figure>
</div>
<ul>
<li>Every observation is divided by the <em>same random quantity</em>, so the normalised values are correlated and the sampling variability of the divisor is discarded.</li>
<li>The expected value of a reciprocal is not the reciprocal of an expected value, so the inhibition trend is biased downwards and the effect concentrations read off it are biased upwards.</li>
<li>Nothing is lost by leaving the response alone. The concentration at which inhibition rises by <span class="math inline">\(x\)</span> per cent is the concentration at which the response falls by <span class="math inline">\(x\)</span> per cent, and the second is what <code>ecx()</code> returns by default.</li>
<li>Dividing by the observed maximum instead of the control mean is worse again, and it forces one observation onto the boundary of the beta’s support.</li>
<li>Where a divisor is unavoidable it must be a constant fixed in advance of the analysis, such as a physiological or design ceiling.</li>
<li><code>bnec()</code> looks for both practices and reports them.</li>
</ul>
<p>Many proportional responses need no divisor at all. The maximum quantum yield used in module 7 is a genuine physical proportion, as is a survival fraction or a bleached-area fraction, and these are modelled as they stand.</p>
<div class="callout callout-style-default callout-note callout-titled" title="The size of the error">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The size of the error
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>From the simulation of an ED10 with six control replicates in <span class="citation" data-cites="Ritz2026">Ritz et al. (<a href="#ref-Ritz2026" role="doc-biblioref">2026</a>)</span>: normalising gave a bias of 6.8% and a coefficient of variation of 26.4%, against 2.1% and 12.7% for the same quantity estimated from the raw response, and nominal 95% intervals covered at 90% rather than 95%. In their simulation of the other experimental design, with a single control replicate, the coverage of the normalised analysis fell to 57%.</p>
<p><code>ecx()</code> returns a decline relative to the <em>fitted</em> control rather than to an observed control mean, and because it is evaluated separately within every posterior draw the uncertainty about the control level propagates into the credible interval instead of being thrown away.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Division by the observed maximum">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Division by the observed maximum
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Dividing by the observed maximum is worse than dividing by the control mean on three counts. An extreme order statistic is more variable and more biased than a mean of three to six values. The divisor then depends on every treatment rather than on the controls alone, so treated groups partly determine their own denominator. And it forces exactly one observation to exactly 1, which is outside the open interval a beta distribution is defined on, so <code>bnec()</code> has to shift it off the boundary.</p>
<p><code>bnec()</code> detects both practices from the response as supplied. Dividing by the observed maximum leaves a maximum of exactly 1 attained by exactly one observation, and dividing by the control mean leaves the control observations averaging to exactly 1. The first check is suppressed where the response lies on a rational grid, because a genuine count-derived proportion such as 19 of 20 surviving routinely produces a single observation at 1 and is not evidence of anything.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="A divisor fixed in advance">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A divisor fixed in advance
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A response above 1 that has to be modelled with a beta distribution needs a divisor. It must be a constant settled before the analysis: a physiological or design ceiling, or a value from accumulated historical controls. <span class="citation" data-cites="Ritz2026">Ritz et al. (<a href="#ref-Ritz2026" role="doc-biblioref">2026</a>)</span> are explicit that the problem is dividing by something <em>random</em> rather than dividing as such. An EC<sub>x</sub> is unaffected by the choice of a constant divisor, because it is a relative decline from the fitted control, and the same holds for any linear rescaling of the response <span class="citation" data-cites="Weimer2012">(<a href="#ref-Weimer2012" role="doc-biblioref">Weimer et al. 2012</a>)</span>.</p>
</div>
</div>
</div>
<section id="the-motive-for-a-divisor" class="level3">
<h3 class="anchored" data-anchor-id="the-motive-for-a-divisor">The motive for a divisor</h3>
<p>Dividing by the observed maximum is often done for a reason that has nothing to do with normalisation. A response on an arbitrary scale, such as a luminescence reading or a cell count, is divided to put it between 0 and 1 so that a beta distribution can be used, because the beta accommodates variability that changes with the mean and a Gaussian does not.</p>
<p>That reasoning identifies a real problem and answers it indirectly. The problem is that replicate variability at the high concentrations is not the same as at the control. The direct answer is the subject of this module: keep the response on its own scale, choose the family that suits it, and model the variability explicitly where it changes. The sections above covered the choice of family, and the section below covers the <code>disp</code> term for a dispersion that varies across the series.</p>
<p>Doing it that way keeps <code>top</code>, <code>bot</code> and <code>nec</code> in the units the experiment was measured in, avoids the bias <span class="citation" data-cites="Ritz2026">Ritz et al. (<a href="#ref-Ritz2026" role="doc-biblioref">2026</a>)</span> measured, and states the change in variability as something estimated from the data rather than absorbed by a transformation. It also avoids forcing an observation onto the boundary of the beta’s support, which division by a maximum does by construction.</p>
</section>
</section>
<section id="modelling-dispersion" class="level2">
<h2 class="anchored" data-anchor-id="modelling-dispersion">Modelling dispersion</h2>
<p>Everything above chooses a family from what kind of quantity the response is. That is the right way to choose one, and on every dataset in this module the family chosen that way, with its variance free to be estimated, reproduced the <em>mean</em> of the curve at all or nearly all concentrations. On two of them it did not reproduce the spread: the beta fit of the PAM yields and the gamma fit of the luminescence plate fail <code>check_fit()</code> on <code>sd_ratio</code>, and so does the growth block of the hurdle fit. In none of the three does a different equation repair it: every equation <code>bnec()</code> admits for each of them was fitted and checked (<code>scripts/screen_module5_models.R</code>). Modelling the dispersion is the remedy, and it is the last step in choosing how a response is modelled rather than an optional refinement.</p>
<p>The reason a correct family can still fail is an assumption made by default and rarely stated. A fit holds the dispersion parameter of the chosen family constant across the whole concentration-response curve. For a Gaussian response that assumes replicate variability is the same at every concentration; for the other families it assumes the coefficient of variation, or the precision, does not change with the mean. Real series often violate it, because variability at a concentration that has killed most of the organisms is not the variability of an untreated control.</p>
<p>Where that is wrong the consequences fall on the credible intervals of the toxicity estimates, and they fall unevenly, because the assumed variability is too large at one end of the series and too small at the other. The <em>NSEC</em> is affected most, because its reference is a quantile of the control posterior, and the width of that posterior is the variability the fit estimated at the control.</p>
<p>The <code>disp</code> term relaxes the assumption, letting the spread vary rather than taking one value for the whole series:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>) <span class="sc">+</span> <span class="fu">disp</span>(<span class="sc">~</span>x)         <span class="co"># varies along the predictor</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>y <span class="sc">~</span> <span class="fu">crf</span>(x, <span class="at">model =</span> <span class="st">"nec4param"</span>) <span class="sc">+</span> <span class="fu">disp</span>(<span class="st">"power"</span>)    <span class="co"># varies with the fitted mean</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Reach for it when the check has failed rather than as a routine addition, and exclude three other explanations of the failure first. A variance function will absorb any cause of apparent heteroscedasticity and report a confident slope regardless. Substituted or censored values cluster at one end of the series and their spread is easily mistaken for changing variability. A misspecified family produces the same appearance, since a constant coefficient of variation is what a gamma already implies, so check the family before adding a term to repair it. And a curve that is systematically wrong in one region leaves large residuals there, which a variance function will describe as noise rather than as lack of fit.</p>
<section id="a-worked-case" class="level3">
<h3 class="anchored" data-anchor-id="a-worked-case">A worked case</h3>
<p>The gamma fit of the luminescence plate is the clearer of the two, because its curve is reproduced and only its spread is not, so whatever <code>disp()</code> changes cannot be confused with a change in the curve. The baseline is <code>exp_4</code> from the gamma section, which fits one equation, <code>ecxll3</code>, so the two fits below differ in the dispersion sub-model and in nothing else.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>exp_4_const <span class="ot">&lt;-</span> exp_4</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">333</span>)</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>exp_4_disp <span class="ot">&lt;-</span> <span class="fu">bnec</span>(rlu <span class="sc">~</span> <span class="fu">crf</span>(log.x, <span class="at">model =</span> <span class="st">"ecxll3"</span>) <span class="sc">+</span> <span class="fu">disp</span>(<span class="st">"power"</span>),</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> lum_data, <span class="at">family =</span> <span class="st">"Gamma"</span>, <span class="at">seed =</span> <span class="dv">333</span>)</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(exp_4_disp, <span class="at">file =</span> <span class="st">"vignettes/fits/m5_exp_4_disp.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"vignettes/fits/m5_exp_4_disp.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>disp("power")</code> is used rather than <code>disp(~ log.x)</code> because the coefficient of variation here rises as the fitted mean falls, which is a relationship with the mean rather than with the predictor. The same term repaired the beta fit of the PAM yields above. Both forms are available and the check is what decides between them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>cf_const <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_4_const)</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_const)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-disp-checkfit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disp-checkfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-disp-checkfit-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disp-checkfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: <code>check_fit()</code> on the constant-dispersion gamma fit.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>cf_disp <span class="ot">&lt;-</span> <span class="fu">check_fit</span>(exp_4_disp)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cf_disp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-disp-checkfit-power" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disp-checkfit-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="5Response_data_and_statistical_distributions_files/figure-html/fig-disp-checkfit-power-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disp-checkfit-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: The same check with <code>disp("power")</code>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Groups falling outside their bar on spread drop from 2 of 11 to 0, and on the mean 1 and 1 fall outside in the two fits. The count of points outside a bar understates the change, because four wells per concentration give wide bars; the table below shows it directly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The `group` column holds the logged predictor, because that is the scale the</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="co"># model was fitted on. It is returned to concentrations here so the table can be</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read against the coefficients of variation above.</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">conc =</span> <span class="fu">signif</span>(<span class="fu">exp</span>(<span class="fu">as.numeric</span>(cf_const<span class="sc">$</span>group)), <span class="dv">3</span>),</span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">obs_sd =</span> <span class="fu">round</span>(cf_const<span class="sc">$</span>obs_sd),</span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">sim_sd_const =</span> <span class="fu">round</span>(cf_const<span class="sc">$</span>sim_sd),</span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">sim_sd_disp =</span> <span class="fu">round</span>(cf_disp<span class="sc">$</span>sim_sd),</span>
<span id="cb112-9"><a href="#cb112-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_ratio_const =</span> <span class="fu">round</span>(cf_const<span class="sc">$</span>sd_ratio, <span class="dv">2</span>),</span>
<span id="cb112-10"><a href="#cb112-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_ratio_disp =</span> <span class="fu">round</span>(cf_disp<span class="sc">$</span>sd_ratio, <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      conc obs_sd sim_sd_const sim_sd_disp sd_ratio_const sd_ratio_disp
1   0.0065  32124        92298       42892           0.35          0.75
2   0.0360  31435        90715       41284           0.35          0.76
3   0.0639  17361        91563       42617           0.19          0.41
4   0.1210  32500        88440       41882           0.37          0.78
5   0.2360  19865        90407       42299           0.22          0.47
6   0.4670  54700        84009       40114           0.65          1.36
7   0.9290  25240        68351       36150           0.37          0.70
8   1.8500  14316        46173       30957           0.31          0.46
9   3.6900  27680        21540       22028           1.29          1.26
10  7.3800  13368         7136       12893           1.87          1.04
11 14.8000   3977         2225        6759           1.79          0.59</code></pre>
</div>
</div>
<p>Read the two <code>sim_sd</code> columns against <code>obs_sd</code>. The observed spread stays between about 14,000 and 55,000 over the first eight concentrations and falls to 3,977 at the highest. The spread the constant-dispersion fit simulates tracks the fitted mean instead, falling from 92,298 at the lowest concentration to 2,225 at the highest, a 41-fold decline. That is what a fixed coefficient of variation obliges it to do. The consequence is <code>sd_ratio</code> as low as 0.19 over the lower part of the series, where the fit simulates up to five times the observed spread, and above 1 at the top, where it simulates too little. With <code>disp("power")</code> the simulated spread falls less steeply than the mean, from 42,892 to 6,759, and the ratio lies between 0.41 and 1.36.</p>
<p>The reason this matters is the estimate rather than the diagnostic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="st">`</span><span class="at">constant dispersion</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">nsec</span>(exp_4_const, <span class="at">xform =</span> exp),</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">disp("power")</span><span class="st">`</span>       <span class="ot">=</span> <span class="fu">nsec</span>(exp_4_disp, <span class="at">xform =</span> exp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Q50      Q2.5     Q97.5
constant dispersion 0.4192010 0.1728633 0.5741229
disp("power")       0.3019244 0.1254368 0.4111826</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="st">`</span><span class="at">constant dispersion</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ecx</span>(exp_4_const, <span class="at">ecx_val =</span> <span class="dv">10</span>, <span class="at">xform =</span> exp),</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">disp("power")</span><span class="st">`</span>       <span class="ot">=</span> <span class="fu">ecx</span>(exp_4_disp, <span class="at">ecx_val =</span> <span class="dv">10</span>, <span class="at">xform =</span> exp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Q50      Q2.5     Q97.5
constant dispersion 0.5730841 0.4811875 0.6779384
disp("power")       0.6069044 0.5197436 0.7058821</code></pre>
</div>
</div>
<p>The <em>NSEC</em> falls from 0.42 to 0.30 mg/L, while the EC<sub>10</sub> changes only from 0.57 to 0.61. The EC<sub>10</sub> is read from the fitted curve, which the dispersion sub-model barely changes; the <em>NSEC</em> is read against the spread of the control. The direction is the one module 3 sets out under the <em>NSEC</em> and module 7 measures on real data: a fit simulating too much variability at the control gives the control posterior too much width, which places the significance reference lower, and a reference placed lower is crossed further along the curve. The constant-dispersion fit therefore reports the less protective of the two figures, and nothing in its sampler diagnostics says so. <code>check_sampling()</code> passes on both.</p>
<p>A guideline value derived from the first <em>NSEC</em> would be 1.4 times the one derived from the second, on the same data and the same equation. The difference is whether the fit was allowed to describe the spread, together with the prior on the dispersion coefficients that the sub-model adds.</p>
<p>Two cautions. This is one plate of a design that has thirty-three, and module 8 fits the plate structure rather than subsetting to one. And a repair as complete as this one is the exception. On the PAM yields above, two of six concentrations remain just outside their bars after the term is added, and on the ametryn data in module 7 one of eight remains flagged. Read the diagnostic after adding the term rather than assuming it has done its work.</p>
</section>
</section>
<section id="open-questions" class="level2">
<h2 class="anchored" data-anchor-id="open-questions">Open questions</h2>
<p>The families implemented in <code>bayesnec</code> cover the common cases in concentration-response work, and choosing between them from the kind of quantity the response is reproduced the mean of the curve at all or nearly all concentrations on every dataset fitted here.</p>
<p>Two things follow for practice. Check which distribution was used, because <code>bnec()</code> infers one where it is not told. And check that it reproduces the variability in the data as well as the mean. The beta and gamma fits in this module did not, whatever equation was used, and both were brought into agreement by modelling the dispersion; the growth block of the hurdle fit did not either, and cannot yet be repaired that way. The negative binomial and Gaussian fits reproduced both on the algal data, and on those data the equation mattered as much as the family. That second check is <code>check_fit()</code>, and module 7 runs it inside a complete analysis and reports what it found.</p>
<p>What is not settled is how far a dispersion sub-model should be taken. A variance function absorbs any cause of apparent heteroscedasticity, so a fit that passes after one has been added has not thereby been validated. The sections above reach for it only where the family was already defensible and the check had already failed, which is the narrowest use it has.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-fisherfox2023" class="csl-entry" role="listitem">
Fisher, Rebecca, and David R. Fox. 2023. <span>“Introducing the No-Significant-Effect Concentration.”</span> <em>Environmental Toxicology and Chemistry</em> n/a (n/a). https://doi.org/<a href="https://doi.org/10.1002/etc.5610">https://doi.org/10.1002/etc.5610</a>.
</div>
<div id="ref-fisheretal2023" class="csl-entry" role="listitem">
Fisher, Rebecca, David R. Fox, Andrew P. Negri, Joost van Dam, Florita Flores, and Darren Koppel. 2023. <span>“Methods for Estimating No-Effect Toxicity Concentrations in Ecotoxicology.”</span> <em>Integrated Environmental Assessment and Management</em>, ahead of print. https://doi.org/<a href="https://doi.org/10.1002/ieam.4809">https://doi.org/10.1002/ieam.4809</a>.
</div>
<div id="ref-flores2021" class="csl-entry" role="listitem">
Flores, F., J. A. Marques, S. Uthicke, et al. 2021. <span>“Combined Effects of Climate Change and the Herbicide Diuron on the Coral <em>Acropora Millepora</em>.”</span> <em>Marine Pollution Bulletin</em> 169: 112582. <a href="https://doi.org/10.1016/j.marpolbul.2021.112582">https://doi.org/10.1016/j.marpolbul.2021.112582</a>.
</div>
<div id="ref-helsel2006" class="csl-entry" role="listitem">
Helsel, Dennis R. 2006. <span>“Fabricating Data: How Substituting Values for Nondetects Can Ruin Results, and What Can Be Done about It.”</span> <em>Chemosphere</em> 65 (11): 2434–39. <a href="https://doi.org/10.1016/j.chemosphere.2006.04.051">https://doi.org/10.1016/j.chemosphere.2006.04.051</a>.
</div>
<div id="ref-luter2025" class="csl-entry" role="listitem">
Luter, Heidi M., Katarina Damjanovic, Marie C. Thomas, Rebecca Fisher, Lone Høj, and Andrew P. Negri. 2025. <span>“A Bioluminescent Bacterial Toxicity Assay for Tropical Marine Environments.”</span> <em>Environmental Toxicology</em>, ahead of print. <a href="https://doi.org/10.1002/tox.70003">https://doi.org/10.1002/tox.70003</a>.
</div>
<div id="ref-martin2005" class="csl-entry" role="listitem">
Martin, Tara G., Brendan A. Wintle, Jonathan R. Rhodes, et al. 2005. <span>“Zero Tolerance Ecology: Improving Ecological Inference by Modelling the Source of Zero Observations.”</span> <em>Ecology Letters</em> 8 (11): 1235–46. <a href="https://doi.org/10.1111/j.1461-0248.2005.00826.x">https://doi.org/10.1111/j.1461-0248.2005.00826.x</a>.
</div>
<div id="ref-oecd2026tg201" class="csl-entry" role="listitem">
OECD. 2026. <em>Test No. 201: Freshwater Alga and Cyanobacteria, Growth Inhibition Test</em>. OECD Guidelines for the Testing of Chemicals, Section 2. OECD Publishing. <a href="https://doi.org/10.1787/9789264069923-en">https://doi.org/10.1787/9789264069923-en</a>.
</div>
<div id="ref-Ritz2026" class="csl-entry" role="listitem">
Ritz, Christian, Daniel Gerhard, and Jens C. Streibig. 2026. <span>“<span class="nocase">Better alternatives than normalizing to control: case studies with algae toxicity and dose-response analysis</span>.”</span> <em>Environmental and Ecological Statistics</em> 33 (1): 35–55. <a href="https://doi.org/10.1007/s10651-025-00698-y">https://doi.org/10.1007/s10651-025-00698-y</a>.
</div>
<div id="ref-warton2005" class="csl-entry" role="listitem">
Warton, David I. 2005. <span>“Many Zeros Does Not Mean Zero Inflation: Comparing the Goodness-of-Fit of Parametric Models to Multivariate Abundance Data.”</span> <em>Environmetrics</em> 16 (3): 275–89. <a href="https://doi.org/10.1002/env.702">https://doi.org/10.1002/env.702</a>.
</div>
<div id="ref-Weimer2012" class="csl-entry" role="listitem">
Weimer, Marc, Xiaoqi Jiang, Oriana Ponta, Sven Stanzel, Alexius Freyberger, and Annette Kopp-Schneider. 2012. <span>“<span class="nocase">The impact of data transformations on concentration-response modeling</span>.”</span> <em>Toxicology Letters</em> 213 (2): 292–98. <a href="https://doi.org/10.1016/j.toxlet.2012.07.012">https://doi.org/10.1016/j.toxlet.2012.07.012</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/open-aims\.github\.io\/cr_modelling_training\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../vignettes/4Model_averaging_and_multimodel_inference.html" class="pagination-link" aria-label="4. Model averaging">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">4. Model averaging</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../vignettes/6Priors_and_Bayesian_inference.html" class="pagination-link" aria-label="6. Priors and Bayesian inference">
        <span class="nav-page-text">6. Priors and Bayesian inference</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Australian Institute of Marine Science — development build, not reviewed</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/open-AIMS/cr_modelling_training/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>