{
  "hash": "087bed74ce66bd0901a5eb80e7d553d8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Response data and statistical distributions\"\nsubtitle: \"Matching the statistical family to the response being modelled\"\nbibliography: bayesnec.bib\n---\n\n\n\n## Background\n\nConcentration-response data are of varied kinds, and the measured response\nfollows a correspondingly wide range of natural distributions. The examples\nbelow are drawn at random to show the shape of each.\n\n**Binary**, modelled by the binomial or beta-binomial. Individual survival,\n0 0 1 1 0 1 1 0 0 0, or counts of survivors out of a\ntotal.\n\n**Bounded continuous**, modelled by the beta. Proportions or ratios that are not\ncounts out of a total: 0.458 0.861 0.246 0.043 0.1 0.697 0.232 0.74 0.866 0.704.\n\n**Counts**, modelled by the Poisson or negative binomial. Numbers of whole\nanimals: 7 2 3 3 3 8 6 4 3 1.\n\n**Positive continuous**, modelled by the gamma. Growth where shrinkage is not\npossible: 0.92 5.11 0.46 5.13 1.67 8.9 0.66 0.62 0.82 1.43.\n\n**Unbounded continuous**, modelled by the Gaussian. Growth where shrinkage is\npossible: 0.08 -0.22 -0.94 0.04 -0.12 0.16 -0.8 -0.09 0.88 0.06.\n\n## Generalised modelling\n\nGeneralised modelling fits data with a statistical distribution matched to the\nnatural range and scaling of the response, rather than assuming one.\n\nFitting a linear model with `lm()` assumes a Gaussian distribution, and so do\nmany non-linear routines such as `nls()`. The normality assumption familiar from\nanalysis of variance is the most common case of non-generalised modelling. It is\nsometimes reasonable, but it was adopted largely because it makes the\nmathematics of fitting and interval estimation tractable.\n\nThat constraint no longer applies. Matching the response to an appropriate\nstatistical family is now standard practice, and the theory is covered well\nelsewhere; this module is concerned with making the right choice in `bayesnec`\nrather than with the underlying mathematics.\n\n![](images/glmbooks.jpg){width=100% fig-align=\"center\"}\n\n## Families available in `brms`\n\n`brms` supports many families, including most of those in the base `stats`\npackage that other R fitting routines use:\n\n![](images/statsfams.jpg){width=100% fig-align=\"center\"}\n\nand a number that are specific to it:\n\n![](images/brmsfams.jpg){width=60% fig-align=\"center\"}\n\n## Link functions\n\nEvery statistical family has a link function. A generalised linear model relates\nthe linear predictor to the response through it: a logit link, for example,\nmaps the probabilities of a binary response onto an unbounded continuous scale.\nGeneralised linear models were formulated by Nelder and Wedderburn as a\nunification of linear regression, logistic regression and Poisson regression,\nwith maximum likelihood estimation of the parameters. Logistic regression is the\nfamiliar case.\n\nThe native link for a family (logit for the binomial, log for the Poisson)\nimposes a non-linear transformation. Concentration-response models are already\nnon-linear and do not use linear predictors, so any further non-linearity from a\nlink changes the model being fitted.\n\n`bayesnec` therefore assigns the identity link to every family. The Bayesian\nmachinery makes this possible, because the parameters can be estimated without\nmapping the response onto an unbounded scale. It keeps `top`, `bot` and `nec` on\nthe scale of the response, where they are directly interpretable. A log or logit\nlink is used only where it is supplied in a family object passed to `bnec()`,\nwhich is why three links are listed below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayesnec:::supported_links()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"identity\" \"log\"      \"logit\"   \n```\n\n\n:::\n:::\n\n\nThis matters when comparing a `bayesnec` fit against a `brms` model written by\nhand. `brms` defaults to logit for a beta response and log for a Poisson, so\nunless the link is passed explicitly the two are different models. ECx and NSEC\nestimates from a fit using any link other than the identity may not behave as\nexpected.\n\n## Families implemented in `bayesnec`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(bayesnec:::mod_fams)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"gaussian\"                  \"Gamma\"                    \n [3] \"poisson\"                   \"negbinomial\"              \n [5] \"bernoulli\"                 \"binomial\"                 \n [7] \"beta_binomial\"             \"beta\"                     \n [9] \"hurdle_gamma\"              \"zero_inflated_beta\"       \n[11] \"zero_inflated_poisson\"     \"zero_inflated_negbinomial\"\n[13] \"hurdle_poisson\"            \"hurdle_negbinomial\"       \n```\n\n\n:::\n:::\n\n\nThe first eight are the ordinary families, and all of them except `bernoulli`\nare covered below. The last six (`hurdle_gamma`, `hurdle_poisson`,\n`hurdle_negbinomial` and the three zero-inflated families) handle responses with\nan excess of zeros, which *Hurdle and zero-inflated models* below introduces.\n\nAdding a family is not trivial, because `bayesnec` generates priors and initial\nvalues by algorithms specific to each one. Requests go to the\n[issue tracker](https://github.com/open-AIMS/bayesnec/issues).\n\n## Default behaviour\n\nWith default settings `bnec` infers the most likely distribution from the\nresponse. That inference must be checked rather than trusted. Two questions\ndecide whether a distribution is adequate:\n\n- does it capture the variability present in the data?\n- does it produce sensibly shaped credible bounds across the whole curve?\n\nGetting the dispersion right matters directly for toxicity estimates, because it\nsets the width of their intervals. It matters most for the *NSEC*, which is\ndefined against the estimated variability in the control: overstate that\nvariability and the estimate becomes less conservative\n[@fisheretal2023; @fisherfox2023].\n\nThe sections below fit a threshold and a smooth model to each of several\nresponse types. Every one uses measured data: the binomial pair come from\n[Gerard Ricardo's\nrepository](https://github.com/gerard-ricardo/NECs/blob/master/NECs) and the\nrest are published datasets shipping with `bayesnec`, which `?alga`,\n`?coral_pam` and `?lum31` document. Nothing below is simulated, and that\nmatters for what the checks show: a constructed response passes or fails its\nown family for reasons of the construction, and tells a participant nothing\nabout the data they will bring.\n\nOne result runs through all of them. Choosing the family from the kind of\nquantity the response is gets the *mean* of the curve right, and that is what the family is for. It does not\nfollow that the family describes the *spread*, because every one of these\nfamilies ties the spread it simulates to the mean through at most one parameter,\nheld constant across the series, and a real concentration series is rarely that tidy.\n*Modelling dispersion*, at the end of the module, is the general repair, and\nmost of the sections below hand to it.\n\n*Preparing the response*, near the end of the module, covers what to do where a\nresponse has already been divided by its control mean or by its observed\nmaximum.\n\n## Binomial\n\nA response is binomial when it is a count out of a total, such as the number of\nsurvivors out of a number exposed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom_data <- read.csv(\"vignettes/example_binomial.csv\") |>\n  mutate(log.x = log(raw_x))\nsummary(binom_data$raw_x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.10   10.94   37.50   99.23  125.00  400.00 \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(binom_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  raw_x suc tot     log.x\n1   0.1 101 175 -2.302585\n2   0.1 106 112 -2.302585\n3   0.1 102 103 -2.302585\n4   0.1 112 114 -2.302585\n5   0.1  58  69 -2.302585\n6   0.1 158 165 -2.302585\n```\n\n\n:::\n:::\n\n\nThe predictor runs from 0.1 to 400 and is strongly right skewed, which is\ntypical of a dilution series. Transforming the predictor, usually by a\nlogarithm, often makes fitting more stable, and the design is generally\nlogarithmic in any case, so this example is fitted on `log.x`. Estimates then\ncome back on the log scale and are returned to concentrations with the `xform`\nargument of `nec()`, `nsec()` and `ecx()`, which module 7 works through.\n\n`suc` holds the number of successes and `tot` the number of trials.\n\nFor a binomial or beta-binomial response the formula takes a `trials` term,\nexactly as in `brms`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuc | trials(tot) ~ crf(log.x, model = \"your_model\")\n```\n:::\n\n\nThe column to the left of the `|` holds the successes (survivors, fertilised\neggs) and the one inside `trials()` the total associated with each. The names\nare whatever they are in your data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_1nec <- bnec(suc | trials(tot) ~ crf(log.x, model = \"nec3param\"),\n                 data = binom_data, seed = 333)\n\nsave(exp_1nec, file = \"vignettes/fits/m5_exp_1nec.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_1nec.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_1nec)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting all 'trials' variables to 1 by default if not specified otherwise.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](5Response_data_and_statistical_distributions_files/figure-html/fig-binom-nec-1.png){#fig-binom-nec width=672}\n:::\n:::\n\n\nThe credible bounds are very tight. The threshold model itself fits reasonably\nand the *NEC* is in a plausible place.\n\n### The dispersion screen\n\nBounds that look too tight are a judgement by eye, and the judgement can be made\nproperly. `dispersion()` compares the variability in the data against the\nvariability the fitted model implies:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion(exp_1nec, summary = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimate     Q2.5    Q97.5    P(>1) \n17.56449 11.99124 27.08505  1.00000 \n```\n\n\n:::\n:::\n\n\nFor each posterior draw it forms the ratio of the observed to the simulated sum\nof squared Pearson residuals, and summarises those ratios to a median, a 95%\ninterval, and `P(>1)`, the posterior probability that the ratio exceeds 1. A\nvalue near 1 means the family's variance assumption holds. A value well above 1\nmeans the data are more variable than the model allows, which is\n**over-dispersion**.\n\nRead `P(>1)` rather than the median, because a point estimate says nothing about\nhow well determined it is. The statistic is symmetric, so `1 - P(>1)` is the\nposterior probability of under-dispersion, which nothing else reports.\n\nHere the ratio is about 18 with a 95% interval well clear of 1, and `P(>1)` is 1.\nThe data are roughly eighteen times more variable than a binomial allows, which\nis why the credible bounds above are as narrow as they are. The eye was right in\nthis case, and the number is what would be reported.\n\nTwo limitations apply. Each draw compares one observed residual sum against a\nsingle simulated replicate, so the spread of the result is dominated by\nsimulation noise rather than by uncertainty about a dispersion parameter; on a\nsmall design it will detect gross over-dispersion and little else. And the screen\nis conditional on the model it was computed from, because a dispersion ratio\ncannot distinguish genuine over-dispersion from a shape that fits badly. Check\nthat the screening fit sampled adequately, with `check_sampling()`, before\nrelying on the number it reports.\n\n`dispersion()` is defined for the binomial and Poisson families only, and returns\nan empty vector for any other. Those two are the families whose variance is fixed\nby their mean, so they are the only ones for which over-dispersion is a question\nabout the family rather than a parameter the fit estimates.\n\nFitting a smooth curve to the same data instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_1ecx <- bnec(suc | trials(tot) ~ crf(log.x, model = \"ecxll3\"),\n                 data = binom_data, seed = 333)\n\nsave(exp_1ecx, file = \"vignettes/fits/m5_exp_1ecx.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_1ecx.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_1ecx)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting all 'trials' variables to 1 by default if not specified otherwise.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](5Response_data_and_statistical_distributions_files/figure-html/fig-binom-ecx-1.png){#fig-binom-ecx width=672}\n:::\n:::\n\n\n## Beta-binomial\n\nThe bounds above are implausibly narrow for data of this kind. A binomial\ndistribution has a single parameter, so its variance is fixed by its mean. Real\ncounts out of a total are usually more variable than that, because the\nindividuals within a replicate are not independent: a batch of eggs shares a\nparent, a container shares its conditions. This is over-dispersion.\n\nThe beta-binomial adds a second parameter and estimates the extra variation\nrather than assuming it away.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_1b <- bnec(suc | trials(tot) ~ crf(log.x, model = c(\"ecxll3\", \"nec3param\")),\n               data = binom_data, family = \"beta_binomial\", seed = 333)\n\nsave(exp_1b, file = \"vignettes/fits/m5_exp_1b.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_1b.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_1b, all_models = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting all 'trials' variables to 1 by default if not specified otherwise.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\nSetting all 'trials' variables to 1 by default if not specified otherwise.\n\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](5Response_data_and_statistical_distributions_files/figure-html/fig-betabinom-1.png){#fig-betabinom width=672}\n:::\n:::\n\n\nThe bounds are now much wider, and they are a better description of the scatter\nin the data.\n\nThe beta-binomial mixes the success probability over a beta distribution, and\nmixing can only *add* variance. It therefore addresses over-dispersion and does\nnothing for the opposite case. A screen pointing below 1 is telling you something\nabout the fit, the design or the process that generated the data, rather than\nabout the family.\n\n`bayesnec` once supplied this as a custom family called `beta_binomial2`,\nbecause `brms` did not provide one natively. It does now, and the family is\nnamed `beta_binomial`; code written against `beta_binomial2` will no longer run.\n\n## Checking the fit against the data\n\nThe two sections above chose between two families by eye and then by a\ndispersion ratio. Neither generalises: the eye is unreliable, and `dispersion()`\nis defined for the binomial and Poisson alone. `check_fit()` is the check that\napplies to every family, and it is what the rest of this module uses.\n\nA dispersion ratio is one number for the whole fit, and one number can hide a\nmodel that is right on average and wrong where it matters. `check_fit()`, named\nin module 2, makes the same comparison within concentration groups, and on a\nmodel set it reports every equation separately.\n\nWhat it compares is the observed mean within each group of the predictor, and\nthe standard deviation of the residuals about the fitted curve, against the same\ntwo statistics computed from datasets simulated by the fitted model. A family that cannot reproduce those two\nnumbers across the concentration range is the wrong family for the response,\nwhatever it says about the kind of quantity the response is. The control group\nmatters most, because both `nsec()` and `ecx()` read their reference from the\nfitted mean there, so an error in the control propagates into every estimate the\nanalysis reports.\n\nRun on the binomial fit from the section above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_1nec <- check_fit(exp_1nec)\ncf_1nec\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              group n obs_mean sim_mean mean_ratio ppp_mean obs_sd sim_sd\n1 -2.30258509299405 6  106.167  102.000      1.041    0.010 24.642  3.861\n2  1.83258146374831 6  103.667  100.167      1.035    0.031 14.344  3.939\n3  2.52572864430826 6   72.833   77.500      0.940    0.999 24.383  3.345\n4   3.2188758248682 6   85.167   81.333      1.047    0.012 11.478  3.451\n5  3.91202300542815 6   75.500   82.833      0.911    1.000 20.819  3.497\n6  4.60517018598809 6   61.500   60.500      1.017    0.371 29.085  4.782\n7  5.29831736654804 6   19.500   22.333      0.873    0.906 13.147  3.975\n8  5.99146454710798 6    9.167    7.667      1.196    0.158  3.973  2.464\n  sd_ratio ppp_sd control\n1    6.383  0.000    TRUE\n2    3.641  0.000   FALSE\n3    7.289  0.000   FALSE\n4    3.326  0.000   FALSE\n5    5.953  0.000   FALSE\n6    6.082  0.000   FALSE\n7    3.308  0.000   FALSE\n8    1.612  0.062   FALSE\n\nThe control group is flagged. nsec() reads its reference from the \ncontrol, so this is the row most likely to move a reported \nno-effect concentration. See ?check_fit.\n```\n\n\n:::\n:::\n\n\n`obs_sd` and `sim_sd` are the observed and simulated residual spread within a group, and\n`ppp_sd` is the proportion of simulated datasets in which the simulated spread\nwas at least as large as the observed one. Read the p-values rather than the\nratios, and read the `control` row first, because both `nsec()` and `ecx()` take\ntheir reference from the fitted mean there.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cf_1nec)\n```\n\n::: {.cell-output-display}\n![`check_fit()` on the binomial fit. Each point is the observed statistic for one concentration group against the 95% span of what the fit simulates, with location and scale drawn separately.](5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-binom-1.png){#fig-checkfit-binom width=672}\n:::\n:::\n\n\nThe groups are labelled on the logged scale, because that is the scale the model\nwas fitted on: -2.30 is the 0.1 control and 5.99 the highest dose of 400. Seven\nof the eight points on the scale panel sit above their bar, `sd_ratio` runs from\n1.6 to 7.3, and `ppp_sd` is 0.000 in seven groups. Four of the eight points on\nthe location panel sit outside their bar as well, because a variance held too low\nleaves the simulated mean too tightly determined to contain the observed one.\nThis is the dispersion ratio of about 18 seen group by group.\n\nThe same check on the beta-binomial fit of the same data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_1b <- check_fit(exp_1b)\ncf_1b\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       model    wi             group n obs_mean sim_mean mean_ratio ppp_mean\n1     ecxll3 0.656 -2.30258509299405 6  106.167  107.500      0.988    0.577\n2     ecxll3 0.656  1.83258146374831 6  103.667  105.167      0.986    0.576\n3     ecxll3 0.656  2.52572864430826 6   72.833   80.500      0.905    0.860\n4     ecxll3 0.656   3.2188758248682 6   85.167   81.500      1.045    0.258\n5     ecxll3 0.656  3.91202300542815 6   75.500   74.000      1.020    0.420\n6     ecxll3 0.656  4.60517018598809 6   61.500   57.667      1.066    0.367\n7     ecxll3 0.656  5.29831736654804 6   19.500   31.333      0.622    0.903\n8     ecxll3 0.656  5.99146454710798 6    9.167   11.333      0.809    0.623\n9  nec3param 0.344 -2.30258509299405 6  106.167  104.167      1.019    0.407\n10 nec3param 0.344  1.83258146374831 6  103.667  102.833      1.008    0.467\n11 nec3param 0.344  2.52572864430826 6   72.833   79.667      0.914    0.831\n12 nec3param 0.344   3.2188758248682 6   85.167   83.000      1.026    0.364\n13 nec3param 0.344  3.91202300542815 6   75.500   81.833      0.923    0.750\n14 nec3param 0.344  4.60517018598809 6   61.500   54.333      1.132    0.263\n15 nec3param 0.344  5.29831736654804 6   19.500   28.833      0.676    0.839\n16 nec3param 0.344  5.99146454710798 6    9.167   14.833      0.618    0.766\n   obs_sd sim_sd sd_ratio ppp_sd control\n1  25.398 14.435    1.759  0.096    TRUE\n2  15.212 14.271    1.066  0.444   FALSE\n3  24.582 11.892    2.067  0.058   FALSE\n4  11.497 13.376    0.860  0.647   FALSE\n5  20.153 16.183    1.245  0.285   FALSE\n6  29.205 20.566    1.420  0.116   FALSE\n7  14.449 19.532    0.740  0.754   FALSE\n8   3.550 12.559    0.283  0.962   FALSE\n9  24.874 16.227    1.533  0.149    TRUE\n10 14.658 15.962    0.918  0.578   FALSE\n11 24.475 12.224    2.002  0.057   FALSE\n12 11.373 12.790    0.889  0.594   FALSE\n13 20.758 14.383    1.443  0.165   FALSE\n14 29.356 20.897    1.405  0.123   FALSE\n15 14.110 19.492    0.724  0.772   FALSE\n16  3.475 14.184    0.245  0.984   FALSE\n\nOne or more groups show a posterior predictive p-value beyond \n[0.05, 0.95]. See ?check_fit.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cf_1b)\n```\n\n::: {.cell-output-display}\n![The same check on the beta-binomial fit, reported for each equation in the set.](5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-betabinom-1.png){#fig-checkfit-betabinom width=672}\n:::\n:::\n\n\nNo group is flagged on the mean for either equation. On spread, only the highest\nconcentration is flagged, where the fit simulates three to four times the\nobserved variability. Six replicates at a success proportion below one in ten\nsupply very little information about spread, so this is what the top of a series usually\nlooks like rather than a fault in the family.\n\n`brms::pp_check()` shows the same comparison as distributions rather than as\nsummary statistics, and module 7 uses it on a continuous response. The grouped\nform is the one to use, `type = \"dens_overlay_grouped\"` for a continuous response\nand `type = \"bars_grouped\"` for a discrete one: pooled over the whole dataset a\nmodel can match the overall distribution while being wrong at every\nconcentration.\n\n## Beta\n\nA response bounded between 0 and 1 that is not a count out of a total is\nmodelled by the beta distribution. Effective quantum yield from PAM fluorometry\nis the common example in coral work: the proportion of absorbed light used in\nphotosynthesis, with no underlying trials to count.\n\n`coral_pam` ships with `bayesnec` and holds yields for the coral *Acropora\nmillepora* exposed to diuron under three climate scenarios [@flores2021]. The\n2018 scenario is used here; module 8 is where a factor covariate of this kind\nis fitted rather than subset away.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(coral_pam)\npam_data <- subset(coral_pam, climate == \"2018\")\ntable(pam_data$diuron)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0 0.29 0.96  2.9  9.6   29 \n  24   24   24   24   24   18 \n```\n\n\n:::\n\n```{.r .cell-code}\nrange(pam_data$yield)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000 0.711\n```\n\n\n:::\n:::\n\n\nSix concentrations, each with three chambers of four fragments read twice, so\ntwenty-four readings at each concentration and eighteen at the highest. The control is\nrecorded as `0`, which is correct and which `log()` cannot take, so an offset is\nadded to the data before fitting, as *The scale of the predictor* in module 7\nsets out. One decade below the lowest exposure is the convention used\nthroughout this course.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npam_data$log.x <- log(pam_data$diuron +\n                        min(pam_data$diuron[pam_data$diuron > 0]) / 10)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_2 <- bnec(yield ~ crf(log.x, model = c(\"ecxwb1\", \"nec3param\")),\n              data = pam_data, seed = 333)\n\nsave(exp_2, file = \"vignettes/fits/m5_exp_2.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_2.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_2, all_models = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](5Response_data_and_statistical_distributions_files/figure-html/fig-beta-1.png){#fig-beta width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp_2$mod_stats[, c(\"model\", \"waic\", \"wi\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              model      waic         wi\necxwb1       ecxwb1 -476.7734 0.99024653\nnec3param nec3param -421.4259 0.00975347\n```\n\n\n:::\n:::\n\n\nThe smooth equation takes almost all of the weight, which is what a yield series\ndeclining from the lowest exposure looks like: there is no flat region for a\nthreshold to sit at the end of. The dispersion columns of `mod_stats`, left out\nabove, hold `NA` for this fit. `dispersion()` is defined for the binomial and Poisson alone, because those are\nthe families whose variance is fixed by their mean; a beta estimates a precision\nparameter of its own, so over-dispersion is not a question about the family\nhere.\n\nThat does not mean the spread is described correctly, and `check_fit()` is what\nsettles it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_2 <- check_fit(exp_2)\ncf_2[, c(\"model\", \"wi\", \"group\", \"mean_ratio\", \"ppp_mean\",\n         \"sd_ratio\", \"ppp_sd\", \"control\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       model   wi               group mean_ratio ppp_mean sd_ratio ppp_sd\n1     ecxwb1 0.99   -3.54045944899566      1.002    0.462    0.560  0.999\n2     ecxwb1 0.99   -1.14256417619729      1.009    0.373    0.381  1.000\n3     ecxwb1 0.99 -0.0110609473594249      0.986    0.663    0.407  1.000\n4     ecxwb1 0.99     1.0746610678456      1.004    0.470    0.471  1.000\n5     ecxwb1 0.99    2.26477937825815      1.460    0.011    2.343  0.000\n6     ecxwb1 0.99    3.36829533031956      1.520    0.073    2.177  0.007\n7  nec3param 0.01   -3.54045944899566      1.043    0.081    0.430  1.000\n8  nec3param 0.01   -1.14256417619729      0.964    0.863    0.303  1.000\n9  nec3param 0.01 -0.0110609473594249      0.959    0.801    0.319  1.000\n10 nec3param 0.01     1.0746610678456      1.372    0.000    0.418  1.000\n11 nec3param 0.01    2.26477937825815      0.851    0.848    1.404  0.058\n12 nec3param 0.01    3.36829533031956      1.241    0.235    1.573  0.084\n   control\n1     TRUE\n2    FALSE\n3    FALSE\n4    FALSE\n5    FALSE\n6    FALSE\n7     TRUE\n8    FALSE\n9    FALSE\n10   FALSE\n11   FALSE\n12   FALSE\n\nThe control group is flagged. nsec() reads its reference from the \ncontrol, so this is the row most likely to move a reported \nno-effect concentration. See ?check_fit.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cf_2)\n```\n\n::: {.cell-output-display}\n![`check_fit()` on the beta fit of PAM yield. The six concentrations are design points with twenty-four readings at most, so no binning is needed.](5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-beta-1.png){#fig-checkfit-beta width=672}\n:::\n:::\n\n\nRead `ecxwb1`, which holds\n0.99 of the weight. The\nlocation panel is inside its bars at every concentration except the second\nhighest, where the observed mean is about one and a half times the fitted one.\nThe scale panel misses at every concentration, and in both directions.\n`sd_ratio` runs from\n0.38 to\n2.34 across the\nseries, and at the control it is\n0.56, so\nthe fit simulates about twice the variability the control fragments show and\nabout half the variability at the two highest concentrations.\n\nThe cause is structural rather than a fault in the fitting. A beta holds one\nprecision parameter for the whole series, and a beta's variance is\n$\\mu(1-\\mu)/(1+\\phi)$, which is largest at a mean of 0.5 and shrinks towards\neither bound. These yields fall from\n0.67 at the control\nto\n0.027\nat the highest concentration, so the spread the fit is obliged to simulate\nchanges across the series whether or not the data's does. Near zero, where some\nfragments had stopped photosynthesising and others had not, the observed spread\nis larger than a beta with the precision the rest of the series needs can\nproduce.\n\nNo choice of equation repairs this. `ecxwb1` was chosen by fitting every\nequation `bnec()` admits for these data (`model = \"all\"`), and every one of them\nmissed on scale at four or more of the six concentrations\n(`scripts/screen_module5_models.R`). The repair is to let the precision vary,\nwhich `disp()` does and *Modelling dispersion* below describes. Here the\nprecision is modelled as a function of the fitted mean:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_2_disp <- bnec(yield ~ crf(log.x, model = \"ecxwb1\") + disp(\"power\"),\n                   data = pam_data, seed = 333)\n\nsave(exp_2_disp, file = \"vignettes/fits/m5_exp_2_disp.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_2_disp.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_2d <- check_fit(exp_2_disp)\nplot(cf_2d)\n```\n\n::: {.cell-output-display}\n![`check_fit()` on the beta fit of PAM yield with `disp(\"power\")`.](5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-beta-disp-1.png){#fig-checkfit-beta-disp width=672}\n:::\n:::\n\n\nWith the precision free to change along the series, the location panel is\ninside its bars at every concentration, and\n2 of the six fall outside on\nscale, against six without it. `sd_ratio` now runs from\n0.69 to\n1.37. The remaining misses are at the\ncontrol and at the fourth concentration, and both lie close to the edge of their\nbar. This is the fit to report an *NSEC* from, rather than `exp_2`.\n\nThe predictor was logged in the formula, as in the binomial example above.\nEstimates returned by `nec()`, `nsec()` and `ecx()` are then on the log scale,\nand `xform` returns them to concentrations, remembering that the offset added\nabove has to be subtracted as part of it.\n\n### Values on the boundary\n\nA beta distribution is defined on the *open* interval between 0 and 1, so a\nresponse recorded as exactly 0 or exactly 1 lies outside it. This is common:\ncomplete mortality at the highest concentration, or complete survival in the\ncontrols, both produce boundary values. These data have them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(pam_data$yield, pam_data$diuron, function(z) sum(z == 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   0 0.29 0.96  2.9  9.6   29 \n   0    0    0    0    3    5 \n```\n\n\n:::\n:::\n\n\n`bayesnec` shifts them rather than refusing the fit. A zero becomes one tenth of\nthe smallest non-zero value in the response, which scales with the data, and a\none is reduced by an absolute 0.001. `bnec_record()` names every value it\naltered, and the fit reports the same thing as a message when it runs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbnec_record(exp_2)$substitutions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     variable             rule n_rows from    to\nzero response shifted off zero      8    0 7e-04\n                                          reason               remedy\nzero a beta distribution cannot represent a zero zero_inflated_beta()\n```\n\n\n:::\n:::\n\n\nThe `remedy` column is the point. Eight readings of exactly zero were shifted to\n7e-04, and every one of\nthem is at the two highest concentrations, where photosynthesis had stopped.\nThose are measurements at a boundary rather than values too small to record, so\nthe analysis above is fitted to shifted data and a methods section has to say\nso. Where the boundary values mean something different from a very small\nresponse, `zero_inflated_beta()` models them as what they are, and the section\non zeros below covers the choice.\n\n## Poisson\n\nCounts of whole things (individuals, cells) are theoretically Poisson\ndistributed: integers from zero upwards. The Poisson has one parameter, so its\nvariance equals its mean, and whether real counts obey that is a question rather\nthan an assumption.\n\n`alga` ships with `bayesnec` and holds final cell density and growth rate for\ntwo marine microalgae against two contaminants, from growth inhibition tests\nwith five replicate cultures per exposure level. The test used here has ten at\nthe control. The symbiotic dinoflagellate *Cladocopium proliferum* against\ncontaminant B is used here and in the Gaussian example below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(alga)\nalga_data <- subset(alga, species == \"c_proliferum\" & contaminant == \"B\")\nalga_data$log.x <- log(alga_data$dose +\n                         min(alga_data$dose[alga_data$dose > 0]) / 10)\nstr(alga_data[, c(\"dose\", \"density\", \"sgr\", \"days\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t70 obs. of  4 variables:\n $ dose   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ density: int  27380 26070 29480 29670 29010 28490 26940 29920 30170 27450 ...\n $ sgr    : num  0.164 0.157 0.175 0.175 0.172 0.17 0.162 0.177 0.178 0.164 ...\n $ days   : int  7 7 7 7 7 7 7 7 7 7 ...\n```\n\n\n:::\n:::\n\n\nThirteen dose levels, the control included, over seven days, with cell\ndensities in the tens of thousands.\nThe arithmetic that makes this a Poisson problem can be done before any model is\nfitted:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nctrl <- alga_data$density[alga_data$dose == 0]\nc(mean = mean(ctrl), observed_sd = sd(ctrl), poisson_sd = sqrt(mean(ctrl)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       mean observed_sd  poisson_sd \n  28458.000    1417.061     168.695 \n```\n\n\n:::\n:::\n\n\nA Poisson with that mean would produce a standard deviation of about\n169. The\nten control cultures show\n1417, about\n8\ntimes as much. Culture-to-culture variation in an inoculum is not counting\nnoise, and no count of this kind ever is; the Poisson is fitted here to show\nwhat that looks like rather than because it is expected to hold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_3 <- bnec(density ~ crf(log.x, model = \"ecxwb1\"),\n              data = alga_data, family = \"poisson\", seed = 333)\n\nsave(exp_3, file = \"vignettes/fits/m5_exp_3.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_3.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_3)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](5Response_data_and_statistical_distributions_files/figure-html/fig-pois-1.png){#fig-pois width=672}\n:::\n:::\n\n\nThe credible bounds are so narrow that they are hard to see against the curve,\nwhich is the visual signature of the arithmetic above.\n\nThe dispersion screen applies here for the reason it applied to the binomial: a\nPoisson has one parameter, so its variance is fixed by its mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion(exp_3, summary = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Estimate      Q2.5     Q97.5     P(>1) \n111.89968  81.10404 157.89680   1.00000 \n```\n\n\n:::\n:::\n\n\nThe dispersion estimate is about\n112, with `P(>1)` of 1.\nThese counts are two orders of magnitude more variable than a Poisson allows,\nnot the modest factor the binomial example showed.\n\nThe equation, `ecxwb1`, is the best supported of those `bnec()` admits for these\ncounts; every equation fitted under a Poisson returns the same failure\n(`scripts/screen_module5_models.R`). A dispersion computed for an equation that\nfits badly counts the variation its curve cannot describe as dispersion, so\nwhere a model set is fitted, read each equation's dispersion against its weight.\n\n`check_fit()` shows where that extra variation sits. The doses are design points\nwith five replicates each and ten at the control, so no binning is needed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_3 <- check_fit(exp_3)\nplot(cf_3)\n```\n\n::: {.cell-output-display}\n![`check_fit()` on the Poisson fit of the algal cell counts. Every point falls outside its bar on the scale panel, and most on the location panel.](5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-pois-1.png){#fig-checkfit-pois width=672}\n:::\n:::\n\n\nBoth panels fail, and the location panel fails *because* the scale panel does. A\nvariance held at a hundredth of the truth leaves the simulated mean far too\ntightly determined, so the observed mean lands outside an interval that should\nhave contained it easily. `sd_ratio` runs from\n2.8 to\n15.6: the data are between\n3 and 16 times more\nvariable than the fit simulates, in every group.\n\nThis is what a wrong family looks like. It is a different failure from the ones\nthe other sections show, where the family is defensible and only the spread is\nmisdescribed.\n\n### Counts observed over an exposure\n\nA count is very often observed over an exposure that differs between replicates:\noffspring counted where the number of fecund adults differs, cells counted over\ndifferent areas, events counted over different lengths of time. The `rate` term\ndeclares that exposure, and is available for the Poisson and negative binomial\nfamilies:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny | rate(n_females) ~ crf(x, model = \"nec4param\")\n```\n:::\n\n\nThe raw counts are passed to `bnec()` unchanged, so a replicate with twenty\nfemales contributes more information than one with eight. Fitting `y / n_females`\nas a continuous response would discard exactly that.\n\nBecause `bayesnec` uses an identity link, `brms` applies the denominator\nmultiplicatively on the response scale rather than as a log offset on a linear\npredictor. The fitted mean therefore *is* the rate, and `top`, `bot` and `nec`\nare directly interpretable as offspring per female. The prediction grid holds the\ndenominator at 1, and `autoplot()` divides the observed counts through to match.\n\nOne caveat decides whether `rate` is the right tool. Where the exposure varies\nfor reasons unrelated to the treatment, because a replicate simply received fewer\nanimals, `rate` does what is wanted. Where the exposure is itself an effect of\nthe treatment, as it would be if the denominator were the number of females\n*surviving* to the point of counting, the endpoint has quietly changed from\nreproductive output to fecundity conditional on survival. Both are legitimate\nendpoints and they will not return the same *NEC*.\n\n## Negative binomial\n\nThe Poisson has one parameter, so like the binomial its variance is determined\nby its mean. Counts that are more variable than that need the negative binomial,\nwhich estimates the additional variation as a parameter of its own. It is the\ncount analogue of the beta-binomial above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_3b <- bnec(density ~ crf(log.x, model = \"ecxwb1\"),\n               data = alga_data, family = \"negbinomial\", seed = 333)\n\nsave(exp_3b, file = \"vignettes/fits/m5_exp_3b.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_3b.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_3b)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](5Response_data_and_statistical_distributions_files/figure-html/fig-negbin-1.png){#fig-negbin width=672}\n:::\n:::\n\n\nThe bounds widen to something a reader can see, as they did for the\nbeta-binomial, and for the same reason.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_3b <- check_fit(exp_3b)\nplot(cf_3b)\n```\n\n::: {.cell-output-display}\n![`check_fit()` on the negative binomial fit of the same counts.](5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-negbin-1.png){#fig-checkfit-negbin width=672}\n:::\n:::\n\n\nBoth panels are repaired, with the same equation and the same data; only the\nfamily has changed. Groups falling outside their bar on the mean drop from\n9 of 13 under\nthe Poisson to\n2 here, and on spread from\n13 to\n1. `sd_ratio` runs from\n0.34 to\n1.28, and at the control it is\n0.70. With five cultures at most\nconcentrations a ratio between about a third and one and a half is within what\nsampling alone produces, which is what the bars show.\n\nThis is what the family is for. With the variance free to be estimated, the fit\nstops being forced into a certainty the data do not support, and one additional\nparameter is enough on these counts because their coefficient of variation stays\nbetween about 0.02 and 0.09 across the series.\n\nThe equation matters as well as the family. Fitted to the same counts under the\nsame family, `nec3param` falls outside its bar on spread at seven of the\nthirteen concentrations, because a threshold followed by an exponential decline\ndoes not follow the shape of this curve and the dispersion parameter absorbs the\ndifference (`scripts/screen_module5_models.R`).\n\n## Gamma\n\nA continuous response that cannot be negative (a length, a mass, a light\nreading, a rate where shrinkage is impossible) is modelled by the gamma. Like\nthe beta and the negative binomial it estimates a spread parameter of its own,\nso it is not the fixed-variance case the Poisson and binomial are. What it does\nfix is the *relative* spread: a gamma holds the coefficient of variation\nconstant, so the standard deviation it simulates is a fixed fraction of the\nfitted mean. That assumption is the one to check.\n\n`lum31` ships with `bayesnec` and holds luminescence readings from the\nbioluminescent bacterium *Vibrio azureus* strain Lum-31 exposed to copper and\nzinc across thirty-three plates [@luter2025]. Module 8 models the plate-to-plate structure; one plate is\nenough here, and a zinc plate is used because every reading on it is positive,\nwhich a gamma requires.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(lum31)\nlum_data <- subset(lum31, plate == \"Zn 28Mar24 Rep1B\" & minutes == 15)\nlum_data$log.x <- log(lum_data$conc)\nc(wells = nrow(lum_data), concentrations = length(unique(lum_data$conc)),\n  min_rlu = min(lum_data$rlu), max_rlu = max(lum_data$rlu))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         wells concentrations        min_rlu        max_rlu \n            44             11          16320         883163 \n```\n\n\n:::\n:::\n\n\nEleven concentrations with four wells each. Every well was read at 15 and at 30\nminutes, and only the 15-minute reading is used: the two readings of one well are\nnot independent replicates, and pooling them would mix the effect of exposure\ntime into the spread at each concentration. The control is recorded at\nits measured dissolved zinc concentration rather than at zero, so the predictor\nis logged without an offset. The coefficient of variation within each\nconcentration is a property of the data alone, with no model involved:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlum_data |>\n  group_by(conc) |>\n  summarise(mean_rlu = round(mean(rlu)), cv = round(sd(rlu) / mean(rlu), 3),\n            .groups = \"drop\") |>\n  as.data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          conc mean_rlu    cv\n1   0.00650000   797369 0.040\n2   0.03599876   831733 0.038\n3   0.06385870   793908 0.022\n4   0.12121739   817449 0.040\n5   0.23593478   866316 0.023\n6   0.46700838   754955 0.072\n7   0.92915558   673048 0.038\n8   1.85017235   451252 0.032\n9   3.69384469   163056 0.170\n10  7.38118939    76659 0.174\n11 14.75587877    18934 0.210\n```\n\n\n:::\n:::\n\n\nIt stays between about 0.02 and 0.07 over the first eight concentrations and\nrises to between 0.17 and 0.21 over the top three, where the luminescence has\nfallen to a fifth of the control or less. A gamma asserts that it is constant.\nThe fit can be made anyway, and the check reports what the assumption does to\nthe fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_4 <- bnec(rlu ~ crf(log.x, model = \"ecxll3\"),\n              data = lum_data, family = \"Gamma\", seed = 333)\n\nsave(exp_4, file = \"vignettes/fits/m5_exp_4.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_4.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_4)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](5Response_data_and_statistical_distributions_files/figure-html/fig-gamma-1.png){#fig-gamma width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_4 <- check_fit(exp_4)\nplot(cf_4)\n```\n\n::: {.cell-output-display}\n![`check_fit()` on the gamma fit of one zinc plate.](5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-gamma-1.png){#fig-checkfit-gamma width=672}\n:::\n:::\n\n\n`ecxll3` is the best supported of the equations `bnec()` admits for these data\n(`scripts/screen_module5_models.R`). Location is reproduced: the number of\nconcentrations outside their bar on the mean is\n1 of 11. The\ncurve is right.\n\nScale is not, although fewer points fall outside their bars than the ratios\nsuggest, because four wells give a wide bar. On spread the number outside is\n2 of 11, and the\npattern of `sd_ratio` follows the coefficients of\nvariation above. Over the first eight concentrations it lies between\n0.19 and\n0.65, so the fit simulates between one\nand a half and five times the observed spread; over the top three it lies\nbetween 1.29 and\n1.87, so it simulates too little. The\nfit estimates one coefficient of variation and settles between the two parts of\nthe series.\n\nThis is the clearest case in the module of a family that is right about the\nresponse and wrong about the spread. The response is a positive continuous\nmeasurement, a gamma is the family for that, and nothing about the choice is\nmistaken. *Modelling dispersion* below takes this fit and repairs it.\n\n\n## Gaussian\n\nA continuous response that can take negative values is modelled by the Gaussian.\nA growth rate is the usual case, because a population can decline as well as\ngrow, and no family bounded below at zero can represent that.\n\n`alga` supplies one directly. Alongside the cell counts fitted above it holds\n`sgr`, the average specific growth rate over the exposure, for the same\ncultures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(alga_data$sgr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.310  0.183\n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(alga_data$sgr, alga_data$dose, function(z) round(mean(z), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     0      1     10     30     60    100    140    200    280    360    420 \n 0.169  0.158  0.167  0.162  0.162  0.173  0.156  0.155  0.110  0.089  0.050 \n   600   1000 \n-0.040 -0.297 \n```\n\n\n:::\n:::\n\n\nThe growth rate falls from about\n0.169 at the control to\n-0.30 at a dose\nof 1000, and\n10 of the 70 cultures are negative: those populations shrank over the\nseven days rather than growing slowly. A gamma or a lognormal cannot represent\nthose observations at all, and neither can an equation whose lower asymptote is\nfixed at zero. `ecxwb1` estimates its lower asymptote, `bot`, and is the best\nsupported of the equations `bnec()` admits for these data\n(`scripts/screen_module5_models.R`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_5 <- bnec(sgr ~ crf(log.x, model = \"ecxwb1\"),\n              data = alga_data, seed = 333,\n              control = list(adapt_delta = 0.99))\n\nsave(exp_5, file = \"vignettes/fits/m5_exp_5.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_5.RData\")\n```\n:::\n\n\n`adapt_delta` is raised from its default of 0.8 because at the default this\nequation returns divergent transitions on these data, and at 0.99 it returns\nnone. Module 7 describes what a divergent transition is and why a smaller step\nsize removes it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"NA\"\n• colour : \"NA\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](5Response_data_and_statistical_distributions_files/figure-html/fig-gauss-1.png){#fig-gauss width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_5 <- check_fit(exp_5)\ncf_5[, c(\"group\", \"mean_ratio\", \"ppp_mean\", \"sd_ratio\", \"ppp_sd\", \"control\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                group mean_ratio ppp_mean sd_ratio ppp_sd control\n1   -2.30258509299405      1.016    0.248    0.703  0.891    TRUE\n2  0.0953101798043249      0.947    0.955    0.673  0.820   FALSE\n3    2.31253542384721      1.003    0.458    0.360  0.972   FALSE\n4    3.40452517175483      0.975    0.778    0.889  0.605   FALSE\n5    4.09600984154116      0.981    0.731    1.210  0.313   FALSE\n6    4.60616968632117      1.071    0.010    1.249  0.274   FALSE\n7    4.94235645334296      0.999    0.513    1.245  0.272   FALSE\n8    5.29881724158969      1.077    0.011    0.353  0.986   FALSE\n9    5.63514668226606      0.917    0.979    0.989  0.510   FALSE\n10   5.88638177065483      1.018    0.357    0.551  0.897   FALSE\n11   6.04049277817534      0.866    0.941    0.460  0.963   FALSE\n12   6.39709630799547      0.855    0.116    1.269  0.271   FALSE\n13   6.90785527398247      1.003    0.578    1.120  0.369   FALSE\n\nOne or more groups show a posterior predictive p-value beyond \n[0.05, 0.95]. See ?check_fit.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cf_5)\n```\n\n::: {.cell-output-display}\n![`check_fit()` on the Gaussian fit of the algal growth rate.](5Response_data_and_statistical_distributions_files/figure-html/fig-checkfit-gauss-1.png){#fig-checkfit-gauss width=672}\n:::\n:::\n\n\nThe fit reproduces these data.\n3 of the 13\nconcentrations fall outside their bar on the mean and\n1 on spread, and `sd_ratio`\nruns from 0.35 to\n1.27, the range sampling alone produces from\nfive cultures. A Gaussian assumes the residual standard deviation is the same at\nevery concentration, and on these growth rates it is: the control cultures agree\nwith one another to\n0.007, and the cultures at\nthe highest dose, which all shrank, to\n0.011.\n\nA Gaussian is the one family whose constant-variance assumption is usually\nstated out loud, because it is the assumption analysis of variance rests on.\nWhere it fails, `disp()` relaxes it, as *Modelling dispersion* below shows on\nthe gamma fit.\n\nTransforming a bounded response onto an unbounded scale and modelling it as\nGaussian is the other way this family gets used: it was standard practice for\nproportion data before generalised methods were routine. Modelling the response\non its own scale with the beta, as above, is preferable. It keeps the parameters\ninterpretable as proportions, and it does not require the transformation to have\nmade the variance constant, which is the very thing this section has just shown\nis not safe to assume.\n\n### Growth rates\n\nThe two `alga` endpoints fitted above are a worked instance of a naming\nconvention worth getting right. OECD Test Guideline 201 [@oecd2026tg201]\ndistinguishes two response variables from the same algal growth inhibition\nexperiment, and this dataset holds both for the same cultures. The average\nspecific growth rate is the logarithmic increase in biomass over the exposure\nperiod, which is `sgr`, and an effect concentration derived from it is written\n**ErC~x~**. Yield is the biomass at the end of the period minus the biomass at\nthe start, which `density` and `density_initial` give, and its effect\nconcentration is written **EyC~x~**.\n\nThe guideline states that an ErC~x~ will generally be higher than the\ncorresponding EyC~x~, and that growth rate is the scientifically preferred\nbasis; yield is retained to satisfy current regulatory requirements in some\ncountries. An estimate\nreported without one of those prefixes has not said which quantity it describes,\nand the two sections above show why that matters beyond nomenclature: the same\ncultures gave a count response needing a negative binomial and a rate response\nneeding a Gaussian, so the family, the candidate set and the estimate all differ\nbetween them.\n\nThe `bayesnec` article on growth data and other potentially negative responses\ncovers the consequences of a response that can go below zero, which reach the\nchoice of both the family and the candidate set.\n\n## Model suitability by response type\n\nNot every equation suits every family. A model predicting negative values cannot\nbe used with a response that must be positive, and `bayesnec` discards any model\nin a requested set that is unsuitable for the distribution of the response. This\nis why a set of twenty-three may return fewer than twenty-three fits, and why\nthe `zero_bounded` set exists.\n\nThree rules account for most of the exclusions.\n\nEquations with no `bot` parameter, the `zero_bounded` set, approach zero and\ncannot go below it. `bnec()` excludes them under a log or logit link. They also\ncannot describe a Gaussian response that falls below zero, although `bnec()`\ndoes not exclude them for the Gaussian, so that choice is yours.\n\nEquations with a linear decay, whose names contain `lin`, decline without limit,\nso they cannot describe a response bounded below at zero under an identity link.\nThat covers the gamma, Poisson, negative binomial, binomial, beta and\nbeta-binomial families.\n\nEquations that raise the predictor to a fractional power cannot be evaluated\nwhere the predictor is negative, which a logged concentration series is wherever\nthe concentration falls below 1.\n\nYou do not have to apply these yourself. `bnec()` excludes what it cannot fit and\nreports the reason, and `bnec_record()` keeps that reason on the fitted object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbnec_record(exp_2)$excluded\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] model  reason\n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n:::\n\n\nNo rows, because that fit named two equations explicitly and both are valid for a\nbeta response on an identity link. A set requested as `\"all\"` on the same data\nreturns several rows, with the rule each equation failed against.\n\n## Censored values\n\nEverything above assumes each recorded value is a measurement of the response.\nIn real datasets some are not. A value below a detection limit and a zero that\nmarks a death are both written down as numbers and neither is a measurement of\nthe response, and the two need different treatment from one another. This\nsection and the two that follow take them in turn.\n\nA value is **censored** when the truth is known to lie in an interval rather than\nat a point: a concentration below a limit of detection, a cell count below the\nresolution of the counting method, a value rounded at the precision it was\nrecorded to. The number written down is a *bound* rather than a measurement.\n\nThe usual treatments are to substitute something for it, commonly half the\ndetection limit, or to delete the row. @helsel2006 reviewed two decades of work\non both and is blunt about the first: substituted values using any fraction\nbetween 0 and 0.99 of the detection limit are \"equivalently arbitrary,\nequivalently precise, equivalently wrong\". Deleting is worse, because it removes\nthe observations at the low end and biases every subsequent estimate of location\nupwards.\n\n`bayesnec` passes through the `cens()` term from `brms`, so the bound can be\ndeclared instead of disguised:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny | cens(censoring) ~ crf(x, model = \"nec4param\")\n```\n:::\n\n\n`censoring` is a column in the data rather than a constant, because in a\nconcentration-response dataset only some rows are censored. It takes the values\n`\"none\"`, `\"left\"`, `\"right\"` or `\"interval\"`. Interval censoring takes a second\nargument giving the upper bound, as `cens(censoring, upper)`.\n\nThe response column holds the bound. On a left-censored row, the number in the\nresponse column is the value the truth is known to be at or below, rather than\nzero and rather than a guess at the unknown truth.\n\nWhat this changes is the contribution each row makes to the likelihood. An\nordinary row contributes a density at a point, which falls away as the fitted\ncurve departs from it, so a substituted value actively pulls the curve back\ntowards the number that was substituted. A censored row instead contributes the\nprobability of falling at or below the bound. As the curve descends past the\nbound that probability rises towards 1 and then *saturates*: the curve is neither\nrewarded for passing further below nor penalised for it.\n\n## Zeros\n\nA zero needs a different treatment depending on what produced it, and the three\ncases are distinguishable from the design rather than from the data.\n\nA zero that is a measurement below the resolution of the method is censored, and\nbelongs in the previous section.\n\nA zero that marks a distinct event is **structural**. An organism that died did\nnot grow slowly; its growth is undefined rather than small. A response of this\nkind has two processes behind it, one deciding whether the event occurred and one\ngenerating the response when it did not, and a **two-block** model fits both.\n\nA zero that is an ordinary draw from a distribution admitting zeros is not\nevidence of anything at all. @warton2005 makes the point directly: many zeros\ndoes not mean zero inflation, and a Poisson or negative binomial with a low mean\nproduces plenty of them. Fit the simpler family and check it before reaching for\na two-block model. @martin2005 sets out how to decide which of the three you are\nlooking at, from what the experiment did rather than from a test.\n\n## Hurdle and zero-inflated models\n\nBoth names describe a two-block model and they are not interchangeable. The\ndistinction is whether the zeros are **observed** or **latent**, and it decides\nwhether the second block is worth interpreting.\n\nUnder a **hurdle** the zeros are observed to be structural. The individual died,\nor the replicate failed, and you know which observations those are. The\nlikelihood then separates exactly into a block for whether the event occurred and\na block for the response given that it did not, and both blocks describe a curve\nyou can read a threshold from.\n\nUnder **zero inflation** a zero could have come from either component, and\nnothing in the data says which. The two are therefore weakly separated precisely\nwhere the ordinary component is small, which is the high-concentration end that\ndetermines the *NEC*. A threshold fitted to the zero-inflation component there\ndescribes a class of observation nobody measured.\n\nThe practical rule follows from the design rather than from the data. Where you\nrecorded *why* each zero occurred, a hurdle is available and its second block\nmeans something. Where you did not, zero inflation is the description the data\nsupport, and the second block should not be read as a concentration-response\ncurve.\n\n`bayesnec` supplies `hurdle_gamma` for a positive continuous response with\nstructural zeros, `hurdle_poisson` and `hurdle_negbinomial` for counts, and the\nzero-inflated beta, Poisson and negative binomial:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(bayesnec:::mod_fams)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"gaussian\"                  \"Gamma\"                    \n [3] \"poisson\"                   \"negbinomial\"              \n [5] \"bernoulli\"                 \"binomial\"                 \n [7] \"beta_binomial\"             \"beta\"                     \n [9] \"hurdle_gamma\"              \"zero_inflated_beta\"       \n[11] \"zero_inflated_poisson\"     \"zero_inflated_negbinomial\"\n[13] \"hurdle_poisson\"            \"hurdle_negbinomial\"       \n```\n\n\n:::\n:::\n\n\n`bnec_hurdle()` and `bnec_joint()` fit the two blocks. The worked example below\nfits one; the [`bayesnec` article on hurdle and zero-inflated\nmodels](https://open-aims.github.io/bayesnec/dev/articles/example6.html) covers\nthe rest, including the crossed weights of the two model sets and when the joint\nform is needed rather than the factorised one.\n\nOne trap is worth naming even though it is not taught. Fitting the positive part\nof a count response by dropping the zeros and using an ordinary Poisson is not\nthe same model: with the zeros removed the remaining counts follow a\n*zero-truncated* Poisson, so an untruncated fit estimates the wrong quantity. The\nerror grows as the mean falls towards zero, which is the high-concentration end\nthat an *NEC* or an EC~x~ is read from. The equivalent construction for\n`hurdle_gamma` is exact, because a gamma distribution has no mass at zero to\nbegin with, which is why the problem appears only for counts.\n\n### A hurdle gamma in practice\n\nThe `nassarius` dataset ships with `bayesnec` and holds chronic toxicity tests\non the tropical marine snail *Nassarius dorsatus*, one row per individual snail\nthat entered the experiment. The contaminants are anonymised as A to D and the\ndose units are not stated, so only the relative spacing of doses is preserved,\nwhich is all a toxicity estimate depends on. Contaminant A is used here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(nassarius)\nsnail <- subset(nassarius, contaminant == \"A\")\nstr(snail)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t204 obs. of  6 variables:\n $ contaminant: Factor w/ 4 levels \"A\",\"B\",\"C\",\"D\": 1 1 1 1 1 1 1 1 1 1 ...\n $ dose       : num  0 0 0 0 0 0 0 0 0 0 ...\n $ tank       : chr  \"A-1\" \"A-1\" \"A-1\" \"A-1\" ...\n $ alive      : int  1 1 1 1 1 0 1 1 1 1 ...\n $ growth     : num  8.72 28.17 27.28 15.86 19.02 ...\n $ record     : Factor w/ 5 levels \"measured\",\"sentinel_code\",..: 1 1 1 1 1 2 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\nThe response is growth, which is positive and continuous, so the survivors are\na gamma. `alive` records which snails died, so the zeros are observed rather\nthan inferred and a hurdle is available.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(snail$alive, snail$dose, function(z) sprintf(\"%d of %d\", sum(z), length(z)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         0       0.01       0.02       0.04       0.08       0.16       0.31 \n\"21 of 24\" \"17 of 18\" \"18 of 18\" \"17 of 18\" \"18 of 18\" \"18 of 18\" \"18 of 18\" \n      0.63       1.25        2.5         20 \n\"18 of 18\" \"18 of 18\"  \"3 of 18\"  \"0 of 18\" \n```\n\n\n:::\n:::\n\n\nMortality is concentrated in the top two doses, which hold 33 of the 38 deaths,\nand is complete at the highest.\nThat is what makes the endpoint worth fitting as two blocks rather than one.\nA survivors-only analysis of these data would contain\n166 snails of the 204 exposed, and the dose of\n20 would not appear in it at all, because a dose at which\nnothing survived contributes no rows. The dose that killed every animal is the\nmost informative one in the experiment and it is the one that dropping the dead\nremoves.\n\nTwo preparation steps are needed and both are stated rather than done quietly.\nThe assay references each snail to a baseline mean rather than to its own\nstarting size, so a few survivors are recorded at or below zero; those are\nmeasurement noise around a true value near zero rather than deaths, and they are\nnudged to half the smallest positive growth in the test. And the doses span\nseveral orders of magnitude, so the fit is on a log scale, which needs the\ncontrol placed somewhere other than `log(0)`: one decade below the lowest tested\ndose is far enough to read as a control and close enough not to stretch the\nfitted range.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npos_min <- min(snail$growth[snail$growth > 0])\nsnail$growth <- ifelse(snail$alive == 1 & snail$growth <= 0, pos_min / 2,\n                       snail$growth)\n\noffset <- min(snail$dose[snail$dose > 0]) / 10\nsnail$log_dose <- log(snail$dose + offset)\nback <- function(z) exp(z) - offset\n```\n:::\n\n\n`bnec_hurdle()` takes the formula for the growth block and fits a survival block\nalongside it. The same model set is used for both here, and `adapt_delta` is\nraised because the survival curve is determined mostly by two doses and samples\nawkwardly at the default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_6 <- bnec_hurdle(growth ~ crf(log_dose, model = c(\"nec3param\", \"ecxll3\")),\n                     data = snail, seed = 333,\n                     control = list(adapt_delta = 0.99))\n\nsave(exp_6, file = \"vignettes/fits/m5_exp_6.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_6.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(exp_6, xform = back)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObject of class bayesnechurdlefit\n\n   204 individuals exposed; 38 recorded as zero ( 18.6% )\n\n  growth   : gamma -- nec3param, ecxll3 \n  survival : bernoulli -- nec3param, ecxll3 \n\nNo-effect toxicity estimates\n                   Q50 Q2.5 Q97.5\ncombined (N(S)EC) 0.56 0.21  0.75\ngrowth (N(S)EC)   0.56 0.23  0.75\nsurvival (N(S)EC) 1.72 1.09  2.41\n\nNSEC values appear where a model set contains smooth (ECx) models, which\ncarry no threshold parameter; N(S)EC is a model-averaged combination\nof the two (Fisher et al. 2023).\n\nThe combined endpoint is the expected response per individual exposed,\ni.e. growth * survival. Use which = to select a component.\n```\n\n\n:::\n:::\n\n\nThree estimates are reported rather than one. **Growth** is the response of the\nsnails that lived, which is what a survivors-only analysis would return.\n**Survival** is the probability of living to be measured. **Combined** is the\nexpected growth per individual *exposed*, which is growth multiplied by\nsurvival, and it is the endpoint a risk assessment asks about, because an\nindividual that died did not grow.\n\nGrowth and survival separate: growth declines from a no-effect estimate of about\n0.56 while survival holds to about 1.72, a factor of three. The combined\nestimate follows growth here, because growth is the more sensitive of the two\nand the combined endpoint is bounded by whichever declines first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(exp_6, which = \"all\")\n```\n\n::: {.cell-output-display}\n![Contaminant A as three curves: the combined endpoint, the growth of survivors, and the probability of survival. The predictor is on the log dose scale the fit used.](5Response_data_and_statistical_distributions_files/figure-html/fig-nass-1.png){#fig-nass width=960}\n:::\n:::\n\n\nThe right-hand panel is the one a survivors-only analysis cannot produce at any\nlevel of effort. Its shape comes almost entirely from the two doses where most snails died,\nand the highest of those contributes no rows to a dataset of survivors.\n\nThe growth block reproduces the mean at every dose and not the spread. Run\n`check_fit()` on `exp_6$growth` and the observed standard deviation is between\nabout 0.4 and 0.65 of the simulated one at the lower doses, and about twice it at\nthe two highest, which is the pattern *Modelling dispersion* below repairs on a\ngamma fit. That repair is not yet available here, because `bnec_hurdle()` copies\na `disp()` term into the survival block as well, where a Bernoulli response has\nno dispersion parameter for it to model\n([`bayesnec` #410](https://github.com/open-AIMS/bayesnec/issues/410)).\n\n## Preparing the response\n\nSupply the response as it was measured, and match a statistical family to it.\nThe common alternative is to convert it first, to percent inhibition, percent of\ncontrol or percent of the observed maximum. That conversion introduces error,\nand the family choice set out above avoids it.\n\nNormalising to the control is conventional in ecotoxicology, usually as\n$y^0_i = 1 - y_i / \\bar{y}_{con}$, where $\\bar{y}_{con}$ is the mean of three to\nsix control replicates. @Ritz2026 measured what it does.\n\n![Ritz, Gerhard and Streibig (2026), the source of the measurements in this section.](images/Ritz_etal2026.png){#fig-ritz width=70% fig-align=\"center\"}\n\n- Every observation is divided by the *same random quantity*, so the normalised\n  values are correlated and the sampling variability of the divisor is\n  discarded.\n- The expected value of a reciprocal is not the reciprocal of an expected value,\n  so the inhibition trend is biased downwards and the effect concentrations read\n  off it are biased upwards.\n- Nothing is lost by leaving the response alone. The concentration at which\n  inhibition rises by $x$ per cent is the concentration at which the response\n  falls by $x$ per cent, and the second is what `ecx()` returns by default.\n- Dividing by the observed maximum instead of the control mean is worse again,\n  and it forces one observation onto the boundary of the beta's support.\n- Where a divisor is unavoidable it must be a constant fixed in advance of the\n  analysis, such as a physiological or design ceiling.\n- `bnec()` looks for both practices and reports them.\n\nMany proportional responses need no divisor at all. The maximum quantum yield\nused in module 7 is a genuine physical proportion, as is a survival fraction or\na bleached-area fraction, and these are modelled as they stand.\n\n::: {.callout-note collapse=\"true\" title=\"The size of the error\"}\n\nFrom the simulation of an ED10 with six control replicates in @Ritz2026:\nnormalising gave a bias of 6.8% and a coefficient of variation of 26.4%, against\n2.1% and 12.7% for the same quantity estimated from the raw response, and\nnominal 95% intervals covered at 90% rather than 95%. In their simulation of the\nother experimental design, with a single control replicate, the coverage of the\nnormalised analysis fell to 57%.\n\n`ecx()` returns a decline relative to the *fitted* control rather than to an\nobserved control mean, and because it is evaluated separately within every\nposterior draw the uncertainty about the control level propagates into the\ncredible interval instead of being thrown away.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Division by the observed maximum\"}\n\nDividing by the observed maximum is worse than dividing by the control mean on\nthree counts. An extreme order statistic is more variable and more biased than a\nmean of three to six values. The divisor then depends on every treatment rather\nthan on the controls alone, so treated groups partly determine their own\ndenominator. And it forces exactly one observation to exactly 1, which is\noutside the open interval a beta distribution is defined on, so `bnec()` has to\nshift it off the boundary.\n\n`bnec()` detects both practices from the response as supplied. Dividing by the\nobserved maximum leaves a maximum of exactly 1 attained by exactly one\nobservation, and dividing by the control mean leaves the control observations\naveraging to exactly 1. The first check is suppressed where the response lies on\na rational grid, because a genuine count-derived proportion such as 19 of 20\nsurviving routinely produces a single observation at 1 and is not evidence of\nanything.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"A divisor fixed in advance\"}\n\nA response above 1 that has to be modelled with a beta distribution needs a\ndivisor. It must be a constant settled before the analysis: a physiological or\ndesign ceiling, or a value from accumulated historical controls. @Ritz2026 are\nexplicit that the problem is dividing by something *random* rather than dividing\nas such. An EC~x~ is unaffected by the choice of a constant divisor, because\nit is a relative decline from the fitted control, and the same holds for any\nlinear rescaling of the response [@Weimer2012].\n:::\n\n### The motive for a divisor\n\nDividing by the observed maximum is often done for a reason that has nothing to\ndo with normalisation. A response on an arbitrary scale, such as a luminescence\nreading or a cell count, is divided to put it between 0 and 1 so that a beta\ndistribution can be used, because the beta accommodates variability that changes\nwith the mean and a Gaussian does not.\n\nThat reasoning identifies a real problem and answers it indirectly. The problem\nis that replicate variability at the high concentrations is not the same as at\nthe control. The direct answer is the subject of this module: keep the response\non its own scale, choose the family that suits it, and model the variability\nexplicitly where it changes. The sections above covered the choice of family,\nand the section below covers the `disp` term for a dispersion that varies across\nthe series.\n\nDoing it that way keeps `top`, `bot` and `nec` in the units the experiment was\nmeasured in, avoids the bias @Ritz2026 measured, and states the change in\nvariability as something estimated from the data rather than absorbed by a\ntransformation. It also avoids forcing an observation onto the boundary of the\nbeta's support, which division by a maximum does by construction.\n\n## Modelling dispersion\n\nEverything above chooses a family from what kind of quantity the response is.\nThat is the right way to choose one, and on every dataset in this module the\nfamily chosen that way, with its variance free to be estimated, reproduced the\n*mean* of the curve at all or nearly all concentrations. On two of them it did\nnot reproduce the spread: the beta fit of the PAM yields and the gamma fit of\nthe luminescence plate fail `check_fit()` on `sd_ratio`, and so does the growth\nblock of the hurdle fit. In none of the three does a different equation repair\nit: every equation `bnec()` admits for each of them was fitted and checked\n(`scripts/screen_module5_models.R`). Modelling the dispersion is the remedy, and\nit is the last step in choosing how a response is modelled rather than an\noptional refinement.\n\nThe reason a correct family can still fail is an assumption made by default and\nrarely stated. A fit holds the dispersion parameter of the chosen family\nconstant across the whole concentration-response curve. For a Gaussian response\nthat assumes replicate variability is the same at every concentration; for the\nother families it assumes the coefficient of variation, or the precision, does\nnot change with the mean. Real series often violate it, because variability at a\nconcentration that has killed most of the organisms is not the variability of an\nuntreated control.\n\nWhere that is wrong the consequences fall on the credible intervals of the\ntoxicity estimates, and they fall unevenly, because the assumed variability is\ntoo large at one end of the series and too small at the other. The *NSEC* is\naffected most, because its reference is a quantile of the control posterior, and the width of that posterior is the\nvariability the fit estimated at the control.\n\nThe `disp` term relaxes the assumption, letting the spread vary rather than\ntaking one value for the whole series:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny ~ crf(x, model = \"nec4param\") + disp(~x)         # varies along the predictor\ny ~ crf(x, model = \"nec4param\") + disp(\"power\")    # varies with the fitted mean\n```\n:::\n\n\nReach for it when the check has failed rather than as a routine addition, and\nexclude three other explanations of the failure first. A variance function will\nabsorb any cause of apparent heteroscedasticity and report a confident slope\nregardless. Substituted or censored values cluster at one end of the series and\ntheir spread is easily mistaken for changing variability. A misspecified family\nproduces the same appearance, since a constant coefficient of variation is what\na gamma already implies, so check the family before adding a term to repair it.\nAnd a curve that is systematically wrong in one region leaves large residuals\nthere, which a variance function will describe as noise rather than as lack of\nfit.\n\n### A worked case\n\nThe gamma fit of the luminescence plate is the clearer of the two, because its\ncurve is reproduced and only its spread is not, so whatever `disp()` changes\ncannot be confused with a change in the curve. The baseline is `exp_4` from the\ngamma section, which fits one equation, `ecxll3`, so the two fits below differ\nin the dispersion sub-model and in nothing else.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp_4_const <- exp_4\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\nexp_4_disp <- bnec(rlu ~ crf(log.x, model = \"ecxll3\") + disp(\"power\"),\n                   data = lum_data, family = \"Gamma\", seed = 333)\n\nsave(exp_4_disp, file = \"vignettes/fits/m5_exp_4_disp.RData\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"vignettes/fits/m5_exp_4_disp.RData\")\n```\n:::\n\n\n`disp(\"power\")` is used rather than `disp(~ log.x)` because the coefficient of\nvariation here rises as the fitted mean falls, which is a relationship with the\nmean rather than with the predictor. The same term repaired the beta fit of the\nPAM yields above. Both forms are available and the check is\nwhat decides between them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_const <- check_fit(exp_4_const)\nplot(cf_const)\n```\n\n::: {.cell-output-display}\n![`check_fit()` on the constant-dispersion gamma fit.](5Response_data_and_statistical_distributions_files/figure-html/fig-disp-checkfit-1.png){#fig-disp-checkfit width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncf_disp <- check_fit(exp_4_disp)\nplot(cf_disp)\n```\n\n::: {.cell-output-display}\n![The same check with `disp(\"power\")`.](5Response_data_and_statistical_distributions_files/figure-html/fig-disp-checkfit-power-1.png){#fig-disp-checkfit-power width=672}\n:::\n:::\n\n\nGroups falling outside their bar on spread drop from\n2 of\n11 to\n0, and on the mean\n1 and\n1 fall outside in\nthe two fits. The count of points outside a bar understates the change, because\nfour wells per concentration give wide bars; the table below shows it directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The `group` column holds the logged predictor, because that is the scale the\n# model was fitted on. It is returned to concentrations here so the table can be\n# read against the coefficients of variation above.\ndata.frame(\n  conc = signif(exp(as.numeric(cf_const$group)), 3),\n  obs_sd = round(cf_const$obs_sd),\n  sim_sd_const = round(cf_const$sim_sd),\n  sim_sd_disp = round(cf_disp$sim_sd),\n  sd_ratio_const = round(cf_const$sd_ratio, 2),\n  sd_ratio_disp = round(cf_disp$sd_ratio, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      conc obs_sd sim_sd_const sim_sd_disp sd_ratio_const sd_ratio_disp\n1   0.0065  32124        92298       42892           0.35          0.75\n2   0.0360  31435        90715       41284           0.35          0.76\n3   0.0639  17361        91563       42617           0.19          0.41\n4   0.1210  32500        88440       41882           0.37          0.78\n5   0.2360  19865        90407       42299           0.22          0.47\n6   0.4670  54700        84009       40114           0.65          1.36\n7   0.9290  25240        68351       36150           0.37          0.70\n8   1.8500  14316        46173       30957           0.31          0.46\n9   3.6900  27680        21540       22028           1.29          1.26\n10  7.3800  13368         7136       12893           1.87          1.04\n11 14.8000   3977         2225        6759           1.79          0.59\n```\n\n\n:::\n:::\n\n\nRead the two `sim_sd` columns against `obs_sd`. The observed spread stays\nbetween about\n14,000 and\n55,000 over the first\neight concentrations and falls to\n3,977 at the\nhighest. The spread the constant-dispersion fit simulates tracks the fitted\nmean instead, falling from\n92,298 at the lowest\nconcentration to\n2,225 at the\nhighest, a\n41-fold decline. That is\nwhat a fixed coefficient of variation obliges it to do. The consequence is\n`sd_ratio` as low as 0.19 over the lower\npart of the series, where the fit simulates up to five times the observed\nspread, and above 1 at the top, where it simulates too little. With\n`disp(\"power\")` the simulated spread falls less steeply than the mean, from\n42,892 to\n6,759, and the ratio\nlies between 0.41 and\n1.36.\n\nThe reason this matters is the estimate rather than the diagnostic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(`constant dispersion` = nsec(exp_4_const, xform = exp),\n      `disp(\"power\")`       = nsec(exp_4_disp, xform = exp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Q50      Q2.5     Q97.5\nconstant dispersion 0.4192010 0.1728633 0.5741229\ndisp(\"power\")       0.3019244 0.1254368 0.4111826\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(`constant dispersion` = ecx(exp_4_const, ecx_val = 10, xform = exp),\n      `disp(\"power\")`       = ecx(exp_4_disp, ecx_val = 10, xform = exp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Q50      Q2.5     Q97.5\nconstant dispersion 0.5730841 0.4811875 0.6779384\ndisp(\"power\")       0.6069044 0.5197436 0.7058821\n```\n\n\n:::\n:::\n\n\nThe *NSEC* falls from\n0.42 to\n0.30 mg/L, while the EC~10~\nchanges only from\n0.57 to\n0.61. The EC~10~\nis read from the fitted curve, which the dispersion sub-model barely changes;\nthe *NSEC* is read against the spread of the control. The direction is the one\nmodule 3 sets out under the *NSEC* and module 7 measures on real data: a fit\nsimulating too much variability at the control gives the control posterior too\nmuch width, which places the significance reference lower, and a reference\nplaced lower is crossed further along the curve. The constant-dispersion fit\ntherefore reports the less protective of the two figures, and nothing in its\nsampler diagnostics says so. `check_sampling()` passes on both.\n\nA guideline value derived from the first *NSEC* would be\n1.4\ntimes the one derived from the second, on the same data and the same equation.\nThe difference is whether the fit was allowed to describe the spread, together\nwith the prior on the dispersion coefficients that the sub-model adds.\n\nTwo cautions. This is one plate of a design that has thirty-three, and module 8\nfits the plate structure rather than subsetting to one. And a repair as complete\nas this one is the exception. On the PAM yields above, two of six concentrations\nremain just outside their bars after the term is added, and on the ametryn data\nin module 7 one of eight remains flagged. Read the diagnostic after adding the\nterm rather than assuming it has done its work.\n\n## Open questions\n\nThe families implemented in `bayesnec` cover the common cases in\nconcentration-response work, and choosing between them from the kind of quantity\nthe response is reproduced the mean of the curve at all or nearly all\nconcentrations on every dataset fitted here.\n\nTwo things follow for practice. Check which distribution was used, because\n`bnec()` infers one where it is not told. And check that it reproduces the\nvariability in the data as well as the mean. The beta and gamma fits in this\nmodule did not, whatever equation was used, and both were brought into agreement\nby modelling the dispersion; the growth block of the hurdle fit did not either,\nand cannot yet be repaired that way. The negative binomial and Gaussian fits\nreproduced both on the algal data, and on those data the equation mattered as\nmuch as the family. That second check is `check_fit()`, and module 7 runs it\ninside a complete analysis and reports what it found.\n\nWhat is not settled is how far a dispersion sub-model should be taken. A\nvariance function absorbs any cause of apparent heteroscedasticity, so a fit\nthat passes after one has been added has not thereby been validated. The\nsections above reach for it only where the family was already defensible and the\ncheck had already failed, which is the narrowest use it has.\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "5Response_data_and_statistical_distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}